#
# PySNMP MIB module AIDIALOUT-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/AIDIALOUT-MIB
# Produced by pysmi-0.3.4 at Wed May  1 11:16:00 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
Integer, OctetString, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "Integer", "OctetString", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, SingleValueConstraint, ConstraintsUnion, ValueSizeConstraint, ValueRangeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "SingleValueConstraint", "ConstraintsUnion", "ValueSizeConstraint", "ValueRangeConstraint")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Unsigned32, MibIdentifier, enterprises, Bits, Counter64, Gauge32, iso, ObjectIdentity, NotificationType, IpAddress, Counter32, Integer32, TimeTicks, MibScalar, MibTable, MibTableRow, MibTableColumn, ModuleIdentity = mibBuilder.importSymbols("SNMPv2-SMI", "Unsigned32", "MibIdentifier", "enterprises", "Bits", "Counter64", "Gauge32", "iso", "ObjectIdentity", "NotificationType", "IpAddress", "Counter32", "Integer32", "TimeTicks", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "ModuleIdentity")
TextualConvention, DisplayString, TruthValue = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "DisplayString", "TruthValue")
class PositiveInteger(Integer32):
    subtypeSpec = Integer32.subtypeSpec + ValueRangeConstraint(1, 2147483647)

aii = MibIdentifier((1, 3, 6, 1, 4, 1, 539))
aiDialOut = ModuleIdentity((1, 3, 6, 1, 4, 1, 539, 36))
if mibBuilder.loadTexts: aiDialOut.setLastUpdated('9909151700Z')
if mibBuilder.loadTexts: aiDialOut.setOrganization('Applied Innovation Inc.')
if mibBuilder.loadTexts: aiDialOut.setContactInfo('Engineering MIB Administrator Postal: Applied Innovation Inc. 5800 Innovation Drive Dublin, Ohio 43017-3271 Tel: 614-798-2000 Fax: 614-798-1770 Email: snmp@aiinet.com')
if mibBuilder.loadTexts: aiDialOut.setDescription('MIB module for Dialout Modem..')
aiDialOutTable = MibTable((1, 3, 6, 1, 4, 1, 539, 36, 1), )
if mibBuilder.loadTexts: aiDialOutTable.setStatus('current')
if mibBuilder.loadTexts: aiDialOutTable.setDescription('Table of dialout information indexed by link number.')
aiDialOutEntry = MibTableRow((1, 3, 6, 1, 4, 1, 539, 36, 1, 1), ).setIndexNames((0, "AIDIALOUT-MIB", "aiDialOutLinkNumber"))
if mibBuilder.loadTexts: aiDialOutEntry.setStatus('current')
if mibBuilder.loadTexts: aiDialOutEntry.setDescription('Entry of aiDialOutTable.')
aiDialOutLinkNumber = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 1), PositiveInteger()).setMaxAccess("readonly")
if mibBuilder.loadTexts: aiDialOutLinkNumber.setStatus('current')
if mibBuilder.loadTexts: aiDialOutLinkNumber.setDescription('Link number to which this table row applies.')
aiDialOutStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 2), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: aiDialOutStatus.setStatus('current')
if mibBuilder.loadTexts: aiDialOutStatus.setDescription('Dial Out Modem Status.')
aiDialOutPrimaryDialString = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 3), DisplayString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: aiDialOutPrimaryDialString.setStatus('current')
if mibBuilder.loadTexts: aiDialOutPrimaryDialString.setDescription('Primary Dial Out String. Maximum length is 80 characters.')
aiDialOutSecondaryDialString = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 4), DisplayString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: aiDialOutSecondaryDialString.setStatus('current')
if mibBuilder.loadTexts: aiDialOutSecondaryDialString.setDescription('Secondary Dial Out String. Maximum length is 80 characters.')
aiDialOutTimeOut = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(5, 300))).setUnits('seconds').setMaxAccess("readwrite")
if mibBuilder.loadTexts: aiDialOutTimeOut.setStatus('current')
if mibBuilder.loadTexts: aiDialOutTimeOut.setDescription('Dialing time-out.')
aiDialOutAttempts = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 10))).setUnits('seconds').setMaxAccess("readwrite")
if mibBuilder.loadTexts: aiDialOutAttempts.setStatus('current')
if mibBuilder.loadTexts: aiDialOutAttempts.setDescription('Dialing attempts.')
aiDialOutInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 539, 36, 1, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 300))).setUnits('seconds').setMaxAccess("readwrite")
if mibBuilder.loadTexts: aiDialOutInterval.setStatus('current')
if mibBuilder.loadTexts: aiDialOutInterval.setDescription('Interval between dialing.')
mibBuilder.exportSymbols("AIDIALOUT-MIB", PositiveInteger=PositiveInteger, aiDialOutPrimaryDialString=aiDialOutPrimaryDialString, aii=aii, aiDialOutTable=aiDialOutTable, aiDialOutSecondaryDialString=aiDialOutSecondaryDialString, aiDialOutTimeOut=aiDialOutTimeOut, aiDialOutEntry=aiDialOutEntry, aiDialOutInterval=aiDialOutInterval, aiDialOut=aiDialOut, aiDialOutAttempts=aiDialOutAttempts, aiDialOutStatus=aiDialOutStatus, PYSNMP_MODULE_ID=aiDialOut, aiDialOutLinkNumber=aiDialOutLinkNumber)
