#
# PySNMP MIB module CNTSVCEXT-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/CNTSVCEXT-MIB
# Produced by pysmi-0.3.4 at Wed May  1 12:25:32 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
cntsvcExt, = mibBuilder.importSymbols("APENT-MIB", "cntsvcExt")
Integer, OctetString, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "Integer", "OctetString", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
SingleValueConstraint, ConstraintsUnion, ConstraintsIntersection, ValueSizeConstraint, ValueRangeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "SingleValueConstraint", "ConstraintsUnion", "ConstraintsIntersection", "ValueSizeConstraint", "ValueRangeConstraint")
NotificationGroup, ModuleCompliance = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance")
MibScalar, MibTable, MibTableRow, MibTableColumn, Unsigned32, Gauge32, Bits, NotificationType, MibIdentifier, ModuleIdentity, TimeTicks, iso, Integer32, Counter64, IpAddress, Counter32, ObjectIdentity = mibBuilder.importSymbols("SNMPv2-SMI", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "Unsigned32", "Gauge32", "Bits", "NotificationType", "MibIdentifier", "ModuleIdentity", "TimeTicks", "iso", "Integer32", "Counter64", "IpAddress", "Counter32", "ObjectIdentity")
TextualConvention, RowStatus, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "RowStatus", "DisplayString")
apCntsvcExtMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 2467, 1, 18, 1))
if mibBuilder.loadTexts: apCntsvcExtMib.setLastUpdated('9710092000Z')
if mibBuilder.loadTexts: apCntsvcExtMib.setOrganization('ArrowPoint Communications Inc.')
if mibBuilder.loadTexts: apCntsvcExtMib.setContactInfo(' Postal: ArrowPoint Communications Inc. 50 Nagog Park Acton, Massachusetts 01720 Tel: +1 978-206-3000 option 1 E-Mail: support@arrowpoint.com')
if mibBuilder.loadTexts: apCntsvcExtMib.setDescription('The MIB module used to describe the ArrowPoint Communications content rule table')
apCntsvcTable = MibTable((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2), )
if mibBuilder.loadTexts: apCntsvcTable.setStatus('current')
if mibBuilder.loadTexts: apCntsvcTable.setDescription('A list of content rule entries.')
apCntsvcEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1), ).setIndexNames((0, "CNTSVCEXT-MIB", "apCntsvcOwnName"), (0, "CNTSVCEXT-MIB", "apCntsvcCntName"), (0, "CNTSVCEXT-MIB", "apCntsvcSvcName"))
if mibBuilder.loadTexts: apCntsvcEntry.setStatus('current')
if mibBuilder.loadTexts: apCntsvcEntry.setDescription('A group of information to uniquely identify a content providing service.')
apCntsvcOwnName = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(1, 31))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: apCntsvcOwnName.setStatus('current')
if mibBuilder.loadTexts: apCntsvcOwnName.setDescription('The name of the Owner.')
apCntsvcCntName = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(1, 31))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: apCntsvcCntName.setStatus('current')
if mibBuilder.loadTexts: apCntsvcCntName.setDescription('The name of the content rule.')
apCntsvcSvcName = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 3), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(1, 31))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: apCntsvcSvcName.setStatus('current')
if mibBuilder.loadTexts: apCntsvcSvcName.setDescription('The name of the service.')
apCntsvcHits = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: apCntsvcHits.setStatus('current')
if mibBuilder.loadTexts: apCntsvcHits.setDescription('Total number of flows placed onto this service for this content rule.')
apCntsvcBytes = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: apCntsvcBytes.setStatus('current')
if mibBuilder.loadTexts: apCntsvcBytes.setDescription('Total number of flows moved by this service for this content rule.')
apCntsvcFrames = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: apCntsvcFrames.setStatus('current')
if mibBuilder.loadTexts: apCntsvcFrames.setDescription('Total number of frames moved by this service for this content rule.')
apCntsvcBucket = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 12)).clone(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: apCntsvcBucket.setStatus('current')
if mibBuilder.loadTexts: apCntsvcBucket.setDescription('The service bucket used for cache divisions.')
apCntsvcStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 8), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: apCntsvcStatus.setStatus('current')
if mibBuilder.loadTexts: apCntsvcStatus.setDescription('Status entry for this row ')
apCntsvcWeight = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 10)).clone(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: apCntsvcWeight.setStatus('current')
if mibBuilder.loadTexts: apCntsvcWeight.setDescription('The service weighting used for weighted round robin.')
apCntsvcDnsHits = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: apCntsvcDnsHits.setStatus('current')
if mibBuilder.loadTexts: apCntsvcDnsHits.setDescription('Total number DNS resolutions to this service on this content rule.')
apCntsvcDnsProximityHits = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: apCntsvcDnsProximityHits.setStatus('current')
if mibBuilder.loadTexts: apCntsvcDnsProximityHits.setDescription('Total number DNS proximity resolutions to this service on this content rule.')
apCntsvcState = MibTableColumn((1, 3, 6, 1, 4, 1, 2467, 1, 18, 2, 1, 12), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 4))).clone(namedValues=NamedValues(("suspended", 1), ("down", 2), ("alive", 4))).clone('suspended')).setMaxAccess("readonly")
if mibBuilder.loadTexts: apCntsvcState.setStatus('current')
if mibBuilder.loadTexts: apCntsvcState.setDescription('The current service state.')
mibBuilder.exportSymbols("CNTSVCEXT-MIB", apCntsvcOwnName=apCntsvcOwnName, apCntsvcState=apCntsvcState, PYSNMP_MODULE_ID=apCntsvcExtMib, apCntsvcEntry=apCntsvcEntry, apCntsvcTable=apCntsvcTable, apCntsvcSvcName=apCntsvcSvcName, apCntsvcCntName=apCntsvcCntName, apCntsvcFrames=apCntsvcFrames, apCntsvcExtMib=apCntsvcExtMib, apCntsvcBytes=apCntsvcBytes, apCntsvcDnsProximityHits=apCntsvcDnsProximityHits, apCntsvcDnsHits=apCntsvcDnsHits, apCntsvcBucket=apCntsvcBucket, apCntsvcHits=apCntsvcHits, apCntsvcStatus=apCntsvcStatus, apCntsvcWeight=apCntsvcWeight)
