#
# PySNMP MIB module HH3C-RMON-EXT2-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/HH3C-RMON-EXT2-MIB
# Produced by pysmi-0.3.4 at Wed May  1 13:29:27 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
Integer, OctetString, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "Integer", "OctetString", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
SingleValueConstraint, ConstraintsUnion, ValueRangeConstraint, ConstraintsIntersection, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "SingleValueConstraint", "ConstraintsUnion", "ValueRangeConstraint", "ConstraintsIntersection", "ValueSizeConstraint")
hh3cCommon, = mibBuilder.importSymbols("HH3C-OID-MIB", "hh3cCommon")
EntryStatus, OwnerString = mibBuilder.importSymbols("RMON-MIB", "EntryStatus", "OwnerString")
NotificationGroup, ModuleCompliance = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance")
Counter32, Unsigned32, ObjectIdentity, IpAddress, Gauge32, Counter64, ModuleIdentity, Integer32, iso, Bits, MibScalar, MibTable, MibTableRow, MibTableColumn, NotificationType, TimeTicks, MibIdentifier = mibBuilder.importSymbols("SNMPv2-SMI", "Counter32", "Unsigned32", "ObjectIdentity", "IpAddress", "Gauge32", "Counter64", "ModuleIdentity", "Integer32", "iso", "Bits", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "NotificationType", "TimeTicks", "MibIdentifier")
TextualConvention, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "DisplayString")
hh3cRmonExt = ModuleIdentity((1, 3, 6, 1, 4, 1, 25506, 2, 125))
hh3cRmonExt.setRevisions(('2012-06-19 00:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: hh3cRmonExt.setRevisionsDescriptions(('The initial revision of this MIB module.',))
if mibBuilder.loadTexts: hh3cRmonExt.setLastUpdated('201206190000Z')
if mibBuilder.loadTexts: hh3cRmonExt.setOrganization('Hangzhou H3C Tech. Co., Ltd.')
if mibBuilder.loadTexts: hh3cRmonExt.setContactInfo('Platform Team Hangzhou H3C Tech. Co., Ltd. Hai-Dian District Beijing P.R. China http://www.h3c.com Zip:100085 ')
if mibBuilder.loadTexts: hh3cRmonExt.setDescription('The private MIB module for managing remote monitoring device implementations.')
hh3cRmonExtAlarmTable = MibTable((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1), )
if mibBuilder.loadTexts: hh3cRmonExtAlarmTable.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmTable.setDescription('A list of alarm entries.')
hh3cRmonExtAlarmEntry = MibTableRow((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1), ).setIndexNames((0, "HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmIndex"))
if mibBuilder.loadTexts: hh3cRmonExtAlarmEntry.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmEntry.setDescription('A list of parameters that set up a periodic checking for alarm conditions. For example, an instance of the alarmValue object might be named alarmValue.8')
hh3cRmonExtAlarmIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hh3cRmonExtAlarmIndex.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmIndex.setDescription('An index that uniquely identifies an entry in the alarm table. Each such entry defines a diagnostic sample at a particular interval for an object on the device.')
hh3cRmonExtAlarmInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(10, 65535)).clone(1800)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmInterval.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmInterval.setDescription('The interval in seconds over which the data is sampled and compared with the rising and falling thresholds. When setting this variable, care should be taken in the case of deltaValue sampling - the interval should be set short enough that the sampled variable is very unlikely to increase or decrease by more than 2^31 - 1 during a single sampling interval. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmVariable = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 3), DisplayString()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmVariable.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmVariable.setDescription('The object identifier of the particular variable to be sampled. Only variables that resolve to an ASN.1 primitive type of INTEGER (INTEGER, Integer32, Unsigned32, Counter32, Counter64, Gauge, or TimeTicks) may be sampled. Because SNMP access control is articulated entirely in terms of the contents of MIB views, no access control mechanism exists that can restrict the value of this object to identify only those objects that exist in a particular MIB view. Because there is thus no acceptable means of restricting the read access that could be obtained through the alarm mechanism, the probe must only grant write access to this object in those views that have read access to all objects on the probe. During a set operation, if the supplied variable name is not available in the selected MIB view, a badValue error must be returned. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmSympol = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 4), DisplayString()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmSympol.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmSympol.setDescription('A comment describing this alarm entry. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmSampleType = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("absoluteValue", 1), ("deltaValue", 2), ("speedValue", 3))).clone('absoluteValue')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmSampleType.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmSampleType.setDescription('The method of sampling the selected variable and calculating the value to be compared against the thresholds. If the value of this object is absoluteValue, the value of the selected variable will be compared directly with the thresholds at the end of the sampling interval. If the value of this object is deltaValue, the value of the selected variable at the last sample will be subtracted from the current value, and the difference compared with the thresholds. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmValue = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hh3cRmonExtAlarmValue.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmValue.setDescription('The value of the statistic during the last sampling period. For example, if the sample type is deltaValue, this value will be the difference between the samples at the beginning and end of the period. If the sample type is absoluteValue, this value will be the sampled value at the end of the period. This is the value that is compared with the rising and falling thresholds. The value during the current sampling period is not made available until the period is completed and will remain available until the next period completes.')
hh3cRmonExtAlarmStartupAlarm = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 7), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("risingAlarm", 1), ("fallingAlarm", 2), ("risingOrFallingAlarm", 3))).clone('risingOrFallingAlarm')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmStartupAlarm.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmStartupAlarm.setDescription('The alarm that may be sent when this entry is first set to valid. If the first sample after this entry becomes valid is greater than or equal to the risingThreshold and alarmStartupAlarm is equal to risingAlarm or risingOrFallingAlarm, then a single rising alarm will be generated. If the first sample after this entry becomes valid is less than or equal to the fallingThreshold and alarmStartupAlarm is equal to fallingAlarm or risingOrFallingAlarm, then a single falling alarm will be generated. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmRisingThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 8), Integer32().clone(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmRisingThreshold.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmRisingThreshold.setDescription('A threshold for the sampled statistic. When the current sampled value is greater than or equal to this threshold, and the value at the last sampling interval was less than this threshold, a single event will be generated. A single event will also be generated if the first sample after this entry becomes valid is greater than or equal to this threshold and the associated alarmStartupAlarm is equal to risingAlarm or risingOrFallingAlarm. After a rising event is generated, another such event will not be generated until the sampled value falls below this threshold and reaches the alarmFallingThreshold. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmFallingThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 9), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmFallingThreshold.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmFallingThreshold.setDescription('A threshold for the sampled statistic. When the current sampled value is less than or equal to this threshold, and the value at the last sampling interval was greater than this threshold, a single event will be generated. A single event will also be generated if the first sample after this entry becomes valid is less than or equal to this threshold and the associated alarmStartupAlarm is equal to fallingAlarm or risingOrFallingAlarm. After a falling event is generated, another such event will not be generated until the sampled value rises above this threshold and reaches the alarmRisingThreshold. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmRisingEvtIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmRisingEvtIndex.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmRisingEvtIndex.setDescription('The index of the eventEntry that is used when a rising threshold is crossed. The eventEntry identified by a particular value of this index is the same as identified by the same value of the eventIndex object. If there is no corresponding entry in the eventTable, then no association exists. In particular, if this value is zero, no associated event will be generated, as zero is not a valid event index. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmFallingEvtIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 11), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 65535))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmFallingEvtIndex.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmFallingEvtIndex.setDescription('The index of the eventEntry that is used when a falling threshold is crossed. The eventEntry identified by a particular value of this index is the same as identified by the same value of the eventIndex object. If there is no corresponding entry in the eventTable, then no association exists. In particular, if this value is zero, no associated event will be generated, as zero is not a valid event index. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmStatCycle = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 12), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmStatCycle.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmStatCycle.setDescription('The lifetime (in seconds) starts when an alarm entry is set in valid state. If the entry has an infinite lifetime, the value of this object MUST be 0. Otherwise the value MUST be greater than the value of hh3cRmonExtAlarmInterval. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmStatType = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 13), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("forever", 1), ("during", 2))).clone('forever')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmStatType.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmStatType.setDescription('This object indicates whether the entry has an infinite or limited lifetime. This object may not be modified if the associated alarmStatus object is equal to valid.')
hh3cRmonExtAlarmOwner = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 14), OwnerString()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmOwner.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmOwner.setDescription('The entity that configured this entry and is therefore using the resources assigned to it. The defalut value of this object is zero length string.')
hh3cRmonExtAlarmStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 25506, 2, 125, 1, 1, 15), EntryStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hh3cRmonExtAlarmStatus.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtAlarmStatus.setDescription('The status of this alarm entry.')
hh3cRmonExtEvent = ObjectIdentity((1, 3, 6, 1, 4, 1, 25506, 2, 125, 0))
if mibBuilder.loadTexts: hh3cRmonExtEvent.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtEvent.setDescription('Definition point for notifications.')
hh3cRmonExtRisingAlarm = NotificationType((1, 3, 6, 1, 4, 1, 25506, 2, 125, 0, 1)).setObjects(("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmIndex"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmSympol"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmSampleType"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmValue"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmRisingThreshold"))
if mibBuilder.loadTexts: hh3cRmonExtRisingAlarm.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtRisingAlarm.setDescription('The SNMP trap that is generated when an alarm entry crosses its rising threshold and generates an event that is configured for sending SNMP traps.')
hh3cRmonExtFallingAlarm = NotificationType((1, 3, 6, 1, 4, 1, 25506, 2, 125, 0, 2)).setObjects(("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmIndex"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmSympol"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmSampleType"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmValue"), ("HH3C-RMON-EXT2-MIB", "hh3cRmonExtAlarmFallingThreshold"))
if mibBuilder.loadTexts: hh3cRmonExtFallingAlarm.setStatus('current')
if mibBuilder.loadTexts: hh3cRmonExtFallingAlarm.setDescription('The SNMP trap that is generated when an alarm entry crosses its falling threshold and generates an event that is configured for sending SNMP traps.')
mibBuilder.exportSymbols("HH3C-RMON-EXT2-MIB", hh3cRmonExtAlarmRisingThreshold=hh3cRmonExtAlarmRisingThreshold, hh3cRmonExtAlarmStatType=hh3cRmonExtAlarmStatType, hh3cRmonExtAlarmInterval=hh3cRmonExtAlarmInterval, hh3cRmonExtAlarmSympol=hh3cRmonExtAlarmSympol, hh3cRmonExtRisingAlarm=hh3cRmonExtRisingAlarm, hh3cRmonExtAlarmStartupAlarm=hh3cRmonExtAlarmStartupAlarm, hh3cRmonExtAlarmVariable=hh3cRmonExtAlarmVariable, hh3cRmonExtAlarmEntry=hh3cRmonExtAlarmEntry, hh3cRmonExtAlarmTable=hh3cRmonExtAlarmTable, hh3cRmonExtEvent=hh3cRmonExtEvent, hh3cRmonExtAlarmFallingThreshold=hh3cRmonExtAlarmFallingThreshold, hh3cRmonExtFallingAlarm=hh3cRmonExtFallingAlarm, hh3cRmonExtAlarmIndex=hh3cRmonExtAlarmIndex, hh3cRmonExtAlarmStatus=hh3cRmonExtAlarmStatus, hh3cRmonExtAlarmRisingEvtIndex=hh3cRmonExtAlarmRisingEvtIndex, PYSNMP_MODULE_ID=hh3cRmonExt, hh3cRmonExtAlarmSampleType=hh3cRmonExtAlarmSampleType, hh3cRmonExtAlarmValue=hh3cRmonExtAlarmValue, hh3cRmonExtAlarmOwner=hh3cRmonExtAlarmOwner, hh3cRmonExtAlarmFallingEvtIndex=hh3cRmonExtAlarmFallingEvtIndex, hh3cRmonExtAlarmStatCycle=hh3cRmonExtAlarmStatCycle, hh3cRmonExt=hh3cRmonExt)
