#
# PySNMP MIB module HPN-ICF-DOT11-RRM-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/HPN-ICF-DOT11-RRM-MIB
# Produced by pysmi-0.3.4 at Wed May  1 13:38:11 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, ObjectIdentifier, Integer = mibBuilder.importSymbols("ASN1", "OctetString", "ObjectIdentifier", "Integer")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsUnion, ValueSizeConstraint, ValueRangeConstraint, ConstraintsIntersection, SingleValueConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsUnion", "ValueSizeConstraint", "ValueRangeConstraint", "ConstraintsIntersection", "SingleValueConstraint")
hpnicfDot11APElementIndex, HpnicfDot11RadioScopeType, HpnicfDot11SSIDStringType, HpnicfDot11ObjectIDType, hpnicfDot11, HpnicfDot11RadioType, HpnicfDot11RadioElementIndex, HpnicfDot11ChannelScopeType = mibBuilder.importSymbols("HPN-ICF-DOT11-REF-MIB", "hpnicfDot11APElementIndex", "HpnicfDot11RadioScopeType", "HpnicfDot11SSIDStringType", "HpnicfDot11ObjectIDType", "hpnicfDot11", "HpnicfDot11RadioType", "HpnicfDot11RadioElementIndex", "HpnicfDot11ChannelScopeType")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
MibIdentifier, NotificationType, IpAddress, Counter32, Counter64, Gauge32, iso, TimeTicks, ObjectIdentity, Bits, MibScalar, MibTable, MibTableRow, MibTableColumn, ModuleIdentity, Integer32, Unsigned32 = mibBuilder.importSymbols("SNMPv2-SMI", "MibIdentifier", "NotificationType", "IpAddress", "Counter32", "Counter64", "Gauge32", "iso", "TimeTicks", "ObjectIdentity", "Bits", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "ModuleIdentity", "Integer32", "Unsigned32")
DateAndTime, RowStatus, TextualConvention, DisplayString, TruthValue, MacAddress = mibBuilder.importSymbols("SNMPv2-TC", "DateAndTime", "RowStatus", "TextualConvention", "DisplayString", "TruthValue", "MacAddress")
hpnicfDot11RRM = ModuleIdentity((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8))
hpnicfDot11RRM.setRevisions(('2010-09-25 18:00', '2010-02-23 18:00', '2009-08-01 20:00', '2009-05-07 20:00', '2009-04-17 20:00', '2008-07-14 14:29',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: hpnicfDot11RRM.setRevisionsDescriptions(('Modified to add new nodes.', 'Modified to add new nodes.', 'Modified to add new nodes and new table.', 'Modified to add new nodes and new table.', 'Modified to add new table and new group.', 'The initial revision of this MIB module.',))
if mibBuilder.loadTexts: hpnicfDot11RRM.setLastUpdated('201009251800Z')
if mibBuilder.loadTexts: hpnicfDot11RRM.setOrganization('')
if mibBuilder.loadTexts: hpnicfDot11RRM.setContactInfo('')
if mibBuilder.loadTexts: hpnicfDot11RRM.setDescription('This MIB file is to provide the object definition of WLAN radio resource management (RRM).')
hpnicfDot11RRMConfigGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1))
hpnicfDot11RRMGlobalCfgPara = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1))
hpnicfDot11RRM11nMadtMaxMcs = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(ValueRangeConstraint(0, 76), ValueRangeConstraint(255, 255), )).clone(255)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11nMadtMaxMcs.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11nMadtMaxMcs.setDescription('Specify the maximum modulation and coding scheme (MCS) index for 802.11n mandatory rates. The value 255 indicates that no maximum MCS index is specified. No maximum MCS index is specified for 802.11n mandatory rates by default. Besides 255, the specified maximum MCS index for 802.11n supported rates must be no less than the specified maximum MCS index for 802.11n mandatory rates.')
hpnicfDot11RRM11nSuptMaxMcs = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 76)).clone(76)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11nSuptMaxMcs.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11nSuptMaxMcs.setDescription('Specify the maximum Modulation and Coding Scheme (MCS) index for 802.11n supported rates. The specified maximum MCS index for 802.11n supported rates must be no less than the specified maximum MCS index for 802.11n mandatory rates.')
hpnicfDot11RRM11gProtect = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 3), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11gProtect.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11gProtect.setDescription('Enable/Disable dot11g protection.')
hpnicfDot11RRM11aPwrConstrt = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 4), Integer32()).setUnits('dBm').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11aPwrConstrt.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11aPwrConstrt.setDescription('Configure the power constraint for all 802.11a radios. The configured power constraint is advertised in beacons if spectrum management is enabled. The range of power constraint is 0 to MAX-POWER-1 (where the MAX-POWER is defined by the regulatory domain).')
hpnicfDot11RRM11aSpectrumManag = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 5), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11aSpectrumManag.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11aSpectrumManag.setDescription('Enable/Disable spectrum management for 802.11a radios. When spectrum management is enabled, the WLAN sub-system advertises power capabilities of the AP and power constraints applicable to all devices in the BSS based on regulatory domain specification.')
hpnicfDot11RRMAutoChlAvoid11h = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 6), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMAutoChlAvoid11h.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAutoChlAvoid11h.setDescription('Configure the auto-channel set as non-dot11h channels, this is, only the non-dot11h channels belonging to the country code are scanned during initial channel selection and one of them is selected.')
hpnicfDot11RRMScanChl = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 7), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("auto", 1), ("all", 2))).clone('auto')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMScanChl.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMScanChl.setDescription('Set the scan mode. auto: When this option is set, all channels of the country code being set are scanned. all: When this option is set, all the channels of the radio band are scanned.')
hpnicfDot11RRMScanRptIntvel = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(5, 120)).clone(10)).setUnits('second').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMScanRptIntvel.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMScanRptIntvel.setDescription('Set the scan report interval.')
hpnicfDot11APInterfNumThreshhd = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 9), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11APInterfNumThreshhd.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11APInterfNumThreshhd.setDescription('Represents threshold of AP interference . If the value of AP interference exceeds this threshold, AP interference trap will be sent. If the value of this node is zero, AP interference trap will be sent immediately.')
hpnicfDot11StaInterfNumThreshhd = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 10), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11StaInterfNumThreshhd.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11StaInterfNumThreshhd.setDescription('Represents threshold of STA interference. If the value of STA interference exceeds this threshold, STA interference trap will be sent. If the value of this node is zero, STA interference trap will be sent immediately. ')
hpnicfDot11RRM11nMultiCastMcs = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 11), Unsigned32().subtype(subtypeSpec=ConstraintsUnion(ValueRangeConstraint(0, 76), ValueRangeConstraint(4294967295, 4294967295), )).clone(4294967295)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11nMultiCastMcs.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11nMultiCastMcs.setDescription('Specify the modulation and coding scheme (MCS) index for 802.11n multicast rates. The value 4294967295 indicates that no MCS index is specified. No MCS index is specified for 802.11n multicast rates by default. Besides 4294967295, the specified MCS index for 802.11n multicast rates must be no less than the specified maximum MCS index for 802.11n mandatory rates. Before configure the MCS index for 802.11n multicast rates, the maximum MCS index for 802.11n mandatory rates must be configured')
hpnicfDot11RRM11acMadtMaxNss = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 12), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 8))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11acMadtMaxNss.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11acMadtMaxNss.setDescription('Specify the maximum NSS index for 802.11ac mandatory rates. The value 0 indicates that no maximum NSS index is specified. No maximum NSS index is specified for 802.11ac mandatory rates by default. The specified maximum NSS index for 802.11ac supported rates must be no less than the specified maximum NSS index for 802.11ac mandatory rates.')
hpnicfDot11RRM11acSuptMaxNss = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 13), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8)).clone(8)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11acSuptMaxNss.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11acSuptMaxNss.setDescription('Specify the maximum NSS index for 802.11ac supported rates. The specified maximum NSS index for 802.11ac supported rates must be no less than the specified maximum NSS index for 802.11ac mandatory rates.')
hpnicfDot11RRM11acMultiCastNss = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 14), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 8))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11acMultiCastNss.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11acMultiCastNss.setDescription('Specify the NSS index for 802.11ac multicast rates. The value 0 indicates that no NSS index is specified. No NSS index is specified for 802.11ac multicast rates by default. The specified NSS index for 802.11ac multicast rates must be no less than the specified maximum NSS index for 802.11ac mandatory rates. Before configuring the NSS index for 802.11ac multicast rates, the maximum NSS index for 802.11ac mandatory rates must be configured. Besides, it must be configured together with the node below.')
hpnicfDot11RRM11acMultiCastVhtMcs = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 1, 15), Integer32().subtype(subtypeSpec=ConstraintsUnion(ValueRangeConstraint(0, 9), ValueRangeConstraint(255, 255), )).clone(255)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRM11acMultiCastVhtMcs.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRM11acMultiCastVhtMcs.setDescription('Specify the MCS index for 802.11ac multicast rates. The value 255 indicates that no MCS index is specified. No MCS index is specified for 802.11ac multicast rates by default. Besides, it must be configured together with the node above.')
hpnicfDot11RRMRadioCfgTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2), )
if mibBuilder.loadTexts: hpnicfDot11RRMRadioCfgTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioCfgTable.setDescription('Configure WLAN RRM based radio type. When 802.11b parameter is modified, 802.11g parameter will be changed at the same time. In the same way, when 802.11g parameter is modified, 802.11b parameter will be changed at the same time.')
hpnicfDot11RRMRadioCfgEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioType"))
if mibBuilder.loadTexts: hpnicfDot11RRMRadioCfgEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioCfgEntry.setDescription('Configure WLAN RRM based radio type. When 802.11b parameter is modified, 802.11g parameter will be changed at the same time. In the same way, when 802.11g parameter is modified, 802.11b parameter will be changed at the same time.')
hpnicfDot11RRMRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 1), HpnicfDot11RadioType())
if mibBuilder.loadTexts: hpnicfDot11RRMRadioType.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioType.setDescription('802.11 radio type.')
hpnicfDot11RRMCfgChlState = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 2), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgChlState.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgChlState.setDescription('Enable/Disable dynamic channel selection.')
hpnicfDot11RRMCfgChlMode = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("selfDecisive", 1), ("userTriggered", 2))).clone('userTriggered')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgChlMode.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgChlMode.setDescription('Configure the mode of channel selection. This node can be configured only when dynamic channel selection is enabled.')
hpnicfDot11RRMChlProntoRadioElmt = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 4), Unsigned32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMChlProntoRadioElmt.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlProntoRadioElmt.setDescription('Specify the AP and radio that will change channel at next calibration cycle. 0 is returned when getting the value of this node. This node can be configured only when the mode of channel selection control is user-triggered. When configuring, the higher 24 bits stand for the AP index, and the last 8 bits stand for the radio index. 4294967295 stand for configuring each radio on all APs.')
hpnicfDot11RRMCfgPwrState = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 5), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgPwrState.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgPwrState.setDescription('Enable/Disable dynamic power selection for the band.')
hpnicfDot11RRMCfgPwrMode = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("selfDecisive", 1), ("userTriggered", 2))).clone('userTriggered')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgPwrMode.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgPwrMode.setDescription('Configure the mode of transmit power control. This node can be configured only when dynamic power selection is enabled.')
hpnicfDot11RRMPwrProntoRadioElmt = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 7), Unsigned32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMPwrProntoRadioElmt.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMPwrProntoRadioElmt.setDescription('Specify the AP and radio that will change power at next calibration cycle. 0 is returned when getting the value of this node. This node can be configured only when the mode of transmit power control is user-triggered. When configuring, the higher 24 bits stand for the AP index, and the last 8 bits stand for the radio index. 4294967295 stand for configuring each radio on all APs.')
hpnicfDot11RRMCfgIntrvl = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 8), Integer32().clone(8)).setUnits('minute').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgIntrvl.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgIntrvl.setDescription('Configure the calibration interval.')
hpnicfDot11RRMCfgIntrfThres = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(40, 100)).clone(50)).setUnits('percent').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgIntrfThres.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgIntrfThres.setDescription('Configure the interface threshold. By default, interference observed on an operating channel is considered during dynamic frequency selection and transmit power control. If the interference percentage on the channel reaches the set threshold, RRM will perform resource adjustment to control the situation.')
hpnicfDot11RRMCfgNoiseThres = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(-127, 127)).clone(-70)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgNoiseThres.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgNoiseThres.setDescription('Configure the noise threshold.')
hpnicfDot11RRMCfgPERThres = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 11), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 100)).clone(20)).setUnits('percent').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgPERThres.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgPERThres.setDescription('Configure the CRC error threshold. If the percentage of CRC errors reaches the threshold, RRM will perform resource adjustment to control the situation.')
hpnicfDot11RRMCfgToleranceFctr = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 12), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 45)).clone(20)).setUnits('percent').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgToleranceFctr.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgToleranceFctr.setDescription('Configure the tolerance level. During dynamic frequency selection (DFS), the channel will be changed only if there is a better channel having lesser interference and packet error rate than those specified by the user.')
hpnicfDot11RRMCfgAdjacencyFctr = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 2, 1, 13), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 16)).clone(3)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCfgAdjacencyFctr.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCfgAdjacencyFctr.setDescription('Configure the adjacency factor for the band. If transmit power control (TPC) is configured, power will be adjusted when the nth neighbor is detected. The value n is the adjacency factor.')
hpnicfDot11RRMAPCfgTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 3), )
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfgTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfgTable.setDescription('This table defines the RRM parameters for AP.')
hpnicfDot11RRMAPCfgEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 3, 1), ).setIndexNames((0, "HPN-ICF-DOT11-REF-MIB", "hpnicfDot11APElementIndex"))
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfgEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfgEntry.setDescription('Each entry contains information of RRM parameters for AP.')
hpnicfDot11RRMAPWorkMode = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 3, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("normal", 1), ("monitor", 2), ("hybrid", 3)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMAPWorkMode.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPWorkMode.setDescription('AP work mode.')
hpnicfDot11RRMSDRadioGroupTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4), )
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupTable.setDescription('This table defines RRM self-decisive radio group.')
hpnicfDot11RRMSDRadioGroupEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMSDRadioGroupId"))
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupEntry.setDescription('Each entry contains information of one RRM self-decisive radio group.')
hpnicfDot11RRMSDRadioGroupId = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4, 1, 1), Unsigned32())
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupId.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupId.setDescription('Represents RRM self-decisive radio group ID.')
hpnicfDot11RRMSDRadioGroupDesc = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4, 1, 2), OctetString()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupDesc.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRadioGroupDesc.setDescription('Represents the description of RRM self-decisive radio group.')
hpnicfDot11RRMSDRdGrpChlHolddownTm = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4, 1, 3), Unsigned32()).setUnits('minute').setMaxAccess("readcreate")
if mibBuilder.loadTexts: hpnicfDot11RRMSDRdGrpChlHolddownTm.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRdGrpChlHolddownTm.setDescription('Represents the channel holddown time of RRM self-decisive radio group.')
hpnicfDot11RRMSDRdGrpPwrHolddownTm = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4, 1, 4), Unsigned32()).setUnits('minute').setMaxAccess("readcreate")
if mibBuilder.loadTexts: hpnicfDot11RRMSDRdGrpPwrHolddownTm.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRdGrpPwrHolddownTm.setDescription('Represents the power holddown time of RRM self-decisive radio group.')
hpnicfDot11RRMSDRdGroupRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 4, 1, 5), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hpnicfDot11RRMSDRdGroupRowStatus.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMSDRdGroupRowStatus.setDescription('The row status of this table entry.')
hpnicfDot11RRMAPCfg2Table = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5), )
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfg2Table.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfg2Table.setDescription('This table defines the RRM parameters for AP.')
hpnicfDot11RRMAPCfg2Entry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMAPSerialID"))
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfg2Entry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPCfg2Entry.setDescription('Each entry contains information of RRM parameters for AP.')
hpnicfDot11RRMAPSerialID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5, 1, 1), HpnicfDot11ObjectIDType())
if mibBuilder.loadTexts: hpnicfDot11RRMAPSerialID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPSerialID.setDescription('Serial ID of the AP.')
hpnicfDot11RRMAPIntfThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5, 1, 2), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMAPIntfThreshold.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAPIntfThreshold.setDescription('Represents threshold of AP interference . If the number of AP interference exceeds this threshold, AP interference trap will be sent.')
hpnicfDot11RRMStaIntfThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5, 1, 3), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMStaIntfThreshold.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMStaIntfThreshold.setDescription('Represents threshold of STA interference. If the number of STA interference exceeds this threshold, station interference trap will be sent.')
hpnicfDot11RRMCoChlIntfTrapThhd = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5, 1, 4), Integer32()).setUnits('dbm').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMCoChlIntfTrapThhd.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMCoChlIntfTrapThhd.setDescription('Represents threshold of interference trap with current ap. If signal strength of the device exceeds this threshold, corresponding trap will be sent.')
hpnicfDot11RRMAdjChlIntfTrapThhd = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 1, 5, 1, 5), Integer32()).setUnits('dbm').setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMAdjChlIntfTrapThhd.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMAdjChlIntfTrapThhd.setDescription('Represents threshold of adjacent interference trap with current ap. If signal strength of the device exceeds this threshold, corresponding trap will be sent.')
hpnicfDot11RRMDetectGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2))
hpnicfDot11RRMChlRptTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1), )
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptTable.setDescription('This table shows the RRM channel information of each radio on all APs.')
hpnicfDot11RRMChlRptEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioIndex"), (0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMChlRptChlNum"))
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptEntry.setDescription('Each entry contains information of RRM channel information of the radio on the AP.')
hpnicfDot11RRMRadioIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 1), HpnicfDot11RadioElementIndex()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: hpnicfDot11RRMRadioIndex.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioIndex.setDescription('Represents index of the radio.')
hpnicfDot11RRMChlRptChlNum = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 2), Integer32()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptChlNum.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptChlNum.setDescription('Channel number.')
hpnicfDot11RRMChlRptChlType = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("primeChannel", 1), ("offChannel", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptChlType.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptChlType.setDescription('Channel type.')
hpnicfDot11RRMChlRptChlQlty = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("good", 1), ("bad", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptChlQlty.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptChlQlty.setDescription('Channel quality.')
hpnicfDot11RRMChlRptNbrCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptNbrCnt.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptNbrCnt.setDescription('Number of neighbors found on the channel.')
hpnicfDot11RRMChlRptLoad = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptLoad.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptLoad.setDescription('Load observed on the channel in percentage.')
hpnicfDot11RRMChlRptUtlz = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptUtlz.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptUtlz.setDescription('Utilization of the channel in percentage.')
hpnicfDot11RRMChlRptIntrf = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptIntrf.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptIntrf.setDescription('Interference observed on the channel in percentage.')
hpnicfDot11RRMChlRptPER = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptPER.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptPER.setDescription('Packet error rate observed on the channel in percentage.')
hpnicfDot11RRMChlRptRetryRate = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptRetryRate.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptRetryRate.setDescription('Percentage of retransmission happened on the channel.')
hpnicfDot11RRMChlRptNoise = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptNoise.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptNoise.setDescription('Noise observed on the channel.')
hpnicfDot11RRMChlRptRadarIndtcr = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 1, 1, 12), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("detected", 1), ("notDetected", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptRadarIndtcr.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMChlRptRadarIndtcr.setDescription('Radar detection status.')
hpnicfDot11RRMNbrInfoTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2), )
if mibBuilder.loadTexts: hpnicfDot11RRMNbrInfoTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMNbrInfoTable.setDescription('This table shows the RRM neighbor information of each radio on all APs.')
hpnicfDot11RRMNbrInfoEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioIndex"), (0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RrmNbrBSSID"))
if mibBuilder.loadTexts: hpnicfDot11RRMNbrInfoEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMNbrInfoEntry.setDescription('Each entry contains information of RRM neighbor information of the radio on an AP.')
hpnicfDot11RrmNbrBSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1, 1), MacAddress())
if mibBuilder.loadTexts: hpnicfDot11RrmNbrBSSID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RrmNbrBSSID.setDescription('MAC address of the AP.')
hpnicfDot11RrmNbrChl = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1, 2), HpnicfDot11ChannelScopeType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RrmNbrChl.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RrmNbrChl.setDescription('Channel number on which the neighbor was found.')
hpnicfDot11RRMNbrIntrf = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMNbrIntrf.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMNbrIntrf.setDescription('Interference observed on the channel in percentage by neighbor.')
hpnicfDot11RrmNbrRSSI = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1, 4), Integer32()).setUnits('dBm').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RrmNbrRSSI.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RrmNbrRSSI.setDescription('Signal strength of the AP in dBm.')
hpnicfDot11RrmNbrType = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("managed", 1), ("unmanaged", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RrmNbrType.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RrmNbrType.setDescription('Type of the AP, managed or unmanaged.')
hpnicfDot11RrmNbrSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 2, 1, 6), HpnicfDot11SSIDStringType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RrmNbrSSID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RrmNbrSSID.setDescription('SSID of the Neighbor.')
hpnicfDot11RRMHistoryTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3), )
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryTable.setDescription('This table shows the details of the latest three channel changes and power changes applied on all APs, including time of change, reason of the change and the channel, power, interference parameters.')
hpnicfDot11RRMHistoryEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioIndex"), (0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMHistoryId"), (0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMHistoryRecIndctr"))
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryEntry.setDescription('Each entry shows the details of channel and power changes.')
hpnicfDot11RRMHistoryId = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 1), Integer32())
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryId.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryId.setDescription('History number of the change.')
hpnicfDot11RRMHistoryRecIndctr = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("before", 1), ("after", 2))))
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryRecIndctr.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryRecIndctr.setDescription('History record type of the change.')
hpnicfDot11RRMHistoryChl = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 3), HpnicfDot11ChannelScopeType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryChl.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryChl.setDescription('Channel on which the radio operates before/after the change of channel or power.')
hpnicfDot11RRMHistoryPwr = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 4), Integer32()).setUnits('dBm').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryPwr.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryPwr.setDescription('Power of the radio before/after the change of channel or power.')
hpnicfDot11RRMHistoryLoad = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryLoad.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryLoad.setDescription('Load observed on the radio in percentage before/after the change of channel or power.')
hpnicfDot11RRMHistoryUtlz = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryUtlz.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryUtlz.setDescription('Utilization of the radio in percentage before/after the change of channel or power.')
hpnicfDot11RRMHistoryIntrf = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryIntrf.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryIntrf.setDescription('Interference observed on the radio in percentage before/after the change of channel or power.')
hpnicfDot11RRMHistoryNoise = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryNoise.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryNoise.setDescription('Noise observed on the radio before/after the change of channel or power.')
hpnicfDot11RRMHistoryPER = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryPER.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryPER.setDescription('Packet error rate observed on the radio in percentage before/after the change of channel or power.')
hpnicfDot11RRMHistoryRetryRate = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryRetryRate.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryRetryRate.setDescription('Percentage of retransmission happened on the radio before/after the change of channel or power.')
hpnicfDot11RRMHistoryChgReason = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 11), Bits().clone(namedValues=NamedValues(("others", 0), ("coverage", 1), ("radar", 2), ("retransmission", 3), ("packetsDiscarded", 4), ("interference", 5)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryChgReason.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryChgReason.setDescription('Reason for the change of channel or power. The various bit positions are: |0 |Others | |1 |Coverage | |2 |Radar | |3 |Retransmission | |4 |Packets discarded | |5 |Interference | 0 is returned when the history record type is after.')
hpnicfDot11RRMHistoryChgDateTime = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 3, 1, 12), DateAndTime()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryChgDateTime.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMHistoryChgDateTime.setDescription('The time when the channel or power change occurred.')
hpnicfDot11RRMRadioNbrInfoTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 4), )
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrInfoTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrInfoTable.setDescription('This table shows the RRM neighbor information of each radio on all APs.')
hpnicfDot11RRMRadioNbrInfoEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 4, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioNbrAPID"), (0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioNbrRadioID"))
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrInfoEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrInfoEntry.setDescription('Each entry contains information of RRM neighbor information of the radio on an AP.')
hpnicfDot11RRMRadioNbrAPID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 4, 1, 1), HpnicfDot11ObjectIDType())
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrAPID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrAPID.setDescription('AP serial id.')
hpnicfDot11RRMRadioNbrRadioID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 4, 1, 2), HpnicfDot11RadioScopeType())
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrRadioID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrRadioID.setDescription('Radio Id on AP.')
hpnicfDot11RRMRadioNbrSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 2, 4, 1, 3), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrSSID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMRadioNbrSSID.setDescription('All neighbour SSIDs scanned by the selected radio.')
hpnicfDot11RRMNotifyGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3))
hpnicfDot11RRMChlQltyNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 1))
hpnicfDot11RRMChlQltyNtfPrefix = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 1, 0))
hpnicfDot11RRMIntrfLimit = NotificationType((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 1, 0, 1)).setObjects(("HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMChlRptIntrf"))
if mibBuilder.loadTexts: hpnicfDot11RRMIntrfLimit.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMIntrfLimit.setDescription('This notification will be sent when interference on the radio exceeds the limit.')
hpnicfDot11RRMPERLimit = NotificationType((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 1, 0, 2)).setObjects(("HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMChlRptPER"))
if mibBuilder.loadTexts: hpnicfDot11RRMPERLimit.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMPERLimit.setDescription('This notification will be sent when packet error rate on the radio exceeds the limit.')
hpnicfDot11RRMNoiseLimit = NotificationType((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 1, 0, 3)).setObjects(("HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMChlRptNoise"))
if mibBuilder.loadTexts: hpnicfDot11RRMNoiseLimit.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMNoiseLimit.setDescription('This notification will be sent when noise on the radio exceeds the limit.')
hpnicfDot11RRMResChgNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 2))
hpnicfDot11RRMResChgNtfPrefix = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 2, 0))
hpnicfDot11RRMPowerChange = NotificationType((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 2, 0, 1)).setObjects(("HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11RRMRadioIndex"), ("HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11NewPower"), ("HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11OldPower"))
if mibBuilder.loadTexts: hpnicfDot11RRMPowerChange.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11RRMPowerChange.setDescription('This notification will be sent when power changed on the radio automatically.')
hpnicfDot11RRMNotificationsVar = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 3))
hpnicfDot11NewPower = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 3, 1), Integer32()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: hpnicfDot11NewPower.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11NewPower.setDescription('Power of the radio after the change of power.')
hpnicfDot11OldPower = MibScalar((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 3, 3, 2), Integer32()).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: hpnicfDot11OldPower.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11OldPower.setDescription('Power of the radio before the change of power.')
hpnicfDot11MonitorDetectedGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4))
hpnicfDot11MonitorDetectedDevTable = MibTable((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1), )
if mibBuilder.loadTexts: hpnicfDot11MonitorDetectedDevTable.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDetectedDevTable.setDescription('This table shows the devices of AP detected')
hpnicfDot11MonitorDetectedDevEntry = MibTableRow((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1), ).setIndexNames((0, "HPN-ICF-DOT11-RRM-MIB", "hpnicfDot11MonitorDevMAC"), (0, "HPN-ICF-DOT11-REF-MIB", "hpnicfDot11APElementIndex"))
if mibBuilder.loadTexts: hpnicfDot11MonitorDetectedDevEntry.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDetectedDevEntry.setDescription('Each entry contains information of detected devices.')
hpnicfDot11MonitorDevMAC = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 1), MacAddress())
if mibBuilder.loadTexts: hpnicfDot11MonitorDevMAC.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevMAC.setDescription('Represents MAC address of the device detected.')
hpnicfDot11MonitorDevType = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))).clone(namedValues=NamedValues(("client", 1), ("ap", 2), ("adhoc", 3), ("wirelessBridge", 4), ("unknown", 5)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevType.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevType.setDescription('Represents type of the device detected.')
hpnicfDot11MonitorDevVendor = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 3), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevVendor.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevVendor.setDescription('Represents vendor of the detected device.')
hpnicfDot11MonitorDevSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 4), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevSSID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevSSID.setDescription('Represents the service set identifier for the ESS of the device which type is ap or adhoc.')
hpnicfDot11MonitorDevBSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 5), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevBSSID.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevBSSID.setDescription('Represents the basic service set identifier of the detected device.')
hpnicfDot11MonitorDevChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 6), HpnicfDot11ChannelScopeType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevChannel.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevChannel.setDescription('Represents the channel in which the device was last detected. AP will choose the channel which has maximum signal strength as effective channel, as there is interference between adjacent channels.')
hpnicfDot11MonitorRadioId = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 7), HpnicfDot11RadioScopeType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorRadioId.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorRadioId.setDescription('Represents the radio ID of the AP that detected the device.')
hpnicfDot11MonitorDevMaxRSSI = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 8), Integer32()).setUnits('dbm').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevMaxRSSI.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevMaxRSSI.setDescription('Represents the maximum detected RSSI of the device in a scan report cycle.')
hpnicfDot11MonitorDevBeaconIntvl = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 9), Integer32()).setUnits('millisecond').setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevBeaconIntvl.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevBeaconIntvl.setDescription('Represents the beacon interval for the detected device(not include the device which type is client).')
hpnicfDot11MonitorDevFstDctTime = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 10), DateAndTime()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevFstDctTime.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevFstDctTime.setDescription('Represents the time at which the device was first detected.')
hpnicfDot11MonitorDevLstDctTime = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 11), DateAndTime()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevLstDctTime.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevLstDctTime.setDescription('Represents the time at which the device was detected last time.')
hpnicfDot11MonitorDevClear = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 12), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevClear.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevClear.setDescription('This object is used to clear the information of the device detected in the WLAN. It will return false for get operation.')
hpnicfDot11MonitorDevSNR = MibTableColumn((1, 3, 6, 1, 4, 1, 11, 2, 14, 11, 15, 2, 75, 8, 4, 1, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hpnicfDot11MonitorDevSNR.setStatus('current')
if mibBuilder.loadTexts: hpnicfDot11MonitorDevSNR.setDescription('Represents the SNR of the device in a scan report cycle.')
mibBuilder.exportSymbols("HPN-ICF-DOT11-RRM-MIB", hpnicfDot11RRMHistoryPER=hpnicfDot11RRMHistoryPER, hpnicfDot11RRMConfigGroup=hpnicfDot11RRMConfigGroup, hpnicfDot11RRMRadioNbrAPID=hpnicfDot11RRMRadioNbrAPID, hpnicfDot11MonitorDevChannel=hpnicfDot11MonitorDevChannel, hpnicfDot11MonitorDevSNR=hpnicfDot11MonitorDevSNR, hpnicfDot11RRMHistoryId=hpnicfDot11RRMHistoryId, hpnicfDot11RRMChlQltyNtfPrefix=hpnicfDot11RRMChlQltyNtfPrefix, hpnicfDot11RRMChlRptNbrCnt=hpnicfDot11RRMChlRptNbrCnt, hpnicfDot11RRMHistoryTable=hpnicfDot11RRMHistoryTable, hpnicfDot11RRMChlQltyNotifications=hpnicfDot11RRMChlQltyNotifications, hpnicfDot11RRMIntrfLimit=hpnicfDot11RRMIntrfLimit, hpnicfDot11MonitorDetectedDevTable=hpnicfDot11MonitorDetectedDevTable, hpnicfDot11MonitorDevLstDctTime=hpnicfDot11MonitorDevLstDctTime, hpnicfDot11RRMChlRptRadarIndtcr=hpnicfDot11RRMChlRptRadarIndtcr, hpnicfDot11RRMRadioNbrSSID=hpnicfDot11RRMRadioNbrSSID, hpnicfDot11RRMRadioNbrInfoEntry=hpnicfDot11RRMRadioNbrInfoEntry, hpnicfDot11RRMRadioCfgEntry=hpnicfDot11RRMRadioCfgEntry, hpnicfDot11RRMHistoryLoad=hpnicfDot11RRMHistoryLoad, hpnicfDot11RRMSDRadioGroupEntry=hpnicfDot11RRMSDRadioGroupEntry, hpnicfDot11OldPower=hpnicfDot11OldPower, hpnicfDot11RRMResChgNtfPrefix=hpnicfDot11RRMResChgNtfPrefix, hpnicfDot11RRMCfgPwrMode=hpnicfDot11RRMCfgPwrMode, hpnicfDot11MonitorDevSSID=hpnicfDot11MonitorDevSSID, hpnicfDot11RRMSDRadioGroupTable=hpnicfDot11RRMSDRadioGroupTable, hpnicfDot11MonitorDevMaxRSSI=hpnicfDot11MonitorDevMaxRSSI, hpnicfDot11RRMRadioNbrRadioID=hpnicfDot11RRMRadioNbrRadioID, hpnicfDot11RRM11nSuptMaxMcs=hpnicfDot11RRM11nSuptMaxMcs, hpnicfDot11RRMChlProntoRadioElmt=hpnicfDot11RRMChlProntoRadioElmt, hpnicfDot11RrmNbrRSSI=hpnicfDot11RrmNbrRSSI, hpnicfDot11RRMGlobalCfgPara=hpnicfDot11RRMGlobalCfgPara, hpnicfDot11MonitorDevVendor=hpnicfDot11MonitorDevVendor, PYSNMP_MODULE_ID=hpnicfDot11RRM, hpnicfDot11RRMAPCfg2Entry=hpnicfDot11RRMAPCfg2Entry, hpnicfDot11RRMRadioNbrInfoTable=hpnicfDot11RRMRadioNbrInfoTable, hpnicfDot11RRMHistoryIntrf=hpnicfDot11RRMHistoryIntrf, hpnicfDot11RRMSDRdGrpPwrHolddownTm=hpnicfDot11RRMSDRdGrpPwrHolddownTm, hpnicfDot11RRM11gProtect=hpnicfDot11RRM11gProtect, hpnicfDot11RRMCfgPwrState=hpnicfDot11RRMCfgPwrState, hpnicfDot11RRMCfgPERThres=hpnicfDot11RRMCfgPERThres, hpnicfDot11MonitorDevClear=hpnicfDot11MonitorDevClear, hpnicfDot11RRMRadioIndex=hpnicfDot11RRMRadioIndex, hpnicfDot11MonitorDevMAC=hpnicfDot11MonitorDevMAC, hpnicfDot11RRMPowerChange=hpnicfDot11RRMPowerChange, hpnicfDot11RRM11acMadtMaxNss=hpnicfDot11RRM11acMadtMaxNss, hpnicfDot11RRMChlRptLoad=hpnicfDot11RRMChlRptLoad, hpnicfDot11RRMHistoryChgReason=hpnicfDot11RRMHistoryChgReason, hpnicfDot11RRMCfgChlMode=hpnicfDot11RRMCfgChlMode, hpnicfDot11RRMAPCfg2Table=hpnicfDot11RRMAPCfg2Table, hpnicfDot11RRMSDRdGroupRowStatus=hpnicfDot11RRMSDRdGroupRowStatus, hpnicfDot11RRMHistoryChl=hpnicfDot11RRMHistoryChl, hpnicfDot11RRMAPSerialID=hpnicfDot11RRMAPSerialID, hpnicfDot11RRM=hpnicfDot11RRM, hpnicfDot11RRMHistoryPwr=hpnicfDot11RRMHistoryPwr, hpnicfDot11MonitorDevType=hpnicfDot11MonitorDevType, hpnicfDot11RRMHistoryRecIndctr=hpnicfDot11RRMHistoryRecIndctr, hpnicfDot11RRMChlRptTable=hpnicfDot11RRMChlRptTable, hpnicfDot11RRMPERLimit=hpnicfDot11RRMPERLimit, hpnicfDot11MonitorDetectedGroup=hpnicfDot11MonitorDetectedGroup, hpnicfDot11RRMCfgNoiseThres=hpnicfDot11RRMCfgNoiseThres, hpnicfDot11RRMChlRptEntry=hpnicfDot11RRMChlRptEntry, hpnicfDot11RRMCfgAdjacencyFctr=hpnicfDot11RRMCfgAdjacencyFctr, hpnicfDot11RRM11nMultiCastMcs=hpnicfDot11RRM11nMultiCastMcs, hpnicfDot11MonitorDetectedDevEntry=hpnicfDot11MonitorDetectedDevEntry, hpnicfDot11RRMCfgIntrvl=hpnicfDot11RRMCfgIntrvl, hpnicfDot11RRMPwrProntoRadioElmt=hpnicfDot11RRMPwrProntoRadioElmt, hpnicfDot11RRMChlRptNoise=hpnicfDot11RRMChlRptNoise, hpnicfDot11RRMChlRptUtlz=hpnicfDot11RRMChlRptUtlz, hpnicfDot11RRMNotifyGroup=hpnicfDot11RRMNotifyGroup, hpnicfDot11RRMSDRadioGroupDesc=hpnicfDot11RRMSDRadioGroupDesc, hpnicfDot11RRMCfgToleranceFctr=hpnicfDot11RRMCfgToleranceFctr, hpnicfDot11RRMCfgIntrfThres=hpnicfDot11RRMCfgIntrfThres, hpnicfDot11RRMNoiseLimit=hpnicfDot11RRMNoiseLimit, hpnicfDot11RRMDetectGroup=hpnicfDot11RRMDetectGroup, hpnicfDot11RRMChlRptChlType=hpnicfDot11RRMChlRptChlType, hpnicfDot11MonitorRadioId=hpnicfDot11MonitorRadioId, hpnicfDot11RRMAPIntfThreshold=hpnicfDot11RRMAPIntfThreshold, hpnicfDot11RRMScanRptIntvel=hpnicfDot11RRMScanRptIntvel, hpnicfDot11MonitorDevFstDctTime=hpnicfDot11MonitorDevFstDctTime, hpnicfDot11RRMChlRptRetryRate=hpnicfDot11RRMChlRptRetryRate, hpnicfDot11RRMRadioType=hpnicfDot11RRMRadioType, hpnicfDot11RRMSDRadioGroupId=hpnicfDot11RRMSDRadioGroupId, hpnicfDot11RRMStaIntfThreshold=hpnicfDot11RRMStaIntfThreshold, hpnicfDot11RRMAPCfgTable=hpnicfDot11RRMAPCfgTable, hpnicfDot11RRMNbrInfoTable=hpnicfDot11RRMNbrInfoTable, hpnicfDot11RRMAdjChlIntfTrapThhd=hpnicfDot11RRMAdjChlIntfTrapThhd, hpnicfDot11RRMAPCfgEntry=hpnicfDot11RRMAPCfgEntry, hpnicfDot11RRM11aPwrConstrt=hpnicfDot11RRM11aPwrConstrt, hpnicfDot11RRMCoChlIntfTrapThhd=hpnicfDot11RRMCoChlIntfTrapThhd, hpnicfDot11RRMChlRptIntrf=hpnicfDot11RRMChlRptIntrf, hpnicfDot11RRMHistoryUtlz=hpnicfDot11RRMHistoryUtlz, hpnicfDot11RRM11acSuptMaxNss=hpnicfDot11RRM11acSuptMaxNss, hpnicfDot11RRM11aSpectrumManag=hpnicfDot11RRM11aSpectrumManag, hpnicfDot11RrmNbrSSID=hpnicfDot11RrmNbrSSID, hpnicfDot11RRMHistoryEntry=hpnicfDot11RRMHistoryEntry, hpnicfDot11RRM11nMadtMaxMcs=hpnicfDot11RRM11nMadtMaxMcs, hpnicfDot11RRMChlRptChlQlty=hpnicfDot11RRMChlRptChlQlty, hpnicfDot11RRMSDRdGrpChlHolddownTm=hpnicfDot11RRMSDRdGrpChlHolddownTm, hpnicfDot11StaInterfNumThreshhd=hpnicfDot11StaInterfNumThreshhd, hpnicfDot11RRMNotificationsVar=hpnicfDot11RRMNotificationsVar, hpnicfDot11RRMAutoChlAvoid11h=hpnicfDot11RRMAutoChlAvoid11h, hpnicfDot11MonitorDevBSSID=hpnicfDot11MonitorDevBSSID, hpnicfDot11RRMRadioCfgTable=hpnicfDot11RRMRadioCfgTable, hpnicfDot11RRMHistoryRetryRate=hpnicfDot11RRMHistoryRetryRate, hpnicfDot11RrmNbrBSSID=hpnicfDot11RrmNbrBSSID, hpnicfDot11RRMResChgNotifications=hpnicfDot11RRMResChgNotifications, hpnicfDot11RRMAPWorkMode=hpnicfDot11RRMAPWorkMode, hpnicfDot11RRM11acMultiCastNss=hpnicfDot11RRM11acMultiCastNss, hpnicfDot11NewPower=hpnicfDot11NewPower, hpnicfDot11RRMScanChl=hpnicfDot11RRMScanChl, hpnicfDot11RRMNbrInfoEntry=hpnicfDot11RRMNbrInfoEntry, hpnicfDot11RRM11acMultiCastVhtMcs=hpnicfDot11RRM11acMultiCastVhtMcs, hpnicfDot11RRMCfgChlState=hpnicfDot11RRMCfgChlState, hpnicfDot11RRMChlRptChlNum=hpnicfDot11RRMChlRptChlNum, hpnicfDot11MonitorDevBeaconIntvl=hpnicfDot11MonitorDevBeaconIntvl, hpnicfDot11RRMHistoryNoise=hpnicfDot11RRMHistoryNoise, hpnicfDot11RrmNbrChl=hpnicfDot11RrmNbrChl, hpnicfDot11RRMNbrIntrf=hpnicfDot11RRMNbrIntrf, hpnicfDot11RRMHistoryChgDateTime=hpnicfDot11RRMHistoryChgDateTime, hpnicfDot11RrmNbrType=hpnicfDot11RrmNbrType, hpnicfDot11RRMChlRptPER=hpnicfDot11RRMChlRptPER, hpnicfDot11APInterfNumThreshhd=hpnicfDot11APInterfNumThreshhd)
