#
# PySNMP MIB module HUAWEI-ALARM-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/HUAWEI-ALARM-MIB
# Produced by pysmi-0.3.4 at Wed May  1 13:42:46 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, Integer, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "OctetString", "Integer", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, ValueSizeConstraint, ValueRangeConstraint, SingleValueConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "ValueSizeConstraint", "ValueRangeConstraint", "SingleValueConstraint")
hwDatacomm, = mibBuilder.importSymbols("HUAWEI-MIB", "hwDatacomm")
NotificationGroup, ModuleCompliance, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance", "ObjectGroup")
MibScalar, MibTable, MibTableRow, MibTableColumn, NotificationType, ModuleIdentity, iso, Bits, Gauge32, ObjectIdentity, Integer32, Counter32, IpAddress, MibIdentifier, TimeTicks, Counter64, Unsigned32 = mibBuilder.importSymbols("SNMPv2-SMI", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "NotificationType", "ModuleIdentity", "iso", "Bits", "Gauge32", "ObjectIdentity", "Integer32", "Counter32", "IpAddress", "MibIdentifier", "TimeTicks", "Counter64", "Unsigned32")
RowStatus, TextualConvention, DateAndTime, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "RowStatus", "TextualConvention", "DateAndTime", "DisplayString")
hwAlarmMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180))
hwAlarmMIB.setRevisions(('2013-10-28 09:43', '2013-10-18 16:43', '2009-12-05 11:50',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: hwAlarmMIB.setRevisionsDescriptions(('Revert to the revision 2.10.', 'Add history alarm MIB.', 'The initial revision of this MIB module .',))
if mibBuilder.loadTexts: hwAlarmMIB.setLastUpdated('201310280943Z')
if mibBuilder.loadTexts: hwAlarmMIB.setOrganization('Huawei Technologies Co.,Ltd.')
if mibBuilder.loadTexts: hwAlarmMIB.setContactInfo("Huawei Industrial Base Bantian, Longgang Shenzhen 518129 People's Republic of China Website: http://www.huawei.com Email: support@huawei.com")
if mibBuilder.loadTexts: hwAlarmMIB.setDescription('The MIB module for creating and deleting bulk files of SNMP data for file transfer.')
hwAlarmObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1))
hwSnmpTargetAddrExtTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1), )
if mibBuilder.loadTexts: hwSnmpTargetAddrExtTable.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrExtTable.setDescription('Define snmp target Address extend table.')
hwSnmpTargetAddrExtEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"))
if mibBuilder.loadTexts: hwSnmpTargetAddrExtEntry.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrExtEntry.setDescription('The entry of the extended snmp target address table.')
hwSnmpTargetAddrExtIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1, 1), OctetString().subtype(subtypeSpec=ValueSizeConstraint(1, 32))).setMaxAccess("accessiblefornotify")
if mibBuilder.loadTexts: hwSnmpTargetAddrExtIndex.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrExtIndex.setDescription('the extended target address table index.')
hwSnmpTargetSlaveAddressList = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1, 2), OctetString().subtype(subtypeSpec=ValueSizeConstraint(1, 255))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwSnmpTargetSlaveAddressList.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetSlaveAddressList.setDescription('Address of slave target host.')
hwSnmpTargetAddrReliability = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwSnmpTargetAddrReliability.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrReliability.setDescription('If enable, then the extend VBs will be added to the alarm parameters. ')
hwSnmpTargetAddrAlarmReliability = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwSnmpTargetAddrAlarmReliability.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrAlarmReliability.setDescription('Alarm reliability function enable flag.')
hwSnmpTargetAddrEventReliability = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2))).clone('enable')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwSnmpTargetAddrEventReliability.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrEventReliability.setDescription('Event reliability function enable flag. ')
hwSnmpTargetAddrExtRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 1, 1, 6), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwSnmpTargetAddrExtRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetAddrExtRowStatus.setDescription('The row status of the target extend table.')
hwMinAlarmSyncIndex = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMinAlarmSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMinAlarmSyncIndex.setDescription('The minimal index value for alarm synchronization.')
hwMaxAlarmSyncIndex = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMaxAlarmSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMaxAlarmSyncIndex.setDescription('The maximal index value for alarm synchronization. ')
hwAlarmSyncTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 4), )
if mibBuilder.loadTexts: hwAlarmSyncTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncTable.setDescription('Alarm synchronization table. ')
hwAlarmSyncEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 4, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"), (0, "HUAWEI-ALARM-MIB", "hwAlarmSyncIndex"))
if mibBuilder.loadTexts: hwAlarmSyncEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncEntry.setDescription('Alarm synchronization table entry.')
hwAlarmSyncIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 4, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647)))
if mibBuilder.loadTexts: hwAlarmSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncIndex.setDescription('Alarm synchronization index.')
hwAlarmSyncId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 4, 1, 2), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmSyncId.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncId.setDescription('Alarm id ')
hwAlarmSyncPara = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 4, 1, 3), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 1400))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmSyncPara.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncPara.setDescription('This object indicates the information contained in the binding variable list of the alarm message.')
hwMinEventSyncIndex = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 5), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMinEventSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMinEventSyncIndex.setDescription('The minimal index value for event synchronization.')
hwMaxEventSyncIndex = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 6), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMaxEventSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMaxEventSyncIndex.setDescription('The maximal index value for event synchronization. ')
hwEventSyncTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 7), )
if mibBuilder.loadTexts: hwEventSyncTable.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncTable.setDescription('The event synchronization table.')
hwEventSyncEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 7, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"), (0, "HUAWEI-ALARM-MIB", "hwEventSyncIndex"))
if mibBuilder.loadTexts: hwEventSyncEntry.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncEntry.setDescription('The event synchronization table entry.')
hwEventSyncIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 7, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647)))
if mibBuilder.loadTexts: hwEventSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncIndex.setDescription('The event synchronization index value.')
hwEventSyncId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 7, 1, 2), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventSyncId.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncId.setDescription('The event id.')
hwEventSyncPara = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 7, 1, 3), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 1400))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventSyncPara.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncPara.setDescription('This object indicates the information contained in the binding variable list of an event.')
hwAlarmActiveTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 8), )
if mibBuilder.loadTexts: hwAlarmActiveTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmActiveTable.setDescription('The active alarm table.')
hwAlarmActiveEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 8, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"), (0, "HUAWEI-ALARM-MIB", "hwActiveAlarmIndex"))
if mibBuilder.loadTexts: hwAlarmActiveEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmActiveEntry.setDescription('Entries appear in this table when alarms are raised. They are removed when the alarm is cleared.')
hwActiveAlarmIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 8, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647)))
if mibBuilder.loadTexts: hwActiveAlarmIndex.setStatus('current')
if mibBuilder.loadTexts: hwActiveAlarmIndex.setDescription('A strictly monotonically increasing integer which acts as the index of all alarms and events. It wraps back to 1 after it reaches its maximum value.')
hwActiveAlarmId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 8, 1, 2), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwActiveAlarmId.setStatus('current')
if mibBuilder.loadTexts: hwActiveAlarmId.setDescription('The id of an alarm.')
hwActiveAlarmPara = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 8, 1, 3), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 1400))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwActiveAlarmPara.setStatus('current')
if mibBuilder.loadTexts: hwActiveAlarmPara.setDescription('This object indicates the parameters of an active alarm.')
hwActiveAlarmRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 8, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwActiveAlarmRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwActiveAlarmRowStatus.setDescription('This object indicates the row status.')
hwEventTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 9), )
if mibBuilder.loadTexts: hwEventTable.setStatus('current')
if mibBuilder.loadTexts: hwEventTable.setDescription('The event table. ')
hwEventEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 9, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"), (0, "HUAWEI-ALARM-MIB", "hwEventIndex"))
if mibBuilder.loadTexts: hwEventEntry.setStatus('current')
if mibBuilder.loadTexts: hwEventEntry.setDescription('Entries appear in this table when events are raised.')
hwEventIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 9, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647)))
if mibBuilder.loadTexts: hwEventIndex.setStatus('current')
if mibBuilder.loadTexts: hwEventIndex.setDescription('A strictly monotonically increasing integer which acts as the index of all alarms and events. It wraps back to 1 after it reaches its maximum value.')
hwEventId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 9, 1, 2), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventId.setStatus('current')
if mibBuilder.loadTexts: hwEventId.setDescription('This object indicates the OID of an event.')
hwEventPara = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 9, 1, 3), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 1400))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventPara.setStatus('current')
if mibBuilder.loadTexts: hwEventPara.setDescription('This object indicates the parameter information of an event.')
hwEventRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 9, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwEventRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwEventRowStatus.setDescription('This object indicates the row status.')
hwAlarmDateAndTime = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 18), DateAndTime())
if mibBuilder.loadTexts: hwAlarmDateAndTime.setStatus('current')
if mibBuilder.loadTexts: hwAlarmDateAndTime.setDescription('This object indicates the time when an alarm is generated or cleared.')
hwAlarmOrEventFlag = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 19), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("alarm", 1), ("event", 2))))
if mibBuilder.loadTexts: hwAlarmOrEventFlag.setStatus('current')
if mibBuilder.loadTexts: hwAlarmOrEventFlag.setDescription('Indicates the type of alarm messages. 1: Alarm 2: Event ')
hwAlarmReasonInfo = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 20), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 255)))
if mibBuilder.loadTexts: hwAlarmReasonInfo.setStatus('current')
if mibBuilder.loadTexts: hwAlarmReasonInfo.setDescription('The reason for the alarm.')
hwAlarmSeverity = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 25), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6))).clone(namedValues=NamedValues(("critical", 1), ("major", 2), ("minor", 3), ("warning", 4), ("indeterminate", 5), ("cleared", 6))))
if mibBuilder.loadTexts: hwAlarmSeverity.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSeverity.setDescription('Alarm severity.')
hwSnmpTargetSyncIndexTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 28), )
if mibBuilder.loadTexts: hwSnmpTargetSyncIndexTable.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetSyncIndexTable.setDescription('The synchronization index of snmp targets table.')
hwSnmpTargetSyncIndexEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 28, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"))
if mibBuilder.loadTexts: hwSnmpTargetSyncIndexEntry.setStatus('current')
if mibBuilder.loadTexts: hwSnmpTargetSyncIndexEntry.setDescription('The entry of the synchronization index table.')
hwMinAlmSyncIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 28, 1, 1), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMinAlmSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMinAlmSyncIndex.setDescription('The minimal index value for alarm synchronization.')
hwMaxAlmSyncIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 28, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMaxAlmSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMaxAlmSyncIndex.setDescription('The maximal index value for alarm synchronization. ')
hwMinEvtSyncIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 28, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMinEvtSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMinEvtSyncIndex.setDescription('The minimal index value for event synchronization.')
hwMaxEvtSyncIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 28, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwMaxEvtSyncIndex.setStatus('current')
if mibBuilder.loadTexts: hwMaxEvtSyncIndex.setDescription('The maximal index value for event synchronization. ')
hwAlarmActiveVsTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 31), )
if mibBuilder.loadTexts: hwAlarmActiveVsTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmActiveVsTable.setDescription('The active alarm management table for LSVS support version. ')
hwAlarmActiveVsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 31, 1), )
hwAlarmActiveEntry.registerAugmentions(("HUAWEI-ALARM-MIB", "hwAlarmActiveVsEntry"))
hwAlarmActiveVsEntry.setIndexNames(*hwAlarmActiveEntry.getIndexNames())
if mibBuilder.loadTexts: hwAlarmActiveVsEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmActiveVsEntry.setDescription('The active alarm table for VS support version. ')
hwAlarmActiveVsId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 31, 1, 9), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmActiveVsId.setStatus('current')
if mibBuilder.loadTexts: hwAlarmActiveVsId.setDescription('The VS id of the alarm. ')
hwEventVsTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 33), )
if mibBuilder.loadTexts: hwEventVsTable.setStatus('current')
if mibBuilder.loadTexts: hwEventVsTable.setDescription('The event table for LSVS support version. ')
hwEventVsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 33, 1), )
hwEventEntry.registerAugmentions(("HUAWEI-ALARM-MIB", "hwEventVsEntry"))
hwEventVsEntry.setIndexNames(*hwEventEntry.getIndexNames())
if mibBuilder.loadTexts: hwEventVsEntry.setStatus('current')
if mibBuilder.loadTexts: hwEventVsEntry.setDescription('The event entry.')
hwEventVsId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 33, 1, 9), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventVsId.setStatus('current')
if mibBuilder.loadTexts: hwEventVsId.setDescription('The VS id of the event. ')
hwAlarmSyncVsTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 36), )
if mibBuilder.loadTexts: hwAlarmSyncVsTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncVsTable.setDescription('Alarm synchronization table. ')
hwAlarmSyncVsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 36, 1), )
hwAlarmSyncEntry.registerAugmentions(("HUAWEI-ALARM-MIB", "hwAlarmSyncVsEntry"))
hwAlarmSyncVsEntry.setIndexNames(*hwAlarmSyncEntry.getIndexNames())
if mibBuilder.loadTexts: hwAlarmSyncVsEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncVsEntry.setDescription('Alarm synchronization table entry.')
hwAlarmSyncVsId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 36, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmSyncVsId.setStatus('current')
if mibBuilder.loadTexts: hwAlarmSyncVsId.setDescription('Alarm VS id.')
hwEventSyncVsTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 39), )
if mibBuilder.loadTexts: hwEventSyncVsTable.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncVsTable.setDescription('The event synchronization table.')
hwEventSyncVsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 39, 1), )
hwEventSyncEntry.registerAugmentions(("HUAWEI-ALARM-MIB", "hwEventSyncVsEntry"))
hwEventSyncVsEntry.setIndexNames(*hwEventSyncEntry.getIndexNames())
if mibBuilder.loadTexts: hwEventSyncVsEntry.setStatus('current')
if mibBuilder.loadTexts: hwEventSyncVsEntry.setDescription('The event synchronization table entry.')
hwEvevtSyncVsId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 1, 39, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEvevtSyncVsId.setStatus('current')
if mibBuilder.loadTexts: hwEvevtSyncVsId.setDescription('The VS id of the event.')
hwAlarmNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 2))
hwAlarmTargetHostDel = NotificationType((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 2, 1)).setObjects(("HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"))
if mibBuilder.loadTexts: hwAlarmTargetHostDel.setStatus('current')
if mibBuilder.loadTexts: hwAlarmTargetHostDel.setDescription('The notification for the deletion of the target host. ')
hwAlarmStorm = NotificationType((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 2, 2))
if mibBuilder.loadTexts: hwAlarmStorm.setStatus('current')
if mibBuilder.loadTexts: hwAlarmStorm.setDescription('The alarm storm notification.')
hwAlarmConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3))
hwAlarmCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 1))
hwAlarmCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 1, 1)).setObjects(("HUAWEI-ALARM-MIB", "hwAlarmReliabilityGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwAlarmCompliance = hwAlarmCompliance.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCompliance.setDescription('The compliance statement for entities which implement the Huawei Alarm mib.')
hwAlarmGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2))
hwAlarmReliabilityGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 1)).setObjects(("HUAWEI-ALARM-MIB", "hwSnmpTargetSlaveAddressList"), ("HUAWEI-ALARM-MIB", "hwSnmpTargetAddrEventReliability"), ("HUAWEI-ALARM-MIB", "hwSnmpTargetAddrAlarmReliability"), ("HUAWEI-ALARM-MIB", "hwSnmpTargetAddrReliability"), ("HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwAlarmReliabilityGroup = hwAlarmReliabilityGroup.setStatus('current')
if mibBuilder.loadTexts: hwAlarmReliabilityGroup.setDescription('The objects for alarm reliability and snmp target address list.')
hwActiveInfoGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 7)).setObjects(("HUAWEI-ALARM-MIB", "hwActiveAlarmId"), ("HUAWEI-ALARM-MIB", "hwActiveAlarmPara"), ("HUAWEI-ALARM-MIB", "hwEventRowStatus"), ("HUAWEI-ALARM-MIB", "hwActiveAlarmRowStatus"), ("HUAWEI-ALARM-MIB", "hwEventId"), ("HUAWEI-ALARM-MIB", "hwEventPara"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwActiveInfoGroup = hwActiveInfoGroup.setStatus('current')
if mibBuilder.loadTexts: hwActiveInfoGroup.setDescription('The nodes for querying the active alarm information.')
hwTrapInfoSyncGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 8)).setObjects(("HUAWEI-ALARM-MIB", "hwMinAlarmSyncIndex"), ("HUAWEI-ALARM-MIB", "hwMaxAlarmSyncIndex"), ("HUAWEI-ALARM-MIB", "hwAlarmSyncId"), ("HUAWEI-ALARM-MIB", "hwAlarmSyncPara"), ("HUAWEI-ALARM-MIB", "hwMinEventSyncIndex"), ("HUAWEI-ALARM-MIB", "hwMaxEventSyncIndex"), ("HUAWEI-ALARM-MIB", "hwEventSyncId"), ("HUAWEI-ALARM-MIB", "hwEventSyncPara"), ("HUAWEI-ALARM-MIB", "hwAlarmDateAndTime"), ("HUAWEI-ALARM-MIB", "hwAlarmCorrAnalyzeSuppressionRootCauseIndication"), ("HUAWEI-ALARM-MIB", "hwAlarmCorrAnalyzeSuppressionParentSequence"), ("HUAWEI-ALARM-MIB", "hwAlarmReasonInfo"), ("HUAWEI-ALARM-MIB", "hwAlarmSeverity"), ("HUAWEI-ALARM-MIB", "hwAlarmOrEventFlag"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwTrapInfoSyncGroup = hwTrapInfoSyncGroup.setStatus('current')
if mibBuilder.loadTexts: hwTrapInfoSyncGroup.setDescription('All information of trap synchronization.')
hwActiveInfoVsGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 9)).setObjects(("HUAWEI-ALARM-MIB", "hwAlarmActiveVsId"), ("HUAWEI-ALARM-MIB", "hwEventVsId"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwActiveInfoVsGroup = hwActiveInfoVsGroup.setStatus('current')
if mibBuilder.loadTexts: hwActiveInfoVsGroup.setDescription('The VS id of the active alarm or event.')
hwTrapSyncVsGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 10)).setObjects(("HUAWEI-ALARM-MIB", "hwAlarmSyncVsId"), ("HUAWEI-ALARM-MIB", "hwEvevtSyncVsId"), ("HUAWEI-ALARM-MIB", "hwMinAlmSyncIndex"), ("HUAWEI-ALARM-MIB", "hwMaxAlmSyncIndex"), ("HUAWEI-ALARM-MIB", "hwMinEvtSyncIndex"), ("HUAWEI-ALARM-MIB", "hwMaxEvtSyncIndex"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwTrapSyncVsGroup = hwTrapSyncVsGroup.setStatus('current')
if mibBuilder.loadTexts: hwTrapSyncVsGroup.setDescription('The VS id and the synchronization sequence number nodes.')
hwAlarmTrapInfoGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 11)).setObjects(("HUAWEI-ALARM-MIB", "hwAlarmTargetHostDel"), ("HUAWEI-ALARM-MIB", "hwAlarmStorm"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwAlarmTrapInfoGroup = hwAlarmTrapInfoGroup.setStatus('current')
if mibBuilder.loadTexts: hwAlarmTrapInfoGroup.setDescription('Alarm trap nodes.')
hwTrapSuppressionGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 12)).setObjects(("HUAWEI-ALARM-MIB", "hwAlarmDelaySuppressionEnable"), ("HUAWEI-ALARM-MIB", "hwAlarmDelaySuppressionCausePersistPeriod"), ("HUAWEI-ALARM-MIB", "hwAlarmDelaySuppressionClearPersistPeriod"), ("HUAWEI-ALARM-MIB", "hwAlarmCorrAnalyzeSuppressionEnable"), ("HUAWEI-ALARM-MIB", "hwAlarmCorrAnalyzeSuppressionStatus"), ("HUAWEI-ALARM-MIB", "hwEventDelaySuppressionEnable"), ("HUAWEI-ALARM-MIB", "hwEventDelaySuppressionCausePersistPeriod"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwTrapSuppressionGroup = hwTrapSuppressionGroup.setStatus('current')
if mibBuilder.loadTexts: hwTrapSuppressionGroup.setDescription('The trap suppression nodes.')
hwTrapInfoGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 3, 2, 13)).setObjects(("HUAWEI-ALARM-MIB", "hwAlarmAttrSeverity"), ("HUAWEI-ALARM-MIB", "hwEventAttrSeverity"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwTrapInfoGroup = hwTrapInfoGroup.setStatus('current')
if mibBuilder.loadTexts: hwTrapInfoGroup.setDescription('The basal information of trap nodes.')
hwAlarmConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5))
hwAlarmAttr = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 1))
hwAlarmAttrTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 1, 1), )
if mibBuilder.loadTexts: hwAlarmAttrTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmAttrTable.setDescription('This table contains attribute of alarms.')
hwAlarmAttrEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 1, 1, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwAlarmName"))
if mibBuilder.loadTexts: hwAlarmAttrEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmAttrEntry.setDescription('Entry of hwAlarmAttrTable.')
hwAlarmName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 1, 1, 1, 1), OctetString().subtype(subtypeSpec=ValueSizeConstraint(1, 64))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmName.setStatus('current')
if mibBuilder.loadTexts: hwAlarmName.setDescription('The name of registered alarms.')
hwAlarmAttrSeverity = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 1, 1, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6))).clone(namedValues=NamedValues(("critical", 1), ("major", 2), ("minor", 3), ("warning", 4), ("indeterminate", 5), ("cleared", 6)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmAttrSeverity.setStatus('current')
if mibBuilder.loadTexts: hwAlarmAttrSeverity.setDescription('The severity of alarms.')
hwAlarmMask = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3))
hwAlarmMaskBasedOnIfnameTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 1), )
if mibBuilder.loadTexts: hwAlarmMaskBasedOnIfnameTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskBasedOnIfnameTable.setDescription('Define alarm mask table, which is based on interface.')
hwAlarmMaskBasedOnIfnameEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 1, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwAlarmMaskIfName"))
if mibBuilder.loadTexts: hwAlarmMaskBasedOnIfnameEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskBasedOnIfnameEntry.setDescription('Entry of hwAlarmMaskBasedOnIfnameTable.')
hwAlarmMaskIfName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 1, 1, 1), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmMaskIfName.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskIfName.setDescription('The interface name for alarm mask.')
hwAlarmMaskBasedOnIfnameRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 1, 1, 51), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwAlarmMaskBasedOnIfnameRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskBasedOnIfnameRowStatus.setDescription('The row status of the alarm mask based on interface table.')
hwAlarmMaskBasedOnEntityTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 2), )
if mibBuilder.loadTexts: hwAlarmMaskBasedOnEntityTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskBasedOnEntityTable.setDescription('Define alarm mask table, which is based on entity index.')
hwAlarmMaskBasedOnEntityEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 2, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwAlarmMaskEntPhysicalIndex"))
if mibBuilder.loadTexts: hwAlarmMaskBasedOnEntityEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskBasedOnEntityEntry.setDescription('Entry of hwAlarmMaskBasedOnEntityTable.')
hwAlarmMaskEntPhysicalIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 2, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwAlarmMaskEntPhysicalIndex.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskEntPhysicalIndex.setDescription('The physical index of entity for alarm mask.')
hwAlarmMaskEntPhysicalName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 2, 1, 2), OctetString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmMaskEntPhysicalName.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskEntPhysicalName.setDescription('The physical name of entity for alarm mask.')
hwAlarmMaskBasedOnEntityRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 3, 2, 1, 51), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwAlarmMaskBasedOnEntityRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwAlarmMaskBasedOnEntityRowStatus.setDescription('The row status of the alarm mask based on entity table.')
hwAlarmDelay = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 4))
hwAlarmDelaySuppressionEnable = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 4, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmDelaySuppressionEnable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmDelaySuppressionEnable.setDescription('The switch of alarm delay suppression. The default is enable.')
hwAlarmDelaySuppressionTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 4, 2), )
if mibBuilder.loadTexts: hwAlarmDelaySuppressionTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmDelaySuppressionTable.setDescription('Define alarm delay suppression table.')
hwAlarmDelaySuppressionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 4, 2, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwAlarmName"))
if mibBuilder.loadTexts: hwAlarmDelaySuppressionEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmDelaySuppressionEntry.setDescription('The entry of the alarm delay suppression table.')
hwAlarmDelaySuppressionCausePersistPeriod = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 4, 2, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 600))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmDelaySuppressionCausePersistPeriod.setStatus('current')
if mibBuilder.loadTexts: hwAlarmDelaySuppressionCausePersistPeriod.setDescription('The cause persist period of alarm delay suppression.')
hwAlarmDelaySuppressionClearPersistPeriod = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 4, 2, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 600))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmDelaySuppressionClearPersistPeriod.setStatus('current')
if mibBuilder.loadTexts: hwAlarmDelaySuppressionClearPersistPeriod.setDescription('The clear persist period of alarm delay suppression.')
hwAlarmCorrAnalyze = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5))
hwAlarmCorrAnalyzeSuppressionEnable = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionEnable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionEnable.setDescription('The switch of alarm correlation analyze suppression.')
hwAlarmCorrAnalyzeSuppressionRootCauseIndication = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2))).clone(namedValues=NamedValues(("independent", 0), ("rootcause", 1), ("nonrootcause", 2))))
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionRootCauseIndication.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionRootCauseIndication.setDescription('If alarm has passed correaltion analysis, this indication is rootcause or nonrootcause, default is independent.')
hwAlarmCorrAnalyzeSuppressionParentSequence = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5, 3), OctetString())
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionParentSequence.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionParentSequence.setDescription('The parent sequence of alarm, whose indication is nonrootcause.')
hwAlarmCorrAnalyzeSuppressionTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5, 4), )
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionTable.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionTable.setDescription('Define alarm correlation analyze suppression table.')
hwAlarmCorrAnalyzeSuppressionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5, 4, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwSnmpTargetAddrExtIndex"))
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionEntry.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionEntry.setDescription('The entry of alarm correlation analyze suppression table.')
hwAlarmCorrAnalyzeSuppressionStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 5, 5, 4, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionStatus.setStatus('current')
if mibBuilder.loadTexts: hwAlarmCorrAnalyzeSuppressionStatus.setDescription('The status of alarm correlation suppression for each target host.')
hwEventConfig = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6))
hwEventAttr = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 1))
hwEventAttrTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 1, 1), )
if mibBuilder.loadTexts: hwEventAttrTable.setStatus('current')
if mibBuilder.loadTexts: hwEventAttrTable.setDescription('This table contains attribute of events.')
hwEventAttrEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 1, 1, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwEventName"))
if mibBuilder.loadTexts: hwEventAttrEntry.setStatus('current')
if mibBuilder.loadTexts: hwEventAttrEntry.setDescription('Entry of hwEventAttrTable.')
hwEventName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 1, 1, 1, 1), OctetString().subtype(subtypeSpec=ValueSizeConstraint(1, 64))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventName.setStatus('current')
if mibBuilder.loadTexts: hwEventName.setDescription('The name of registered events.')
hwEventAttrSeverity = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 1, 1, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6))).clone(namedValues=NamedValues(("critical", 1), ("major", 2), ("minor", 3), ("warning", 4), ("indeterminate", 5), ("cleared", 6)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwEventAttrSeverity.setStatus('current')
if mibBuilder.loadTexts: hwEventAttrSeverity.setDescription('The severity of evens.')
hwEventDelay = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 4))
hwEventDelaySuppressionEnable = MibScalar((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 4, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enable", 1), ("disable", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwEventDelaySuppressionEnable.setStatus('current')
if mibBuilder.loadTexts: hwEventDelaySuppressionEnable.setDescription('The switch of event delay suppression.')
hwEventDelaySuppressionTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 4, 2), )
if mibBuilder.loadTexts: hwEventDelaySuppressionTable.setStatus('current')
if mibBuilder.loadTexts: hwEventDelaySuppressionTable.setDescription('Define event delay suppression table.')
hwEventDelaySuppressionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 4, 2, 1), ).setIndexNames((0, "HUAWEI-ALARM-MIB", "hwEventName"))
if mibBuilder.loadTexts: hwEventDelaySuppressionEntry.setStatus('current')
if mibBuilder.loadTexts: hwEventDelaySuppressionEntry.setDescription('The entry of event delay suppression table.')
hwEventDelaySuppressionCausePersistPeriod = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 180, 6, 4, 2, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 600))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwEventDelaySuppressionCausePersistPeriod.setStatus('current')
if mibBuilder.loadTexts: hwEventDelaySuppressionCausePersistPeriod.setDescription('The cause persist period of event delay suppression.')
mibBuilder.exportSymbols("HUAWEI-ALARM-MIB", hwAlarmDelaySuppressionClearPersistPeriod=hwAlarmDelaySuppressionClearPersistPeriod, hwAlarmCorrAnalyzeSuppressionEntry=hwAlarmCorrAnalyzeSuppressionEntry, hwAlarmActiveVsEntry=hwAlarmActiveVsEntry, hwAlarmDelaySuppressionEntry=hwAlarmDelaySuppressionEntry, hwAlarmMaskBasedOnIfnameRowStatus=hwAlarmMaskBasedOnIfnameRowStatus, hwAlarmAttr=hwAlarmAttr, hwMaxEvtSyncIndex=hwMaxEvtSyncIndex, hwAlarmAttrEntry=hwAlarmAttrEntry, hwEventDelaySuppressionEnable=hwEventDelaySuppressionEnable, hwSnmpTargetAddrReliability=hwSnmpTargetAddrReliability, PYSNMP_MODULE_ID=hwAlarmMIB, hwEventAttrTable=hwEventAttrTable, hwAlarmSyncVsTable=hwAlarmSyncVsTable, hwActiveAlarmId=hwActiveAlarmId, hwEventName=hwEventName, hwAlarmSeverity=hwAlarmSeverity, hwSnmpTargetSlaveAddressList=hwSnmpTargetSlaveAddressList, hwSnmpTargetAddrExtTable=hwSnmpTargetAddrExtTable, hwEventSyncEntry=hwEventSyncEntry, hwEventSyncVsEntry=hwEventSyncVsEntry, hwEventDelaySuppressionEntry=hwEventDelaySuppressionEntry, hwAlarmDelaySuppressionTable=hwAlarmDelaySuppressionTable, hwEventSyncTable=hwEventSyncTable, hwEventEntry=hwEventEntry, hwAlarmSyncIndex=hwAlarmSyncIndex, hwAlarmCompliances=hwAlarmCompliances, hwEventAttrSeverity=hwEventAttrSeverity, hwTrapInfoGroup=hwTrapInfoGroup, hwAlarmMaskBasedOnEntityRowStatus=hwAlarmMaskBasedOnEntityRowStatus, hwEventDelay=hwEventDelay, hwEventSyncPara=hwEventSyncPara, hwAlarmReasonInfo=hwAlarmReasonInfo, hwAlarmDelay=hwAlarmDelay, hwAlarmAttrTable=hwAlarmAttrTable, hwEventConfig=hwEventConfig, hwEventId=hwEventId, hwEventSyncId=hwEventSyncId, hwActiveInfoGroup=hwActiveInfoGroup, hwActiveAlarmRowStatus=hwActiveAlarmRowStatus, hwAlarmMaskBasedOnIfnameEntry=hwAlarmMaskBasedOnIfnameEntry, hwAlarmMaskBasedOnEntityTable=hwAlarmMaskBasedOnEntityTable, hwAlarmSyncId=hwAlarmSyncId, hwEventAttr=hwEventAttr, hwAlarmCorrAnalyzeSuppressionEnable=hwAlarmCorrAnalyzeSuppressionEnable, hwEventDelaySuppressionCausePersistPeriod=hwEventDelaySuppressionCausePersistPeriod, hwAlarmMask=hwAlarmMask, hwSnmpTargetAddrExtIndex=hwSnmpTargetAddrExtIndex, hwAlarmCompliance=hwAlarmCompliance, hwAlarmMaskIfName=hwAlarmMaskIfName, hwEventSyncVsTable=hwEventSyncVsTable, hwSnmpTargetAddrAlarmReliability=hwSnmpTargetAddrAlarmReliability, hwAlarmConfig=hwAlarmConfig, hwAlarmDelaySuppressionEnable=hwAlarmDelaySuppressionEnable, hwSnmpTargetAddrEventReliability=hwSnmpTargetAddrEventReliability, hwEventPara=hwEventPara, hwAlarmMaskEntPhysicalName=hwAlarmMaskEntPhysicalName, hwAlarmActiveEntry=hwAlarmActiveEntry, hwEventAttrEntry=hwEventAttrEntry, hwTrapSyncVsGroup=hwTrapSyncVsGroup, hwAlarmNotifications=hwAlarmNotifications, hwAlarmSyncVsEntry=hwAlarmSyncVsEntry, hwMinEventSyncIndex=hwMinEventSyncIndex, hwEventVsEntry=hwEventVsEntry, hwAlarmGroups=hwAlarmGroups, hwMaxAlmSyncIndex=hwMaxAlmSyncIndex, hwAlarmActiveTable=hwAlarmActiveTable, hwAlarmMIB=hwAlarmMIB, hwSnmpTargetAddrExtEntry=hwSnmpTargetAddrExtEntry, hwTrapSuppressionGroup=hwTrapSuppressionGroup, hwAlarmCorrAnalyzeSuppressionStatus=hwAlarmCorrAnalyzeSuppressionStatus, hwAlarmMaskEntPhysicalIndex=hwAlarmMaskEntPhysicalIndex, hwMinAlarmSyncIndex=hwMinAlarmSyncIndex, hwAlarmDateAndTime=hwAlarmDateAndTime, hwAlarmOrEventFlag=hwAlarmOrEventFlag, hwEventRowStatus=hwEventRowStatus, hwAlarmReliabilityGroup=hwAlarmReliabilityGroup, hwEventSyncIndex=hwEventSyncIndex, hwEventVsTable=hwEventVsTable, hwAlarmSyncPara=hwAlarmSyncPara, hwMaxEventSyncIndex=hwMaxEventSyncIndex, hwSnmpTargetSyncIndexEntry=hwSnmpTargetSyncIndexEntry, hwAlarmObjects=hwAlarmObjects, hwAlarmTargetHostDel=hwAlarmTargetHostDel, hwAlarmAttrSeverity=hwAlarmAttrSeverity, hwAlarmCorrAnalyzeSuppressionTable=hwAlarmCorrAnalyzeSuppressionTable, hwMinEvtSyncIndex=hwMinEvtSyncIndex, hwEvevtSyncVsId=hwEvevtSyncVsId, hwEventIndex=hwEventIndex, hwEventVsId=hwEventVsId, hwAlarmMaskBasedOnIfnameTable=hwAlarmMaskBasedOnIfnameTable, hwAlarmTrapInfoGroup=hwAlarmTrapInfoGroup, hwMaxAlarmSyncIndex=hwMaxAlarmSyncIndex, hwAlarmSyncVsId=hwAlarmSyncVsId, hwAlarmDelaySuppressionCausePersistPeriod=hwAlarmDelaySuppressionCausePersistPeriod, hwAlarmActiveVsTable=hwAlarmActiveVsTable, hwAlarmStorm=hwAlarmStorm, hwActiveAlarmIndex=hwActiveAlarmIndex, hwActiveAlarmPara=hwActiveAlarmPara, hwAlarmCorrAnalyze=hwAlarmCorrAnalyze, hwMinAlmSyncIndex=hwMinAlmSyncIndex, hwAlarmName=hwAlarmName, hwAlarmActiveVsId=hwAlarmActiveVsId, hwActiveInfoVsGroup=hwActiveInfoVsGroup, hwTrapInfoSyncGroup=hwTrapInfoSyncGroup, hwSnmpTargetAddrExtRowStatus=hwSnmpTargetAddrExtRowStatus, hwEventDelaySuppressionTable=hwEventDelaySuppressionTable, hwAlarmSyncTable=hwAlarmSyncTable, hwSnmpTargetSyncIndexTable=hwSnmpTargetSyncIndexTable, hwEventTable=hwEventTable, hwAlarmCorrAnalyzeSuppressionParentSequence=hwAlarmCorrAnalyzeSuppressionParentSequence, hwAlarmSyncEntry=hwAlarmSyncEntry, hwAlarmConformance=hwAlarmConformance, hwAlarmCorrAnalyzeSuppressionRootCauseIndication=hwAlarmCorrAnalyzeSuppressionRootCauseIndication, hwAlarmMaskBasedOnEntityEntry=hwAlarmMaskBasedOnEntityEntry)
