#
# PySNMP MIB module HUAWEI-WLAN-WIDS-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/HUAWEI-WLAN-WIDS-MIB
# Produced by pysmi-0.3.4 at Wed May  1 13:49:58 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
Integer, ObjectIdentifier, OctetString = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsUnion, ValueSizeConstraint, ConstraintsIntersection, ValueRangeConstraint, SingleValueConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsUnion", "ValueSizeConstraint", "ConstraintsIntersection", "ValueRangeConstraint", "SingleValueConstraint")
hwApIndex, hwApType, hwApMac = mibBuilder.importSymbols("HUAWEI-WLAN-DEVICE-MIB", "hwApIndex", "hwApType", "hwApMac")
hwWlan, = mibBuilder.importSymbols("HUAWEI-WLAN-MIB", "hwWlan")
NotificationGroup, ModuleCompliance, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance", "ObjectGroup")
Integer32, Gauge32, ObjectIdentity, IpAddress, ModuleIdentity, TimeTicks, Counter64, MibScalar, MibTable, MibTableRow, MibTableColumn, MibIdentifier, Counter32, iso, Bits, NotificationType, Unsigned32 = mibBuilder.importSymbols("SNMPv2-SMI", "Integer32", "Gauge32", "ObjectIdentity", "IpAddress", "ModuleIdentity", "TimeTicks", "Counter64", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "MibIdentifier", "Counter32", "iso", "Bits", "NotificationType", "Unsigned32")
RowStatus, TextualConvention, MacAddress, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "RowStatus", "TextualConvention", "MacAddress", "DisplayString")
hwWlanWids = ModuleIdentity((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8))
hwWlanWids.setRevisions(('2014-05-04 16:00', '2013-09-04 10:22', '2013-05-21 15:40', '2012-05-10 00:00', '2012-05-08 00:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: hwWlanWids.setRevisionsDescriptions(('V1.03, update for v2r5 change', 'V1.02, update for v2r3 change', 'V1.01, update for v2r3 change', 'V1.01, Add wids device', ' V1.00, Inital version. ',))
if mibBuilder.loadTexts: hwWlanWids.setLastUpdated('201405041600Z')
if mibBuilder.loadTexts: hwWlanWids.setOrganization('Huawei Technologies Co.,Ltd.')
if mibBuilder.loadTexts: hwWlanWids.setContactInfo("Huawei Industrial Base Bantian, Longgang Shenzhen 518129 People's Republic of China Website: http://www.huawei.com Email: support@huawei.com ")
if mibBuilder.loadTexts: hwWlanWids.setDescription('The MIB module include wids informations.')
hwWlanWidsNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1))
hwWlanWidsNotify = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1))
hwWlanWidsRougeDevDetectedNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 1)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevRSSI"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevSSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioId"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPIP"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"))
if mibBuilder.loadTexts: hwWlanWidsRougeDevDetectedNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsRougeDevDetectedNotify.setDescription('Description.')
hwWlanWidsRougeDevClearNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 2)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevRSSI"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevSSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioId"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPIP"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"))
if mibBuilder.loadTexts: hwWlanWidsRougeDevClearNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsRougeDevClearNotify.setDescription('Description.')
hwWlanWidsNonWifiDetNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 3)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPName"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioId"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiDeviceType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiInterChannel"))
if mibBuilder.loadTexts: hwWlanWidsNonWifiDetNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsNonWifiDetNotify.setDescription('Description.')
hwWlanWidsNonWifiClearNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 4)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPName"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioId"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiDeviceType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiInterChannel"))
if mibBuilder.loadTexts: hwWlanWidsNonWifiClearNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsNonWifiClearNotify.setDescription('Description.')
hwWlanWidsFloodAttackDetectedNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 5)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsFloodAttackDetectedNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsFloodAttackDetectedNotify.setDescription('Description.')
hwWlanWidsFloodAttackClearNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 6)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsFloodAttackClearNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsFloodAttackClearNotify.setDescription('Description.')
hwWlanWidsSpoofAttackDetectedNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 7)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsSpoofAttackDetectedNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsSpoofAttackDetectedNotify.setDescription('Description.')
hwWlanWidsSpoofAttackClearNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 8)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsSpoofAttackClearNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsSpoofAttackClearNotify.setDescription('Description.')
hwWlanWidsWeakIvAttackDetectedNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 9)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsWeakIvAttackDetectedNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsWeakIvAttackDetectedNotify.setDescription('Description.')
hwWlanWidsWeakIvAttackClearNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 10)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsWeakIvAttackClearNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsWeakIvAttackClearNotify.setDescription('Description.')
hwWlanWidsPSKAttackDetectedNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 11)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsPSKAttackDetectedNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsPSKAttackDetectedNotify.setDescription('Description.')
hwWlanWidsPSKAttackClearNotify = NotificationType((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 1, 12)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if mibBuilder.loadTexts: hwWlanWidsPSKAttackClearNotify.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsPSKAttackClearNotify.setDescription('Description.')
hwWlanWidsNotifyObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2))
hwWlanObjWidsRogueDevMAC = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 1), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevMAC.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevMAC.setDescription('Description.')
hwWlanObjWidsRogueDevType = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevType.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevType.setDescription('Description.')
hwWlanObjWidsRogueDevChannel = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevChannel.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevChannel.setDescription('Description.')
hwWlanObjWidsRogueDevRSSI = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevRSSI.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevRSSI.setDescription('Description.')
hwWlanObjWidsRogueDevSSID = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 5), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevSSID.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsRogueDevSSID.setDescription('Description.')
hwWlanObjWidsDetAPID = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsDetAPID.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetAPID.setDescription('Description.')
hwWlanObjWidsDetRadioId = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsDetRadioId.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetRadioId.setDescription('Description.')
hwWlanObjWidsDetAPChannel = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsDetAPChannel.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetAPChannel.setDescription('Description.')
hwWlanObjWidsDetAPMAC = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 9), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsDetAPMAC.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetAPMAC.setDescription('Description.')
hwWlanObjWidsDetAPIP = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 10), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsDetAPIP.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetAPIP.setDescription('Description.')
hwWlanObjWidsNonWifiDeviceType = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsNonWifiDeviceType.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsNonWifiDeviceType.setDescription('Description.')
hwWlanObjWidsNonWifiInterChannel = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 12), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsNonWifiInterChannel.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsNonWifiInterChannel.setDescription('Description.')
hwWlanObjWidsNonWifiRssi = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 13), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsNonWifiRssi.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsNonWifiRssi.setDescription('Description.')
hwWlanObjWidsDetAPName = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 14), OctetString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWlanObjWidsDetAPName.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetAPName.setDescription('Description.')
hwWlanObjWidsDetRadioType = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 15), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWlanObjWidsDetRadioType.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsDetRadioType.setDescription('Description.')
hwWlanObjWidsAttackDevMAC = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 16), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsAttackDevMAC.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsAttackDevMAC.setDescription('Description.')
hwWlanObjWidsAttackType = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 17), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsAttackType.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsAttackType.setDescription('Description.')
hwWlanObjWidsAttackTypeStr = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 1, 2, 18), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWlanObjWidsAttackTypeStr.setStatus('current')
if mibBuilder.loadTexts: hwWlanObjWidsAttackTypeStr.setDescription('Description.')
hwWlanWidsGloablOpt = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2))
hwWidsResetDetDevTableAll = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 1), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetDetDevTableAll.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetDetDevTableAll.setDescription('Description.')
hwWidsResetDetDevTableByType = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 2), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetDetDevTableByType.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetDetDevTableByType.setDescription('Description.')
hwWidsResetRogueHistoryAll = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 3), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetRogueHistoryAll.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetRogueHistoryAll.setDescription('Description.')
hwWidsResetRogueHistoryByDevType = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 4), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetRogueHistoryByDevType.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetRogueHistoryByDevType.setDescription('Description.')
hwWidsResetAttackDev = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 5), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetAttackDev.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetAttackDev.setDescription('Description.')
hwWidsResetAttackStat = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 6), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetAttackStat.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetAttackStat.setDescription('Description.')
hwWidsResetDynamicBlacklist = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 7), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetDynamicBlacklist.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetDynamicBlacklist.setDescription('Description.')
hwWidsResetDynamicBlacklistMac = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 8), MacAddress()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetDynamicBlacklistMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetDynamicBlacklistMac.setDescription('Description.')
hwWidsResetAttackHistory = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 2, 9), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwWidsResetAttackHistory.setStatus('current')
if mibBuilder.loadTexts: hwWidsResetAttackHistory.setDescription('Description.')
hwWidsDetDevTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3), )
if mibBuilder.loadTexts: hwWidsDetDevTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevTable.setDescription('Detected device table. ')
hwWidsDetDevEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMac"))
if mibBuilder.loadTexts: hwWidsDetDevEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevEntry.setDescription('Ap UpdateEntry.')
hwWidsDetDevMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 1), MacAddress())
if mibBuilder.loadTexts: hwWidsDetDevMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMac.setDescription('Index. Detected device mac.')
hwWidsDetDevType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevType.setDescription('Detected device type :')
hwWidsDetDevRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevRssi.setDescription('Detected device rssi')
hwWidsDetDevChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevChannel.setDescription('Detected device channel')
hwWidsDetDevSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 5), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevSSID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevSSID.setDescription('Detected device ssid. ')
hwWidsDetDevRogue = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevRogue.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevRogue.setDescription('Detected device is rouge device')
hwWidsDetDevLastTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 7), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevLastTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevLastTime.setDescription('Last Detected time ')
hwWidsDetDevIsCountermeasuresed = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disbale", 1), ("enable", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevIsCountermeasuresed.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevIsCountermeasuresed.setDescription('Description.')
hwWidsDetDevInterference = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevInterference.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevInterference.setDescription('Description.')
hwWidsDetDevBSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 10), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevBSSID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevBSSID.setDescription('Description.')
hwWidsDetDevFirstDetTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 3, 1, 11), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevFirstDetTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevFirstDetTime.setDescription('Description.')
hwWidsDetDevMonitorTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4), )
if mibBuilder.loadTexts: hwWidsDetDevMonitorTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorTable.setDescription('Description.')
hwWidsDetDevMonitorEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMac"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApID"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApRadioID"))
if mibBuilder.loadTexts: hwWidsDetDevMonitorEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorEntry.setDescription('Description.')
hwWidsDetDevMonitorApID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 1), Integer32())
if mibBuilder.loadTexts: hwWidsDetDevMonitorApID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApID.setDescription('Description.')
hwWidsDetDevMonitorApRadioID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 2), Integer32())
if mibBuilder.loadTexts: hwWidsDetDevMonitorApRadioID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApRadioID.setDescription('Description.')
hwWidsDetDevMonitorApMAC = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 3), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorApMAC.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApMAC.setDescription('Description.')
hwWidsDetDevMonitorApIP = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 4), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorApIP.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApIP.setDescription('Description.')
hwWidsDetDevMonitorApChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorApChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApChannel.setDescription('Description.')
hwWidsDetDevMonitorApRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorApRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApRssi.setDescription('Description.')
hwWidsDetDevMonitorApLastDetTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 7), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorApLastDetTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApLastDetTime.setDescription('Description.')
hwWidsDetDevMonitorApCountermeasuresDev = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 8), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("disable", 1), ("enable", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorApCountermeasuresDev.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorApCountermeasuresDev.setDescription('Description.')
hwWidsDetDevMonitorDetAtt = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 4, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetDevMonitorDetAtt.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorDetAtt.setDescription('Description.')
hwWidsRogueHistoryTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5), )
if mibBuilder.loadTexts: hwWidsRogueHistoryTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueHistoryTable.setDescription('Description.')
hwWidsRogueHistoryEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueDevMac"))
if mibBuilder.loadTexts: hwWidsRogueHistoryEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueHistoryEntry.setDescription('Description.')
hwWidsRogueDevMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1, 1), MacAddress())
if mibBuilder.loadTexts: hwWidsRogueDevMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueDevMac.setDescription('Description.')
hwWidsRogueDevType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsRogueDevType.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueDevType.setDescription('Description.')
hwWidsRogueDevRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsRogueDevRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueDevRssi.setDescription('Description.')
hwWidsRogueDevChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsRogueDevChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueDevChannel.setDescription('Description.')
hwWidsRogueDevSSID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1, 5), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsRogueDevSSID.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueDevSSID.setDescription('Description.')
hwWidsRogueDevLastTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 5, 1, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsRogueDevLastTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueDevLastTime.setDescription('Description.')
hwSsidWhitelistTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 6), )
if mibBuilder.loadTexts: hwSsidWhitelistTable.setStatus('current')
if mibBuilder.loadTexts: hwSsidWhitelistTable.setDescription('Description.')
hwSsidWhitelistEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 6, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwSsidWhitelistSsid"))
if mibBuilder.loadTexts: hwSsidWhitelistEntry.setStatus('current')
if mibBuilder.loadTexts: hwSsidWhitelistEntry.setDescription('Description.')
hwSsidWhitelistSsid = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 6, 1, 1), OctetString())
if mibBuilder.loadTexts: hwSsidWhitelistSsid.setStatus('current')
if mibBuilder.loadTexts: hwSsidWhitelistSsid.setDescription('Description.')
hwSsidWhitelisttRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 6, 1, 2), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwSsidWhitelisttRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwSsidWhitelisttRowStatus.setDescription('Description.')
hwWidsDetNonWifiDevTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7), )
if mibBuilder.loadTexts: hwWidsDetNonWifiDevTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevTable.setDescription('Description.')
hwWidsDetNonWifiDevEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevMonitorApMac"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevMonitorRadioId"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiType"))
if mibBuilder.loadTexts: hwWidsDetNonWifiDevEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevEntry.setDescription('Description.')
hwWidsDetNonWifiDevMonitorApMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 1), MacAddress())
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorApMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorApMac.setDescription('Description.')
hwWidsDetNonWifiDevMonitorRadioId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 2), Integer32())
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorRadioId.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorRadioId.setDescription('Description.')
hwWidsDetNonWifiType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 3), Integer32())
if mibBuilder.loadTexts: hwWidsDetNonWifiType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiType.setDescription('Description.')
hwWidsDetNonWifiRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 4), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiRssi.setDescription('Description.')
hwWidsDetNonWifiFrequencyType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiFrequencyType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiFrequencyType.setDescription('Description.')
hwWidsDetNonWifiChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 6), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiChannel.setDescription('Description.')
hwWidsDetNonWifiDevLastTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDevLastTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevLastTime.setDescription('Description.')
hwWidsDetNonWifiCenterFrequency = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiCenterFrequency.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiCenterFrequency.setDescription('Description.')
hwWidsDetNonWifiBandwidth = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiBandwidth.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiBandwidth.setDescription('Description.')
hwWidsDetNonWifiDutycycle = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDutycycle.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDutycycle.setDescription('Description.')
hwWidsDetNonWifiInterferenceLevel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiInterferenceLevel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiInterferenceLevel.setDescription('Description.')
hwWidsDetNonWifiDevMonitorAPName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 12), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorAPName.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorAPName.setDescription('Description.')
hwWidsDetNonWifiDevMonitorAPID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorAPID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorAPID.setDescription('Description.')
hwWidsDetNonWifiDevRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 14), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDevRadioType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevRadioType.setDescription('Description.')
hwWidsDetNonWifiDevMonitorAPChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorAPChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevMonitorAPChannel.setDescription('Description.')
hwWidsDetNonWifiDevFirstTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 7, 1, 16), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiDevFirstTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevFirstTime.setDescription('Description.')
hwWidsAttackHistoryTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8), )
if mibBuilder.loadTexts: hwWidsAttackHistoryTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryTable.setDescription('Description.')
hwWidsAttackHistoryEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistorySeq"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistorySubSeq"))
if mibBuilder.loadTexts: hwWidsAttackHistoryEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryEntry.setDescription('Description.')
hwWidsAttackHistorySeq = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 1), Unsigned32())
if mibBuilder.loadTexts: hwWidsAttackHistorySeq.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistorySeq.setDescription('Description.')
hwWidsAttackHistorySubSeq = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 2), Unsigned32())
if mibBuilder.loadTexts: hwWidsAttackHistorySubSeq.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistorySubSeq.setDescription('Description.')
hwWidsAttackHistoryDevMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 3), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryDevMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryDevMac.setDescription('Description.')
hwWidsAttackHistoryDevType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryDevType.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryDevType.setDescription('Description.')
hwWidsAttackHistoryRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryRssi.setDescription('Description.')
hwWidsAttackHistoryChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryChannel.setDescription('Description.')
hwWidsAttackHistoryAttackType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryAttackType.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryAttackType.setDescription('Description.')
hwWidsAttackHistoryPacketBmp1 = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryPacketBmp1.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryPacketBmp1.setDescription('Description.')
hwWidsAttackHistoryPacketBmp2 = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryPacketBmp2.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryPacketBmp2.setDescription('Description.')
hwWidsAttackHistorySSID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 10), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistorySSID.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistorySSID.setDescription('Description.')
hwWidsAttackHistoryDetTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 11), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryDetTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryDetTime.setDescription('Description.')
hwWidsAttackHistoryDetectorApId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 8, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackHistoryDetectorApId.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryDetectorApId.setDescription('Description.')
hwWidsEnableAPTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 9), )
if mibBuilder.loadTexts: hwWidsEnableAPTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableAPTable.setDescription('Description.')
hwWidsEnableAPEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 9, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsEnableAPID"))
if mibBuilder.loadTexts: hwWidsEnableAPEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableAPEntry.setDescription('Description.')
hwWidsEnableAPID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 9, 1, 1), Integer32())
if mibBuilder.loadTexts: hwWidsEnableAPID.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableAPID.setDescription('Description.')
hwWidsEnableDevDetSwitch = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 9, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsEnableDevDetSwitch.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableDevDetSwitch.setDescription('Description.')
hwWidsEnableAttackDetSwitch = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 9, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsEnableAttackDetSwitch.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableAttackDetSwitch.setDescription('Description.')
hwWidsEnableAPName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 9, 1, 4), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsEnableAPName.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableAPName.setDescription('Description.')
hwWidsAttackStatTable = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10))
hwWidsAttackStatProbeRequestFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 1), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatProbeRequestFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatProbeRequestFloodAttack.setDescription('Description.')
hwWidsAttackStatAuthRequestFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatAuthRequestFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatAuthRequestFloodAttack.setDescription('Description.')
hwWidsAttackStatDeAuthenFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatDeAuthenFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatDeAuthenFloodAttack.setDescription('Description.')
hwWidsAttackStatAssocReqFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatAssocReqFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatAssocReqFloodAttack.setDescription('Description.')
hwWidsAttackStatDisassocReqFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 5), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatDisassocReqFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatDisassocReqFloodAttack.setDescription('Description.')
hwWidsAttackStatReassocReqFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatReassocReqFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatReassocReqFloodAttack.setDescription('Description.')
hwWidsAttackStatActionFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 7), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatActionFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatActionFloodAttack.setDescription('Description.')
hwWidsAttackStatNullDataFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 8), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatNullDataFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatNullDataFloodAttack.setDescription('Description.')
hwWidsAttackStatWeakIvAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 9), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatWeakIvAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatWeakIvAttack.setDescription('Description.')
hwWidsAttackStatDeauthSpoofAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 10), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatDeauthSpoofAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatDeauthSpoofAttack.setDescription('Description.')
hwWidsAttackStatDisassocSpoofAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 11), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatDisassocSpoofAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatDisassocSpoofAttack.setDescription('Description.')
hwWidsAttackStatWepShareKeyAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 12), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatWepShareKeyAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatWepShareKeyAttack.setDescription('Description.')
hwWidsAttackStatWpaAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 13), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatWpaAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatWpaAttack.setDescription('Description.')
hwWidsAttackStatWpa2Attack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 14), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatWpa2Attack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatWpa2Attack.setDescription('Description.')
hwWidsAttackStatWapiAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 15), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatWapiAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatWapiAttack.setDescription('Description.')
hwWidsAttackStatStartTime = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 16), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatStartTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatStartTime.setDescription('Description.')
hwWidsAttackStatEAPOLStartFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 17), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatEAPOLStartFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatEAPOLStartFloodAttack.setDescription('Description.')
hwWidsAttackStatEAPOLLogoffFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 18), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatEAPOLLogoffFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatEAPOLLogoffFloodAttack.setDescription('Description.')
hwWidsAttackStatNullQosFloodAttack = MibScalar((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 10, 19), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackStatNullQosFloodAttack.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatNullQosFloodAttack.setDescription('Description.')
hwWidsDynamicBlacklistTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11), )
if mibBuilder.loadTexts: hwWidsDynamicBlacklistTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistTable.setDescription('Description.')
hwWidsDynamicBlacklistEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistDevMac"))
if mibBuilder.loadTexts: hwWidsDynamicBlacklistEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistEntry.setDescription('Description.')
hwWidsDynamicBlacklistDevMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1, 1), MacAddress())
if mibBuilder.loadTexts: hwWidsDynamicBlacklistDevMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistDevMac.setDescription('Description.')
hwWidsDynamicBlacklistDevType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistDevType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistDevType.setDescription('Description.')
hwWidsDynamicBlacklistDevAttackType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistDevAttackType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistDevAttackType.setDescription('Description.')
hwWidsDynamicBlacklistAttackPacketBmp1 = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAttackPacketBmp1.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAttackPacketBmp1.setDescription('Description.')
hwWidsDynamicBlacklistAttackPacketBmp2 = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAttackPacketBmp2.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAttackPacketBmp2.setDescription('Description.')
hwWidsDynamicBlacklistLastTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 11, 1, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistLastTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistLastTime.setDescription('Description.')
hwWidsDynamicBlacklistAPTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12), )
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPTable.setDescription('Description.')
hwWidsDynamicBlacklistAPEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistDevMac"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistApID"))
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPEntry.setDescription('Description.')
hwWidsDynamicBlacklistApID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12, 1, 1), Integer32())
if mibBuilder.loadTexts: hwWidsDynamicBlacklistApID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistApID.setDescription('Description.')
hwWidsDynamicBlacklistAPMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12, 1, 2), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPMac.setDescription('Description.')
hwWidsDynamicBlacklistApIP = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12, 1, 3), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistApIP.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistApIP.setDescription('Description.')
hwWidsDynamicBlacklistAttackType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAttackType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAttackType.setDescription('Description.')
hwWidsDynamicBlacklistAPLastTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 12, 1, 5), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPLastTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPLastTime.setDescription('Description.')
hwWlanWidsObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13))
hwWidsDetNonWifiDevHistTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1), )
if mibBuilder.loadTexts: hwWidsDetNonWifiDevHistTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevHistTable.setDescription('Description.')
hwWidsDetNonWifiDevHistEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistIndex"))
if mibBuilder.loadTexts: hwWidsDetNonWifiDevHistEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevHistEntry.setDescription('Description.')
hwWidsDetNonWifiHistIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 1), Integer32())
if mibBuilder.loadTexts: hwWidsDetNonWifiHistIndex.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistIndex.setDescription('Description.')
hwWidsDetNonWifiHistMonitorApMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 2), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorApMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorApMac.setDescription('Description.')
hwWidsDetNonWifiHistMonitorAPName = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 3), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorAPName.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorAPName.setDescription('Description.')
hwWidsDetNonWifiHistMonitorAPID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorAPID.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorAPID.setDescription('Description.')
hwWidsDetNonWifiHistMonitorRadioId = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorRadioId.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorRadioId.setDescription('Description.')
hwWidsDetNonWifiHistMonitorRadioType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorRadioType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorRadioType.setDescription('Description.')
hwWidsDetNonWifiHistMonitorAPChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorAPChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistMonitorAPChannel.setDescription('Description.')
hwWidsDetNonWifiHistDevType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDevType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDevType.setDescription('Description.')
hwWidsDetNonWifiHistRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 9), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistRssi.setDescription('Description.')
hwWidsDetNonWifiHistFrequencyType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistFrequencyType.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistFrequencyType.setDescription('Description.')
hwWidsDetNonWifiHistChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 11), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistChannel.setDescription('Description.')
hwWidsDetNonWifiHistDevLastTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDevLastTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDevLastTime.setDescription('Description.')
hwWidsDetNonWifiHistCenterFrequency = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistCenterFrequency.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistCenterFrequency.setDescription('Description.')
hwWidsDetNonWifiHistBandwidth = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 14), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistBandwidth.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistBandwidth.setDescription('Description.')
hwWidsDetNonWifiHistDutycycle = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDutycycle.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDutycycle.setDescription('Description.')
hwWidsDetNonWifiHistInterferenceLevel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 16), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistInterferenceLevel.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistInterferenceLevel.setDescription('Description.')
hwWidsDetNonWifiHistDevFirstTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 1, 1, 17), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDevFirstTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiHistDevFirstTime.setDescription('Description.')
hwWidsAttDevTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2), )
if mibBuilder.loadTexts: hwWidsAttDevTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttDevTable.setDescription('Description.')
hwWidsAttDevEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevMac"))
if mibBuilder.loadTexts: hwWidsAttDevEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttDevEntry.setDescription('Description.')
hwWidsAttackDevMac = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1, 1), MacAddress())
if mibBuilder.loadTexts: hwWidsAttackDevMac.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevMac.setDescription('Description.')
hwWidsAttackDevChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDevChannel.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevChannel.setDescription('Description.')
hwWidsAttackDevRssi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDevRssi.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevRssi.setDescription('Description.')
hwWidsAttackDevLastAttType = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDevLastAttType.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevLastAttType.setDescription('Description.')
hwWidsAttackDevLastPacketBmp = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1, 5), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDevLastPacketBmp.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevLastPacketBmp.setDescription('Description.')
hwWidsAttackDevLastDetTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 2, 1, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDevLastDetTime.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevLastDetTime.setDescription('Description.')
hwWidsAttackDetorTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3), )
if mibBuilder.loadTexts: hwWidsAttackDetorTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorTable.setDescription('Description.')
hwWidsAttackDetorEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevMac"), (0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorApID"))
if mibBuilder.loadTexts: hwWidsAttackDetorEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorEntry.setDescription('Description.')
hwWidsAttackDetorApID = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 1), Unsigned32())
if mibBuilder.loadTexts: hwWidsAttackDetorApID.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorApID.setDescription('Description.')
hwWidsAttackDetorAttTypeBmp = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorAttTypeBmp.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorAttTypeBmp.setDescription('Description.')
hwWidsAttackDetorPacketBmpFlood = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorPacketBmpFlood.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorPacketBmpFlood.setDescription('Description.')
hwWidsAttackDetorPacketBmpSpoof = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorPacketBmpSpoof.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorPacketBmpSpoof.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeFlood = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 5), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeFlood.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeFlood.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeSpoof = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeSpoof.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeSpoof.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeWeakIv = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 7), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWeakIv.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWeakIv.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeWep = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 8), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWep.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWep.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeWpa = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 9), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWpa.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWpa.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeWpa2 = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 10), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWpa2.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWpa2.setDescription('Description.')
hwWidsAttackDetorFirstDetTimeWapi = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 3, 1, 11), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWapi.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorFirstDetTimeWapi.setDescription('Description.')
hwOuiWhitelistTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 4), )
if mibBuilder.loadTexts: hwOuiWhitelistTable.setStatus('current')
if mibBuilder.loadTexts: hwOuiWhitelistTable.setDescription('Description.')
hwOuiWhitelistEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 4, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwOuiWhitelistOui"))
if mibBuilder.loadTexts: hwOuiWhitelistEntry.setStatus('current')
if mibBuilder.loadTexts: hwOuiWhitelistEntry.setDescription('Description.')
hwOuiWhitelistOui = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 4, 1, 1), OctetString())
if mibBuilder.loadTexts: hwOuiWhitelistOui.setStatus('current')
if mibBuilder.loadTexts: hwOuiWhitelistOui.setDescription('Description.')
hwOuiWhitelistRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 4, 1, 2), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwOuiWhitelistRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwOuiWhitelistRowStatus.setDescription('Description.')
hwMacAddressWhitelistTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 5), )
if mibBuilder.loadTexts: hwMacAddressWhitelistTable.setStatus('current')
if mibBuilder.loadTexts: hwMacAddressWhitelistTable.setDescription('Description.')
hwMacAddressWhitelistEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 5, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwMacAddressWhitelistMacAddress"))
if mibBuilder.loadTexts: hwMacAddressWhitelistEntry.setStatus('current')
if mibBuilder.loadTexts: hwMacAddressWhitelistEntry.setDescription('Description.')
hwMacAddressWhitelistMacAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 5, 1, 1), MacAddress())
if mibBuilder.loadTexts: hwMacAddressWhitelistMacAddress.setStatus('current')
if mibBuilder.loadTexts: hwMacAddressWhitelistMacAddress.setDescription('Description.')
hwMacAddressWhitelistRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 5, 1, 2), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwMacAddressWhitelistRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwMacAddressWhitelistRowStatus.setDescription('Description.')
hwWidsSpoofSsidRuleListTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 6), )
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleListTable.setStatus('current')
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleListTable.setDescription('Description.')
hwWidsSpoofSsidRuleListEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 6, 1), ).setIndexNames((0, "HUAWEI-WLAN-WIDS-MIB", "hwWidsSpoofSsidRule"))
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleListEntry.setStatus('current')
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleListEntry.setDescription('Description.')
hwWidsSpoofSsidRule = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 6, 1, 1), OctetString())
if mibBuilder.loadTexts: hwWidsSpoofSsidRule.setStatus('current')
if mibBuilder.loadTexts: hwWidsSpoofSsidRule.setDescription('Description.')
hwWidsSpoofSsidRuleListRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 13, 6, 1, 2), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleListRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleListRowStatus.setDescription('Description.')
hwWlanWidsConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14))
hwWlanWidsCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 1))
hwWlanWidsCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 1, 1)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsMIBNotifyObjectGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsMIBNotifyGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsGlobalOptGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueHistoryGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwSsidWhitelistGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsEnableAPGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistAPGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevHistGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevGroup"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWlanWidsCompliance = hwWlanWidsCompliance.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsCompliance.setDescription('Description.')
hwWlanWidsObjectGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2))
hwWlanWidsMIBNotifyObjectGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 1)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevRSSI"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsRogueDevSSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioId"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPIP"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiDeviceType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiInterChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsNonWifiRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetAPName"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsDetRadioType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackDevMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanObjWidsAttackTypeStr"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWlanWidsMIBNotifyObjectGroup = hwWlanWidsMIBNotifyObjectGroup.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsMIBNotifyObjectGroup.setDescription('Description.')
hwWlanWidsMIBNotifyGroup = NotificationGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 2)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsRougeDevDetectedNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsRougeDevClearNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsNonWifiDetNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsNonWifiClearNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsFloodAttackDetectedNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsFloodAttackClearNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsSpoofAttackDetectedNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsSpoofAttackClearNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsWeakIvAttackDetectedNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsWeakIvAttackClearNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsPSKAttackDetectedNotify"), ("HUAWEI-WLAN-WIDS-MIB", "hwWlanWidsPSKAttackClearNotify"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWlanWidsMIBNotifyGroup = hwWlanWidsMIBNotifyGroup.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsMIBNotifyGroup.setDescription('Description.')
hwWlanWidsGlobalOptGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 3)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetDetDevTableAll"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetDetDevTableByType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetRogueHistoryAll"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetRogueHistoryByDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetAttackDev"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetAttackStat"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetDynamicBlacklist"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetDynamicBlacklistMac"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsResetAttackHistory"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWlanWidsGlobalOptGroup = hwWlanWidsGlobalOptGroup.setStatus('current')
if mibBuilder.loadTexts: hwWlanWidsGlobalOptGroup.setDescription('Description.')
hwWidsDetDevGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 4)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevSSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevRogue"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevLastTime"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevIsCountermeasuresed"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevInterference"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevBSSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevFirstDetTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsDetDevGroup = hwWidsDetDevGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevGroup.setDescription('Description.')
hwWidsDetDevMonitorGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 5)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApMAC"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApIP"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApLastDetTime"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorApCountermeasuresDev"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetDevMonitorDetAtt"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsDetDevMonitorGroup = hwWidsDetDevMonitorGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetDevMonitorGroup.setDescription('Description.')
hwWidsRogueHistoryGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 6)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueDevRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueDevChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueDevSSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsRogueDevLastTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsRogueHistoryGroup = hwWidsRogueHistoryGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsRogueHistoryGroup.setDescription('Description.')
hwSsidWhitelistGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 7)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwSsidWhitelisttRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwSsidWhitelistGroup = hwSsidWhitelistGroup.setStatus('current')
if mibBuilder.loadTexts: hwSsidWhitelistGroup.setDescription('Description.')
hwWidsDetNonWifiDevGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 8)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiFrequencyType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevLastTime"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiCenterFrequency"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiBandwidth"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDutycycle"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiInterferenceLevel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevMonitorAPName"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevMonitorAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevRadioType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevMonitorAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiDevFirstTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsDetNonWifiDevGroup = hwWidsDetNonWifiDevGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevGroup.setDescription('Description.')
hwWidsAttackHistoryGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 9)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryDevMac"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryPacketBmp1"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryPacketBmp2"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistorySSID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryDetTime"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackHistoryDetectorApId"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsAttackHistoryGroup = hwWidsAttackHistoryGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackHistoryGroup.setDescription('Description.')
hwWidsEnableAPGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 10)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsEnableDevDetSwitch"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsEnableAttackDetSwitch"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsEnableAPName"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsEnableAPGroup = hwWidsEnableAPGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsEnableAPGroup.setDescription('Description.')
hwWidsAttackStatGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 11)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatProbeRequestFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatAuthRequestFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatDeAuthenFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatAssocReqFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatDisassocReqFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatReassocReqFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatActionFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatNullDataFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatWeakIvAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatDeauthSpoofAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatDisassocSpoofAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatWepShareKeyAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatWpaAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatWpa2Attack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatWapiAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatStartTime"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatEAPOLStartFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatEAPOLLogoffFloodAttack"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackStatNullQosFloodAttack"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsAttackStatGroup = hwWidsAttackStatGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackStatGroup.setDescription('Description.')
hwWidsDynamicBlacklistGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 12)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistDevAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistAttackPacketBmp1"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistAttackPacketBmp2"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistLastTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsDynamicBlacklistGroup = hwWidsDynamicBlacklistGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistGroup.setDescription('Description.')
hwWidsDynamicBlacklistAPGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 13)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistAPMac"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistApIP"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistAttackType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDynamicBlacklistAPLastTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsDynamicBlacklistAPGroup = hwWidsDynamicBlacklistAPGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsDynamicBlacklistAPGroup.setDescription('Description.')
hwWidsDetNonWifiDevHistGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 14)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistMonitorApMac"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistMonitorAPName"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistMonitorAPID"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistMonitorRadioId"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistMonitorRadioType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistMonitorAPChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistDevType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistFrequencyType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistDevLastTime"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistCenterFrequency"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistBandwidth"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistDutycycle"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistInterferenceLevel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsDetNonWifiHistDevFirstTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsDetNonWifiDevHistGroup = hwWidsDetNonWifiDevHistGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsDetNonWifiDevHistGroup.setDescription('Description.')
hwWidsAttackDevGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 15)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevChannel"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevRssi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevLastAttType"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevLastPacketBmp"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDevLastDetTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsAttackDevGroup = hwWidsAttackDevGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDevGroup.setDescription('Description.')
hwWidsAttackDetorGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 16)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorPacketBmpFlood"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorPacketBmpSpoof"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeFlood"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeSpoof"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeWeakIv"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeWep"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeWpa"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeWpa2"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorFirstDetTimeWapi"), ("HUAWEI-WLAN-WIDS-MIB", "hwWidsAttackDetorAttTypeBmp"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsAttackDetorGroup = hwWidsAttackDetorGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsAttackDetorGroup.setDescription('Description.')
hwWidsOuiWhitelistGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 17)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwOuiWhitelistRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsOuiWhitelistGroup = hwWidsOuiWhitelistGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsOuiWhitelistGroup.setDescription('Description.')
hwWidsMacAddressWhitelistGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 18)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwMacAddressWhitelistRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsMacAddressWhitelistGroup = hwWidsMacAddressWhitelistGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsMacAddressWhitelistGroup.setDescription('Description.')
hwWidsSpoofSsidRuleGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 6, 139, 8, 14, 2, 19)).setObjects(("HUAWEI-WLAN-WIDS-MIB", "hwWidsSpoofSsidRuleListRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwWidsSpoofSsidRuleGroup = hwWidsSpoofSsidRuleGroup.setStatus('current')
if mibBuilder.loadTexts: hwWidsSpoofSsidRuleGroup.setDescription('Description.')
mibBuilder.exportSymbols("HUAWEI-WLAN-WIDS-MIB", hwWidsDetNonWifiHistIndex=hwWidsDetNonWifiHistIndex, hwWidsDetDevBSSID=hwWidsDetDevBSSID, hwWidsAttackDetorFirstDetTimeWapi=hwWidsAttackDetorFirstDetTimeWapi, hwWidsEnableAPName=hwWidsEnableAPName, hwWidsAttackStatWpa2Attack=hwWidsAttackStatWpa2Attack, hwMacAddressWhitelistRowStatus=hwMacAddressWhitelistRowStatus, hwWidsDetNonWifiHistBandwidth=hwWidsDetNonWifiHistBandwidth, hwWidsAttackDetorFirstDetTimeWpa2=hwWidsAttackDetorFirstDetTimeWpa2, hwWlanObjWidsNonWifiInterChannel=hwWlanObjWidsNonWifiInterChannel, hwWidsAttackDevLastPacketBmp=hwWidsAttackDevLastPacketBmp, hwWidsEnableAPID=hwWidsEnableAPID, hwWidsDetNonWifiHistRssi=hwWidsDetNonWifiHistRssi, hwSsidWhitelistTable=hwSsidWhitelistTable, hwWidsDetNonWifiDevHistGroup=hwWidsDetNonWifiDevHistGroup, hwSsidWhitelistSsid=hwSsidWhitelistSsid, hwWidsDetNonWifiDevGroup=hwWidsDetNonWifiDevGroup, hwWidsDetDevGroup=hwWidsDetDevGroup, hwWlanWidsSpoofAttackDetectedNotify=hwWlanWidsSpoofAttackDetectedNotify, hwWidsAttackHistoryDevMac=hwWidsAttackHistoryDevMac, hwWidsAttackHistorySSID=hwWidsAttackHistorySSID, hwWidsAttackDevMac=hwWidsAttackDevMac, hwWidsDetNonWifiInterferenceLevel=hwWidsDetNonWifiInterferenceLevel, hwWidsDetNonWifiDevHistTable=hwWidsDetNonWifiDevHistTable, hwWidsDetNonWifiDevMonitorAPChannel=hwWidsDetNonWifiDevMonitorAPChannel, hwSsidWhitelisttRowStatus=hwSsidWhitelisttRowStatus, hwWidsDetNonWifiDevRadioType=hwWidsDetNonWifiDevRadioType, hwWidsAttDevTable=hwWidsAttDevTable, hwWlanObjWidsDetAPIP=hwWlanObjWidsDetAPIP, hwWidsResetAttackStat=hwWidsResetAttackStat, hwWidsDetNonWifiHistDutycycle=hwWidsDetNonWifiHistDutycycle, hwWidsDetDevMonitorApLastDetTime=hwWidsDetDevMonitorApLastDetTime, hwWidsEnableAPEntry=hwWidsEnableAPEntry, hwWidsAttackStatAssocReqFloodAttack=hwWidsAttackStatAssocReqFloodAttack, hwWidsAttackDevRssi=hwWidsAttackDevRssi, hwWlanWidsObjects=hwWlanWidsObjects, hwWidsDynamicBlacklistAttackPacketBmp1=hwWidsDynamicBlacklistAttackPacketBmp1, hwWlanWidsPSKAttackClearNotify=hwWlanWidsPSKAttackClearNotify, hwWidsDetDevChannel=hwWidsDetDevChannel, hwWidsRogueDevMac=hwWidsRogueDevMac, hwWidsAttackDetorFirstDetTimeWpa=hwWidsAttackDetorFirstDetTimeWpa, hwWidsAttackDevLastAttType=hwWidsAttackDevLastAttType, hwWidsAttackHistoryDevType=hwWidsAttackHistoryDevType, hwOuiWhitelistRowStatus=hwOuiWhitelistRowStatus, hwWidsEnableAPGroup=hwWidsEnableAPGroup, hwWidsDetNonWifiHistDevType=hwWidsDetNonWifiHistDevType, hwWidsDetNonWifiDutycycle=hwWidsDetNonWifiDutycycle, hwWlanWidsFloodAttackClearNotify=hwWlanWidsFloodAttackClearNotify, hwWidsDetDevFirstDetTime=hwWidsDetDevFirstDetTime, hwWidsSpoofSsidRuleListTable=hwWidsSpoofSsidRuleListTable, hwWidsAttackStatNullDataFloodAttack=hwWidsAttackStatNullDataFloodAttack, hwWidsDetDevMonitorApRadioID=hwWidsDetDevMonitorApRadioID, hwWidsDetDevRssi=hwWidsDetDevRssi, hwWlanWids=hwWlanWids, hwWlanObjWidsRogueDevChannel=hwWlanObjWidsRogueDevChannel, hwWidsDetNonWifiRssi=hwWidsDetNonWifiRssi, hwWidsAttackStatNullQosFloodAttack=hwWidsAttackStatNullQosFloodAttack, hwWidsDynamicBlacklistDevMac=hwWidsDynamicBlacklistDevMac, hwWidsDetNonWifiHistMonitorAPName=hwWidsDetNonWifiHistMonitorAPName, hwWidsSpoofSsidRuleListRowStatus=hwWidsSpoofSsidRuleListRowStatus, hwWidsAttackHistorySubSeq=hwWidsAttackHistorySubSeq, hwWlanObjWidsNonWifiDeviceType=hwWlanObjWidsNonWifiDeviceType, hwWidsDetNonWifiChannel=hwWidsDetNonWifiChannel, hwWidsAttackStatActionFloodAttack=hwWidsAttackStatActionFloodAttack, hwWlanWidsNotifications=hwWlanWidsNotifications, hwWidsDetDevEntry=hwWidsDetDevEntry, hwWidsAttackStatStartTime=hwWidsAttackStatStartTime, hwWidsDetNonWifiType=hwWidsDetNonWifiType, hwWidsSpoofSsidRuleGroup=hwWidsSpoofSsidRuleGroup, hwWidsDetDevMonitorApCountermeasuresDev=hwWidsDetDevMonitorApCountermeasuresDev, hwWidsDetDevIsCountermeasuresed=hwWidsDetDevIsCountermeasuresed, hwWlanWidsSpoofAttackClearNotify=hwWlanWidsSpoofAttackClearNotify, hwWidsDetNonWifiHistDevLastTime=hwWidsDetNonWifiHistDevLastTime, hwWidsEnableAPTable=hwWidsEnableAPTable, hwWidsDetNonWifiHistMonitorAPChannel=hwWidsDetNonWifiHistMonitorAPChannel, hwWlanWidsRougeDevClearNotify=hwWlanWidsRougeDevClearNotify, hwWidsDetDevMonitorApID=hwWidsDetDevMonitorApID, hwWidsRogueDevSSID=hwWidsRogueDevSSID, hwWidsAttackDetorEntry=hwWidsAttackDetorEntry, hwWidsDetDevMac=hwWidsDetDevMac, hwWidsResetDynamicBlacklist=hwWidsResetDynamicBlacklist, hwWidsAttackStatReassocReqFloodAttack=hwWidsAttackStatReassocReqFloodAttack, hwWidsDetDevMonitorApMAC=hwWidsDetDevMonitorApMAC, hwWidsAttackStatWapiAttack=hwWidsAttackStatWapiAttack, hwWlanObjWidsDetRadioType=hwWlanObjWidsDetRadioType, hwWidsRogueDevRssi=hwWidsRogueDevRssi, hwWidsDetDevMonitorDetAtt=hwWidsDetDevMonitorDetAtt, hwWidsAttackStatWepShareKeyAttack=hwWidsAttackStatWepShareKeyAttack, hwWidsDynamicBlacklistAttackType=hwWidsDynamicBlacklistAttackType, hwWidsRogueHistoryGroup=hwWidsRogueHistoryGroup, hwWidsResetRogueHistoryAll=hwWidsResetRogueHistoryAll, hwWidsDetNonWifiDevHistEntry=hwWidsDetNonWifiDevHistEntry, hwOuiWhitelistEntry=hwOuiWhitelistEntry, hwWlanObjWidsAttackTypeStr=hwWlanObjWidsAttackTypeStr, hwWlanObjWidsRogueDevMAC=hwWlanObjWidsRogueDevMAC, hwWidsAttackStatWpaAttack=hwWidsAttackStatWpaAttack, hwWlanObjWidsDetRadioId=hwWlanObjWidsDetRadioId, hwWlanObjWidsAttackType=hwWlanObjWidsAttackType, hwWidsAttackDetorAttTypeBmp=hwWidsAttackDetorAttTypeBmp, hwWidsRogueHistoryTable=hwWidsRogueHistoryTable, hwWidsAttackHistoryPacketBmp1=hwWidsAttackHistoryPacketBmp1, hwWidsAttackDetorApID=hwWidsAttackDetorApID, hwWidsDetNonWifiDevFirstTime=hwWidsDetNonWifiDevFirstTime, hwWlanObjWidsAttackDevMAC=hwWlanObjWidsAttackDevMAC, hwWidsDetNonWifiDevMonitorAPID=hwWidsDetNonWifiDevMonitorAPID, hwWidsAttackStatDisassocSpoofAttack=hwWidsAttackStatDisassocSpoofAttack, hwWidsResetAttackDev=hwWidsResetAttackDev, hwWidsDynamicBlacklistTable=hwWidsDynamicBlacklistTable, hwWidsAttackStatDeauthSpoofAttack=hwWidsAttackStatDeauthSpoofAttack, hwWidsEnableAttackDetSwitch=hwWidsEnableAttackDetSwitch, hwWlanWidsConformance=hwWlanWidsConformance, hwWlanWidsNonWifiDetNotify=hwWlanWidsNonWifiDetNotify, hwWidsAttackHistoryPacketBmp2=hwWidsAttackHistoryPacketBmp2, hwWidsAttackStatTable=hwWidsAttackStatTable, hwWlanWidsGlobalOptGroup=hwWlanWidsGlobalOptGroup, hwWidsAttackDetorPacketBmpSpoof=hwWidsAttackDetorPacketBmpSpoof, hwWidsDetDevMonitorEntry=hwWidsDetDevMonitorEntry, hwWlanWidsMIBNotifyObjectGroup=hwWlanWidsMIBNotifyObjectGroup, hwWidsAttackHistoryDetTime=hwWidsAttackHistoryDetTime, hwWidsAttackHistoryRssi=hwWidsAttackHistoryRssi, hwWlanWidsPSKAttackDetectedNotify=hwWlanWidsPSKAttackDetectedNotify, hwWlanObjWidsDetAPID=hwWlanObjWidsDetAPID, hwWidsAttackStatWeakIvAttack=hwWidsAttackStatWeakIvAttack, hwWidsAttackDevGroup=hwWidsAttackDevGroup, hwWidsDetNonWifiHistInterferenceLevel=hwWidsDetNonWifiHistInterferenceLevel, hwWidsDetNonWifiDevMonitorAPName=hwWidsDetNonWifiDevMonitorAPName, hwWidsAttackStatDisassocReqFloodAttack=hwWidsAttackStatDisassocReqFloodAttack, hwWidsDetDevMonitorTable=hwWidsDetDevMonitorTable, hwWidsAttackDetorTable=hwWidsAttackDetorTable, hwWlanObjWidsDetAPChannel=hwWlanObjWidsDetAPChannel, hwWidsDetNonWifiHistChannel=hwWidsDetNonWifiHistChannel, hwWidsAttackStatAuthRequestFloodAttack=hwWidsAttackStatAuthRequestFloodAttack, hwWlanWidsWeakIvAttackClearNotify=hwWlanWidsWeakIvAttackClearNotify, hwWidsAttackDetorPacketBmpFlood=hwWidsAttackDetorPacketBmpFlood, hwWidsDetNonWifiHistDevFirstTime=hwWidsDetNonWifiHistDevFirstTime, hwWidsResetDetDevTableAll=hwWidsResetDetDevTableAll, hwWidsAttackHistoryChannel=hwWidsAttackHistoryChannel, hwWidsAttackStatEAPOLStartFloodAttack=hwWidsAttackStatEAPOLStartFloodAttack, hwWidsDetDevRogue=hwWidsDetDevRogue, hwWidsDetDevType=hwWidsDetDevType, hwWidsAttackStatEAPOLLogoffFloodAttack=hwWidsAttackStatEAPOLLogoffFloodAttack, hwWidsDynamicBlacklistAPEntry=hwWidsDynamicBlacklistAPEntry, hwWidsDetNonWifiDevEntry=hwWidsDetNonWifiDevEntry, hwWidsDynamicBlacklistAPTable=hwWidsDynamicBlacklistAPTable, hwMacAddressWhitelistTable=hwMacAddressWhitelistTable, hwWlanWidsNotifyObjects=hwWlanWidsNotifyObjects, hwWidsDynamicBlacklistAPLastTime=hwWidsDynamicBlacklistAPLastTime, hwWlanObjWidsRogueDevRSSI=hwWlanObjWidsRogueDevRSSI, hwWlanWidsCompliances=hwWlanWidsCompliances, hwWidsDynamicBlacklistDevAttackType=hwWidsDynamicBlacklistDevAttackType, hwWidsDynamicBlacklistApIP=hwWidsDynamicBlacklistApIP, hwWlanWidsMIBNotifyGroup=hwWlanWidsMIBNotifyGroup, hwWidsAttackStatDeAuthenFloodAttack=hwWidsAttackStatDeAuthenFloodAttack, hwWidsAttackHistoryAttackType=hwWidsAttackHistoryAttackType, hwWidsMacAddressWhitelistGroup=hwWidsMacAddressWhitelistGroup, hwSsidWhitelistEntry=hwSsidWhitelistEntry, hwWidsRogueHistoryEntry=hwWidsRogueHistoryEntry, hwWidsResetRogueHistoryByDevType=hwWidsResetRogueHistoryByDevType, hwWidsAttackDetorFirstDetTimeFlood=hwWidsAttackDetorFirstDetTimeFlood, hwWidsDetNonWifiHistCenterFrequency=hwWidsDetNonWifiHistCenterFrequency, hwWidsResetAttackHistory=hwWidsResetAttackHistory, hwWidsAttackHistoryEntry=hwWidsAttackHistoryEntry, hwWidsAttackDevLastDetTime=hwWidsAttackDevLastDetTime, hwWidsAttackStatGroup=hwWidsAttackStatGroup, hwWlanWidsNonWifiClearNotify=hwWlanWidsNonWifiClearNotify, hwWlanObjWidsNonWifiRssi=hwWlanObjWidsNonWifiRssi, hwWidsDynamicBlacklistAPMac=hwWidsDynamicBlacklistAPMac, hwWidsAttackDetorFirstDetTimeWeakIv=hwWidsAttackDetorFirstDetTimeWeakIv, hwWidsDetNonWifiHistFrequencyType=hwWidsDetNonWifiHistFrequencyType, hwWidsDetDevLastTime=hwWidsDetDevLastTime, hwWidsDetDevInterference=hwWidsDetDevInterference, hwWidsDetNonWifiHistMonitorApMac=hwWidsDetNonWifiHistMonitorApMac, hwWidsAttackStatProbeRequestFloodAttack=hwWidsAttackStatProbeRequestFloodAttack, hwWlanWidsFloodAttackDetectedNotify=hwWlanWidsFloodAttackDetectedNotify, hwWidsAttackDevChannel=hwWidsAttackDevChannel, hwWidsDetNonWifiDevLastTime=hwWidsDetNonWifiDevLastTime, hwWidsResetDynamicBlacklistMac=hwWidsResetDynamicBlacklistMac, hwWidsDetNonWifiDevTable=hwWidsDetNonWifiDevTable, hwWidsDynamicBlacklistApID=hwWidsDynamicBlacklistApID, hwWlanObjWidsRogueDevSSID=hwWlanObjWidsRogueDevSSID, hwWlanWidsGloablOpt=hwWlanWidsGloablOpt, hwWlanObjWidsDetAPName=hwWlanObjWidsDetAPName, hwWidsDetNonWifiHistMonitorRadioType=hwWidsDetNonWifiHistMonitorRadioType, hwWidsAttDevEntry=hwWidsAttDevEntry, PYSNMP_MODULE_ID=hwWlanWids, hwWidsDynamicBlacklistEntry=hwWidsDynamicBlacklistEntry, hwWidsSpoofSsidRuleListEntry=hwWidsSpoofSsidRuleListEntry, hwWlanWidsCompliance=hwWlanWidsCompliance, hwWidsDynamicBlacklistAPGroup=hwWidsDynamicBlacklistAPGroup, hwWidsDetNonWifiDevMonitorRadioId=hwWidsDetNonWifiDevMonitorRadioId, hwWidsDetNonWifiHistMonitorAPID=hwWidsDetNonWifiHistMonitorAPID, hwWidsDetDevSSID=hwWidsDetDevSSID, hwWidsDetDevMonitorGroup=hwWidsDetDevMonitorGroup, hwWidsRogueDevChannel=hwWidsRogueDevChannel, hwWlanWidsObjectGroups=hwWlanWidsObjectGroups, hwWlanObjWidsRogueDevType=hwWlanObjWidsRogueDevType, hwOuiWhitelistTable=hwOuiWhitelistTable, hwWlanWidsWeakIvAttackDetectedNotify=hwWlanWidsWeakIvAttackDetectedNotify, hwWlanObjWidsDetAPMAC=hwWlanObjWidsDetAPMAC, hwWidsDetNonWifiBandwidth=hwWidsDetNonWifiBandwidth, hwWidsEnableDevDetSwitch=hwWidsEnableDevDetSwitch, hwMacAddressWhitelistEntry=hwMacAddressWhitelistEntry, hwWidsDynamicBlacklistGroup=hwWidsDynamicBlacklistGroup, hwWidsDetDevMonitorApChannel=hwWidsDetDevMonitorApChannel, hwWidsRogueDevType=hwWidsRogueDevType, hwWidsAttackDetorGroup=hwWidsAttackDetorGroup, hwWidsAttackHistoryGroup=hwWidsAttackHistoryGroup, hwWidsDetNonWifiDevMonitorApMac=hwWidsDetNonWifiDevMonitorApMac, hwWidsSpoofSsidRule=hwWidsSpoofSsidRule, hwWidsAttackHistoryTable=hwWidsAttackHistoryTable, hwWidsDetNonWifiFrequencyType=hwWidsDetNonWifiFrequencyType, hwMacAddressWhitelistMacAddress=hwMacAddressWhitelistMacAddress, hwWidsDynamicBlacklistDevType=hwWidsDynamicBlacklistDevType, hwSsidWhitelistGroup=hwSsidWhitelistGroup, hwWlanWidsNotify=hwWlanWidsNotify, hwWidsDynamicBlacklistAttackPacketBmp2=hwWidsDynamicBlacklistAttackPacketBmp2, hwWlanWidsRougeDevDetectedNotify=hwWlanWidsRougeDevDetectedNotify, hwWidsDetDevMonitorApRssi=hwWidsDetDevMonitorApRssi, hwWidsRogueDevLastTime=hwWidsRogueDevLastTime, hwWidsDetDevMonitorApIP=hwWidsDetDevMonitorApIP, hwWidsAttackDetorFirstDetTimeSpoof=hwWidsAttackDetorFirstDetTimeSpoof, hwWidsDetDevTable=hwWidsDetDevTable, hwWidsResetDetDevTableByType=hwWidsResetDetDevTableByType, hwWidsOuiWhitelistGroup=hwWidsOuiWhitelistGroup, hwWidsAttackDetorFirstDetTimeWep=hwWidsAttackDetorFirstDetTimeWep, hwWidsAttackHistorySeq=hwWidsAttackHistorySeq, hwWidsDynamicBlacklistLastTime=hwWidsDynamicBlacklistLastTime, hwOuiWhitelistOui=hwOuiWhitelistOui, hwWidsDetNonWifiCenterFrequency=hwWidsDetNonWifiCenterFrequency, hwWidsDetNonWifiHistMonitorRadioId=hwWidsDetNonWifiHistMonitorRadioId, hwWidsAttackHistoryDetectorApId=hwWidsAttackHistoryDetectorApId)
