#
# PySNMP MIB module HUAWEI-BRAS-VT-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/HUAWEI-BRAS-VT-MIB
# Produced by pysmi-0.3.4 at Wed May  1 13:43:40 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, ObjectIdentifier, Integer = mibBuilder.importSymbols("ASN1", "OctetString", "ObjectIdentifier", "Integer")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsUnion, ValueSizeConstraint, ValueRangeConstraint, ConstraintsIntersection, SingleValueConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsUnion", "ValueSizeConstraint", "ValueRangeConstraint", "ConstraintsIntersection", "SingleValueConstraint")
hwBRASMib, = mibBuilder.importSymbols("HUAWEI-MIB", "hwBRASMib")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Counter64, ModuleIdentity, NotificationType, ObjectIdentity, iso, Unsigned32, TimeTicks, Integer32, Counter32, Bits, MibIdentifier, Gauge32, IpAddress, MibScalar, MibTable, MibTableRow, MibTableColumn = mibBuilder.importSymbols("SNMPv2-SMI", "Counter64", "ModuleIdentity", "NotificationType", "ObjectIdentity", "iso", "Unsigned32", "TimeTicks", "Integer32", "Counter32", "Bits", "MibIdentifier", "Gauge32", "IpAddress", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn")
DisplayString, TextualConvention, RowStatus = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention", "RowStatus")
hwIFVT = ModuleIdentity((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10))
if mibBuilder.loadTexts: hwIFVT.setLastUpdated('200508101200Z')
if mibBuilder.loadTexts: hwIFVT.setOrganization('HAUWEI MIB Standard community ')
if mibBuilder.loadTexts: hwIFVT.setContactInfo('Floor 5, Block 4, R&D Building, Huawei Longgang Production Base, Shenzhen, P.R.C. http://www.huawei.com Zip:518057 ')
if mibBuilder.loadTexts: hwIFVT.setDescription(' V1.00 The VT mib is for all datacomm product. ')
hwhwIFVTMibObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1))
hwIFVTTable = MibTable((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1, 1), )
if mibBuilder.loadTexts: hwIFVTTable.setStatus('current')
if mibBuilder.loadTexts: hwIFVTTable.setDescription('VT Configuration Table.')
hwIFVTEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1, 1, 1), ).setIndexNames((0, "HUAWEI-BRAS-VT-MIB", "hwifVTNo"))
if mibBuilder.loadTexts: hwIFVTEntry.setStatus('current')
if mibBuilder.loadTexts: hwIFVTEntry.setDescription('An entry of Description.')
hwifVTNo = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 1023))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwifVTNo.setStatus('current')
if mibBuilder.loadTexts: hwifVTNo.setDescription('VT Index.')
hwifVTDescr = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1, 1, 1, 2), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 80))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwifVTDescr.setStatus('current')
if mibBuilder.loadTexts: hwifVTDescr.setDescription('VT Description.')
hwifVTMtu = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1, 1, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(128, 1500)).clone(1500)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwifVTMtu.setStatus('current')
if mibBuilder.loadTexts: hwifVTMtu.setDescription('VT Mtu.')
hwifVTRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 1, 1, 1, 4), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: hwifVTRowStatus.setStatus('current')
if mibBuilder.loadTexts: hwifVTRowStatus.setDescription('VT RowStatus.')
hwIfVtConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 2))
hwIfVtCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 2, 1))
hwIfVtCompliance = ModuleCompliance((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 2, 1, 1)).setObjects(("HUAWEI-BRAS-VT-MIB", "hwIfVtTableGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwIfVtCompliance = hwIfVtCompliance.setStatus('current')
if mibBuilder.loadTexts: hwIfVtCompliance.setDescription('The compliance statement for systems supporting the this module.')
hwIfVtObjectGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 2, 2))
hwIfVtTableGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 2011, 5, 25, 40, 10, 2, 2, 1)).setObjects(("HUAWEI-BRAS-VT-MIB", "hwifVTNo"), ("HUAWEI-BRAS-VT-MIB", "hwifVTDescr"), ("HUAWEI-BRAS-VT-MIB", "hwifVTMtu"), ("HUAWEI-BRAS-VT-MIB", "hwifVTRowStatus"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    hwIfVtTableGroup = hwIfVtTableGroup.setStatus('current')
if mibBuilder.loadTexts: hwIfVtTableGroup.setDescription('The VT configuration table.')
mibBuilder.exportSymbols("HUAWEI-BRAS-VT-MIB", hwIfVtCompliances=hwIfVtCompliances, hwIFVT=hwIFVT, hwIfVtTableGroup=hwIfVtTableGroup, PYSNMP_MODULE_ID=hwIFVT, hwifVTNo=hwifVTNo, hwIfVtConformance=hwIfVtConformance, hwIFVTEntry=hwIFVTEntry, hwIFVTTable=hwIFVTTable, hwifVTDescr=hwifVTDescr, hwIfVtObjectGroups=hwIfVtObjectGroups, hwifVTRowStatus=hwifVTRowStatus, hwifVTMtu=hwifVTMtu, hwhwIFVTMibObjects=hwhwIFVTMibObjects, hwIfVtCompliance=hwIfVtCompliance)
