#
# PySNMP MIB module NETSCREEN-SMI (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/NETSCREEN-SMI
# Produced by pysmi-0.3.4 at Wed May  1 14:20:02 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, ObjectIdentifier, Integer = mibBuilder.importSymbols("ASN1", "OctetString", "ObjectIdentifier", "Integer")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ValueSizeConstraint, ConstraintsIntersection, SingleValueConstraint, ValueRangeConstraint, ConstraintsUnion = mibBuilder.importSymbols("ASN1-REFINEMENT", "ValueSizeConstraint", "ConstraintsIntersection", "SingleValueConstraint", "ValueRangeConstraint", "ConstraintsUnion")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
MibScalar, MibTable, MibTableRow, MibTableColumn, Unsigned32, IpAddress, TimeTicks, ModuleIdentity, MibIdentifier, NotificationType, Counter64, ObjectIdentity, Integer32, Bits, Counter32, Gauge32, enterprises, iso = mibBuilder.importSymbols("SNMPv2-SMI", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "Unsigned32", "IpAddress", "TimeTicks", "ModuleIdentity", "MibIdentifier", "NotificationType", "Counter64", "ObjectIdentity", "Integer32", "Bits", "Counter32", "Gauge32", "enterprises", "iso")
TextualConvention, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "DisplayString")
netscreen = ModuleIdentity((1, 3, 6, 1, 4, 1, 3224))
netscreen.setRevisions(('2004-08-31 00:00', '2004-05-03 00:00', '2004-03-03 00:00', '2001-09-28 00:00', '2000-08-02 00:00',))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    if mibBuilder.loadTexts: netscreen.setRevisionsDescriptions(('SMI Mib', 'Modified copyright and contact information', 'Converted to SMIv2 by Longview Software', 'No comment', 'Creation Date',))
if mibBuilder.loadTexts: netscreen.setLastUpdated('200408310000Z')
if mibBuilder.loadTexts: netscreen.setOrganization('Juniper Networks, Inc.')
if mibBuilder.loadTexts: netscreen.setContactInfo('Customer Support 1194 North Mathilda Avenue Sunnyvale, California 94089-1206 USA Tel: 1-800-638-8296 E-mail: customerservice@juniper.net HTTP://www.juniper.net')
if mibBuilder.loadTexts: netscreen.setDescription('Modified SMI Mib Module')
netscreenTrap = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 0))
netscreenProducts = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 1))
netscreenTrapInfo = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 2))
netscreenIDS = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 3))
netscreenVpn = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 4))
netscreenQos = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 5))
netscreenNsrp = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 6))
netscreenSetting = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 7))
netscreenZone = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 8))
netscreenInterface = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 9))
netscreenPolicy = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 10))
netscreenNAT = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 11))
netscreenAddr = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 12))
netscreenService = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 13))
netscreenSchedule = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 14))
netscreenVsys = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 15))
netscreenResource = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 16))
netscreenIp = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 17))
netscreenVR = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 18))
netscreenChassis = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 21))
netscreenSettingMibModule = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 7, 0))
netscreenVpnMibModule = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 4, 0))
mibBuilder.exportSymbols("NETSCREEN-SMI", netscreenVpnMibModule=netscreenVpnMibModule, netscreenNsrp=netscreenNsrp, netscreenSchedule=netscreenSchedule, PYSNMP_MODULE_ID=netscreen, netscreenTrap=netscreenTrap, netscreenProducts=netscreenProducts, netscreenInterface=netscreenInterface, netscreenIDS=netscreenIDS, netscreenIp=netscreenIp, netscreenVpn=netscreenVpn, netscreenZone=netscreenZone, netscreenSettingMibModule=netscreenSettingMibModule, netscreenTrapInfo=netscreenTrapInfo, netscreenResource=netscreenResource, netscreenVR=netscreenVR, netscreenQos=netscreenQos, netscreenChassis=netscreenChassis, netscreenVsys=netscreenVsys, netscreenPolicy=netscreenPolicy, netscreenService=netscreenService, netscreenAddr=netscreenAddr, netscreen=netscreen, netscreenSetting=netscreenSetting, netscreenNAT=netscreenNAT)
