#
# PySNMP MIB module Wellfleet-DVMRP-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/Wellfleet-DVMRP-MIB
# Produced by pysmi-0.3.4 at Wed May  1 15:40:03 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
Integer, OctetString, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "Integer", "OctetString", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
SingleValueConstraint, ConstraintsUnion, ConstraintsIntersection, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "SingleValueConstraint", "ConstraintsUnion", "ConstraintsIntersection", "ValueRangeConstraint", "ValueSizeConstraint")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Integer32, MibScalar, MibTable, MibTableRow, MibTableColumn, Bits, TimeTicks, ModuleIdentity, MibIdentifier, Counter64, iso, Counter32, Gauge32, ObjectIdentity, Unsigned32, IpAddress, NotificationType = mibBuilder.importSymbols("SNMPv2-SMI", "Integer32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "Bits", "TimeTicks", "ModuleIdentity", "MibIdentifier", "Counter64", "iso", "Counter32", "Gauge32", "ObjectIdentity", "Unsigned32", "IpAddress", "NotificationType")
DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")
wfDvmrpGroup, = mibBuilder.importSymbols("Wellfleet-COMMON-MIB", "wfDvmrpGroup")
wfDvmrpBase = MibIdentifier((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1))
wfDvmrpBaseCreate = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("created", 1), ("deleted", 2))).clone('created')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseCreate.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseCreate.setDescription('This entry will provide the base configuration for the DVMRP multicast support on the router.')
wfDvmrpBaseEnable = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseEnable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseEnable.setDescription('Enable or disable DVMRP support in router')
wfDvmrpBaseState = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))).clone(namedValues=NamedValues(("up", 1), ("down", 2), ("init", 3), ("notpres", 4))).clone('notpres')).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpBaseState.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseState.setDescription('State of DVMRP base module')
wfDvmrpBaseFullUpdateInterval = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(10, 2000)).clone(60)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseFullUpdateInterval.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseFullUpdateInterval.setDescription('Full update interval. This value specifies, in seconds, how often routing messages containing complete routing tables are sent.')
wfDvmrpBaseTriggeredUpdateInterval = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(5, 1000)).clone(5)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseTriggeredUpdateInterval.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseTriggeredUpdateInterval.setDescription('Triggered update interval. This value specifies, in seconds, how often triggered routing messages are sent; this represents the minimum amount of time between these type of messages. Triggered updates are sent between full update; the timers restart when a full update is sent so this value should be less than the full update rate.')
wfDvmrpBaseLeafTimeout = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(25, 4000)).clone(200)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseLeafTimeout.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseLeafTimeout.setDescription('Leaf timeout. This value specifies, in seconds, the virtual interface hold down timer.')
wfDvmrpBaseNeighborTimeout = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(35, 8000)).clone(35)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseNeighborTimeout.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseNeighborTimeout.setDescription("Neighbor timeout. This value specifies, in seconds, how long a router neighbor is considered 'up' without confirmation.")
wfDvmrpBaseRouteExpirationTimeout = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(20, 4000)).clone(140)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseRouteExpirationTimeout.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseRouteExpirationTimeout.setDescription('Route Expiration timeout. This value specifies, in seconds, how long a route is considered valid without confirmation; this represents the duration of time that this route will be used.')
wfDvmrpBaseGarbageTimeout = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(40, 8000)).clone(260)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseGarbageTimeout.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseGarbageTimeout.setDescription('Garbage timeout. This value specifies, in seconds, how long a route exists without confirmation; this represents the duration of time that this route will be included in routing updates. This value must be greater than the route expiration timeout.')
wfDvmrpBaseEstimatedRoutes = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(10, 2147483647)).clone(25)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseEstimatedRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseEstimatedRoutes.setDescription('Estimated number of routes, per slot. This is used for pre-allocating routing tables. Note that routes are kept on a per-source network basis, independent of multicast group. This number must include a route for every local network that has a CCT configured for multicasting.')
wfDvmrpBaseNeighborProbeInterval = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 11), Integer32().subtype(subtypeSpec=ValueRangeConstraint(5, 30)).clone(10)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseNeighborProbeInterval.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseNeighborProbeInterval.setDescription('Neighbor probe interval: how often to send a probe on VIFs')
wfDvmrpBaseRouteSwitchTimeout = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 12), Integer32().subtype(subtypeSpec=ValueRangeConstraint(20, 2000)).clone(140)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseRouteSwitchTimeout.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseRouteSwitchTimeout.setDescription('Route switch timeout. How long to wait, without receiving a subsequent route update from the original neighbor, before switching to a different neighbor.')
wfDvmrpBaseActualRoutes = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpBaseActualRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseActualRoutes.setDescription('Count of number of entries currently in route table')
wfDvmrpBaseDebugLevel = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 14), Gauge32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295)).clone(1)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseDebugLevel.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseDebugLevel.setDescription("Turn DVMRP log ON or OFF for DVMRP debuging messages The levels are: NO_DISPLAY_LOG 0x0001 - Reserved ROUTE_UPDATE_LOG 0x0002 - Displays all routing table events CACHE_ADD_LOG 0x0004 - Displays events relating to addition of cache entry by the cache gate CACHE_DELETE_LOG 0x0008 - Displays all events relating to deletion of cache entry CACHE_CHANGE_LOG 0x0010 - Displays all events relating to updates of cache entries CACHE_DATA_LOG 0x0020 - obsolete PRUNE_MSG_LOG 0x0040 - Display router received pruning related messages, including prunes, grafts, graft_acks, and neighbor reset PRUNE_XMIT_LOG 0x0080 - Display a messaged when a initial prune state is established for a (src, group). IGMP_COM_LOG 0x0100 - Display communication events between IGMP and DVMRP, events including some hosts joining a group, and all hosts leaving a group. DVMRP_XMIT_LOG 0x0200 - Display transmission events by the router, e.g, prune, grafts... CACHE_NO_GH_LOG 0x0400 - Display buffer forwarding to non-existing main or remote cache gate. CACHE_DBG_LOG 0x0800 - Display general debugging messaages MEM_DBG_LOG 0x1000 - Display dvmrp memory usage activities INTEROP_DBG_LOG 0x2000 - Display dvmrp mospf debug CACHE_BASE_ADD_LOG 0x4000 - Obsolete CACHE_VIF_ADD_LOG 0x8000 - Obsolete CACHE_BASE_DELETE_LOG 0x10000 - Obsolete CACHE_VIF_DELETE_LOG 0x20000 - Obsolete MTRACE_UPDATE_LOG 0x40000 - Displays mtrace update info NEIGHBOR_UPDATE_LOG 0x80000 - Display events relating to addition, deletion and update of neighbor's info MTM_INTERFACE_LOG 0x100000 - Display events relating to MTM-DVMRP interface, events as MTM inbound, outbound interact with DVMRP and entries deletion/addition. ROUTE_ADD_LOG 0x200000 - ROUTE_DEL_LOG 0x400000 - REMOTE_CACHE_ADD_LOG 0x800000 - Display addition event for the outgoing interface of (source, group) cache entry REMOTE_CACHE_DELETE_LOG 0x1000000 - Display deletion event for the outgoing interface of (source, group) cache entry RX_CONFLICT_ROUTE_INFO_LOG 0x2000000 - Display received conflict route information")
wfDvmrpBasePruningEnable = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 15), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBasePruningEnable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBasePruningEnable.setDescription('Enable or Disable Pruning functionality at the Base level')
wfDvmrpBaseFragmentMtuThreshold = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 16), Integer32().subtype(subtypeSpec=ValueRangeConstraint(910, 2147483647)).clone(1514)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseFragmentMtuThreshold.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpBaseFragmentMtuThreshold.setDescription('the default value is the CSMACD_MTU, and the MINiMUN is X25_DDN_MTU. Both are taken from dp.h')
wfDvmrpBaseMaxRoutes = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 17), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseMaxRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseMaxRoutes.setDescription('Max number of routes, per slot. This is used to limit the size of routing tables. Note that routes are kept on a per-source network basis, independent of multicast group. This number must include a route for every local network that has a CCT configured for multicasting.')
wfDvmrpBasePolicyEnable = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 18), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBasePolicyEnable.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpBasePolicyEnable.setDescription('Enable or Disable route policy functionality at the Base level')
wfDvmrpBaseHolddownEnable = MibScalar((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 1, 19), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpBaseHolddownEnable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpBaseHolddownEnable.setDescription('Enable or Disable holddown of deleted routes.')
wfDvmrpCircuitEntryTable = MibTable((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2), )
if mibBuilder.loadTexts: wfDvmrpCircuitEntryTable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitEntryTable.setDescription('Circuit virtual interfaces (aka physical VIFs)')
wfDvmrpCircuitEntry = MibTableRow((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1), ).setIndexNames((0, "Wellfleet-DVMRP-MIB", "wfDvmrpCircuitCCT"))
if mibBuilder.loadTexts: wfDvmrpCircuitEntry.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitEntry.setDescription('One instance of this object exists for every CCT that supports this feature. The instance ID for this object will be the circuit number.')
wfDvmrpCircuitCreate = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("created", 1), ("deleted", 2))).clone('created')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitCreate.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitCreate.setDescription('Create or delete')
wfDvmrpCircuitEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitEnable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitEnable.setDescription('Enable or disable DVMRP on this circuit')
wfDvmrpCircuitState = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))).clone(namedValues=NamedValues(("up", 1), ("down", 2), ("init", 3), ("invalid", 4), ("notpres", 5))).clone('notpres')).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitState.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitState.setDescription('The current state of the DVMRP interface. Invalid indicates an error in processing the configuration record.')
wfDvmrpCircuitCCT = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitCCT.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitCCT.setDescription('This circuit number.')
wfDvmrpCircuitRouteEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitRouteEnable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitRouteEnable.setDescription("Enable/disble this circuit for routing. If enabled, this circuit will be used to propogate routing information, information about this circuit will be incorporated into routing updates, and multicast datagrams will be forwarded 'in native mode' (e.g. as multicast datagrams) via this circuit. If disabled, this circuit exists only to support unicast tunnels; in this case, all other paramters are ignored.")
wfDvmrpCircuitMetric = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 31)).clone(1)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitMetric.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitMetric.setDescription('Metric. This value represents the cost of this interface; the cost of using this hop. This value must be smaller than the route infinity value')
wfDvmrpCircuitRouteThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 254)).clone(1)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitRouteThreshold.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitRouteThreshold.setDescription('Threshold. This value can be used to filter out datagrams that are being forwarded to a neighboring router; if the IP TTL is not >= the threshold, the datagram is dropped by this router')
wfDvmrpCircuitInPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 8), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitInPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitInPkts.setDescription('Number of datagrams received on this interface')
wfDvmrpCircuitOutPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 9), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitOutPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitOutPkts.setDescription('Number of datagrams send on this interface')
wfDvmrpCircuitInRouteUpdates = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 10), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitInRouteUpdates.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitInRouteUpdates.setDescription('Number of DVMRP route update messages received')
wfDvmrpCircuitOutRouteUpdates = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 11), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitOutRouteUpdates.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitOutRouteUpdates.setDescription('Number of DVMRP route update messages sent')
wfDvmrpCircuitInPktDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 12), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitInPktDiscards.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitInPktDiscards.setDescription('Number of inbound datagrams discarded due to route not found')
wfDvmrpCircuitOutPktDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 13), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitOutPktDiscards.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitOutPktDiscards.setDescription('Number of outbound datagrams discarded due to route not found')
wfDvmrpCircuitFwdCacheSize = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 14), Integer32().subtype(subtypeSpec=ValueRangeConstraint(32, 512)).clone(32)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitFwdCacheSize.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitFwdCacheSize.setDescription('Maximum number of entries allowed in the Forwarding table at one time. there is a Forwarding table per vif')
wfDvmrpCircuitFwdCacheTTL = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 15), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 86400)).clone(7200)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitFwdCacheTTL.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitFwdCacheTTL.setDescription('The time_to_live for the Forwarding table entries in seconds .')
wfDvmrpCircuitAdvertiseSelf = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 16), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitAdvertiseSelf.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitAdvertiseSelf.setDescription('If enabled the router will advertise itself as one of the source net. If not enabled the router will not advertise itself as one of the source net.')
wfDvmrpCircuitFwdCacheEntries = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 17), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitFwdCacheEntries.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitFwdCacheEntries.setDescription('The most up to date number of entries in the forwarding cache')
wfDvmrpCircuitInPrunePkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 18), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitInPrunePkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitInPrunePkts.setDescription('Number of PRUNE datagrams received on this interface')
wfDvmrpCircuitOutPrunePkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 19), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitOutPrunePkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitOutPrunePkts.setDescription('Number of PRUNE datagrams send on this interface')
wfDvmrpCircuitInGraftPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 20), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitInGraftPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitInGraftPkts.setDescription('Number of GRAFT datagrams received on this interface')
wfDvmrpCircuitOutGraftPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 21), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitOutGraftPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitOutGraftPkts.setDescription('Number of GRAFT datagrams send on this interface')
wfDvmrpCircuitInGraftAckPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 22), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitInGraftAckPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitInGraftAckPkts.setDescription('Number of GRAFT_ACK datagrams received on this interface')
wfDvmrpCircuitOutGraftAckPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 23), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitOutGraftAckPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitOutGraftAckPkts.setDescription('Number of GRAFT_ACK datagrams send on this interface')
wfDvmrpCircuitDefaultRouteSupply = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 24), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2), ("generate", 3))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitDefaultRouteSupply.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitDefaultRouteSupply.setDescription('enabled : Send the default route, 0.0.0.0 if learned, form this interface. disabled: no default route is sent from this interface. generate: generate default route, 0.0.0.0 from this interface.')
wfDvmrpCircuitDefaultRouteListen = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 25), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitDefaultRouteListen.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitDefaultRouteListen.setDescription('Receive the default route, 0.0.0.0 on this interface')
wfDvmrpCircuitReportDependProbe = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 26), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitReportDependProbe.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitReportDependProbe.setDescription('This is to control accepting the route report. According to the protocol, dvmrp should send probe packet before sending the route report packet to the neighbors. But some vendor implementation did not send probes before sending reports. Enable: only process the routes from the neighbor sending probes. Disable: No Dependency (no restriction).')
wfDvmrpCircuitPruneLifeTime = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 27), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 86400)).clone(7200)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpCircuitPruneLifeTime.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitPruneLifeTime.setDescription('The life time of the prune message the router sends to its neighbor in seconds.')
wfDvmrpCircuitAcceptAggregateRoutes = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 28), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitAcceptAggregateRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitAcceptAggregateRoutes.setDescription('Count of number of routes received have been aggregated to the specific aggregate route currently in route table for this interface.')
wfDvmrpCircuitAnnounceAggregatedRoutes = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 2, 1, 29), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpCircuitAnnounceAggregatedRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpCircuitAnnounceAggregatedRoutes.setDescription('Count of number of routes have been aggregated to the specific aggregate route for advertisement currently in route table for this interface.')
wfDvmrpTunnelEntryTable = MibTable((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3), )
if mibBuilder.loadTexts: wfDvmrpTunnelEntryTable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelEntryTable.setDescription('Tunnel virtual interfaces')
wfDvmrpTunnelEntry = MibTableRow((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1), ).setIndexNames((0, "Wellfleet-DVMRP-MIB", "wfDvmrpTunnelCCT"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpTunnelLocalRouterIpAddress"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpTunnelRemoteRouterIpAddress"))
if mibBuilder.loadTexts: wfDvmrpTunnelEntry.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelEntry.setDescription("This object is used to specify the set of 'multicast tunnels', unicast pipes that are used to send IP multicast datagrams to remote network multicast routers via intermediate routers that may not support this style of IP multicasting. One instance of this object exists for every separate tunnel destination. The instance identifier is the IP address of the remote router neighbor and the local circuit number.")
wfDvmrpTunnelCreate = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("created", 1), ("deleted", 2))).clone('created')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelCreate.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelCreate.setDescription('create/delete')
wfDvmrpTunnelEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('enabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelEnable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelEnable.setDescription('enable/disable this tunnel interface')
wfDvmrpTunnelState = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))).clone(namedValues=NamedValues(("up", 1), ("down", 2), ("init", 3), ("invalid", 4), ("notpres", 5))).clone('notpres')).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelState.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelState.setDescription('The current state of the DVMRP tunnel interface. Invalid indicates an error in processing the configuration record.')
wfDvmrpTunnelCCT = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelCCT.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelCCT.setDescription('The multicast circuit associated with this tunnel.')
wfDvmrpTunnelRemoteRouterIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 5), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelRemoteRouterIpAddress.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelRemoteRouterIpAddress.setDescription('(unicast) IP address of remote network router neighbor.')
wfDvmrpTunnelEncapsMode = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("ip-in-ip", 1), ("lssr", 2))).clone('ip-in-ip')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelEncapsMode.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelEncapsMode.setDescription('Will these tunnelled datagrams be encapsulated within an IP datagram, or will they be loosely encapsulated using the LSSR option (for the latter, refer to RFC 1075; this is needed for backward compatibility)')
wfDvmrpTunnelMetric = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 31)).clone(1)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelMetric.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelMetric.setDescription('Cost of using this tunnel')
wfDvmrpTunnelThreshold = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 254)).clone(1)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelThreshold.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelThreshold.setDescription('Threshold for forwarding through this tunnel; if TTL < threshold, the datagram is dropped.')
wfDvmrpTunnelInPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 9), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelInPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelInPkts.setDescription('Number of datagrams received on this interface')
wfDvmrpTunnelOutPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 10), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelOutPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelOutPkts.setDescription('Number of datagrams send on this interface')
wfDvmrpTunnelInRouteUpdates = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 11), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelInRouteUpdates.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelInRouteUpdates.setDescription('Number of DVMRP route update messages received')
wfDvmrpTunnelOutRouteUpdates = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 12), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelOutRouteUpdates.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelOutRouteUpdates.setDescription('Number of DVMRP route update messages sent')
wfDvmrpTunnelInPktDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 13), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelInPktDiscards.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelInPktDiscards.setDescription('Number of inbound datagrams discarded due to route not found or due to invalid inner address (dest address != multicast)')
wfDvmrpTunnelOutPktDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 14), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelOutPktDiscards.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelOutPktDiscards.setDescription('Number of outbound datagrams discarded due to route not found')
wfDvmrpTunnelLocalRouterIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 15), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelLocalRouterIpAddress.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelLocalRouterIpAddress.setDescription('(unicast) IP address of local network router. To support multinet.')
wfDvmrpTunnelFwdCacheSize = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 16), Integer32().subtype(subtypeSpec=ValueRangeConstraint(32, 512)).clone(32)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelFwdCacheSize.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelFwdCacheSize.setDescription('Maximum number of entries allowed in the Forwarding table at one time. there is a Forwarding table per vif')
wfDvmrpTunnelFwdCacheTTL = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 17), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 86400)).clone(7200)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelFwdCacheTTL.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelFwdCacheTTL.setDescription('The time_to_live for the Forwarding table entries in seconds .')
wfDvmrpTunnelFwdCacheEntries = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 18), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelFwdCacheEntries.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelFwdCacheEntries.setDescription('The most up to date number of entries in the forwarding cache')
wfDvmrpTunnelInPrunePkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 19), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelInPrunePkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelInPrunePkts.setDescription('Number of PRUNE datagrams received on this interface')
wfDvmrpTunnelOutPrunePkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 20), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelOutPrunePkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelOutPrunePkts.setDescription('Number of PRUNE datagrams send on this interface')
wfDvmrpTunnelInGraftPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 21), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelInGraftPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelInGraftPkts.setDescription('Number of GRAFT datagrams received on this interface')
wfDvmrpTunnelOutGraftPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 22), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelOutGraftPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelOutGraftPkts.setDescription('Number of GRAFT datagrams send on this interface')
wfDvmrpTunnelInGraftAckPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 23), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelInGraftAckPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelInGraftAckPkts.setDescription('Number of GRAFT_ACK datagrams received on this interface')
wfDvmrpTunnelOutGraftAckPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 24), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelOutGraftAckPkts.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelOutGraftAckPkts.setDescription('Number of GRAFT_ACK datagrams send on this interface')
wfDvmrpTunnelDefaultRouteSupply = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 25), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2), ("generate", 3))).clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelDefaultRouteSupply.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelDefaultRouteSupply.setDescription('Send the default route, 0.0.0.0 on this interface')
wfDvmrpTunnelDefaultRouteListen = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 26), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelDefaultRouteListen.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelDefaultRouteListen.setDescription('Receive the default route, 0.0.0.0 on this interface')
wfDvmrpTunnelCtrlMsgMode = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 27), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("native", 1), ("ip-in-ip", 2))).clone('native')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelCtrlMsgMode.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelCtrlMsgMode.setDescription('Dvmrp tunneling control messages encapsulated type. noencaps is the mode that control messages are sent in regular igmp packets with ip protocol type set to IP_PROTOCOL_IGMP. encaps is the mode that control messages are encapsed inside ip packets with ip protocol type set to IP_PROTOCOL_IPINIP. All DVMRP messages sent across tunnels will be encapsulated in the same way as data packets in this mode.')
wfDvmrpTunnelReportDependProbe = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 28), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2))).clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelReportDependProbe.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelReportDependProbe.setDescription('This is to control accepting the route report. According to the protocol, dvmrp should send probe packet before sending the route report packet to the neighbors. But some vendor implementations do not send probes before sending reports. Enable: only process the routes from the neighbor sending probes. Disable: No Dependency (no restriction).')
wfDvmrpTunnelPruneLifeTime = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 29), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 86400)).clone(7200)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: wfDvmrpTunnelPruneLifeTime.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelPruneLifeTime.setDescription('The life time of the prune message the router send to its neighbor in seconds.')
wfDvmrpTunnelAcceptAggregateRoutes = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 30), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelAcceptAggregateRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelAcceptAggregateRoutes.setDescription('Count of number of routes received have been aggregated to the specific aggregate route currently in route table for this interface.')
wfDvmrpTunnelAnnounceAggregatedRoutes = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 3, 1, 31), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpTunnelAnnounceAggregatedRoutes.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpTunnelAnnounceAggregatedRoutes.setDescription('Count of number of routes have been aggregated to the specific aggregate route for advertisement currently in route table for this interface.')
wfDvmrpRouteEntryTable = MibTable((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4), )
if mibBuilder.loadTexts: wfDvmrpRouteEntryTable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteEntryTable.setDescription('MIB proxy: main DVMRP routing table')
wfDvmrpRouteEntry = MibTableRow((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1), ).setIndexNames((0, "Wellfleet-DVMRP-MIB", "wfDvmrpRouteSourceNetwork"))
if mibBuilder.loadTexts: wfDvmrpRouteEntry.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteEntry.setDescription('Supported by mib proxy. One entry exists for each active route.')
wfDvmrpRouteSourceNetwork = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 1), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteSourceNetwork.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteSourceNetwork.setDescription('A source of multicast datagrams')
wfDvmrpRouteSourceMask = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteSourceMask.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteSourceMask.setDescription('Mask for the specified source network')
wfDvmrpRouteNextHopRouter = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 3), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteNextHopRouter.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteNextHopRouter.setDescription('Next hop multicast router to the specified source network; we consider this neighboring router to be on the shortest path to the source. Note that this neighboring router may be a tunnel endpoint.')
wfDvmrpRouteNextHopInterfaceCCT = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteNextHopInterfaceCCT.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteNextHopInterfaceCCT.setDescription('Next hop interface (CCT) to the specified source router; we consider this interface to be on the shortest path to the source.')
wfDvmrpRouteNextHopInterfaceTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 5), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteNextHopInterfaceTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteNextHopInterfaceTunnelId.setDescription('Next hop interface (tunnel id) to the specified source router; we consider this interface to be on the shortest path to the source.')
wfDvmrpRouteNextHopInterfaceLocalTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 6), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteNextHopInterfaceLocalTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteNextHopInterfaceLocalTunnelId.setDescription('Next hop interface (local tunnel id) to the specified source router; we consider this interface to be on the shortest path to the source.')
wfDvmrpRouteTimer = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteTimer.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteTimer.setDescription('route timer')
wfDvmrpRouteState = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteState.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteState.setDescription('Set of flags indicating state of entry. Note that the router uses this field as a bit mask. 0x8000 Network is local to this router 0x4000 Route is being timed 0x2000 Route is garbaged')
wfDvmrpRouteMetric = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteMetric.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteMetric.setDescription('current route metric')
wfDvmrpRouteProtocol = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteProtocol.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteProtocol.setDescription('current route protocol dvmrp (2) or mospf (4) or internal (6) which is the route from unicast and incoming interface no i dvmrp configure, if dvmrp is configured then the protocol will be set to 2, see wfIgmpRoutingProtocol')
wfDvmrpRouteType = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteType.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteType.setDescription('The orginal route source from. If it is from pure dvmrp route (0x0001) unicast best route (0x0002) unciast route but has dvmrp interface (0x0003) ospf(0x0004) ospf best route (0x0006) ospf ase route (0x0008)')
wfDvmrpRouteAggregatedType = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 4, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteAggregatedType.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteAggregatedType.setDescription('Route Aggregated types : 0 - normal route 1 - inbound aggregated route 2 - outbound aggregated route 4 - inbound aggregate route 8 - outbound aggregate route')
wfDvmrpRouteInterfaceEntryTable = MibTable((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5), )
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceEntryTable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceEntryTable.setDescription('MIB proxy: DVMRP VIF routing table')
wfDvmrpRouteInterfaceEntry = MibTableRow((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1), ).setIndexNames((0, "Wellfleet-DVMRP-MIB", "wfDvmrpRouteInterfaceSourceNetwork"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpRouteInterfaceParentCCT"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpRouteInterfaceParentLocalTunnelId"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpRouteInterfaceParentTunnelId"))
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceEntry.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceEntry.setDescription('Supported by mib proxy. One entry exists for each virtual interface on an active route. It is associated with a route via the source network/ net mask fields. The instance ID includes tunnel ID, which is 0 for non-tunnel interfaces.')
wfDvmrpRouteInterfaceSourceNetwork = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 1), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSourceNetwork.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSourceNetwork.setDescription('A source of multicast datagrams')
wfDvmrpRouteInterfaceSourceMask = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSourceMask.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSourceMask.setDescription('Mask for the specified source network')
wfDvmrpRouteInterfaceNextHopInterfaceCCT = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceNextHopInterfaceCCT.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceNextHopInterfaceCCT.setDescription('circuit number with which this route is associated')
wfDvmrpRouteInterfaceNextHopInterfaceLocalTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 4), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceNextHopInterfaceLocalTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceNextHopInterfaceLocalTunnelId.setDescription('Tunnel ID for tunnelled interfaces. This value is zero for non-tunnelled interfaces, otherwise it contains the local IP address of the tunnel.')
wfDvmrpRouteInterfaceNextHopInterfaceTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 5), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceNextHopInterfaceTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceNextHopInterfaceTunnelId.setDescription('Tunnel ID for tunnelled interfaces. This value is zero for non-tunnelled interfaces, otherwise it contains the remote IP address of the tunnel.')
wfDvmrpRouteInterfaceState = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceState.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceState.setDescription('state of interface for this route. Note that the router uses this field as a bit mask. 0x8000 - interface is leaf 0x4000 - interface is child 0x2000 - interface is in hold-down state 0x1000 - interface has loop neighbor for this route')
wfDvmrpRouteInterfaceDominantRouter = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 7), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceDominantRouter.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceDominantRouter.setDescription('dominant router address for virtual interface')
wfDvmrpRouteInterfaceSubordinateRouter = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 8), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSubordinateRouter.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSubordinateRouter.setDescription('subordinate router address for virtual interface')
wfDvmrpRouteInterfaceHoldDownTimer = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceHoldDownTimer.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceHoldDownTimer.setDescription('Current value of hold down timer, used to determine if interface is for leaf or non-leaf network. Non-leaf network means that a local network router considers us to be in the shortest path to the source (they have sent us a route update with metric >= infinity).')
wfDvmrpRouteInterfaceSPInDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 10), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSPInDiscards.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSPInDiscards.setDescription('Count of inbound packets discarded because interface not on shortest path')
wfDvmrpRouteInterfaceSPOutDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 11), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSPOutDiscards.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceSPOutDiscards.setDescription('Count of outbound packets discarded because interface not on shortest path')
wfDvmrpRouteInterfaceThresholdOutDiscards = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 12), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceThresholdOutDiscards.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceThresholdOutDiscards.setDescription('Count of outbound packets discarded because of threshold')
wfDvmrpRouteInterfaceInSuccessfulPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 13), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceInSuccessfulPkts.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceInSuccessfulPkts.setDescription('Count of inbound packets accepted for forwarding')
wfDvmrpRouteInterfaceOutSuccessfulPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 14), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceOutSuccessfulPkts.setStatus('obsolete')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceOutSuccessfulPkts.setDescription('Count of outbound packets accepted for forwarding')
wfDvmrpRouteInterfaceParentCCT = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceParentCCT.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceParentCCT.setDescription('circuit number with which this route is associated;parent VIF')
wfDvmrpRouteInterfaceParentLocalTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 16), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceParentLocalTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceParentLocalTunnelId.setDescription('Tunnel ID for tunnelled interfaces. This value is zero for non-tunnelled interfaces, otherwise it contains the local IP address of the tunnel; parent VIF.')
wfDvmrpRouteInterfaceParentTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 5, 1, 17), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceParentTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpRouteInterfaceParentTunnelId.setDescription('Tunnel ID for tunnelled interfaces. This value is zero for non-tunnelled interfaces, otherwise it contains the remote IP address of the tunnel; parent VIF.')
wfDvmrpNeighboringRouterEntryTable = MibTable((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6), )
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterEntryTable.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterEntryTable.setDescription('MIB proxy: DVMRP neighbor table')
wfDvmrpNeighboringRouterEntry = MibTableRow((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1), ).setIndexNames((0, "Wellfleet-DVMRP-MIB", "wfDvmrpNeighboringRouterCCT"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpNeighboringRouterLocalTunnelId"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpNeighboringRouterTunnelId"), (0, "Wellfleet-DVMRP-MIB", "wfDvmrpNeighboringRouterIpAddr"))
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterEntry.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterEntry.setDescription('This entry is used to indentify the known neighboring routers for a circuit. This object will be indentified by circuit number, tunnel id (to identify local interface), and the IP address of the neighbor. ')
wfDvmrpNeighboringRouterCCT = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterCCT.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterCCT.setDescription('Local circuit number')
wfDvmrpNeighboringRouterLocalTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterLocalTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterLocalTunnelId.setDescription('Tunnel Id for interface. This value is zero for non- tunnelled interfaces, otherwise it contains the IP address of the local tunnel endpoint.')
wfDvmrpNeighboringRouterTunnelId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 3), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterTunnelId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterTunnelId.setDescription('Tunnel Id for interface. This value is zero for non- tunnelled interfaces, otherwise it contains the IP address of the remote tunnel endpoint.')
wfDvmrpNeighboringRouterIpAddr = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 4), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterIpAddr.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterIpAddr.setDescription('IP address of neighboring router')
wfDvmrpNeighboringRouterState = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterState.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterState.setDescription('State of neighbor. The router uses this as a bit mask. 0x8000 - Neighbor is being timed')
wfDvmrpNeighboringRouterTimer = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterTimer.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterTimer.setDescription('Current value of neighbor timer')
wfDvmrpNeighboringRouterGenId = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterGenId.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterGenId.setDescription("The neighboring router's generation identifier.")
wfDvmrpNeighboringRouterMajorVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 8), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterMajorVersion.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterMajorVersion.setDescription("The neighboring router's major DVMRP version number.")
wfDvmrpNeighboringRouterMinorVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterMinorVersion.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterMinorVersion.setDescription("The neighboring router's minor DVMRP version number.")
wfDvmrpNeighboringRouterCapabilities = MibTableColumn((1, 3, 6, 1, 4, 1, 18, 3, 5, 3, 12, 6, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterCapabilities.setStatus('mandatory')
if mibBuilder.loadTexts: wfDvmrpNeighboringRouterCapabilities.setDescription("This object describes the neighboring router's capabilities. The leaf bit indicates that the neighbor has only one interface with neighbors. The prune bit indicates that the neighbor supports pruning. The generationID bit indicates that the neighbor sends its generationID in Probe messages. The mtrace bit indicates that the neighbor can handle mtrace requests.")
mibBuilder.exportSymbols("Wellfleet-DVMRP-MIB", wfDvmrpTunnelRemoteRouterIpAddress=wfDvmrpTunnelRemoteRouterIpAddress, wfDvmrpNeighboringRouterEntryTable=wfDvmrpNeighboringRouterEntryTable, wfDvmrpTunnelOutRouteUpdates=wfDvmrpTunnelOutRouteUpdates, wfDvmrpRouteEntryTable=wfDvmrpRouteEntryTable, wfDvmrpTunnelReportDependProbe=wfDvmrpTunnelReportDependProbe, wfDvmrpRouteNextHopRouter=wfDvmrpRouteNextHopRouter, wfDvmrpRouteInterfaceNextHopInterfaceCCT=wfDvmrpRouteInterfaceNextHopInterfaceCCT, wfDvmrpRouteInterfaceNextHopInterfaceLocalTunnelId=wfDvmrpRouteInterfaceNextHopInterfaceLocalTunnelId, wfDvmrpCircuitEnable=wfDvmrpCircuitEnable, wfDvmrpCircuitInGraftPkts=wfDvmrpCircuitInGraftPkts, wfDvmrpCircuitInPkts=wfDvmrpCircuitInPkts, wfDvmrpCircuitFwdCacheTTL=wfDvmrpCircuitFwdCacheTTL, wfDvmrpTunnelOutGraftPkts=wfDvmrpTunnelOutGraftPkts, wfDvmrpBaseFragmentMtuThreshold=wfDvmrpBaseFragmentMtuThreshold, wfDvmrpCircuitRouteEnable=wfDvmrpCircuitRouteEnable, wfDvmrpTunnelDefaultRouteListen=wfDvmrpTunnelDefaultRouteListen, wfDvmrpTunnelCtrlMsgMode=wfDvmrpTunnelCtrlMsgMode, wfDvmrpRouteInterfaceHoldDownTimer=wfDvmrpRouteInterfaceHoldDownTimer, wfDvmrpTunnelAcceptAggregateRoutes=wfDvmrpTunnelAcceptAggregateRoutes, wfDvmrpTunnelInPrunePkts=wfDvmrpTunnelInPrunePkts, wfDvmrpRouteInterfaceDominantRouter=wfDvmrpRouteInterfaceDominantRouter, wfDvmrpTunnelPruneLifeTime=wfDvmrpTunnelPruneLifeTime, wfDvmrpCircuitOutPktDiscards=wfDvmrpCircuitOutPktDiscards, wfDvmrpCircuitFwdCacheSize=wfDvmrpCircuitFwdCacheSize, wfDvmrpTunnelInGraftAckPkts=wfDvmrpTunnelInGraftAckPkts, wfDvmrpCircuitAnnounceAggregatedRoutes=wfDvmrpCircuitAnnounceAggregatedRoutes, wfDvmrpTunnelEntryTable=wfDvmrpTunnelEntryTable, wfDvmrpBaseTriggeredUpdateInterval=wfDvmrpBaseTriggeredUpdateInterval, wfDvmrpRouteEntry=wfDvmrpRouteEntry, wfDvmrpRouteInterfaceNextHopInterfaceTunnelId=wfDvmrpRouteInterfaceNextHopInterfaceTunnelId, wfDvmrpRouteInterfaceEntryTable=wfDvmrpRouteInterfaceEntryTable, wfDvmrpBaseMaxRoutes=wfDvmrpBaseMaxRoutes, wfDvmrpTunnelCreate=wfDvmrpTunnelCreate, wfDvmrpBaseLeafTimeout=wfDvmrpBaseLeafTimeout, wfDvmrpRouteInterfaceOutSuccessfulPkts=wfDvmrpRouteInterfaceOutSuccessfulPkts, wfDvmrpTunnelInPktDiscards=wfDvmrpTunnelInPktDiscards, wfDvmrpRouteInterfaceState=wfDvmrpRouteInterfaceState, wfDvmrpCircuitFwdCacheEntries=wfDvmrpCircuitFwdCacheEntries, wfDvmrpRouteNextHopInterfaceLocalTunnelId=wfDvmrpRouteNextHopInterfaceLocalTunnelId, wfDvmrpRouteType=wfDvmrpRouteType, wfDvmrpCircuitOutRouteUpdates=wfDvmrpCircuitOutRouteUpdates, wfDvmrpBaseState=wfDvmrpBaseState, wfDvmrpRouteSourceNetwork=wfDvmrpRouteSourceNetwork, wfDvmrpTunnelEncapsMode=wfDvmrpTunnelEncapsMode, wfDvmrpTunnelOutPkts=wfDvmrpTunnelOutPkts, wfDvmrpNeighboringRouterIpAddr=wfDvmrpNeighboringRouterIpAddr, wfDvmrpCircuitOutGraftPkts=wfDvmrpCircuitOutGraftPkts, wfDvmrpCircuitInPrunePkts=wfDvmrpCircuitInPrunePkts, wfDvmrpRouteInterfaceSPInDiscards=wfDvmrpRouteInterfaceSPInDiscards, wfDvmrpCircuitDefaultRouteListen=wfDvmrpCircuitDefaultRouteListen, wfDvmrpNeighboringRouterTimer=wfDvmrpNeighboringRouterTimer, wfDvmrpRouteInterfaceParentCCT=wfDvmrpRouteInterfaceParentCCT, wfDvmrpTunnelDefaultRouteSupply=wfDvmrpTunnelDefaultRouteSupply, wfDvmrpNeighboringRouterTunnelId=wfDvmrpNeighboringRouterTunnelId, wfDvmrpTunnelInPkts=wfDvmrpTunnelInPkts, wfDvmrpTunnelFwdCacheSize=wfDvmrpTunnelFwdCacheSize, wfDvmrpBaseNeighborProbeInterval=wfDvmrpBaseNeighborProbeInterval, wfDvmrpBaseRouteSwitchTimeout=wfDvmrpBaseRouteSwitchTimeout, wfDvmrpNeighboringRouterGenId=wfDvmrpNeighboringRouterGenId, wfDvmrpTunnelAnnounceAggregatedRoutes=wfDvmrpTunnelAnnounceAggregatedRoutes, wfDvmrpCircuitReportDependProbe=wfDvmrpCircuitReportDependProbe, wfDvmrpTunnelEnable=wfDvmrpTunnelEnable, wfDvmrpTunnelInRouteUpdates=wfDvmrpTunnelInRouteUpdates, wfDvmrpCircuitInRouteUpdates=wfDvmrpCircuitInRouteUpdates, wfDvmrpRouteInterfaceSPOutDiscards=wfDvmrpRouteInterfaceSPOutDiscards, wfDvmrpNeighboringRouterEntry=wfDvmrpNeighboringRouterEntry, wfDvmrpCircuitMetric=wfDvmrpCircuitMetric, wfDvmrpRouteTimer=wfDvmrpRouteTimer, wfDvmrpNeighboringRouterCapabilities=wfDvmrpNeighboringRouterCapabilities, wfDvmrpCircuitDefaultRouteSupply=wfDvmrpCircuitDefaultRouteSupply, wfDvmrpTunnelOutGraftAckPkts=wfDvmrpTunnelOutGraftAckPkts, wfDvmrpTunnelInGraftPkts=wfDvmrpTunnelInGraftPkts, wfDvmrpCircuitAdvertiseSelf=wfDvmrpCircuitAdvertiseSelf, wfDvmrpBaseEnable=wfDvmrpBaseEnable, wfDvmrpTunnelLocalRouterIpAddress=wfDvmrpTunnelLocalRouterIpAddress, wfDvmrpRouteSourceMask=wfDvmrpRouteSourceMask, wfDvmrpRouteState=wfDvmrpRouteState, wfDvmrpNeighboringRouterCCT=wfDvmrpNeighboringRouterCCT, wfDvmrpCircuitCreate=wfDvmrpCircuitCreate, wfDvmrpRouteProtocol=wfDvmrpRouteProtocol, wfDvmrpCircuitEntryTable=wfDvmrpCircuitEntryTable, wfDvmrpCircuitPruneLifeTime=wfDvmrpCircuitPruneLifeTime, wfDvmrpBasePolicyEnable=wfDvmrpBasePolicyEnable, wfDvmrpBaseHolddownEnable=wfDvmrpBaseHolddownEnable, wfDvmrpRouteInterfaceSubordinateRouter=wfDvmrpRouteInterfaceSubordinateRouter, wfDvmrpRouteInterfaceParentTunnelId=wfDvmrpRouteInterfaceParentTunnelId, wfDvmrpCircuitInPktDiscards=wfDvmrpCircuitInPktDiscards, wfDvmrpRouteMetric=wfDvmrpRouteMetric, wfDvmrpBasePruningEnable=wfDvmrpBasePruningEnable, wfDvmrpCircuitOutPkts=wfDvmrpCircuitOutPkts, wfDvmrpBaseFullUpdateInterval=wfDvmrpBaseFullUpdateInterval, wfDvmrpBaseRouteExpirationTimeout=wfDvmrpBaseRouteExpirationTimeout, wfDvmrpRouteInterfaceSourceNetwork=wfDvmrpRouteInterfaceSourceNetwork, wfDvmrpRouteAggregatedType=wfDvmrpRouteAggregatedType, wfDvmrpRouteInterfaceInSuccessfulPkts=wfDvmrpRouteInterfaceInSuccessfulPkts, wfDvmrpBaseActualRoutes=wfDvmrpBaseActualRoutes, wfDvmrpRouteInterfaceEntry=wfDvmrpRouteInterfaceEntry, wfDvmrpTunnelFwdCacheTTL=wfDvmrpTunnelFwdCacheTTL, wfDvmrpTunnelCCT=wfDvmrpTunnelCCT, wfDvmrpTunnelMetric=wfDvmrpTunnelMetric, wfDvmrpBaseGarbageTimeout=wfDvmrpBaseGarbageTimeout, wfDvmrpTunnelEntry=wfDvmrpTunnelEntry, wfDvmrpTunnelOutPktDiscards=wfDvmrpTunnelOutPktDiscards, wfDvmrpBaseDebugLevel=wfDvmrpBaseDebugLevel, wfDvmrpRouteNextHopInterfaceCCT=wfDvmrpRouteNextHopInterfaceCCT, wfDvmrpNeighboringRouterState=wfDvmrpNeighboringRouterState, wfDvmrpCircuitInGraftAckPkts=wfDvmrpCircuitInGraftAckPkts, wfDvmrpBaseCreate=wfDvmrpBaseCreate, wfDvmrpCircuitCCT=wfDvmrpCircuitCCT, wfDvmrpCircuitOutGraftAckPkts=wfDvmrpCircuitOutGraftAckPkts, wfDvmrpCircuitState=wfDvmrpCircuitState, wfDvmrpNeighboringRouterLocalTunnelId=wfDvmrpNeighboringRouterLocalTunnelId, wfDvmrpRouteInterfaceSourceMask=wfDvmrpRouteInterfaceSourceMask, wfDvmrpCircuitEntry=wfDvmrpCircuitEntry, wfDvmrpTunnelState=wfDvmrpTunnelState, wfDvmrpNeighboringRouterMinorVersion=wfDvmrpNeighboringRouterMinorVersion, wfDvmrpRouteInterfaceParentLocalTunnelId=wfDvmrpRouteInterfaceParentLocalTunnelId, wfDvmrpRouteInterfaceThresholdOutDiscards=wfDvmrpRouteInterfaceThresholdOutDiscards, wfDvmrpNeighboringRouterMajorVersion=wfDvmrpNeighboringRouterMajorVersion, wfDvmrpCircuitAcceptAggregateRoutes=wfDvmrpCircuitAcceptAggregateRoutes, wfDvmrpBaseNeighborTimeout=wfDvmrpBaseNeighborTimeout, wfDvmrpBase=wfDvmrpBase, wfDvmrpTunnelThreshold=wfDvmrpTunnelThreshold, wfDvmrpRouteNextHopInterfaceTunnelId=wfDvmrpRouteNextHopInterfaceTunnelId, wfDvmrpBaseEstimatedRoutes=wfDvmrpBaseEstimatedRoutes, wfDvmrpCircuitOutPrunePkts=wfDvmrpCircuitOutPrunePkts, wfDvmrpTunnelOutPrunePkts=wfDvmrpTunnelOutPrunePkts, wfDvmrpCircuitRouteThreshold=wfDvmrpCircuitRouteThreshold, wfDvmrpTunnelFwdCacheEntries=wfDvmrpTunnelFwdCacheEntries)
