#
# PySNMP MIB module ZYXEL-MLD-SNOOPING-PROXY-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/ZYXEL-MLD-SNOOPING-PROXY-MIB
# Produced by pysmi-0.3.4 at Wed May  1 15:50:54 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, Integer, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "OctetString", "Integer", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ValueSizeConstraint, ValueRangeConstraint, SingleValueConstraint, ConstraintsUnion, ConstraintsIntersection = mibBuilder.importSymbols("ASN1-REFINEMENT", "ValueSizeConstraint", "ValueRangeConstraint", "SingleValueConstraint", "ConstraintsUnion", "ConstraintsIntersection")
dot1dBasePort, = mibBuilder.importSymbols("BRIDGE-MIB", "dot1dBasePort")
InetAddressType, InetAddress = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddressType", "InetAddress")
EnabledStatus, = mibBuilder.importSymbols("P-BRIDGE-MIB", "EnabledStatus")
PortList, = mibBuilder.importSymbols("Q-BRIDGE-MIB", "PortList")
NotificationGroup, ModuleCompliance = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance")
Gauge32, IpAddress, ObjectIdentity, iso, TimeTicks, Counter64, Bits, MibIdentifier, NotificationType, Counter32, MibScalar, MibTable, MibTableRow, MibTableColumn, ModuleIdentity, Integer32, Unsigned32 = mibBuilder.importSymbols("SNMPv2-SMI", "Gauge32", "IpAddress", "ObjectIdentity", "iso", "TimeTicks", "Counter64", "Bits", "MibIdentifier", "NotificationType", "Counter32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "ModuleIdentity", "Integer32", "Unsigned32")
TextualConvention, RowStatus, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "RowStatus", "DisplayString")
esMgmt, = mibBuilder.importSymbols("ZYXEL-ES-SMI", "esMgmt")
zyxelMldSnoopingProxy = ModuleIdentity((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51))
if mibBuilder.loadTexts: zyxelMldSnoopingProxy.setLastUpdated('201207010000Z')
if mibBuilder.loadTexts: zyxelMldSnoopingProxy.setOrganization('Enterprise Solution ZyXEL')
if mibBuilder.loadTexts: zyxelMldSnoopingProxy.setContactInfo('')
if mibBuilder.loadTexts: zyxelMldSnoopingProxy.setDescription('The subtree for Multicast Listener Discovery (MLD) snooping proxy')
zyxelMldSnoopingProxyFilteringSetup = MibIdentifier((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1))
zyxelMldSnoopingProxyStatistics = MibIdentifier((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2))
zyxelMldSnoopingProxySetup = MibIdentifier((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3))
zyxelMldSnoopingProxyMembershipStatus = MibIdentifier((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4))
zyMldSnoopingProxyFilteringMaxNumberOfProfiles = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringMaxNumberOfProfiles.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringMaxNumberOfProfiles.setDescription('The maximum number of MLD Snooping filter profile entries that can be created.')
zyxelMldSnoopingProxyFilteringProfileTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringProfileTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringProfileTable.setDescription('The table contains MLD snooping proxy filtering profile configuration.')
zyxelMldSnoopingProxyFilteringProfileEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyFilteringProfileName"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyFilteringProfileStartIpAddressType"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyFilteringProfileStartIpAddress"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyFilteringProfileEndIpAddressType"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyFilteringProfileEndIpAddress"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringProfileEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringProfileEntry.setDescription('An entry contains MLD snooping proxy filtering profile configuration.')
zyMldSnoopingProxyFilteringProfileName = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1, 1), OctetString())
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileName.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileName.setDescription('A descriptive name for the profile for identification purposes.')
zyMldSnoopingProxyFilteringProfileStartIpAddressType = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1, 2), InetAddressType())
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileStartIpAddressType.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileStartIpAddressType.setDescription('The start address type of filtering range for filtering profile.')
zyMldSnoopingProxyFilteringProfileStartIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1, 3), InetAddress())
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileStartIpAddress.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileStartIpAddress.setDescription('The start address of filtering range for filtering profile.')
zyMldSnoopingProxyFilteringProfileEndIpAddressType = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1, 4), InetAddressType())
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileEndIpAddressType.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileEndIpAddressType.setDescription('The end address type of filtering range for filtering profile.')
zyMldSnoopingProxyFilteringProfileEndIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1, 5), InetAddress())
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileEndIpAddress.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileEndIpAddress.setDescription('The end address of filtering range for filtering profile.')
zyMldSnoopingProxyFilteringProfileRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 2, 1, 6), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileRowStatus.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringProfileRowStatus.setDescription('This object allow entry to be create and deleted a MLD Snooping-proxy filter profile entry.')
zyxelMldSnoopingProxyFilteringPortTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 3), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringPortTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringPortTable.setDescription('The table contains MLD snooping proxy filtering port configuration.')
zyxelMldSnoopingProxyFilteringPortEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 3, 1), ).setIndexNames((0, "BRIDGE-MIB", "dot1dBasePort"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringPortEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyFilteringPortEntry.setDescription('An entry contains MLD snooping proxy filtering port configuration.')
zyMldSnoopingProxyFilteringPortProfile = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 3, 1, 1), OctetString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringPortProfile.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringPortProfile.setDescription('Type a name of the MLD Snooping-proxy filtering profile to use for this port. ')
zyMldSnoopingProxyFilteringPortGroupLimitState = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 3, 1, 2), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringPortGroupLimitState.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringPortGroupLimitState.setDescription('Enable/disable this entry to limit the number of multicast groups on this port is allowed to join. ')
zyMldSnoopingProxyFilteringPortMaxNumberOfGroups = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 1, 3, 1, 3), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringPortMaxNumberOfGroups.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringPortMaxNumberOfGroups.setDescription('The maximum number of group number on the port, when group limit is enable.')
zyMldSnoopingProxySysStatisticsV1QueryRx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1QueryRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1QueryRx.setDescription('MLDv1 Query Rx statistic for system.')
zyMldSnoopingProxySysStatisticsV1QueryTx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1QueryTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1QueryTx.setDescription('MLDv1 Query Tx statistic for system.')
zyMldSnoopingProxySysStatisticsV1QueryDrop = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1QueryDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1QueryDrop.setDescription('MLDv1 Query Drop statistic for system.')
zyMldSnoopingProxySysStatisticsV1ReportRx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1ReportRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1ReportRx.setDescription('MLDv1 Report Rx statistic for system.')
zyMldSnoopingProxySysStatisticsV1ReportTx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1ReportTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1ReportTx.setDescription('MLDv1 Report Tx statistic for system.')
zyMldSnoopingProxySysStatisticsV1ReportDrop = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1ReportDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1ReportDrop.setDescription('MLDv1 Report Drop statistic for system.')
zyMldSnoopingProxySysStatisticsV1DoneRx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1DoneRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1DoneRx.setDescription('MLDv1 Done Rx statistic for system.')
zyMldSnoopingProxySysStatisticsV1DoneTx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1DoneTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1DoneTx.setDescription('MLDv1 Done Tx statistic for system.')
zyMldSnoopingProxySysStatisticsV1DoneDrop = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1DoneDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV1DoneDrop.setDescription('MLDv1 Done Drop statistic for system.')
zyMldSnoopingProxySysStatisticsV2QueryRx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2QueryRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2QueryRx.setDescription('MLDv2 Query Rx statistic for system.')
zyMldSnoopingProxySysStatisticsV2QueryTx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2QueryTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2QueryTx.setDescription('MLDv2 Query Tx statistic for system.')
zyMldSnoopingProxySysStatisticsV2QueryDrop = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2QueryDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2QueryDrop.setDescription('MLDv2 Query Drop statistic for system.')
zyMldSnoopingProxySysStatisticsV2ReportRx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2ReportRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2ReportRx.setDescription('MLDv2Report Rx statistic for system.')
zyMldSnoopingProxySysStatisticsV2ReportTx = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 14), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2ReportTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2ReportTx.setDescription('MLDv2 Report Tx statistic for system.')
zyMldSnoopingProxySysStatisticsV2ReportDrop = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2ReportDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxySysStatisticsV2ReportDrop.setDescription('MLDv2 Report Drop statistic for system.')
zyxelMldSnoopingProxyStatisticsVlanTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsVlanTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsVlanTable.setDescription('The table contains MLD snooping proxy statistics VLAN information.')
zyxelMldSnoopingProxyStatisticsVlanEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyVlanVid"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsVlanEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsVlanEntry.setDescription('An entry contains MLD snooping proxy statistics VLAN information.')
zyMldSnoopingProxyStatisticsVlanV1QueryRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1QueryRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1QueryRx.setDescription('MLDv1 Query Rx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1QueryTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1QueryTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1QueryTx.setDescription('MLDv1 Query Tx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1QueryDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1QueryDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1QueryDrop.setDescription('MLDv1 Query Drop statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1ReportRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1ReportRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1ReportRx.setDescription('MLDv1 Report Rx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1ReportTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1ReportTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1ReportTx.setDescription('MLDv1 Report Tx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1ReportDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1ReportDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1ReportDrop.setDescription('MLDv1 Report Drop statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1DoneRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1DoneRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1DoneRx.setDescription('MLDv1 Done Rx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1DoneTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1DoneTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1DoneTx.setDescription('MLDv1 Done Tx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV1DoneDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1DoneDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV1DoneDrop.setDescription('MLDv1 Done Drop statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV2QueryRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2QueryRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2QueryRx.setDescription('MLDv2 Query Rx statistic for VALN')
zyMldSnoopingProxyStatisticsVlanV2QueryTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2QueryTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2QueryTx.setDescription('MLDv2 Query Tx statistic for VALN')
zyMldSnoopingProxyStatisticsVlanV2QueryDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2QueryDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2QueryDrop.setDescription('MLDv2 Query Drop statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV2ReportRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2ReportRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2ReportRx.setDescription('MLDv2Report Rx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV2ReportTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 14), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2ReportTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2ReportTx.setDescription('MLDv2 Report Tx statistic for VLAN')
zyMldSnoopingProxyStatisticsVlanV2ReportDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 16, 1, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2ReportDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsVlanV2ReportDrop.setDescription('MLDv2 Report Drop statistic for VLAN')
zyxelMldSnoopingProxyStatisticsPortTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsPortTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsPortTable.setDescription('The table contains MLD snooping proxy statistics port information.')
zyxelMldSnoopingProxyStatisticsPortEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1), ).setIndexNames((0, "BRIDGE-MIB", "dot1dBasePort"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsPortEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyStatisticsPortEntry.setDescription('An entry contains MLD snooping proxy statistics port information.')
zyMldSnoopingProxyStatisticsPortV1QueryRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1QueryRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1QueryRx.setDescription('MLDv1 Query Rx statistic for port')
zyMldSnoopingProxyStatisticsPortV1QueryTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1QueryTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1QueryTx.setDescription('MLDv1 Query Tx statistic for port')
zyMldSnoopingProxyStatisticsPortV1QueryDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1QueryDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1QueryDrop.setDescription('MLDv1 Query Drop statistic for port')
zyMldSnoopingProxyStatisticsPortV1ReportRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1ReportRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1ReportRx.setDescription('MLDv1 Report Rx statistic for port')
zyMldSnoopingProxyStatisticsPortV1ReportTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1ReportTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1ReportTx.setDescription('MLDv1 Report Tx statistic for port')
zyMldSnoopingProxyStatisticsPortV1ReportDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1ReportDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1ReportDrop.setDescription('MLDv1 Report Drop statistic for port')
zyMldSnoopingProxyStatisticsPortV1DoneRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1DoneRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1DoneRx.setDescription('MLDv1 Done Rx statistic for port')
zyMldSnoopingProxyStatisticsPortV1DoneTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1DoneTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1DoneTx.setDescription('MLDv1 Done Tx statistic for port')
zyMldSnoopingProxyStatisticsPortV1DoneDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1DoneDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV1DoneDrop.setDescription('MLDv1 Done Drop statistic for port')
zyMldSnoopingProxyStatisticsPortV2QueryRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 10), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2QueryRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2QueryRx.setDescription('MLDv2 Query Rx statistic for port')
zyMldSnoopingProxyStatisticsPortV2QueryTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2QueryTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2QueryTx.setDescription('MLDv2 Query Tx statistic for port')
zyMldSnoopingProxyStatisticsPortV2QueryDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2QueryDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2QueryDrop.setDescription('MLDv2 Query Drop statistic for port')
zyMldSnoopingProxyStatisticsPortV2ReportRx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 13), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2ReportRx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2ReportRx.setDescription('MLDv2Report Rx statistic for port')
zyMldSnoopingProxyStatisticsPortV2ReportTx = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 14), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2ReportTx.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2ReportTx.setDescription('MLDv2 Report Tx statistic for port')
zyMldSnoopingProxyStatisticsPortV2ReportDrop = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 17, 1, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2ReportDrop.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsPortV2ReportDrop.setDescription('MLDv2 Report Drop statistic for port')
zyMldSnoopingProxyStatisticsClear = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 18), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClear.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClear.setDescription('Clear all MLD snooping proxy statistics of the switch.')
zyMldSnoopingProxyStatisticsClearSystem = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 19), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClearSystem.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClearSystem.setDescription('Clear the MLD snooping proxy statistics of the system.')
zyMldSnoopingProxyStatisticsClearPort = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 20), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClearPort.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClearPort.setDescription('Clear the MLD snooping proxy statistics of the port(s).')
zyMldSnoopingProxyStatisticsClearVlan = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 2, 21), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClearVlan.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyStatisticsClearVlan.setDescription('Clear the MLD snooping proxy statistics of the VLAN(s).')
zyMldSnoopingProxyState = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 1), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyState.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyState.setDescription('Enable/disable MLD Snooping-proxy to forward multicast traffic only to ports that are members of that multicast group. ')
zyMldSnoopingProxyFilteringState = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 2), EnabledStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringState.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyFilteringState.setDescription('Enable/disable MLD Snooping-proxy filtering to control which MLD Snooping-proxy groups a subscriber on a port can join. Note: If you enable MLD Snooping-proxy filtering, you must create and assign MLD Snooping-proxy filtering profiles for the ports that you want to allow to join multicast groups. ')
zyMldSnoopingProxy8021pPriority = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 3), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxy8021pPriority.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxy8021pPriority.setDescription('Enter a priority level (0-7) to which the switch changes the priority in outgoing MLD control packets (The default value is 0).')
zyMldSnoopingProxyMaxNumberOfVlans = MibScalar((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyMaxNumberOfVlans.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyMaxNumberOfVlans.setDescription('The maximum number of MLD Snoopign-proxy VLAN entries that can be created.')
zyxelMldSnoopingProxyVlanTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 5), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyVlanTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyVlanTable.setDescription('The table contains MLD snooping proxy VLAN configuration.')
zyxelMldSnoopingProxyVlanEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 5, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyVlanVid"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyVlanEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyVlanEntry.setDescription('An entry contains MLD snooping proxy VLAN configuration.')
zyMldSnoopingProxyVlanVid = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 5, 1, 1), Integer32())
if mibBuilder.loadTexts: zyMldSnoopingProxyVlanVid.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyVlanVid.setDescription('The VLAN ID for which MLD Snoopign-proxy is enabled.')
zyMldSnoopingProxyVlanRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 5, 1, 2), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: zyMldSnoopingProxyVlanRowStatus.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyVlanRowStatus.setDescription('This object allow entry to be create and deleted a MLD Snoopign-proxy VLAN entry.')
zyxelMldSnoopingProxyUpstreamVlanTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyUpstreamVlanTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyUpstreamVlanTable.setDescription('The table contains MLD snooping proxy upstream VLAN configuration.')
zyxelMldSnoopingProxyUpstreamVlanEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyVlanVid"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyUpstreamVlanEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyUpstreamVlanEntry.setDescription('An entry contains MLD snooping proxy upstream VLAN configuration.')
zyMldSnoopingProxyUpstreamVlanPorts = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6, 1, 1), PortList()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanPorts.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanPorts.setDescription('Port list for the Upstream part on a particular VLAN.')
zyMldSnoopingProxyUpstreamVlanQueryInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1000, 31744000))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanQueryInterval.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanQueryInterval.setDescription('The query interval for the Uptream part on a particular VLAN.')
zyMldSnoopingProxyUpstreamVlanMaxResponseTime = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1000, 25000))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanMaxResponseTime.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanMaxResponseTime.setDescription('The maximum query response interval for the Uptream part on a particular VLAN.')
zyMldSnoopingProxyUpstreamVlanRobustness = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 25))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanRobustness.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanRobustness.setDescription('The Robustness Variable for the Upwnstream part on a particular VLAN. The Robustness Variable allows tuning for the expected packet loss on a subnet. If a subnet is expected to be lossy, the Robustness Variable may be increased.')
zyMldSnoopingProxyUpstreamVlanLastMemberQueryInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 6, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8387584))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanLastMemberQueryInterval.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyUpstreamVlanLastMemberQueryInterval.setDescription('The last member query interval for the Upstream part on a particular VLAN. The Last Member Query Interval is the Max Query Response Interval inserted into group-specific queries sent in response to leave group messages, and is also the amount of time between group-specific query messages. This value may be tuned to modify the leave latency of the network. A reduced value results in reduced time to detect the loss of the last member of a group.')
zyxelMldSnoopingProxyDownstreamVlanTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 7), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanTable.setDescription('The table contains MLD snooping proxy downstream VLAN configuration.')
zyxelMldSnoopingProxyDownstreamVlanEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 7, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyVlanVid"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanEntry.setDescription('An entry contains MLD snooping proxy downstream VLAN configuration.')
zyMldSnoopingProxyDownstreamVlanPorts = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 7, 1, 1), PortList()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPorts.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPorts.setDescription('Port list for the Downstream part on a particular VLAN.')
zyMldSnoopingProxyDownstreamVlanQueryInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 7, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1000, 31744000))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanQueryInterval.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanQueryInterval.setDescription('Sets the amount of time (in miliseconds) between general query messages sent by the downstream port.')
zyMldSnoopingProxyDownstreamVlanMaxResponseTime = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 7, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1000, 25000))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanMaxResponseTime.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanMaxResponseTime.setDescription('Sets the maximum time (in miliseconds) that the Switch waits for a response to a general query message sent by the downstream port.')
zyxelMldSnoopingProxyDownstreamVlanPortTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 8), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanPortTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanPortTable.setDescription('The table contains MLD snooping proxy downstream VLAN port configuration.')
zyxelMldSnoopingProxyDownstreamVlanPortEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 8, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyVlanVid"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyDownstreamVlanPortIndex"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanPortEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyDownstreamVlanPortEntry.setDescription('An entry contains MLD snooping proxy downstream VLAN port configuration.')
zyMldSnoopingProxyDownstreamVlanPortIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 8, 1, 1), Integer32())
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortIndex.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortIndex.setDescription('Index number of downstream port is enabled.')
zyMldSnoopingProxyDownstreamVlanPortLeaveMode = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 8, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1, 2))).clone(namedValues=NamedValues(("immediate", 0), ("normal", 1), ("fast", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortLeaveMode.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortLeaveMode.setDescription('Leave mode for the port. When a done report is received, downstream sends MASQ to confirm a multicast address has no listener. Once the MASQ is timeout, the multicast group is deleted. This entry handle the mode of deleting a multicast address. Immediate : when a done report is received, a multicast address is immediately deleted. Fast: a timer for wating a response of a MASQ, and a multicast address is deleted when the timer is timout. Normal: a timer for wating a response of a MASQ, and a multicast address is deleted when the timer is timout.')
zyMldSnoopingProxyDownstreamVlanPortLeaveTimeout = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 8, 1, 3), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortLeaveTimeout.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortLeaveTimeout.setDescription('Set the MLD snooping normal leave timeout (in miliseconds) the Switch uses to update the forwarding table for the specified downstream port(s).This defines how many seconds the Switch waits for an MLD report before removing an MLD snooping membership entry (learned on a downstream port) when an MLD Done message is received on this port from a host.')
zyMldSnoopingProxyDownstreamVlanPortFastLeaveTimeout = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 3, 8, 1, 4), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortFastLeaveTimeout.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyDownstreamVlanPortFastLeaveTimeout.setDescription('Sets the fast leave timeout (in miliseconds) for the specified downstream port(s). This defines how many seconds the Switch waits for an MLD report before removing an MLD snooping membership entry (learned on a downstream port) when an MLD Done message is received on this port from a host.')
zyxelMldSnoopingProxyMembershipTable = MibTable((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1), )
if mibBuilder.loadTexts: zyxelMldSnoopingProxyMembershipTable.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyMembershipTable.setDescription('The table contains MLD snooping proxy Membership information.')
zyxelMldSnoopingProxyMembershipEntry = MibTableRow((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1, 1), ).setIndexNames((0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyMembershipVid"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyMembershipPort"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyMembershipGroupIpAddressType"), (0, "ZYXEL-MLD-SNOOPING-PROXY-MIB", "zyMldSnoopingProxyMembershipGroupIpAddress"))
if mibBuilder.loadTexts: zyxelMldSnoopingProxyMembershipEntry.setStatus('current')
if mibBuilder.loadTexts: zyxelMldSnoopingProxyMembershipEntry.setDescription('An entry contains MLD snooping proxy Membership information.')
zyMldSnoopingProxyMembershipVid = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 4094)))
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipVid.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipVid.setDescription('The VLAN ID for which this entry contains information for an IPv6 multicast group address.')
zyMldSnoopingProxyMembershipPort = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1, 1, 2), Integer32())
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipPort.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipPort.setDescription('The port for which this entry contains information for an IPv6 multicast group address.')
zyMldSnoopingProxyMembershipGroupIpAddressType = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1, 1, 3), InetAddressType())
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipGroupIpAddressType.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipGroupIpAddressType.setDescription('The type of multicast group address for which this entry contains information.')
zyMldSnoopingProxyMembershipGroupIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1, 1, 4), InetAddress())
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipGroupIpAddress.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipGroupIpAddress.setDescription('The multicast group address for which this entry contains information.')
zyMldSnoopingProxyMembershipGroupTimeout = MibTableColumn((1, 3, 6, 1, 4, 1, 890, 1, 15, 3, 51, 4, 1, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipGroupTimeout.setStatus('current')
if mibBuilder.loadTexts: zyMldSnoopingProxyMembershipGroupTimeout.setDescription('This value represents the time remaining before the Group Membership Interval state expires. The value must always be greater than or equal to 1.')
mibBuilder.exportSymbols("ZYXEL-MLD-SNOOPING-PROXY-MIB", zyMldSnoopingProxy8021pPriority=zyMldSnoopingProxy8021pPriority, zyMldSnoopingProxyStatisticsVlanV1QueryRx=zyMldSnoopingProxyStatisticsVlanV1QueryRx, zyxelMldSnoopingProxyUpstreamVlanEntry=zyxelMldSnoopingProxyUpstreamVlanEntry, zyMldSnoopingProxyStatisticsVlanV1DoneRx=zyMldSnoopingProxyStatisticsVlanV1DoneRx, zyMldSnoopingProxyStatisticsVlanV1DoneTx=zyMldSnoopingProxyStatisticsVlanV1DoneTx, zyMldSnoopingProxySysStatisticsV1DoneRx=zyMldSnoopingProxySysStatisticsV1DoneRx, zyMldSnoopingProxyStatisticsPortV2ReportTx=zyMldSnoopingProxyStatisticsPortV2ReportTx, zyMldSnoopingProxySysStatisticsV1QueryDrop=zyMldSnoopingProxySysStatisticsV1QueryDrop, zyMldSnoopingProxyStatisticsClearSystem=zyMldSnoopingProxyStatisticsClearSystem, zyxelMldSnoopingProxyFilteringPortTable=zyxelMldSnoopingProxyFilteringPortTable, zyMldSnoopingProxyDownstreamVlanQueryInterval=zyMldSnoopingProxyDownstreamVlanQueryInterval, zyMldSnoopingProxyStatisticsClearPort=zyMldSnoopingProxyStatisticsClearPort, zyxelMldSnoopingProxyFilteringSetup=zyxelMldSnoopingProxyFilteringSetup, zyMldSnoopingProxyMembershipVid=zyMldSnoopingProxyMembershipVid, zyxelMldSnoopingProxyFilteringPortEntry=zyxelMldSnoopingProxyFilteringPortEntry, zyMldSnoopingProxyStatisticsVlanV2ReportDrop=zyMldSnoopingProxyStatisticsVlanV2ReportDrop, zyxelMldSnoopingProxyStatisticsPortTable=zyxelMldSnoopingProxyStatisticsPortTable, zyMldSnoopingProxyFilteringPortMaxNumberOfGroups=zyMldSnoopingProxyFilteringPortMaxNumberOfGroups, zyMldSnoopingProxyDownstreamVlanPortLeaveMode=zyMldSnoopingProxyDownstreamVlanPortLeaveMode, zyMldSnoopingProxyDownstreamVlanPortLeaveTimeout=zyMldSnoopingProxyDownstreamVlanPortLeaveTimeout, zyMldSnoopingProxySysStatisticsV1QueryRx=zyMldSnoopingProxySysStatisticsV1QueryRx, zyMldSnoopingProxyFilteringProfileName=zyMldSnoopingProxyFilteringProfileName, zyMldSnoopingProxySysStatisticsV2ReportRx=zyMldSnoopingProxySysStatisticsV2ReportRx, zyMldSnoopingProxyUpstreamVlanQueryInterval=zyMldSnoopingProxyUpstreamVlanQueryInterval, zyMldSnoopingProxySysStatisticsV1QueryTx=zyMldSnoopingProxySysStatisticsV1QueryTx, zyMldSnoopingProxySysStatisticsV2QueryRx=zyMldSnoopingProxySysStatisticsV2QueryRx, zyMldSnoopingProxyStatisticsVlanV2QueryRx=zyMldSnoopingProxyStatisticsVlanV2QueryRx, zyMldSnoopingProxyStatisticsVlanV2ReportRx=zyMldSnoopingProxyStatisticsVlanV2ReportRx, zyMldSnoopingProxyStatisticsVlanV1QueryTx=zyMldSnoopingProxyStatisticsVlanV1QueryTx, zyMldSnoopingProxyStatisticsVlanV1ReportRx=zyMldSnoopingProxyStatisticsVlanV1ReportRx, zyMldSnoopingProxyFilteringProfileEndIpAddressType=zyMldSnoopingProxyFilteringProfileEndIpAddressType, zyMldSnoopingProxyMembershipGroupIpAddressType=zyMldSnoopingProxyMembershipGroupIpAddressType, zyMldSnoopingProxyStatisticsPortV2QueryDrop=zyMldSnoopingProxyStatisticsPortV2QueryDrop, zyxelMldSnoopingProxyDownstreamVlanEntry=zyxelMldSnoopingProxyDownstreamVlanEntry, zyMldSnoopingProxySysStatisticsV2ReportDrop=zyMldSnoopingProxySysStatisticsV2ReportDrop, zyMldSnoopingProxyStatisticsVlanV1ReportDrop=zyMldSnoopingProxyStatisticsVlanV1ReportDrop, zyxelMldSnoopingProxyFilteringProfileTable=zyxelMldSnoopingProxyFilteringProfileTable, zyMldSnoopingProxySysStatisticsV1ReportDrop=zyMldSnoopingProxySysStatisticsV1ReportDrop, zyMldSnoopingProxyStatisticsVlanV1ReportTx=zyMldSnoopingProxyStatisticsVlanV1ReportTx, zyMldSnoopingProxyUpstreamVlanRobustness=zyMldSnoopingProxyUpstreamVlanRobustness, zyMldSnoopingProxyDownstreamVlanPorts=zyMldSnoopingProxyDownstreamVlanPorts, zyMldSnoopingProxyStatisticsVlanV1QueryDrop=zyMldSnoopingProxyStatisticsVlanV1QueryDrop, zyMldSnoopingProxySysStatisticsV2QueryTx=zyMldSnoopingProxySysStatisticsV2QueryTx, zyMldSnoopingProxyFilteringProfileEndIpAddress=zyMldSnoopingProxyFilteringProfileEndIpAddress, zyxelMldSnoopingProxyMembershipStatus=zyxelMldSnoopingProxyMembershipStatus, zyMldSnoopingProxyStatisticsPortV1DoneDrop=zyMldSnoopingProxyStatisticsPortV1DoneDrop, zyxelMldSnoopingProxyDownstreamVlanPortEntry=zyxelMldSnoopingProxyDownstreamVlanPortEntry, zyMldSnoopingProxySysStatisticsV1DoneTx=zyMldSnoopingProxySysStatisticsV1DoneTx, zyxelMldSnoopingProxyFilteringProfileEntry=zyxelMldSnoopingProxyFilteringProfileEntry, zyMldSnoopingProxyStatisticsPortV2QueryRx=zyMldSnoopingProxyStatisticsPortV2QueryRx, zyMldSnoopingProxyFilteringPortProfile=zyMldSnoopingProxyFilteringPortProfile, zyMldSnoopingProxyStatisticsPortV2ReportRx=zyMldSnoopingProxyStatisticsPortV2ReportRx, zyMldSnoopingProxySysStatisticsV1ReportRx=zyMldSnoopingProxySysStatisticsV1ReportRx, zyxelMldSnoopingProxyVlanTable=zyxelMldSnoopingProxyVlanTable, zyMldSnoopingProxyStatisticsVlanV1DoneDrop=zyMldSnoopingProxyStatisticsVlanV1DoneDrop, zyMldSnoopingProxyState=zyMldSnoopingProxyState, zyMldSnoopingProxyStatisticsPortV1ReportDrop=zyMldSnoopingProxyStatisticsPortV1ReportDrop, zyMldSnoopingProxyFilteringProfileStartIpAddressType=zyMldSnoopingProxyFilteringProfileStartIpAddressType, zyMldSnoopingProxyStatisticsPortV2QueryTx=zyMldSnoopingProxyStatisticsPortV2QueryTx, zyMldSnoopingProxyVlanVid=zyMldSnoopingProxyVlanVid, zyxelMldSnoopingProxy=zyxelMldSnoopingProxy, zyMldSnoopingProxyStatisticsPortV1DoneRx=zyMldSnoopingProxyStatisticsPortV1DoneRx, zyMldSnoopingProxyFilteringProfileStartIpAddress=zyMldSnoopingProxyFilteringProfileStartIpAddress, zyMldSnoopingProxyStatisticsPortV1QueryTx=zyMldSnoopingProxyStatisticsPortV1QueryTx, zyMldSnoopingProxyStatisticsVlanV2QueryTx=zyMldSnoopingProxyStatisticsVlanV2QueryTx, zyMldSnoopingProxyUpstreamVlanLastMemberQueryInterval=zyMldSnoopingProxyUpstreamVlanLastMemberQueryInterval, zyMldSnoopingProxySysStatisticsV1DoneDrop=zyMldSnoopingProxySysStatisticsV1DoneDrop, zyMldSnoopingProxyStatisticsVlanV2QueryDrop=zyMldSnoopingProxyStatisticsVlanV2QueryDrop, zyMldSnoopingProxyMembershipGroupIpAddress=zyMldSnoopingProxyMembershipGroupIpAddress, zyxelMldSnoopingProxySetup=zyxelMldSnoopingProxySetup, zyMldSnoopingProxyMembershipGroupTimeout=zyMldSnoopingProxyMembershipGroupTimeout, zyMldSnoopingProxyStatisticsPortV1ReportRx=zyMldSnoopingProxyStatisticsPortV1ReportRx, zyMldSnoopingProxySysStatisticsV1ReportTx=zyMldSnoopingProxySysStatisticsV1ReportTx, zyMldSnoopingProxyStatisticsVlanV2ReportTx=zyMldSnoopingProxyStatisticsVlanV2ReportTx, PYSNMP_MODULE_ID=zyxelMldSnoopingProxy, zyMldSnoopingProxyMaxNumberOfVlans=zyMldSnoopingProxyMaxNumberOfVlans, zyMldSnoopingProxyUpstreamVlanPorts=zyMldSnoopingProxyUpstreamVlanPorts, zyMldSnoopingProxySysStatisticsV2QueryDrop=zyMldSnoopingProxySysStatisticsV2QueryDrop, zyxelMldSnoopingProxyStatisticsVlanEntry=zyxelMldSnoopingProxyStatisticsVlanEntry, zyMldSnoopingProxySysStatisticsV2ReportTx=zyMldSnoopingProxySysStatisticsV2ReportTx, zyMldSnoopingProxyStatisticsPortV1ReportTx=zyMldSnoopingProxyStatisticsPortV1ReportTx, zyxelMldSnoopingProxyStatisticsPortEntry=zyxelMldSnoopingProxyStatisticsPortEntry, zyMldSnoopingProxyFilteringState=zyMldSnoopingProxyFilteringState, zyMldSnoopingProxyMembershipPort=zyMldSnoopingProxyMembershipPort, zyxelMldSnoopingProxyDownstreamVlanTable=zyxelMldSnoopingProxyDownstreamVlanTable, zyMldSnoopingProxyUpstreamVlanMaxResponseTime=zyMldSnoopingProxyUpstreamVlanMaxResponseTime, zyxelMldSnoopingProxyDownstreamVlanPortTable=zyxelMldSnoopingProxyDownstreamVlanPortTable, zyMldSnoopingProxyDownstreamVlanPortFastLeaveTimeout=zyMldSnoopingProxyDownstreamVlanPortFastLeaveTimeout, zyxelMldSnoopingProxyStatistics=zyxelMldSnoopingProxyStatistics, zyMldSnoopingProxyFilteringProfileRowStatus=zyMldSnoopingProxyFilteringProfileRowStatus, zyMldSnoopingProxyStatisticsPortV1QueryRx=zyMldSnoopingProxyStatisticsPortV1QueryRx, zyxelMldSnoopingProxyStatisticsVlanTable=zyxelMldSnoopingProxyStatisticsVlanTable, zyMldSnoopingProxyStatisticsPortV1DoneTx=zyMldSnoopingProxyStatisticsPortV1DoneTx, zyxelMldSnoopingProxyUpstreamVlanTable=zyxelMldSnoopingProxyUpstreamVlanTable, zyMldSnoopingProxyStatisticsClear=zyMldSnoopingProxyStatisticsClear, zyMldSnoopingProxyDownstreamVlanPortIndex=zyMldSnoopingProxyDownstreamVlanPortIndex, zyxelMldSnoopingProxyMembershipEntry=zyxelMldSnoopingProxyMembershipEntry, zyMldSnoopingProxyStatisticsPortV1QueryDrop=zyMldSnoopingProxyStatisticsPortV1QueryDrop, zyMldSnoopingProxyStatisticsClearVlan=zyMldSnoopingProxyStatisticsClearVlan, zyMldSnoopingProxyFilteringPortGroupLimitState=zyMldSnoopingProxyFilteringPortGroupLimitState, zyMldSnoopingProxyVlanRowStatus=zyMldSnoopingProxyVlanRowStatus, zyMldSnoopingProxyDownstreamVlanMaxResponseTime=zyMldSnoopingProxyDownstreamVlanMaxResponseTime, zyxelMldSnoopingProxyVlanEntry=zyxelMldSnoopingProxyVlanEntry, zyMldSnoopingProxyFilteringMaxNumberOfProfiles=zyMldSnoopingProxyFilteringMaxNumberOfProfiles, zyMldSnoopingProxyStatisticsPortV2ReportDrop=zyMldSnoopingProxyStatisticsPortV2ReportDrop, zyxelMldSnoopingProxyMembershipTable=zyxelMldSnoopingProxyMembershipTable)
