#
# PySNMP MIB module CISCO-MDI-METRICS-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/CISCO-MDI-METRICS-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 17:49:57 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, Integer, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "OctetString", "Integer", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
SingleValueConstraint, ConstraintsIntersection, ValueRangeConstraint, ConstraintsUnion, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "SingleValueConstraint", "ConstraintsIntersection", "ValueRangeConstraint", "ConstraintsUnion", "ValueSizeConstraint")
cfmFlowId, cfmFlowMonitorId, cfmFlowMetricsIntNumber = mibBuilder.importSymbols("CISCO-FLOW-MONITOR-MIB", "cfmFlowId", "cfmFlowMonitorId", "cfmFlowMetricsIntNumber")
FlowBitRateUnits, FlowMetricValue, FlowCfgRateType, FlowMetricPrecision, FlowMetricScale = mibBuilder.importSymbols("CISCO-FLOW-MONITOR-TC-MIB", "FlowBitRateUnits", "FlowMetricValue", "FlowCfgRateType", "FlowMetricPrecision", "FlowMetricScale")
ReportIntervalCount, = mibBuilder.importSymbols("CISCO-REPORT-INTERVAL-TC-MIB", "ReportIntervalCount")
ciscoMgmt, = mibBuilder.importSymbols("CISCO-SMI", "ciscoMgmt")
TimeIntervalMin, = mibBuilder.importSymbols("CISCO-TC", "TimeIntervalMin")
NotificationGroup, ModuleCompliance, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance", "ObjectGroup")
ModuleIdentity, IpAddress, ObjectIdentity, Integer32, NotificationType, Gauge32, Bits, Counter32, MibScalar, MibTable, MibTableRow, MibTableColumn, MibIdentifier, TimeTicks, Counter64, iso, Unsigned32 = mibBuilder.importSymbols("SNMPv2-SMI", "ModuleIdentity", "IpAddress", "ObjectIdentity", "Integer32", "NotificationType", "Gauge32", "Bits", "Counter32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "MibIdentifier", "TimeTicks", "Counter64", "iso", "Unsigned32")
TextualConvention, TimeStamp, DisplayString = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "TimeStamp", "DisplayString")
ciscoMdiMetricsMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699))
ciscoMdiMetricsMIB.setRevisions(('2009-11-02 00:00', '2009-06-05 00:00',))
if mibBuilder.loadTexts: ciscoMdiMetricsMIB.setLastUpdated('200911020000Z')
if mibBuilder.loadTexts: ciscoMdiMetricsMIB.setOrganization('Cisco Systems, Inc.')
ciscoMdiMetricsMIBNotifs = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 0))
ciscoMdiMetricsMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 1))
ciscoMdiMetricsMIBConform = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 2))
ciscoMdiMetricsMIBIds = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 3))
cfmMdiMetrics = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1))
cfmMdiMetricsTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1), )
if mibBuilder.loadTexts: cfmMdiMetricsTable.setStatus('current')
cfmMdiMetricsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1), ).setIndexNames((0, "CISCO-FLOW-MONITOR-MIB", "cfmFlowMonitorId"), (0, "CISCO-FLOW-MONITOR-MIB", "cfmFlowId"))
if mibBuilder.loadTexts: cfmMdiMetricsEntry.setStatus('current')
cfmMdiMetricsCfgRateType = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 1), FlowCfgRateType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsCfgRateType.setStatus('current')
cfmMdiMetricsCfgBitRate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 2), FlowBitRateUnits()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsCfgBitRate.setStatus('current')
cfmMdiMetricsCfgRate = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 3), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsCfgRate.setStatus('current')
cfmMdiMetricsCfgMediaPktSize = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 4), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(64, 65535))).setUnits('octets').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsCfgMediaPktSize.setStatus('current')
cfmMdiMetricsValid = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 5), Bits().clone(namedValues=NamedValues(("lostPkts", 0), ("mediaLossRate", 1), ("mediaDiscontinuityCount", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsValid.setStatus('current')
cfmMdiMetricsLostPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 6), Counter64()).setUnits('packets').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsLostPkts.setStatus('current')
cfmMdiMetricsMlrScale = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 7), FlowMetricScale()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsMlrScale.setStatus('current')
cfmMdiMetricsMlrPrecision = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 8), FlowMetricPrecision()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsMlrPrecision.setStatus('current')
cfmMdiMetricsMlr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 9), FlowMetricValue()).setUnits('packets per second').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsMlr.setStatus('current')
cfmMdiMetricsMdc = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 1, 1, 10), Counter64()).setUnits('Events').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsMdc.setStatus('current')
cfmMdiMetricsTableChanged = MibScalar((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 2), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsTableChanged.setStatus('current')
cfmMdiMetricsIntTable = MibTable((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3), )
if mibBuilder.loadTexts: cfmMdiMetricsIntTable.setStatus('current')
cfmMdiMetricsIntEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1), ).setIndexNames((0, "CISCO-FLOW-MONITOR-MIB", "cfmFlowMonitorId"), (0, "CISCO-FLOW-MONITOR-MIB", "cfmFlowId"), (0, "CISCO-FLOW-MONITOR-MIB", "cfmFlowMetricsIntNumber"))
if mibBuilder.loadTexts: cfmMdiMetricsIntEntry.setStatus('current')
cfmMdiMetricsIntValid = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 1), Bits().clone(namedValues=NamedValues(("lostPkts", 0), ("vbMin", 1), ("vbMax", 2), ("mediaRate", 3), ("delayFactor", 4), ("mediaLossRate", 5), ("mediaDiscontinuityCount", 6)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntValid.setStatus('current')
cfmMdiMetricsIntLostPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 2), ReportIntervalCount()).setUnits('packets').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntLostPkts.setStatus('current')
cfmMdiMetricsIntVbMin = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 3), ReportIntervalCount()).setUnits('bytes').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntVbMin.setStatus('current')
cfmMdiMetricsIntVbMax = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 4), ReportIntervalCount()).setUnits('bytes').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntVbMax.setStatus('current')
cfmMdiMetricsIntMrUnits = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 5), FlowBitRateUnits()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntMrUnits.setStatus('current')
cfmMdiMetricsIntMr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 6), ReportIntervalCount()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntMr.setStatus('current')
cfmMdiMetricsIntDfScale = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 7), FlowMetricScale()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntDfScale.setStatus('current')
cfmMdiMetricsIntDfPrecision = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 8), FlowMetricPrecision()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntDfPrecision.setStatus('current')
cfmMdiMetricsIntDf = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 9), FlowMetricValue()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntDf.setStatus('current')
cfmMdiMetricsIntMlrScale = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 10), FlowMetricScale()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntMlrScale.setStatus('current')
cfmMdiMetricsIntMlrPrecision = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 11), FlowMetricPrecision()).setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntMlrPrecision.setStatus('current')
cfmMdiMetricsIntMlr = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 12), FlowMetricValue()).setUnits('packets per second').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntMlr.setStatus('current')
cfmMdiMetricsIntMdc = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 9, 699, 1, 1, 3, 1, 13), ReportIntervalCount()).setUnits('Events').setMaxAccess("readonly")
if mibBuilder.loadTexts: cfmMdiMetricsIntMdc.setStatus('current')
cfmMdiMonitoredElements = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1))
cfmeMdiCumulativeLostPkts = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 1))
if mibBuilder.loadTexts: cfmeMdiCumulativeLostPkts.setStatus('current')
cfmeMdiCumulativeMlr = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 2))
if mibBuilder.loadTexts: cfmeMdiCumulativeMlr.setStatus('current')
cfmeMdiCumulativeMdc = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 3))
if mibBuilder.loadTexts: cfmeMdiCumulativeMdc.setStatus('current')
cfmeMdiLostPkts = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 4))
if mibBuilder.loadTexts: cfmeMdiLostPkts.setStatus('current')
cfmeMdiDf = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 5))
if mibBuilder.loadTexts: cfmeMdiDf.setStatus('current')
cfmeMdiMlr = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 6))
if mibBuilder.loadTexts: cfmeMdiMlr.setStatus('current')
cfmeMdiMdc = ObjectIdentity((1, 3, 6, 1, 4, 1, 9, 9, 699, 3, 1, 7))
if mibBuilder.loadTexts: cfmeMdiMdc.setStatus('current')
ciscoMdiMetricsMIBCompliances = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 2, 1))
ciscoMdiMetricsMIBGroups = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 9, 699, 2, 2))
ciscoMdiMetricsCompliance01 = ModuleCompliance((1, 3, 6, 1, 4, 1, 9, 9, 699, 2, 1, 1)).setObjects(("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    ciscoMdiMetricsCompliance01 = ciscoMdiMetricsCompliance01.setStatus('current')
cfmMdiMetricsGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 9, 9, 699, 2, 2, 1)).setObjects(("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsCfgRateType"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsCfgBitRate"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsCfgRate"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsCfgMediaPktSize"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsValid"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsLostPkts"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsMlrScale"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsMlrPrecision"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsMlr"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsMdc"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsTableChanged"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntValid"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntLostPkts"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntVbMin"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntVbMax"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntMrUnits"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntMr"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntDfScale"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntDfPrecision"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntDf"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntMlrScale"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntMlrPrecision"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntMlr"), ("CISCO-MDI-METRICS-MIB", "cfmMdiMetricsIntMdc"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    cfmMdiMetricsGroup = cfmMdiMetricsGroup.setStatus('current')
mibBuilder.exportSymbols("CISCO-MDI-METRICS-MIB", cfmMdiMetrics=cfmMdiMetrics, cfmMdiMetricsTable=cfmMdiMetricsTable, cfmMdiMetricsCfgMediaPktSize=cfmMdiMetricsCfgMediaPktSize, cfmMdiMetricsEntry=cfmMdiMetricsEntry, ciscoMdiMetricsMIBNotifs=ciscoMdiMetricsMIBNotifs, cfmMdiMetricsCfgRateType=cfmMdiMetricsCfgRateType, ciscoMdiMetricsMIBObjects=ciscoMdiMetricsMIBObjects, cfmMdiMetricsMlr=cfmMdiMetricsMlr, cfmMdiMetricsValid=cfmMdiMetricsValid, cfmeMdiCumulativeLostPkts=cfmeMdiCumulativeLostPkts, cfmeMdiCumulativeMdc=cfmeMdiCumulativeMdc, cfmMdiMetricsIntMr=cfmMdiMetricsIntMr, cfmMdiMetricsLostPkts=cfmMdiMetricsLostPkts, cfmMdiMetricsTableChanged=cfmMdiMetricsTableChanged, cfmMdiMetricsCfgRate=cfmMdiMetricsCfgRate, cfmMdiMonitoredElements=cfmMdiMonitoredElements, cfmeMdiMlr=cfmeMdiMlr, cfmMdiMetricsIntMdc=cfmMdiMetricsIntMdc, cfmMdiMetricsIntValid=cfmMdiMetricsIntValid, cfmMdiMetricsIntEntry=cfmMdiMetricsIntEntry, cfmMdiMetricsIntVbMax=cfmMdiMetricsIntVbMax, cfmeMdiDf=cfmeMdiDf, cfmeMdiCumulativeMlr=cfmeMdiCumulativeMlr, cfmeMdiMdc=cfmeMdiMdc, cfmMdiMetricsIntTable=cfmMdiMetricsIntTable, cfmMdiMetricsIntMrUnits=cfmMdiMetricsIntMrUnits, ciscoMdiMetricsMIBIds=ciscoMdiMetricsMIBIds, cfmMdiMetricsGroup=cfmMdiMetricsGroup, cfmMdiMetricsCfgBitRate=cfmMdiMetricsCfgBitRate, cfmMdiMetricsMlrScale=cfmMdiMetricsMlrScale, cfmMdiMetricsMdc=cfmMdiMetricsMdc, cfmMdiMetricsIntDfPrecision=cfmMdiMetricsIntDfPrecision, cfmMdiMetricsIntMlrScale=cfmMdiMetricsIntMlrScale, cfmMdiMetricsIntVbMin=cfmMdiMetricsIntVbMin, cfmMdiMetricsIntMlrPrecision=cfmMdiMetricsIntMlrPrecision, ciscoMdiMetricsMIBGroups=ciscoMdiMetricsMIBGroups, cfmMdiMetricsIntDfScale=cfmMdiMetricsIntDfScale, ciscoMdiMetricsMIBConform=ciscoMdiMetricsMIBConform, ciscoMdiMetricsCompliance01=ciscoMdiMetricsCompliance01, cfmMdiMetricsIntDf=cfmMdiMetricsIntDf, ciscoMdiMetricsMIBCompliances=ciscoMdiMetricsMIBCompliances, ciscoMdiMetricsMIB=ciscoMdiMetricsMIB, cfmMdiMetricsIntLostPkts=cfmMdiMetricsIntLostPkts, PYSNMP_MODULE_ID=ciscoMdiMetricsMIB, cfmMdiMetricsIntMlr=cfmMdiMetricsIntMlr, cfmMdiMetricsMlrPrecision=cfmMdiMetricsMlrPrecision, cfmeMdiLostPkts=cfmeMdiLostPkts)
