#
# PySNMP MIB module H323MC-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/H323MC-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 19:07:56 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
ObjectIdentifier, OctetString, Integer = mibBuilder.importSymbols("ASN1", "ObjectIdentifier", "OctetString", "Integer")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsUnion, ConstraintsIntersection, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsUnion", "ConstraintsIntersection", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
ifIndex, = mibBuilder.importSymbols("IF-MIB", "ifIndex")
MmTAddressTag, MmGlobalIdentifier, mmH323Root = mibBuilder.importSymbols("MULTI-MEDIA-MIB-TC", "MmTAddressTag", "MmGlobalIdentifier", "mmH323Root")
ObjectGroup, NotificationGroup, ModuleCompliance = mibBuilder.importSymbols("SNMPv2-CONF", "ObjectGroup", "NotificationGroup", "ModuleCompliance")
ObjectIdentity, Bits, ModuleIdentity, TimeTicks, Gauge32, MibIdentifier, iso, Unsigned32, Counter64, NotificationType, Integer32, IpAddress, Counter32, MibScalar, MibTable, MibTableRow, MibTableColumn = mibBuilder.importSymbols("SNMPv2-SMI", "ObjectIdentity", "Bits", "ModuleIdentity", "TimeTicks", "Gauge32", "MibIdentifier", "iso", "Unsigned32", "Counter64", "NotificationType", "Integer32", "IpAddress", "Counter32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn")
DisplayString, TAddress, TruthValue, DateAndTime, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TAddress", "TruthValue", "DateAndTime", "TextualConvention")
h323MC = ModuleIdentity((0, 0, 8, 341, 1, 1, 4))
if mibBuilder.loadTexts: h323MC.setLastUpdated('9812172253Z')
if mibBuilder.loadTexts: h323MC.setOrganization('ITU')
h323McSystem = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 1))
h323McConfig = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 2))
h323McConference = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 3))
h323McStats = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 4))
h323McControls = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 5))
h323McEvents = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 6, 0))
h323McSystemTable = MibTable((0, 0, 8, 341, 1, 1, 4, 1, 1), )
if mibBuilder.loadTexts: h323McSystemTable.setStatus('current')
h323McSystemTableEntry = MibTableRow((0, 0, 8, 341, 1, 1, 4, 1, 1, 1), ).setIndexNames((0, "IF-MIB", "ifIndex"))
if mibBuilder.loadTexts: h323McSystemTableEntry.setStatus('current')
h323McSystemNameAndMaker = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 1, 1, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 255))).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McSystemNameAndMaker.setStatus('current')
h323McSystemSoftwareVersionNumber = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 1, 1, 1, 2), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McSystemSoftwareVersionNumber.setStatus('current')
h323McSystemHardwareVersionNumber = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 1, 1, 1, 3), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McSystemHardwareVersionNumber.setStatus('current')
h323McSystemStartUpTime = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 1, 1, 1, 4), DateAndTime()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McSystemStartUpTime.setStatus('current')
h323McConfigTable = MibTable((0, 0, 8, 341, 1, 1, 4, 2, 1), )
if mibBuilder.loadTexts: h323McConfigTable.setStatus('current')
h323McConfigTableEntry = MibTableRow((0, 0, 8, 341, 1, 1, 4, 2, 1, 1), ).setIndexNames((0, "IF-MIB", "ifIndex"))
if mibBuilder.loadTexts: h323McConfigTableEntry.setStatus('current')
h323McConfigMcCallSignalingTag = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 2, 1, 1, 1), MmTAddressTag()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConfigMcCallSignalingTag.setStatus('current')
h323McConfigMcCallSignalingAddress = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 2, 1, 1, 2), TAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConfigMcCallSignalingAddress.setStatus('current')
h323McConfigGatekeeperAddressTag = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 2, 1, 1, 3), MmTAddressTag()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConfigGatekeeperAddressTag.setStatus('current')
h323McConfigGatekeeperAddress = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 2, 1, 1, 4), TAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConfigGatekeeperAddress.setStatus('current')
h323McConfigIsRegisteredWithGatekeeper = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 2, 1, 1, 5), TruthValue()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConfigIsRegisteredWithGatekeeper.setStatus('current')
h323McConfigEnableNotifications = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 2, 1, 1, 6), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("enabled", 1), ("disabled", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConfigEnableNotifications.setStatus('current')
h323McConferenceTable = MibTable((0, 0, 8, 341, 1, 1, 4, 3, 1), )
if mibBuilder.loadTexts: h323McConferenceTable.setStatus('current')
h323McConferenceTableEntry = MibTableRow((0, 0, 8, 341, 1, 1, 4, 3, 1, 1), ).setIndexNames((0, "IF-MIB", "ifIndex"), (0, "H323MC-MIB", "h323McConferenceConferenceId"))
if mibBuilder.loadTexts: h323McConferenceTableEntry.setStatus('current')
h323McConferenceConferenceId = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 1, 1, 1), MmGlobalIdentifier()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceConferenceId.setStatus('current')
h323McConferenceConferenceStartTime = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 1, 1, 2), DateAndTime()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceConferenceStartTime.setStatus('current')
h323McConferenceConferenceEndTime = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 1, 1, 3), DateAndTime()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceConferenceEndTime.setStatus('current')
h323McConferenceCentralizedOrDistributed = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 1, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("centralized", 1), ("distributed", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceCentralizedOrDistributed.setStatus('current')
h323McConferenceUniOrMulticast = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 1, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("unicast", 1), ("multicast", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceUniOrMulticast.setStatus('current')
h323McConferenceActiveMcAddress = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 1, 1, 6), TAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceActiveMcAddress.setStatus('current')
h323McConferenceParticipantsTable = MibTable((0, 0, 8, 341, 1, 1, 4, 3, 2), )
if mibBuilder.loadTexts: h323McConferenceParticipantsTable.setStatus('current')
h323McConferenceParticipantsTableEntry = MibTableRow((0, 0, 8, 341, 1, 1, 4, 3, 2, 1), ).setIndexNames((0, "IF-MIB", "ifIndex"), (0, "H323MC-MIB", "h323McConferenceConferenceId"), (0, "H323MC-MIB", "h323McConferenceParticipantsTableIndex"))
if mibBuilder.loadTexts: h323McConferenceParticipantsTableEntry.setStatus('current')
h323McConferenceParticipantsTableIndex = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 1), Integer32())
if mibBuilder.loadTexts: h323McConferenceParticipantsTableIndex.setStatus('current')
h323McConferenceParticipantsTerminalLabel = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 2), OctetString().subtype(subtypeSpec=ValueSizeConstraint(2, 2)).setFixedLength(2)).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsTerminalLabel.setStatus('current')
h323McConferenceParticipantsCallSignalingTAddressTag = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 3), MmTAddressTag()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsCallSignalingTAddressTag.setStatus('current')
h323McConferenceParticipantsCallSignalingAddress = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 4), TAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsCallSignalingAddress.setStatus('current')
h323McConferenceParticipantsCallId = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 5), MmGlobalIdentifier()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsCallId.setStatus('current')
h323McConferenceParticipantsControlChannelIndex = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsControlChannelIndex.setStatus('current')
h323McConferenceParticipantsNumberOfLogicalChannels = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsNumberOfLogicalChannels.setStatus('current')
h323McConferenceParticipantsRtpSessionIndex = MibTableColumn((0, 0, 8, 341, 1, 1, 4, 3, 2, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McConferenceParticipantsRtpSessionIndex.setStatus('current')
h323McStatsTotalConferences = MibScalar((0, 0, 8, 341, 1, 1, 4, 4, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McStatsTotalConferences.setStatus('current')
h323McStatsSuccessfullyCompletedConferences = MibScalar((0, 0, 8, 341, 1, 1, 4, 4, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McStatsSuccessfullyCompletedConferences.setStatus('current')
h323McStatsAbnormalyTerminatedConferences = MibScalar((0, 0, 8, 341, 1, 1, 4, 4, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: h323McStatsAbnormalyTerminatedConferences.setStatus('current')
h323McControlsCommands = MibScalar((0, 0, 8, 341, 1, 1, 4, 5, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11))).clone(namedValues=NamedValues(("other", 1), ("abruptRestart", 2), ("gracefulRestart", 3), ("abruptShutdown", 4), ("gracefulShutdown", 5), ("enterQuiescence", 6), ("exitQuiescence", 7), ("startLog", 8), ("stopLog", 9), ("resetStatistics", 10), ("runDiagnostic", 11)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: h323McControlsCommands.setStatus('current')
lastConferenceTerminationReason = MibScalar((0, 0, 8, 341, 1, 1, 4, 6, 0, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("normalTermination", 1), ("administrativelyTerminated", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: lastConferenceTerminationReason.setStatus('current')
lastTerminatedConferenceId = MibScalar((0, 0, 8, 341, 1, 1, 4, 6, 0, 2), MmGlobalIdentifier()).setMaxAccess("readonly")
if mibBuilder.loadTexts: lastTerminatedConferenceId.setStatus('current')
conferenceTermination = NotificationType((0, 0, 8, 341, 1, 1, 4, 6, 0, 3)).setObjects(("H323MC-MIB", "lastTerminatedConferenceId"), ("H323MC-MIB", "lastConferenceTerminationReason"), ("IF-MIB", "ifIndex"))
if mibBuilder.loadTexts: conferenceTermination.setStatus('current')
h323McMIBConformance = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 7))
h323McMIBGroups = MibIdentifier((0, 0, 8, 341, 1, 1, 4, 7, 1))
h323McSystemGroup = ObjectGroup((0, 0, 8, 341, 1, 1, 4, 7, 1, 1)).setObjects(("H323MC-MIB", "h323McSystemNameAndMaker"), ("H323MC-MIB", "h323McSystemSoftwareVersionNumber"), ("H323MC-MIB", "h323McSystemHardwareVersionNumber"), ("H323MC-MIB", "h323McSystemStartUpTime"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    h323McSystemGroup = h323McSystemGroup.setStatus('current')
h323McConfigGroup = ObjectGroup((0, 0, 8, 341, 1, 1, 4, 7, 1, 2)).setObjects(("H323MC-MIB", "h323McConfigMcCallSignalingTag"), ("H323MC-MIB", "h323McConfigMcCallSignalingAddress"), ("H323MC-MIB", "h323McConfigGatekeeperAddressTag"), ("H323MC-MIB", "h323McConfigGatekeeperAddress"), ("H323MC-MIB", "h323McConfigIsRegisteredWithGatekeeper"), ("H323MC-MIB", "h323McConfigEnableNotifications"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    h323McConfigGroup = h323McConfigGroup.setStatus('current')
h323McConferenceGroup = ObjectGroup((0, 0, 8, 341, 1, 1, 4, 7, 1, 3)).setObjects(("H323MC-MIB", "h323McConferenceConferenceId"), ("H323MC-MIB", "h323McConferenceConferenceStartTime"), ("H323MC-MIB", "h323McConferenceConferenceEndTime"), ("H323MC-MIB", "h323McConferenceCentralizedOrDistributed"), ("H323MC-MIB", "h323McConferenceUniOrMulticast"), ("H323MC-MIB", "h323McConferenceActiveMcAddress"), ("H323MC-MIB", "h323McConferenceParticipantsTerminalLabel"), ("H323MC-MIB", "h323McConferenceParticipantsCallSignalingTAddressTag"), ("H323MC-MIB", "h323McConferenceParticipantsCallSignalingAddress"), ("H323MC-MIB", "h323McConferenceParticipantsCallId"), ("H323MC-MIB", "h323McConferenceParticipantsControlChannelIndex"), ("H323MC-MIB", "h323McConferenceParticipantsNumberOfLogicalChannels"), ("H323MC-MIB", "h323McConferenceParticipantsRtpSessionIndex"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    h323McConferenceGroup = h323McConferenceGroup.setStatus('current')
h323McStatsGroup = ObjectGroup((0, 0, 8, 341, 1, 1, 4, 7, 1, 4)).setObjects(("H323MC-MIB", "h323McStatsTotalConferences"), ("H323MC-MIB", "h323McStatsSuccessfullyCompletedConferences"), ("H323MC-MIB", "h323McStatsAbnormalyTerminatedConferences"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    h323McStatsGroup = h323McStatsGroup.setStatus('current')
h323McControlsGroup = ObjectGroup((0, 0, 8, 341, 1, 1, 4, 7, 1, 5)).setObjects(("H323MC-MIB", "h323McControlsCommands"))
if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    h323McControlsGroup = h323McControlsGroup.setStatus('current')
h323McMIBCompliance = ModuleCompliance((0, 0, 8, 341, 1, 1, 4, 7, 2)).setObjects(("H323MC-MIB", "h323McSystemGroup"), ("H323MC-MIB", "h323McConfigGroup"), ("H323MC-MIB", "h323McConferenceGroup"), ("H323MC-MIB", "h323McStatsGroup"), ("H323MC-MIB", "h323McControlsGroup"), ("H323MC-MIB", "h323McEventsGroup"))

if getattr(mibBuilder, 'version', (0, 0, 0)) > (4, 4, 0):
    h323McMIBCompliance = h323McMIBCompliance.setStatus('current')
mibBuilder.exportSymbols("H323MC-MIB", conferenceTermination=conferenceTermination, h323McConference=h323McConference, h323McConferenceParticipantsTableEntry=h323McConferenceParticipantsTableEntry, h323McStatsSuccessfullyCompletedConferences=h323McStatsSuccessfullyCompletedConferences, h323McStats=h323McStats, h323McStatsTotalConferences=h323McStatsTotalConferences, h323McConferenceTable=h323McConferenceTable, h323McConfigIsRegisteredWithGatekeeper=h323McConfigIsRegisteredWithGatekeeper, h323McConferenceParticipantsCallSignalingAddress=h323McConferenceParticipantsCallSignalingAddress, h323McSystemTableEntry=h323McSystemTableEntry, h323McConferenceParticipantsCallSignalingTAddressTag=h323McConferenceParticipantsCallSignalingTAddressTag, h323McConfigTableEntry=h323McConfigTableEntry, h323McConfigGroup=h323McConfigGroup, h323McConferenceCentralizedOrDistributed=h323McConferenceCentralizedOrDistributed, lastTerminatedConferenceId=lastTerminatedConferenceId, h323McConferenceTableEntry=h323McConferenceTableEntry, h323McSystemSoftwareVersionNumber=h323McSystemSoftwareVersionNumber, h323McConferenceParticipantsControlChannelIndex=h323McConferenceParticipantsControlChannelIndex, h323McConfigMcCallSignalingAddress=h323McConfigMcCallSignalingAddress, h323McConferenceConferenceEndTime=h323McConferenceConferenceEndTime, h323McMIBCompliance=h323McMIBCompliance, h323McConfigGatekeeperAddress=h323McConfigGatekeeperAddress, h323McConfigGatekeeperAddressTag=h323McConfigGatekeeperAddressTag, h323McSystemHardwareVersionNumber=h323McSystemHardwareVersionNumber, h323McControls=h323McControls, h323McConfigMcCallSignalingTag=h323McConfigMcCallSignalingTag, h323McConfig=h323McConfig, h323McSystemTable=h323McSystemTable, h323MC=h323MC, h323McConfigTable=h323McConfigTable, lastConferenceTerminationReason=lastConferenceTerminationReason, h323McMIBGroups=h323McMIBGroups, h323McSystemGroup=h323McSystemGroup, h323McControlsGroup=h323McControlsGroup, h323McConfigEnableNotifications=h323McConfigEnableNotifications, h323McControlsCommands=h323McControlsCommands, PYSNMP_MODULE_ID=h323MC, h323McEvents=h323McEvents, h323McConferenceParticipantsTerminalLabel=h323McConferenceParticipantsTerminalLabel, h323McStatsAbnormalyTerminatedConferences=h323McStatsAbnormalyTerminatedConferences, h323McConferenceParticipantsTable=h323McConferenceParticipantsTable, h323McConferenceConferenceId=h323McConferenceConferenceId, h323McConferenceParticipantsNumberOfLogicalChannels=h323McConferenceParticipantsNumberOfLogicalChannels, h323McMIBConformance=h323McMIBConformance, h323McSystemNameAndMaker=h323McSystemNameAndMaker, h323McSystem=h323McSystem, h323McConferenceUniOrMulticast=h323McConferenceUniOrMulticast, h323McConferenceParticipantsCallId=h323McConferenceParticipantsCallId, h323McConferenceGroup=h323McConferenceGroup, h323McStatsGroup=h323McStatsGroup, h323McConferenceActiveMcAddress=h323McConferenceActiveMcAddress, h323McSystemStartUpTime=h323McSystemStartUpTime, h323McConferenceParticipantsRtpSessionIndex=h323McConferenceParticipantsRtpSessionIndex, h323McConferenceParticipantsTableIndex=h323McConferenceParticipantsTableIndex, h323McConferenceConferenceStartTime=h323McConferenceConferenceStartTime)
