#
# PySNMP MIB module MARVELL-SFLOW-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/MARVELL-SFLOW-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 19:59:55 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
ObjectIdentifier, Integer, OctetString = mibBuilder.importSymbols("ASN1", "ObjectIdentifier", "Integer", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ValueRangeConstraint, ConstraintsUnion, ConstraintsIntersection, SingleValueConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ValueRangeConstraint", "ConstraintsUnion", "ConstraintsIntersection", "SingleValueConstraint", "ValueSizeConstraint")
ifIndex, = mibBuilder.importSymbols("IF-MIB", "ifIndex")
rnd, = mibBuilder.importSymbols("RADLAN-MIB", "rnd")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
MibScalar, MibTable, MibTableRow, MibTableColumn, Integer32, ModuleIdentity, Counter64, Unsigned32, ObjectIdentity, Counter32, Gauge32, IpAddress, TimeTicks, iso, NotificationType, MibIdentifier, Bits = mibBuilder.importSymbols("SNMPv2-SMI", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "Integer32", "ModuleIdentity", "Counter64", "Unsigned32", "ObjectIdentity", "Counter32", "Gauge32", "IpAddress", "TimeTicks", "iso", "NotificationType", "MibIdentifier", "Bits")
DisplayString, TextualConvention = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")
rlsFlowMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 89, 147))
rlsFlowMib.setRevisions(('2009-10-27 00:00',))
if mibBuilder.loadTexts: rlsFlowMib.setLastUpdated('200910270000Z')
if mibBuilder.loadTexts: rlsFlowMib.setOrganization('Marvell Computer Communications Ltd.')
rlsFlowStatisticsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 147, 1), ).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlsFlowStatisticsTable.setStatus('current')
rlsFlowStatisticsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 147, 1, 1), ).setMaxAccess("readonly").setIndexNames((0, "MARVELL-SFLOW-MIB", "rlsFlowDataSource"))
if mibBuilder.loadTexts: rlsFlowStatisticsEntry.setStatus('current')
rlsFlowDataSource = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 147, 1, 1, 1), ObjectIdentifier()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlsFlowDataSource.setStatus('current')
rlsFlowStatisticsSampledPackets = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 147, 1, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlsFlowStatisticsSampledPackets.setStatus('current')
rlsFlowStatisticsDatagramSent = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 147, 1, 1, 3), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlsFlowStatisticsDatagramSent.setStatus('current')
rlsFlowStatisticsAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 147, 1, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("noaction", 1), ("clear", 2)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlsFlowStatisticsAction.setStatus('current')
rlsFlowStatisticsReset = MibScalar((1, 3, 6, 1, 4, 1, 89, 147, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("noaction", 1), ("clear", 2))).clone(1)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlsFlowStatisticsReset.setStatus('current')
mibBuilder.exportSymbols("MARVELL-SFLOW-MIB", rlsFlowStatisticsTable=rlsFlowStatisticsTable, rlsFlowStatisticsDatagramSent=rlsFlowStatisticsDatagramSent, rlsFlowStatisticsEntry=rlsFlowStatisticsEntry, rlsFlowStatisticsAction=rlsFlowStatisticsAction, PYSNMP_MODULE_ID=rlsFlowMib, rlsFlowMib=rlsFlowMib, rlsFlowStatisticsSampledPackets=rlsFlowStatisticsSampledPackets, rlsFlowDataSource=rlsFlowDataSource, rlsFlowStatisticsReset=rlsFlowStatisticsReset)
