#
# PySNMP MIB module NETI-CHMGR-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/NETI-CHMGR-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 20:09:54 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
Integer, OctetString, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "Integer", "OctetString", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ValueRangeConstraint, SingleValueConstraint, ConstraintsUnion, ConstraintsIntersection, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ValueRangeConstraint", "SingleValueConstraint", "ConstraintsUnion", "ConstraintsIntersection", "ValueSizeConstraint")
netiExperimentalGeneric, = mibBuilder.importSymbols("NETI-COMMON-MIB", "netiExperimentalGeneric")
DtmAddress, = mibBuilder.importSymbols("NETI-DTM-MIB", "DtmAddress")
SnmpAdminString, = mibBuilder.importSymbols("SNMP-FRAMEWORK-MIB", "SnmpAdminString")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
MibScalar, MibTable, MibTableRow, MibTableColumn, iso, Bits, Counter32, ModuleIdentity, MibIdentifier, Counter64, Integer32, TimeTicks, IpAddress, Unsigned32, NotificationType, Gauge32, ObjectIdentity = mibBuilder.importSymbols("SNMPv2-SMI", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "iso", "Bits", "Counter32", "ModuleIdentity", "MibIdentifier", "Counter64", "Integer32", "TimeTicks", "IpAddress", "Unsigned32", "NotificationType", "Gauge32", "ObjectIdentity")
RowPointer, MacAddress, DisplayString, TruthValue, TextualConvention, RowStatus, TimeStamp = mibBuilder.importSymbols("SNMPv2-TC", "RowPointer", "MacAddress", "DisplayString", "TruthValue", "TextualConvention", "RowStatus", "TimeStamp")
netiChmgrMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14))
netiChmgrMIB.setRevisions(('2015-01-08 15:00', '2014-05-05 12:00', '2014-02-06 15:00', '2013-09-02 16:00', '2012-03-19 09:00', '2012-01-26 15:00', '2010-04-06 08:00', '2009-09-25 11:00', '2008-12-12 14:00', '2008-01-28 14:00', '2008-01-03 16:00', '2007-06-29 12:00', '2006-09-20 08:00', '2006-04-20 09:00', '2005-09-27 00:00', '2004-11-18 00:00', '2003-04-24 00:00',))
if mibBuilder.loadTexts: netiChmgrMIB.setLastUpdated('201501081500Z')
if mibBuilder.loadTexts: netiChmgrMIB.setOrganization('Net Insight AB')
class Dst(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(0, 1, 4, 5, 8, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26))
    namedValues = NamedValues(("ctrl", 0), ("dleCrtlAndData", 1), ("pdh", 4), ("dleInterServer", 5), ("ets", 8), ("ping", 12), ("e1", 13), ("ds1", 14), ("sdi", 15), ("dvb", 16), ("sdh", 18), ("ttcp", 19), ("aesebu", 20), ("j2kSdSdi", 21), ("j2kHdSdi", 22), ("j2k3gSdi", 23), ("j2kHdSdi2", 24), ("j2k3gSdi2", 25), ("j2kSdSdi2", 26))

class Dsti(TextualConvention, Unsigned32):
    status = 'current'
    displayHint = 'd'
    subtypeSpec = Unsigned32.subtypeSpec + ValueRangeConstraint(0, 32769)

class ChannelId(TextualConvention, Unsigned32):
    status = 'current'
    displayHint = 'x'

class DcapType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("dcap0", 1), ("dcap1", 2))

class DtmNode(TextualConvention, OctetString):
    status = 'current'
    subtypeSpec = OctetString.subtypeSpec + ValueSizeConstraint(0, 64)

class DcpVersion(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("auto", 1), ("dcp2", 2), ("dcp3", 3))

chmgrObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1))
chmgrNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 2))
chmgrConformance = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 3))
chmgrODescriptionGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1))
chmgrTDescriptionGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 2))
chmgrSourceRouteGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3))
chmgrOConnectionGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4))
chmgrTConnectionGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5))
chmgrStatisticsGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6))
chmgrChannelGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7))
chmgrODescriptionTimeStamp = MibScalar((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 1), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescriptionTimeStamp.setStatus('current')
chmgrODescriptionTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2), )
if mibBuilder.loadTexts: chmgrODescriptionTable.setStatus('current')
chmgrODescriptionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrODescrIndex"))
if mibBuilder.loadTexts: chmgrODescriptionEntry.setStatus('current')
chmgrODescrIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 1), Unsigned32())
if mibBuilder.loadTexts: chmgrODescrIndex.setStatus('current')
chmgrODescrType = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("ets", 1), ("its", 2), ("dle", 3)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrType.setStatus('current')
chmgrODescrCapabilities = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 3), Bits().clone(namedValues=NamedValues(("allowCapacityInterval", 0), ("destination", 1), ("allowDynamicCapacity", 2), ("isMulticast", 3), ("allowEstablish", 4), ("allowProtection", 5), ("allowReestablish", 6), ("allowScheduling", 7), ("allowSourceRoute", 8), ("requireCapacity", 9), ("allowAlternative", 10), ("allowZeroCapacity", 11)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrCapabilities.setStatus('current')
chmgrODescrCustomerId = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrCustomerId.setStatus('current')
chmgrODescrServiceReference = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 5), RowPointer()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrServiceReference.setStatus('current')
chmgrODescrAcceptableBps = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 6), Gauge32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrAcceptableBps.setStatus('current')
chmgrODescrAcceptableSlots = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 7), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrAcceptableSlots.setStatus('current')
chmgrODescrRequestedBps = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 8), Gauge32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrRequestedBps.setStatus('current')
chmgrODescrRequestedSlots = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 9), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrRequestedSlots.setStatus('current')
chmgrODescrReestablishMethod = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 10), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1))).clone(namedValues=NamedValues(("exponential", 1))).clone('exponential')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrReestablishMethod.setStatus('current')
chmgrODescrMinInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 11), Gauge32().subtype(subtypeSpec=ValueRangeConstraint(0, 3600000)).clone(500)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrMinInterval.setStatus('current')
chmgrODescrMaxInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 12), Gauge32().subtype(subtypeSpec=ValueRangeConstraint(0, 3600000)).clone(10000)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrMaxInterval.setStatus('current')
chmgrODescrEstablish = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 13), TruthValue().clone('true')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrEstablish.setStatus('current')
chmgrODescrNextDestTableIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 14), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODescrNextDestTableIndex.setStatus('current')
chmgrODescrPrecedence = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 15), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrPrecedence.setStatus('current')
chmgrODescrSuppressAlarms = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 16), Bits().clone(namedValues=NamedValues(("route", 0)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrSuppressAlarms.setStatus('current')
chmgrODescrAcceptableMbps = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 17), Gauge32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrAcceptableMbps.setStatus('current')
chmgrODescrRequestedMbps = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 18), Gauge32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrRequestedMbps.setStatus('current')
chmgrODescrRequestedDcpVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 19), DcpVersion()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrRequestedDcpVersion.setStatus('current')
chmgrODescrOneHopSpareCapUtilization = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 2, 1, 20), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrODescrOneHopSpareCapUtilization.setStatus('current')
chmgrODescrDestinationTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3), )
if mibBuilder.loadTexts: chmgrODescrDestinationTable.setStatus('current')
chmgrODescrDestinationEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrODescrIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrDestIndex"))
if mibBuilder.loadTexts: chmgrODescrDestinationEntry.setStatus('current')
chmgrODescrDestIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3, 1, 1), Unsigned32())
if mibBuilder.loadTexts: chmgrODescrDestIndex.setStatus('current')
chmgrODescrDestAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3, 1, 2), DtmNode().clone(hexValue="")).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrODescrDestAddress.setStatus('current')
chmgrODescrDestDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3, 1, 3), Dsti()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrODescrDestDsti.setStatus('current')
chmgrODescrDestRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrODescrDestRowStatus.setStatus('current')
chmgrODescrDestAdminStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 3, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("up", 1), ("down", 2)))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrODescrDestAdminStatus.setStatus('current')
chmgrODescrChannelTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 4), )
if mibBuilder.loadTexts: chmgrODescrChannelTable.setStatus('current')
chmgrODescrChannelEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 4, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrODescrIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrDestIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrChanIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrChanSourceRouteIndex"))
if mibBuilder.loadTexts: chmgrODescrChannelEntry.setStatus('current')
chmgrODescrChanIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 4, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2)))
if mibBuilder.loadTexts: chmgrODescrChanIndex.setStatus('current')
chmgrODescrChanSourceRouteIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 4, 1, 2), Unsigned32())
if mibBuilder.loadTexts: chmgrODescrChanSourceRouteIndex.setStatus('current')
chmgrODescrChanSourceRoute = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 4, 1, 3), Unsigned32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrODescrChanSourceRoute.setStatus('current')
chmgrODescrChanRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 1, 4, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrODescrChanRowStatus.setStatus('current')
chmgrSourceRouteTimeStamp = MibScalar((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 1), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrSourceRouteTimeStamp.setStatus('current')
chmgrSourceRouteTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2), )
if mibBuilder.loadTexts: chmgrSourceRouteTable.setStatus('current')
chmgrSourceRouteEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrSourceRouteIndex"))
if mibBuilder.loadTexts: chmgrSourceRouteEntry.setStatus('current')
chmgrSourceRouteIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1, 1), Unsigned32())
if mibBuilder.loadTexts: chmgrSourceRouteIndex.setStatus('current')
chmgrSourceRouteName = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1, 2), SnmpAdminString()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrSourceRouteName.setStatus('current')
chmgrSourceRouteTypeOfRoute = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("strict", 1), ("loose", 2))).clone('strict')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteTypeOfRoute.setStatus('current')
chmgrSourceRouteFirstIfBoard = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1, 4), Unsigned32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteFirstIfBoard.setStatus('current')
chmgrSourceRouteFirstIfPort = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1, 5), Unsigned32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteFirstIfPort.setStatus('current')
chmgrSourceRouteRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 2, 1, 6), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteRowStatus.setStatus('current')
chmgrSourceRouteHopTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3), )
if mibBuilder.loadTexts: chmgrSourceRouteHopTable.setStatus('current')
chmgrSourceRouteHopEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrSourceRouteIndex"), (0, "NETI-CHMGR-MIB", "chmgrSourceRouteHopIndex"))
if mibBuilder.loadTexts: chmgrSourceRouteHopEntry.setStatus('current')
chmgrSourceRouteHopIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3, 1, 1), Unsigned32())
if mibBuilder.loadTexts: chmgrSourceRouteHopIndex.setStatus('current')
chmgrSourceRouteHopAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3, 1, 2), DtmNode()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteHopAddress.setStatus('current')
chmgrSourceRouteHopNextIfBoard = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3, 1, 3), Unsigned32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteHopNextIfBoard.setStatus('current')
chmgrSourceRouteHopNextIfPort = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3, 1, 4), Unsigned32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteHopNextIfPort.setStatus('current')
chmgrSourceRouteHopRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 3, 3, 1, 5), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: chmgrSourceRouteHopRowStatus.setStatus('current')
chmgrOConnectionTimeStamp = MibScalar((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 1), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnectionTimeStamp.setStatus('current')
chmgrOConnectionTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2), )
if mibBuilder.loadTexts: chmgrOConnectionTable.setStatus('current')
chmgrOConnectionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrOConnIndex"))
if mibBuilder.loadTexts: chmgrOConnectionEntry.setStatus('current')
chmgrOConnIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 1), Unsigned32())
if mibBuilder.loadTexts: chmgrOConnIndex.setStatus('current')
chmgrOConnCustomerId = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnCustomerId.setStatus('current')
chmgrOConnODescrIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 3), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnODescrIndex.setStatus('current')
chmgrOConnServiceReference = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 4), RowPointer()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnServiceReference.setStatus('current')
chmgrOConnAllocatedSlots = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 5), Gauge32().subtype(subtypeSpec=ValueRangeConstraint(0, 8389))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnAllocatedSlots.setStatus('current')
chmgrOConnAllocatedSlotsChanged = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 6), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnAllocatedSlotsChanged.setStatus('current')
chmgrOConnDcapType = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 7), DcapType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnDcapType.setStatus('current')
chmgrOConnDst = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 8), Dst()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnDst.setStatus('current')
chmgrOConnSourceAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 9), DtmNode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnSourceAddress.setStatus('current')
chmgrOConnSourceDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 10), Dsti()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnSourceDsti.setStatus('current')
chmgrOConnStatusLastChanged = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 11), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnStatusLastChanged.setStatus('current')
chmgrOConnAdminStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 12), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("up", 1), ("down", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnAdminStatus.setStatus('current')
chmgrOConnOperStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 13), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 5))).clone(namedValues=NamedValues(("up", 1), ("down", 2), ("partial", 3), ("dormant", 5)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnOperStatus.setStatus('current')
chmgrOConnReestablish = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 14), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("notApplicable", 0), ("reestablish", 1)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrOConnReestablish.setStatus('current')
chmgrOConnForceSourceRoute = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 15), Unsigned32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrOConnForceSourceRoute.setStatus('current')
chmgrOConnDcpVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 2, 1, 16), DcpVersion()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOConnDcpVersion.setStatus('current')
chmgrODestinationTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 3), )
if mibBuilder.loadTexts: chmgrODestinationTable.setStatus('current')
chmgrODestinationEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 3, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrOConnIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrDestIndex"))
if mibBuilder.loadTexts: chmgrODestinationEntry.setStatus('current')
chmgrODestDestinationAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 3, 1, 1), DtmNode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODestDestinationAddress.setStatus('current')
chmgrODestDestinationDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 3, 1, 2), Dsti()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrODestDestinationDsti.setStatus('current')
chmgrOChannelTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4), )
if mibBuilder.loadTexts: chmgrOChannelTable.setStatus('current')
chmgrOChannelEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrOConnIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrDestIndex"), (0, "NETI-CHMGR-MIB", "chmgrODescrChanIndex"))
if mibBuilder.loadTexts: chmgrOChannelEntry.setStatus('current')
chmgrOChanSourceRouteIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 1), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOChanSourceRouteIndex.setStatus('current')
chmgrOChanChannelId = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 2), ChannelId()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOChanChannelId.setStatus('current')
chmgrOChanErrorMessage = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 3), SnmpAdminString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOChanErrorMessage.setStatus('current')
chmgrOChanErrorAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 4), DtmNode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOChanErrorAddress.setStatus('current')
chmgrOChanOperStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("up", 1), ("down", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOChanOperStatus.setStatus('current')
chmgrOChanStatusChanged = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 6), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOChanStatusChanged.setStatus('current')
chmgrOChanReestablish = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 4, 4, 1, 7), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(0, 1))).clone(namedValues=NamedValues(("notApplicable", 0), ("reestablish", 1)))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: chmgrOChanReestablish.setStatus('current')
chmgrTConnectionTimeStamp = MibScalar((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 1), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnectionTimeStamp.setStatus('current')
chmgrTConnectionTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2), )
if mibBuilder.loadTexts: chmgrTConnectionTable.setStatus('current')
chmgrTConnectionEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrTConnIndex"))
if mibBuilder.loadTexts: chmgrTConnectionEntry.setStatus('current')
chmgrTConnIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 1), Unsigned32())
if mibBuilder.loadTexts: chmgrTConnIndex.setStatus('current')
chmgrTConnCustomerId = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnCustomerId.setStatus('current')
chmgrTConnNumberOfChannels = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 3), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnNumberOfChannels.setStatus('current')
chmgrTConnActiveChannel = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 4), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 2))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnActiveChannel.setStatus('current')
chmgrTConnServiceReference = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 5), RowPointer()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnServiceReference.setStatus('current')
chmgrTConnAllocatedSlots = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 6), Gauge32().subtype(subtypeSpec=ValueRangeConstraint(0, 8389))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnAllocatedSlots.setStatus('current')
chmgrTConnAllocatedSlotsChanged = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 7), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnAllocatedSlotsChanged.setStatus('current')
chmgrTConnDcapType = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 8), DcapType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnDcapType.setStatus('current')
chmgrTConnDst = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 9), Dst()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnDst.setStatus('current')
chmgrTConnSourceDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 10), Dsti()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnSourceDsti.setStatus('current')
chmgrTConnSourceAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 11), DtmNode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnSourceAddress.setStatus('current')
chmgrTConnDestinationDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 12), Dsti()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnDestinationDsti.setStatus('current')
chmgrTConnDestinationAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 13), DtmNode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnDestinationAddress.setStatus('current')
chmgrTConnStatusLastChanged = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 14), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnStatusLastChanged.setStatus('current')
chmgrTConnAdminStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 15), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("up", 1), ("down", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnAdminStatus.setStatus('current')
chmgrTConnOperStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 16), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 5))).clone(namedValues=NamedValues(("up", 1), ("down", 2), ("dormant", 5)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnOperStatus.setStatus('current')
chmgrTConnDcpVersion = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 2, 1, 17), DcpVersion()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTConnDcpVersion.setStatus('current')
chmgrTChannelTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 3), )
if mibBuilder.loadTexts: chmgrTChannelTable.setStatus('current')
chmgrTChannelEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 3, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrTConnIndex"), (0, "NETI-CHMGR-MIB", "chmgrTChanIndex"))
if mibBuilder.loadTexts: chmgrTChannelEntry.setStatus('current')
chmgrTChanIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 3, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 2)))
if mibBuilder.loadTexts: chmgrTChanIndex.setStatus('current')
chmgrTChanChannelId = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 3, 1, 2), ChannelId()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTChanChannelId.setStatus('current')
chmgrTChanCreated = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 5, 3, 1, 3), TimeStamp()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTChanCreated.setStatus('current')
chmgrOStatDcap1Table = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1), )
if mibBuilder.loadTexts: chmgrOStatDcap1Table.setStatus('current')
chmgrOStatDcap1Entry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrOConnIndex"))
if mibBuilder.loadTexts: chmgrOStatDcap1Entry.setStatus('current')
chmgrOStatDcap1Octets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1Octets.setStatus('current')
chmgrOStatDcap1Packets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1Packets.setStatus('current')
chmgrOStatDcap1UtilizedBps = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 3), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1UtilizedBps.setStatus('current')
chmgrOStatDcap1DiscardOctets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1DiscardOctets.setStatus('current')
chmgrOStatDcap1DiscardPackets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 5), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1DiscardPackets.setStatus('current')
chmgrOStatDcap1Bitrate = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 6), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1Bitrate.setStatus('current')
chmgrOStatDcap1Load = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 1, 1, 7), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrOStatDcap1Load.setStatus('current')
chmgrTStatDcap1Table = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2), )
if mibBuilder.loadTexts: chmgrTStatDcap1Table.setStatus('current')
chmgrTStatDcap1Entry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrTConnIndex"))
if mibBuilder.loadTexts: chmgrTStatDcap1Entry.setStatus('current')
chmgrTStatDcap1Octets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1Octets.setStatus('current')
chmgrTStatDcap1Packets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 2), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1Packets.setStatus('current')
chmgrTStatDcap1UtilizedBps = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 3), Gauge32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1UtilizedBps.setStatus('current')
chmgrTStatDcap1DiscardOctets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1DiscardOctets.setStatus('current')
chmgrTStatDcap1DiscardPackets = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 5), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1DiscardPackets.setStatus('current')
chmgrTStatDcap1ErrorCRC = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 6), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1ErrorCRC.setStatus('current')
chmgrTStatDcap1ErrorLods = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 7), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1ErrorLods.setStatus('current')
chmgrTStatDcap1Bitrate = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 8), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1Bitrate.setStatus('current')
chmgrTStatDcap1Load = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 2, 1, 9), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatDcap1Load.setStatus('current')
chmgrTStatPMReferenceTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 3), )
if mibBuilder.loadTexts: chmgrTStatPMReferenceTable.setStatus('deprecated')
chmgrTStatPMReferenceEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 3, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrTConnIndex"))
if mibBuilder.loadTexts: chmgrTStatPMReferenceEntry.setStatus('deprecated')
chmgrTStatPMReference = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 6, 3, 1, 1), RowPointer()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrTStatPMReference.setStatus('deprecated')
chmgrChannelTable = MibTable((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1), )
if mibBuilder.loadTexts: chmgrChannelTable.setStatus('current')
chmgrChannelEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1), ).setIndexNames((0, "NETI-CHMGR-MIB", "chmgrChanSourceMacAddress"), (0, "NETI-CHMGR-MIB", "chmgrChanChannelId"), (0, "NETI-CHMGR-MIB", "chmgrChanOutgoingIfBoard"), (0, "NETI-CHMGR-MIB", "chmgrChanOutgoingIfPort"))
if mibBuilder.loadTexts: chmgrChannelEntry.setStatus('current')
chmgrChanSourceMacAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 1), MacAddress())
if mibBuilder.loadTexts: chmgrChanSourceMacAddress.setStatus('current')
chmgrChanChannelId = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 2), ChannelId())
if mibBuilder.loadTexts: chmgrChanChannelId.setStatus('current')
chmgrChanOutgoingIfBoard = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 3), Unsigned32())
if mibBuilder.loadTexts: chmgrChanOutgoingIfBoard.setStatus('current')
chmgrChanOutgoingIfPort = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 4), Unsigned32())
if mibBuilder.loadTexts: chmgrChanOutgoingIfPort.setStatus('current')
chmgrChanOutgoingIfMacAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 5), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanOutgoingIfMacAddress.setStatus('current')
chmgrChanNextHopMacAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 6), MacAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanNextHopMacAddress.setStatus('current')
chmgrChanNextHopDtmAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 7), DtmAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanNextHopDtmAddress.setStatus('current')
chmgrChanIncomingIfBoard = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 8), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanIncomingIfBoard.setStatus('current')
chmgrChanIncomingIfPort = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 9), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanIncomingIfPort.setStatus('current')
chmgrChanSourceDtmAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 10), DtmAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanSourceDtmAddress.setStatus('current')
chmgrChanDst = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 11), Dst()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanDst.setStatus('current')
chmgrChanSourceDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 12), Dsti()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanSourceDsti.setStatus('current')
chmgrChanIsMulticast = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 13), TruthValue()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanIsMulticast.setStatus('current')
chmgrChanCapacity = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 14), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanCapacity.setStatus('current')
chmgrChanDestDsti = MibTableColumn((1, 3, 6, 1, 4, 1, 2928, 6, 2, 14, 1, 7, 1, 1, 15), Dsti()).setMaxAccess("readonly")
if mibBuilder.loadTexts: chmgrChanDestDsti.setStatus('current')
mibBuilder.exportSymbols("NETI-CHMGR-MIB", chmgrOConnDcpVersion=chmgrOConnDcpVersion, chmgrTConnStatusLastChanged=chmgrTConnStatusLastChanged, chmgrODescrType=chmgrODescrType, chmgrChanOutgoingIfPort=chmgrChanOutgoingIfPort, chmgrChanSourceMacAddress=chmgrChanSourceMacAddress, chmgrOConnectionGroup=chmgrOConnectionGroup, chmgrSourceRouteHopIndex=chmgrSourceRouteHopIndex, chmgrTConnAdminStatus=chmgrTConnAdminStatus, chmgrTStatDcap1DiscardPackets=chmgrTStatDcap1DiscardPackets, chmgrTStatDcap1ErrorCRC=chmgrTStatDcap1ErrorCRC, chmgrChannelEntry=chmgrChannelEntry, chmgrODescrAcceptableBps=chmgrODescrAcceptableBps, chmgrODescrDestDsti=chmgrODescrDestDsti, chmgrOStatDcap1Load=chmgrOStatDcap1Load, chmgrOChanChannelId=chmgrOChanChannelId, chmgrTChannelEntry=chmgrTChannelEntry, chmgrTChanIndex=chmgrTChanIndex, chmgrTStatDcap1ErrorLods=chmgrTStatDcap1ErrorLods, chmgrChanNextHopMacAddress=chmgrChanNextHopMacAddress, Dst=Dst, chmgrTConnCustomerId=chmgrTConnCustomerId, chmgrOConnSourceAddress=chmgrOConnSourceAddress, chmgrSourceRouteFirstIfPort=chmgrSourceRouteFirstIfPort, chmgrSourceRouteFirstIfBoard=chmgrSourceRouteFirstIfBoard, chmgrODescrAcceptableMbps=chmgrODescrAcceptableMbps, DcapType=DcapType, chmgrChanIncomingIfBoard=chmgrChanIncomingIfBoard, chmgrTStatDcap1Bitrate=chmgrTStatDcap1Bitrate, chmgrOChanErrorMessage=chmgrOChanErrorMessage, chmgrTStatDcap1Octets=chmgrTStatDcap1Octets, chmgrTConnDst=chmgrTConnDst, chmgrODescrPrecedence=chmgrODescrPrecedence, chmgrSourceRouteGroup=chmgrSourceRouteGroup, chmgrTConnectionTimeStamp=chmgrTConnectionTimeStamp, chmgrODescrAcceptableSlots=chmgrODescrAcceptableSlots, chmgrTConnAllocatedSlots=chmgrTConnAllocatedSlots, chmgrTConnOperStatus=chmgrTConnOperStatus, chmgrODescrRequestedBps=chmgrODescrRequestedBps, chmgrODescrDestinationEntry=chmgrODescrDestinationEntry, chmgrTStatDcap1Load=chmgrTStatDcap1Load, chmgrTStatPMReference=chmgrTStatPMReference, chmgrOConnDst=chmgrOConnDst, chmgrTConnDestinationAddress=chmgrTConnDestinationAddress, chmgrTStatDcap1Table=chmgrTStatDcap1Table, chmgrTConnActiveChannel=chmgrTConnActiveChannel, chmgrSourceRouteTimeStamp=chmgrSourceRouteTimeStamp, chmgrOChanReestablish=chmgrOChanReestablish, chmgrODescrDestAdminStatus=chmgrODescrDestAdminStatus, chmgrODescrOneHopSpareCapUtilization=chmgrODescrOneHopSpareCapUtilization, chmgrOConnSourceDsti=chmgrOConnSourceDsti, chmgrChanNextHopDtmAddress=chmgrChanNextHopDtmAddress, chmgrTChanChannelId=chmgrTChanChannelId, chmgrOConnAllocatedSlotsChanged=chmgrOConnAllocatedSlotsChanged, chmgrOConnServiceReference=chmgrOConnServiceReference, chmgrODescriptionTable=chmgrODescriptionTable, chmgrODescriptionGroup=chmgrODescriptionGroup, chmgrTChanCreated=chmgrTChanCreated, chmgrODescriptionEntry=chmgrODescriptionEntry, chmgrSourceRouteRowStatus=chmgrSourceRouteRowStatus, chmgrTConnDcpVersion=chmgrTConnDcpVersion, chmgrSourceRouteIndex=chmgrSourceRouteIndex, chmgrOConnForceSourceRoute=chmgrOConnForceSourceRoute, chmgrODescrDestIndex=chmgrODescrDestIndex, chmgrOConnCustomerId=chmgrOConnCustomerId, chmgrODescrNextDestTableIndex=chmgrODescrNextDestTableIndex, chmgrODescrDestRowStatus=chmgrODescrDestRowStatus, chmgrChanChannelId=chmgrChanChannelId, chmgrODescrCustomerId=chmgrODescrCustomerId, chmgrOChanErrorAddress=chmgrOChanErrorAddress, chmgrOStatDcap1DiscardPackets=chmgrOStatDcap1DiscardPackets, chmgrODescriptionTimeStamp=chmgrODescriptionTimeStamp, chmgrTStatDcap1Packets=chmgrTStatDcap1Packets, chmgrTConnectionTable=chmgrTConnectionTable, chmgrSourceRouteHopRowStatus=chmgrSourceRouteHopRowStatus, chmgrConformance=chmgrConformance, chmgrODescrSuppressAlarms=chmgrODescrSuppressAlarms, ChannelId=ChannelId, chmgrODescrReestablishMethod=chmgrODescrReestablishMethod, chmgrOStatDcap1UtilizedBps=chmgrOStatDcap1UtilizedBps, chmgrSourceRouteTypeOfRoute=chmgrSourceRouteTypeOfRoute, chmgrOStatDcap1DiscardOctets=chmgrOStatDcap1DiscardOctets, chmgrOStatDcap1Entry=chmgrOStatDcap1Entry, chmgrTStatDcap1Entry=chmgrTStatDcap1Entry, chmgrChanOutgoingIfMacAddress=chmgrChanOutgoingIfMacAddress, netiChmgrMIB=netiChmgrMIB, chmgrOConnectionTable=chmgrOConnectionTable, chmgrSourceRouteHopNextIfBoard=chmgrSourceRouteHopNextIfBoard, chmgrOConnStatusLastChanged=chmgrOConnStatusLastChanged, chmgrODescrChanSourceRoute=chmgrODescrChanSourceRoute, chmgrOStatDcap1Table=chmgrOStatDcap1Table, chmgrODescrDestinationTable=chmgrODescrDestinationTable, chmgrODescrMaxInterval=chmgrODescrMaxInterval, chmgrODescrRequestedSlots=chmgrODescrRequestedSlots, chmgrSourceRouteHopAddress=chmgrSourceRouteHopAddress, chmgrChanIsMulticast=chmgrChanIsMulticast, chmgrChanSourceDtmAddress=chmgrChanSourceDtmAddress, chmgrODescrChanRowStatus=chmgrODescrChanRowStatus, chmgrOStatDcap1Bitrate=chmgrOStatDcap1Bitrate, chmgrOConnectionTimeStamp=chmgrOConnectionTimeStamp, chmgrStatisticsGroup=chmgrStatisticsGroup, chmgrODescrChannelEntry=chmgrODescrChannelEntry, chmgrTConnNumberOfChannels=chmgrTConnNumberOfChannels, chmgrOConnDcapType=chmgrOConnDcapType, chmgrTStatDcap1UtilizedBps=chmgrTStatDcap1UtilizedBps, chmgrOConnAdminStatus=chmgrOConnAdminStatus, chmgrODestDestinationAddress=chmgrODestDestinationAddress, chmgrObjects=chmgrObjects, chmgrODescrCapabilities=chmgrODescrCapabilities, chmgrSourceRouteName=chmgrSourceRouteName, chmgrTConnectionEntry=chmgrTConnectionEntry, chmgrTConnSourceAddress=chmgrTConnSourceAddress, chmgrChanCapacity=chmgrChanCapacity, chmgrOConnAllocatedSlots=chmgrOConnAllocatedSlots, chmgrOStatDcap1Octets=chmgrOStatDcap1Octets, PYSNMP_MODULE_ID=netiChmgrMIB, chmgrNotifications=chmgrNotifications, chmgrODescrChannelTable=chmgrODescrChannelTable, chmgrOConnectionEntry=chmgrOConnectionEntry, chmgrTStatPMReferenceEntry=chmgrTStatPMReferenceEntry, chmgrODescrDestAddress=chmgrODescrDestAddress, chmgrChanSourceDsti=chmgrChanSourceDsti, chmgrTStatPMReferenceTable=chmgrTStatPMReferenceTable, chmgrTConnServiceReference=chmgrTConnServiceReference, chmgrChanDestDsti=chmgrChanDestDsti, Dsti=Dsti, chmgrODescrChanSourceRouteIndex=chmgrODescrChanSourceRouteIndex, chmgrChanOutgoingIfBoard=chmgrChanOutgoingIfBoard, chmgrSourceRouteHopNextIfPort=chmgrSourceRouteHopNextIfPort, chmgrODescrServiceReference=chmgrODescrServiceReference, chmgrTConnDcapType=chmgrTConnDcapType, chmgrODestDestinationDsti=chmgrODestDestinationDsti, DcpVersion=DcpVersion, chmgrOChanStatusChanged=chmgrOChanStatusChanged, chmgrSourceRouteTable=chmgrSourceRouteTable, chmgrTDescriptionGroup=chmgrTDescriptionGroup, DtmNode=DtmNode, chmgrODescrRequestedMbps=chmgrODescrRequestedMbps, chmgrOChannelTable=chmgrOChannelTable, chmgrOChanSourceRouteIndex=chmgrOChanSourceRouteIndex, chmgrODescrEstablish=chmgrODescrEstablish, chmgrODescrRequestedDcpVersion=chmgrODescrRequestedDcpVersion, chmgrSourceRouteEntry=chmgrSourceRouteEntry, chmgrOConnReestablish=chmgrOConnReestablish, chmgrChanIncomingIfPort=chmgrChanIncomingIfPort, chmgrODescrIndex=chmgrODescrIndex, chmgrTStatDcap1DiscardOctets=chmgrTStatDcap1DiscardOctets, chmgrTConnAllocatedSlotsChanged=chmgrTConnAllocatedSlotsChanged, chmgrTConnSourceDsti=chmgrTConnSourceDsti, chmgrSourceRouteHopEntry=chmgrSourceRouteHopEntry, chmgrODestinationEntry=chmgrODestinationEntry, chmgrOConnOperStatus=chmgrOConnOperStatus, chmgrChannelGroup=chmgrChannelGroup, chmgrTChannelTable=chmgrTChannelTable, chmgrODescrChanIndex=chmgrODescrChanIndex, chmgrODestinationTable=chmgrODestinationTable, chmgrOChannelEntry=chmgrOChannelEntry, chmgrChannelTable=chmgrChannelTable, chmgrSourceRouteHopTable=chmgrSourceRouteHopTable, chmgrOStatDcap1Packets=chmgrOStatDcap1Packets, chmgrChanDst=chmgrChanDst, chmgrOChanOperStatus=chmgrOChanOperStatus, chmgrOConnODescrIndex=chmgrOConnODescrIndex, chmgrTConnDestinationDsti=chmgrTConnDestinationDsti, chmgrTConnectionGroup=chmgrTConnectionGroup, chmgrOConnIndex=chmgrOConnIndex, chmgrTConnIndex=chmgrTConnIndex, chmgrODescrMinInterval=chmgrODescrMinInterval)
