#
# PySNMP MIB module RADLAN-QOS-CLI-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/RADLAN-QOS-CLI-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 20:40:08 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
ObjectIdentifier, OctetString, Integer = mibBuilder.importSymbols("ASN1", "ObjectIdentifier", "OctetString", "Integer")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
SingleValueConstraint, ValueSizeConstraint, ValueRangeConstraint, ConstraintsIntersection, ConstraintsUnion = mibBuilder.importSymbols("ASN1-REFINEMENT", "SingleValueConstraint", "ValueSizeConstraint", "ValueRangeConstraint", "ConstraintsIntersection", "ConstraintsUnion")
InterfaceIndex, InterfaceIndexOrZero = mibBuilder.importSymbols("IF-MIB", "InterfaceIndex", "InterfaceIndexOrZero")
VlanId, PortList = mibBuilder.importSymbols("Q-BRIDGE-MIB", "VlanId", "PortList")
VlanList4, VlanList3, VlanList2, VlanList1 = mibBuilder.importSymbols("RADLAN-BRIDGEMIBOBJECTS-MIB", "VlanList4", "VlanList3", "VlanList2", "VlanList1")
rnd, Percents = mibBuilder.importSymbols("RADLAN-MIB", "rnd", "Percents")
StatisticsDPType, StatisticsClearActionType = mibBuilder.importSymbols("RADLAN-POLICY-MIB", "StatisticsDPType", "StatisticsClearActionType")
ModuleCompliance, NotificationGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup")
Counter32, NotificationType, Counter64, ObjectIdentity, Unsigned32, Bits, iso, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, ModuleIdentity, Integer32, MibIdentifier, Gauge32, IpAddress = mibBuilder.importSymbols("SNMPv2-SMI", "Counter32", "NotificationType", "Counter64", "ObjectIdentity", "Unsigned32", "Bits", "iso", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "ModuleIdentity", "Integer32", "MibIdentifier", "Gauge32", "IpAddress")
DisplayString, TruthValue, TextualConvention, RowStatus, RowPointer = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TruthValue", "TextualConvention", "RowStatus", "RowPointer")
rlQosCliMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 89, 88))
rlQosCliMib.setRevisions(('2006-02-12 00:00', '2006-02-12 00:00', '2005-03-14 00:00', '2005-02-07 00:00', '2005-01-27 00:00', '2004-11-15 00:00', '2003-09-29 00:00', '2003-09-21 00:00', '2005-04-17 00:00',))
if mibBuilder.loadTexts: rlQosCliMib.setLastUpdated('200604040000Z')
if mibBuilder.loadTexts: rlQosCliMib.setOrganization('Radlan Computer Communications Ltd.')
class ClassOffsetType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13))
    namedValues = NamedValues(("packetStart", 1), ("layer2-start", 2), ("mpls-start", 3), ("layer3-start", 4), ("layer4-start", 5), ("layer5-start", 6), ("vlan", 7), ("in-port", 8), ("out-port", 9), ("vpt", 10), ("ethertype", 11), ("inner-vlan", 12), ("layer3-ipv6-start", 13))

class ClassTupleType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32))
    namedValues = NamedValues(("protocol", 1), ("ip-src", 2), ("ip-dest", 3), ("dscp", 4), ("ip-precedence", 5), ("udp-port-src", 6), ("udp-port-dest", 7), ("tcp-port-src", 8), ("tcp-port-dest", 9), ("mac-src", 10), ("mac-dest", 11), ("vlan", 12), ("in-port", 13), ("out-port", 14), ("general", 15), ("vpt", 16), ("ether-type", 17), ("tcp-flags", 18), ("icmp-type", 19), ("icmp-code", 20), ("igmp-type", 21), ("inner-vlan", 22), ("ipv6-src", 23), ("ipv6-dest", 24), ("udp-port-range-start-src", 25), ("udp-port-range-end-src", 26), ("udp-port-range-start-dest", 27), ("udp-port-range-end-dest", 28), ("tcp-port-range-start-src", 29), ("tcp-port-range-end-src", 30), ("tcp-port-range-start-dest", 31), ("tcp-port-range-end-dest", 32))

class AceActionType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))
    namedValues = NamedValues(("permit", 1), ("deny", 2), ("deny-DisablePort", 3), ("deny-LogInput", 4), ("permit-LogInput", 5))

class AceObjectType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13))
    namedValues = NamedValues(("ip", 1), ("ip-TCP", 2), ("ip-UDP", 3), ("ip-Offset", 4), ("mac", 5), ("mac-Offset", 6), ("ip-ICMP", 7), ("ip-IGMP", 8), ("ipv6", 9), ("ipv6-TCP", 10), ("ipv6-UDP", 11), ("ipv6-Offset", 12), ("ipv6-ICMP", 13))

class AclObjectType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("mac", 1), ("ip", 2), ("ipv6", 3))

class ClassMapType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("matchAll", 1), ("matchAny", 2))

class ClassMapAction(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6))
    namedValues = NamedValues(("none", 1), ("setIP-Precedence", 2), ("setDSCP", 3), ("setQueue", 4), ("setCos", 5), ("trust", 6))

class MarkVlanAction(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("noMark", 1), ("mark", 2), ("markNestedVlan", 3))

class RedirectAction(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
    namedValues = NamedValues(("disabled", 1), ("trap", 2), ("redirectToInterface", 3), ("redirectToAllPorts", 4), ("mirror", 5), ("analyzerPort", 6), ("loopback", 7), ("redirectToPortGroup", 8), ("mirrorAndRedirectToInterface", 9), ("mirrorAndRedirectToInterfacesGroup", 10))

class PolicerType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("single", 1), ("aggregate", 2), ("cascade", 3))

class PolicerAction(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5))
    namedValues = NamedValues(("none", 1), ("drop", 2), ("remark", 3), ("explicit-remark", 4), ("cascadePointer", 5))

class QosGlobalMode(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("disable", 1), ("basic", 2), ("advance", 3))

class QosTrustMode(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("cos", 1), ("dscp", 2), ("cos-dscp", 3))

class BinaryStatus(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("disable", 1), ("enable", 2))

class QueueType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("ef", 1), ("wrr", 2))

class AclDefaultAction(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3))
    namedValues = NamedValues(("deny-all", 1), ("forward-all", 2), ("application-specific", 3))

class InterfaceType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("vlan", 1), ("port", 2))

class StatisticsCntrNumOfBitsType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(32, 48, 64))
    namedValues = NamedValues(("uint32", 32), ("uint48", 48), ("uint64", 64))

class StatisticsCntrType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("statisticsCntrTypeSetDSCP", 1), ("statisticsCntrTypeDeny", 2))

class RlQosTimeBasedAclWeekPeriodicList(TextualConvention, Bits):
    status = 'current'
    namedValues = NamedValues(("monday", 0), ("tuesday", 1), ("wednesday", 2), ("thursday", 3), ("friday", 4), ("saturday", 5), ("sunday", 6))

class RlQosAceTidxActionDropType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2))
    namedValues = NamedValues(("hardDrop", 1), ("softDrop", 2))

class RlQosApplicationDefaultActionType(TextualConvention, Integer32):
    status = 'current'
    subtypeSpec = Integer32.subtypeSpec + ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))
    namedValues = NamedValues(("forward", 1), ("hard-Drop", 2), ("soft-Drop", 3), ("trap", 4))

rlQosCliQosMode = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 1), QosGlobalMode()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosCliQosMode.setStatus('deprecated')
rlQosCliBasicModeCfg = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 2), QosTrustMode()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosCliBasicModeCfg.setStatus('deprecated')
rlQosMaxNumOfAce = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosMaxNumOfAce.setStatus('current')
rlQosOffsetTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 4), )
if mibBuilder.loadTexts: rlQosOffsetTable.setStatus('deprecated')
rlQosOffsetEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 4, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosOffsetIndex"))
if mibBuilder.loadTexts: rlQosOffsetEntry.setStatus('deprecated')
rlQosOffsetIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosOffsetIndex.setStatus('deprecated')
rlQosOffsetType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 2), ClassOffsetType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosOffsetType.setStatus('deprecated')
rlQosOffsetValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 3), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosOffsetValue.setStatus('deprecated')
rlQosOffsetMask = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 255))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosOffsetMask.setStatus('deprecated')
rlQosOffsetPattern = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 255))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosOffsetPattern.setStatus('deprecated')
rlQosOffsetTuplePointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 6), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosOffsetTuplePointer.setStatus('deprecated')
rlQosOffsetStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 4, 1, 7), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosOffsetStatus.setStatus('deprecated')
rlQosTupleTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 5), )
if mibBuilder.loadTexts: rlQosTupleTable.setStatus('current')
rlQosTupleEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 5, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosTupleIndex"))
if mibBuilder.loadTexts: rlQosTupleEntry.setStatus('current')
rlQosTupleIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 5, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosTupleIndex.setStatus('current')
rlQosTupleType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 5, 1, 2), ClassTupleType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTupleType.setStatus('current')
rlQosTupleValue1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 5, 1, 3), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTupleValue1.setStatus('current')
rlQosTupleValue2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 5, 1, 4), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTupleValue2.setStatus('current')
rlQosTupleStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 5, 1, 5), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTupleStatus.setStatus('current')
rlQosAceTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 6), )
if mibBuilder.loadTexts: rlQosAceTable.setStatus('current')
rlQosAceEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 6, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosAceIndex"))
if mibBuilder.loadTexts: rlQosAceEntry.setStatus('current')
rlQosAceIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosAceIndex.setStatus('current')
rlQosAceAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 2), AceActionType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceAction.setStatus('current')
rlQosAceType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 3), AceObjectType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceType.setStatus('current')
rlQosAceTuple1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 4), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple1.setStatus('current')
rlQosAceTuple2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 5), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple2.setStatus('current')
rlQosAceTuple3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 6), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple3.setStatus('current')
rlQosAceTuple4 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple4.setStatus('current')
rlQosAceTuple5 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 8), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple5.setStatus('current')
rlQosAceTuple6 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 9), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple6.setStatus('current')
rlQosAceTuple7 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 10), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple7.setStatus('current')
rlQosAceTuple8 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 11), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTuple8.setStatus('current')
rlQosAceAccount = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 12), BinaryStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceAccount.setStatus('current')
rlQosAceStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 6, 1, 13), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceStatus.setStatus('current')
rlQosAclTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 7), )
if mibBuilder.loadTexts: rlQosAclTable.setStatus('current')
rlQosAclEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 7, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosAclIndex"))
if mibBuilder.loadTexts: rlQosAclEntry.setStatus('current')
rlQosAclIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 7, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosAclIndex.setStatus('current')
rlQosAclName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 7, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclName.setStatus('current')
rlQosAclType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 7, 1, 3), AclObjectType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclType.setStatus('current')
rlQosAclStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 7, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclStatus.setStatus('current')
rlQosAclNumOfAces = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 7, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAclNumOfAces.setStatus('current')
rlQosAclAceRefTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 8), )
if mibBuilder.loadTexts: rlQosAclAceRefTable.setStatus('current')
rlQosAclAceRefEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 8, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosAclAceRefAcePointer"))
if mibBuilder.loadTexts: rlQosAclAceRefEntry.setStatus('current')
rlQosAclAceRefAcePointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 8, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosAclAceRefAcePointer.setStatus('current')
rlQosAclAceRefAclPointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 8, 1, 2), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclAceRefAclPointer.setStatus('current')
rlQosAclAceRefStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 8, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclAceRefStatus.setStatus('current')
rlQosClassMapTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 9), )
if mibBuilder.loadTexts: rlQosClassMapTable.setStatus('current')
rlQosClassMapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 9, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosClassMapIndex"))
if mibBuilder.loadTexts: rlQosClassMapEntry.setStatus('current')
rlQosClassMapIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosClassMapIndex.setStatus('current')
rlQosClassMapName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapName.setStatus('current')
rlQosClassMapType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 3), ClassMapType().clone(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapType.setStatus('current')
rlQosClassMapAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 4), ClassMapAction().clone(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapAction.setStatus('current')
rlQosClassMapMarkValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 5), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapMarkValue.setStatus('current')
rlQosClassMapPolicer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 6), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapPolicer.setStatus('current')
rlQosClassMapMatch1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapMatch1.setStatus('current')
rlQosClassMapMatch2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 8), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapMatch2.setStatus('current')
rlQosClassMapMarkVlan = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 9), MarkVlanAction().clone(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapMarkVlan.setStatus('current')
rlQosClassMapNewVlan = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 4095))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapNewVlan.setStatus('current')
rlQosClassMapRedirectAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 11), RedirectAction().clone('disabled')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapRedirectAction.setStatus('current')
rlQosClassMapDestInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 12), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapDestInterface.setStatus('current')
rlQosClassMapStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 13), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapStatus.setStatus('current')
rlQosClassMapMatch3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 14), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapMatch3.setStatus('current')
rlQosClassMapTrapId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 15), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapTrapId.setStatus('current')
rlQosClassMapCounterEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 16), TruthValue().clone('false')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapCounterEnable.setStatus('current')
rlQosClassMapTunnelIdx = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 9, 1, 17), Unsigned32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosClassMapTunnelIdx.setStatus('current')
rlQosPolicerTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 10), )
if mibBuilder.loadTexts: rlQosPolicerTable.setStatus('current')
rlQosPolicerEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 10, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPolicerIndex"))
if mibBuilder.loadTexts: rlQosPolicerEntry.setStatus('current')
rlQosPolicerIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosPolicerIndex.setStatus('current')
rlQosPolicerName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerName.setStatus('current')
rlQosPolicerType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 3), PolicerType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerType.setStatus('current')
rlQosPolicerCir = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 4), Unsigned32()).setUnits('kbps').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerCir.setStatus('current')
rlQosPolicerCbs = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 5), Unsigned32()).setUnits('bytes').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerCbs.setStatus('current')
rlQosPolicerAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 6), PolicerAction()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerAction.setStatus('current')
rlQosPolicerCasPointerRemVal = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerCasPointerRemVal.setStatus('current')
rlQosPolicerStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 8), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerStatus.setStatus('current')
rlQosPolicerPir = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 9), Unsigned32()).setUnits('kbps').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerPir.setStatus('current')
rlQosPolicerPbs = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 10), Unsigned32()).setUnits('bytes').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerPbs.setStatus('current')
rlQosPolicerPeakAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 10, 1, 11), PolicerAction()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicerPeakAction.setStatus('current')
rlQosPolicyMapTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 11), )
if mibBuilder.loadTexts: rlQosPolicyMapTable.setStatus('current')
rlQosPolicyMapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 11, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPolicyMapIndex"))
if mibBuilder.loadTexts: rlQosPolicyMapEntry.setStatus('current')
rlQosPolicyMapIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 11, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosPolicyMapIndex.setStatus('current')
rlQosPolicyMapName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 11, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyMapName.setStatus('current')
rlQosPolicyMapStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 11, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyMapStatus.setStatus('current')
rlQosPolicyClassRefTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 12), )
if mibBuilder.loadTexts: rlQosPolicyClassRefTable.setStatus('current')
rlQosPolicyClassRefEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 12, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPolicyClassRefClassPointer"))
if mibBuilder.loadTexts: rlQosPolicyClassRefEntry.setStatus('current')
rlQosPolicyClassRefClassPointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 12, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosPolicyClassRefClassPointer.setStatus('current')
rlQosPolicyClassRefPolicyPointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 12, 1, 2), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyClassRefPolicyPointer.setStatus('current')
rlQosPolicyClassRefStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 12, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyClassRefStatus.setStatus('current')
rlQosIfPolicyTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 13), )
if mibBuilder.loadTexts: rlQosIfPolicyTable.setStatus('current')
rlQosIfPolicyEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 13, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlIfIndex"), (0, "RADLAN-QOS-CLI-MIB", "rlIfType"))
if mibBuilder.loadTexts: rlQosIfPolicyEntry.setStatus('current')
rlIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 1), Integer32())
if mibBuilder.loadTexts: rlIfIndex.setStatus('current')
rlIfType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 2), InterfaceType())
if mibBuilder.loadTexts: rlIfType.setStatus('current')
rlQosIfPolicyMapPointerIn = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 3), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfPolicyMapPointerIn.setStatus('current')
rlQosIfPolicyMapPointerOut = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 4), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfPolicyMapPointerOut.setStatus('current')
rlQosIfTrustActive = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 5), BinaryStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfTrustActive.setStatus('current')
rlQosPortShaperStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 6), BinaryStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPortShaperStatus.setStatus('current')
rlQosCirPortShaper = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 7), Integer32()).setUnits('bps').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirPortShaper.setStatus('current')
rlQosCbsPortShaper = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 8), Integer32()).setUnits('bytes').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsPortShaper.setStatus('current')
rlQosIfProfilePointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 9), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfProfilePointer.setStatus('current')
rlQosQueueProfilePointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 10), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosQueueProfilePointer.setStatus('current')
rlQosQueueShapeProfilePointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 11), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosQueueShapeProfilePointer.setStatus('current')
rlQosAclDefaultAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 12), AclDefaultAction()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclDefaultAction.setStatus('current')
rlQosIfPolicyMapStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 13), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfPolicyMapStatus.setStatus('current')
rlQosIfAclIn = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 14), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfAclIn.setStatus('current')
rlQosIfAclOut = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 15), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfAclOut.setStatus('current')
rlQosIfPolicerIn = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 16), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfPolicerIn.setStatus('current')
rlQosPortRateLimitStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 17), BinaryStatus().clone('disable')).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPortRateLimitStatus.setStatus('current')
rlQosCirPortRateLimit = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 18), Integer32()).setUnits('bps').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirPortRateLimit.setStatus('current')
rlQosCbsPortRateLimit = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 19), Integer32()).setUnits('bytes').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsPortRateLimit.setStatus('current')
rlQosIfIpv6AclIn = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 20), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfIpv6AclIn.setStatus('current')
rlQosIfIpv6AclOut = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 21), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfIpv6AclOut.setStatus('current')
rlQosAclDefaultActionOut = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 13, 1, 22), AclDefaultAction()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAclDefaultActionOut.setStatus('current')
rlQosIfProfileCfgTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 14), )
if mibBuilder.loadTexts: rlQosIfProfileCfgTable.setStatus('current')
rlQosIfProfileCfgEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 14, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlIfProfileName"), (0, "RADLAN-QOS-CLI-MIB", "rlQosQueueId"))
if mibBuilder.loadTexts: rlQosIfProfileCfgEntry.setStatus('current')
rlIfProfileName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32)))
if mibBuilder.loadTexts: rlIfProfileName.setStatus('current')
rlQosQueueId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8)))
if mibBuilder.loadTexts: rlQosQueueId.setStatus('current')
rlQosTdThersholdDp0 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTdThersholdDp0.setStatus('current')
rlQosTdThersholdDp1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTdThersholdDp1.setStatus('current')
rlQosTdThersholdDp2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTdThersholdDp2.setStatus('current')
rlQosRedMinDp0 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedMinDp0.setStatus('current')
rlQosRedMaxDp0 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedMaxDp0.setStatus('current')
rlQosRedProbDp0 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 8), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedProbDp0.setStatus('current')
rlQosRedMinDp1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 9), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedMinDp1.setStatus('current')
rlQosRedMaxDp1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 10), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedMaxDp1.setStatus('current')
rlQosRedProbDp1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 11), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedProbDp1.setStatus('current')
rlQosRedMinDp2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 12), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedMinDp2.setStatus('current')
rlQosRedMaxDp2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 13), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setUnits('percent').setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedMaxDp2.setStatus('current')
rlQosRedProbDp2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 14), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedProbDp2.setStatus('current')
rlQosRedQweight = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 15), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRedQweight.setStatus('current')
rlQosIfprofileStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 14, 1, 16), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosIfprofileStatus.setStatus('current')
rlQosDscpMutationTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 15), )
if mibBuilder.loadTexts: rlQosDscpMutationTable.setStatus('current')
rlQosDscpMutationEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 15, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosOldDscp"))
if mibBuilder.loadTexts: rlQosDscpMutationEntry.setStatus('current')
rlQosOldDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 15, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63)))
if mibBuilder.loadTexts: rlQosOldDscp.setStatus('current')
rlQosNewDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 15, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosNewDscp.setStatus('current')
rlQosDscpRemarkTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 16), )
if mibBuilder.loadTexts: rlQosDscpRemarkTable.setStatus('current')
rlQosDscpRemarkEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 16, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosRmOldDscp"))
if mibBuilder.loadTexts: rlQosDscpRemarkEntry.setStatus('current')
rlQosRmOldDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 16, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63)))
if mibBuilder.loadTexts: rlQosRmOldDscp.setStatus('current')
rlQosRmNewDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 16, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRmNewDscp.setStatus('current')
rlQosRmNewExceedDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 16, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosRmNewExceedDscp.setStatus('current')
rlQosCosQueueTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 17), )
if mibBuilder.loadTexts: rlQosCosQueueTable.setStatus('current')
rlQosCosQueueEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 17, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosCosIndex"))
if mibBuilder.loadTexts: rlQosCosQueueEntry.setStatus('current')
rlQosCosIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 17, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 7)))
if mibBuilder.loadTexts: rlQosCosIndex.setStatus('current')
rlQosCosQueueId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 17, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCosQueueId.setStatus('current')
rlQosDscpQueueTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 18), )
if mibBuilder.loadTexts: rlQosDscpQueueTable.setStatus('current')
rlQosDscpQueueEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 18, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosDscpIndex"))
if mibBuilder.loadTexts: rlQosDscpQueueEntry.setStatus('current')
rlQosDscpIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 18, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63)))
if mibBuilder.loadTexts: rlQosDscpIndex.setStatus('current')
rlQosQueueNum = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 18, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosQueueNum.setStatus('current')
rlQosTcpPortQueueTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 19), )
if mibBuilder.loadTexts: rlQosTcpPortQueueTable.setStatus('current')
rlQosTcpPortQueueEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 19, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosTcpPort"))
if mibBuilder.loadTexts: rlQosTcpPortQueueEntry.setStatus('current')
rlQosTcpPort = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 19, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosTcpPort.setStatus('current')
rlQosTcpQueueValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 19, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTcpQueueValue.setStatus('current')
rlQosTcpPortQueueStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 19, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTcpPortQueueStatus.setStatus('current')
rlQosUdpPortQueueTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 20), )
if mibBuilder.loadTexts: rlQosUdpPortQueueTable.setStatus('current')
rlQosUdpPortQueueEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 20, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosUdpPort"))
if mibBuilder.loadTexts: rlQosUdpPortQueueEntry.setStatus('current')
rlQosUdpPort = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 20, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosUdpPort.setStatus('current')
rlQosUdpQueueValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 20, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosUdpQueueValue.setStatus('current')
rlQosUdpPortQueueStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 20, 1, 3), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosUdpPortQueueStatus.setStatus('current')
rlQosEfManageTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 21), )
if mibBuilder.loadTexts: rlQosEfManageTable.setStatus('current')
rlQosEfManageEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 21, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosEfQueueId"))
if mibBuilder.loadTexts: rlQosEfManageEntry.setStatus('current')
rlQosEfQueueId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 21, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8)))
if mibBuilder.loadTexts: rlQosEfQueueId.setStatus('current')
rlQosEfState = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 21, 1, 2), BinaryStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosEfState.setStatus('current')
rlQosEfPriority = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 21, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosEfPriority.setStatus('current')
rlQosQueueProfileTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 22), )
if mibBuilder.loadTexts: rlQosQueueProfileTable.setStatus('current')
rlQosQueueProfileEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 22, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQueueProfileName"))
if mibBuilder.loadTexts: rlQosQueueProfileEntry.setStatus('current')
rlQueueProfileName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32)))
if mibBuilder.loadTexts: rlQueueProfileName.setStatus('current')
rlQosTypeQueue1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 2), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue1.setStatus('current')
rlQosValueQueue1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 3), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue1.setStatus('current')
rlQosTypeQueue2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 4), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue2.setStatus('current')
rlQosValueQueue2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 5), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue2.setStatus('current')
rlQosTypeQueue3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 6), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue3.setStatus('current')
rlQosValueQueue3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue3.setStatus('current')
rlQosTypeQueue4 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 8), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue4.setStatus('current')
rlQosValueQueue4 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 9), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue4.setStatus('current')
rlQosTypeQueue5 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 10), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue5.setStatus('current')
rlQosValueQueue5 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 11), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue5.setStatus('current')
rlQosTypeQueue6 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 12), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue6.setStatus('current')
rlQosValueQueue6 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 13), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue6.setStatus('current')
rlQosTypeQueue7 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 14), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue7.setStatus('current')
rlQosValueQueue7 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 15), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue7.setStatus('current')
rlQosTypeQueue8 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 16), QueueType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosTypeQueue8.setStatus('current')
rlQosValueQueue8 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 17), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosValueQueue8.setStatus('current')
rlQosQueueProfileStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 18), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosQueueProfileStatus.setStatus('current')
rlQosNumOfIfConnections = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 22, 1, 19), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosNumOfIfConnections.setStatus('current')
rlQosQueueShapeProfileTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 23), )
if mibBuilder.loadTexts: rlQosQueueShapeProfileTable.setStatus('current')
rlQosQueueShapeProfileEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 23, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosQueueShapeIndex"))
if mibBuilder.loadTexts: rlQosQueueShapeProfileEntry.setStatus('current')
rlQosQueueShapeIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosQueueShapeIndex.setStatus('current')
rlQosCirQueue1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 2), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue1.setStatus('current')
rlQosCbsQueue1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 3), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue1.setStatus('current')
rlQosCirQueue2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 4), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue2.setStatus('current')
rlQosCbsQueue2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 5), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue2.setStatus('current')
rlQosCirQueue3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 6), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue3.setStatus('current')
rlQosCbsQueue3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue3.setStatus('current')
rlQosCirQueue4 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 8), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue4.setStatus('current')
rlQosCbsQueue4 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 9), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue4.setStatus('current')
rlQosCirQueue5 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 10), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue5.setStatus('current')
rlQosCbsQueue5 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 11), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue5.setStatus('current')
rlQosCirQueue6 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 12), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue6.setStatus('current')
rlQosCbsQueue6 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 13), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue6.setStatus('current')
rlQosCirQueue7 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 14), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue7.setStatus('current')
rlQosCbsQueue7 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 15), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue7.setStatus('current')
rlQosCirQueue8 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 16), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCirQueue8.setStatus('current')
rlQosCbsQueue8 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 17), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosCbsQueue8.setStatus('current')
rlQosQueueShapeProfileStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 23, 1, 18), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosQueueShapeProfileStatus.setStatus('current')
rlQosAclCounterTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 24), )
if mibBuilder.loadTexts: rlQosAclCounterTable.setStatus('current')
rlQosAclCounterEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 24, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosAclCounterInterface"), (0, "RADLAN-QOS-CLI-MIB", "rlQosAclCounterAclIndex"), (0, "RADLAN-QOS-CLI-MIB", "rlQosAclCounterAceIndex"))
if mibBuilder.loadTexts: rlQosAclCounterEntry.setStatus('current')
rlQosAclCounterInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 24, 1, 1), InterfaceIndex()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAclCounterInterface.setStatus('current')
rlQosAclCounterAclIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 24, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAclCounterAclIndex.setStatus('current')
rlQosAclCounterAceIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 24, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAclCounterAceIndex.setStatus('current')
rlQosAclCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 24, 1, 4), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAclCounterValue.setStatus('current')
rlQosFreeIndexesTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 25), )
if mibBuilder.loadTexts: rlQosFreeIndexesTable.setStatus('current')
rlQosFreeIndexesEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 25, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosFreeIndexesTableId"))
if mibBuilder.loadTexts: rlQosFreeIndexesEntry.setStatus('current')
rlQosFreeIndexesTableId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 25, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8))).clone(namedValues=NamedValues(("tuple", 1), ("offset", 2), ("ace", 3), ("acl", 4), ("class", 5), ("policy", 6), ("policer", 7), ("shaper", 8)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosFreeIndexesTableId.setStatus('current')
rlQosFreeIndexesValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 25, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosFreeIndexesValue.setStatus('current')
rlQosNamesToIndexesTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 26), )
if mibBuilder.loadTexts: rlQosNamesToIndexesTable.setStatus('current')
rlQosNamesToIndexesEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 26, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosNamesToIndexesTableId"), (0, "RADLAN-QOS-CLI-MIB", "rlQosNamesToIndexesName"))
if mibBuilder.loadTexts: rlQosNamesToIndexesEntry.setStatus('current')
rlQosNamesToIndexesTableId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 26, 1, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4))).clone(namedValues=NamedValues(("acl", 1), ("class", 2), ("policy", 3), ("policer", 4))))
if mibBuilder.loadTexts: rlQosNamesToIndexesTableId.setStatus('current')
rlQosNamesToIndexesName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 26, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32)))
if mibBuilder.loadTexts: rlQosNamesToIndexesName.setStatus('current')
rlQosNamesToIndexesValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 26, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosNamesToIndexesValue.setStatus('current')
rlQosStackControlQueue = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 27), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosStackControlQueue.setStatus('current')
rlQosStackControlCos = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 28), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosStackControlCos.setStatus('current')
rlQosCosQueueDefaultMapTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 29), )
if mibBuilder.loadTexts: rlQosCosQueueDefaultMapTable.setStatus('current')
rlQosCosQueueDefaultMapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 29, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosCosQueueDefaultMapVpt"))
if mibBuilder.loadTexts: rlQosCosQueueDefaultMapEntry.setStatus('current')
rlQosCosQueueDefaultMapVpt = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 29, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 7))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosCosQueueDefaultMapVpt.setStatus('current')
rlQosCosQueueDefaultMapQueueId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 29, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosCosQueueDefaultMapQueueId.setStatus('current')
rlQosPredefBlockAclTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 30), )
if mibBuilder.loadTexts: rlQosPredefBlockAclTable.setStatus('current')
rlQosPredefBlockAclEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 30, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPredefBlockAclIfIndex"), (0, "RADLAN-QOS-CLI-MIB", "rlQosPredefBlockAclIfType"))
if mibBuilder.loadTexts: rlQosPredefBlockAclEntry.setStatus('current')
rlQosPredefBlockAclIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 30, 1, 1), InterfaceIndex())
if mibBuilder.loadTexts: rlQosPredefBlockAclIfIndex.setStatus('current')
rlQosPredefBlockAclIfType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 30, 1, 2), InterfaceType())
if mibBuilder.loadTexts: rlQosPredefBlockAclIfType.setStatus('current')
rlQosPredefBlockAclMask = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 30, 1, 3), OctetString().subtype(subtypeSpec=ValueSizeConstraint(1, 1)).setFixedLength(1)).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPredefBlockAclMask.setStatus('current')
rlQosPredefBlockAclStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 30, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPredefBlockAclStatus.setStatus('current')
rlQosAceTidxTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 31), )
if mibBuilder.loadTexts: rlQosAceTidxTable.setStatus('current')
rlQosAceTidxEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 31, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosAceTidxAclIndex"), (0, "RADLAN-QOS-CLI-MIB", "rlQosAceTidxIndex"))
if mibBuilder.loadTexts: rlQosAceTidxEntry.setStatus('current')
rlQosAceTidxAclIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosAceTidxAclIndex.setStatus('current')
rlQosAceTidxIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 2), Integer32())
if mibBuilder.loadTexts: rlQosAceTidxIndex.setStatus('current')
rlQosAceTidxAction = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 3), AceActionType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxAction.setStatus('current')
rlQosAceTidxType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 4), AceObjectType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxType.setStatus('current')
rlQosAceTidxTuple1 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 5), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple1.setStatus('current')
rlQosAceTidxTuple2 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 6), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple2.setStatus('current')
rlQosAceTidxTuple3 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 7), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple3.setStatus('current')
rlQosAceTidxTuple4 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 8), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple4.setStatus('current')
rlQosAceTidxTuple5 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 9), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple5.setStatus('current')
rlQosAceTidxTuple6 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 10), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple6.setStatus('current')
rlQosAceTidxTuple7 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 11), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple7.setStatus('current')
rlQosAceTidxTuple8 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 12), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple8.setStatus('current')
rlQosAceTidxAccount = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 13), BinaryStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxAccount.setStatus('current')
rlQosAceTidxStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 14), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxStatus.setStatus('current')
rlQosAceTidxTimeRange = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 15), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTimeRange.setStatus('current')
rlQosAceTidxTimeRangeIsActive = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 16), TruthValue()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAceTidxTimeRangeIsActive.setStatus('current')
rlQosAceTidxTuple9 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 17), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple9.setStatus('current')
rlQosAceTidxTuple10 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 18), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple10.setStatus('current')
rlQosAceTidxTuple11 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 19), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxTuple11.setStatus('current')
rlQosAceTidxActionDropType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 31, 1, 20), RlQosAceTidxActionDropType()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosAceTidxActionDropType.setStatus('current')
rlQosMibVersion = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 32), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosMibVersion.setStatus('current')
rlQosDscpQueueDefaultMapTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 33), )
if mibBuilder.loadTexts: rlQosDscpQueueDefaultMapTable.setStatus('current')
rlQosDscpQueueDefaultMapEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 33, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosDscpQueueDefaultMapDscp"))
if mibBuilder.loadTexts: rlQosDscpQueueDefaultMapEntry.setStatus('current')
rlQosDscpQueueDefaultMapDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 33, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosDscpQueueDefaultMapDscp.setStatus('current')
rlQosDscpQueueDefaultMapQueueId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 33, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosDscpQueueDefaultMapQueueId.setStatus('current')
rlQosDscpToDpTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 34), )
if mibBuilder.loadTexts: rlQosDscpToDpTable.setStatus('current')
rlQosDscpToDpEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 34, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosDscp"))
if mibBuilder.loadTexts: rlQosDscpToDpEntry.setStatus('current')
rlQosDscp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 34, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 63)))
if mibBuilder.loadTexts: rlQosDscp.setStatus('current')
rlQosDp = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 34, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2))).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosDp.setStatus('current')
rlQosStatistics = MibIdentifier((1, 3, 6, 1, 4, 1, 89, 88, 35))
rlQosPortPolicyStatisticsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 35, 1), )
if mibBuilder.loadTexts: rlQosPortPolicyStatisticsTable.setStatus('current')
rlQosPortPolicyStatisticsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 35, 1, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlIfIndex"), (0, "RADLAN-QOS-CLI-MIB", "rlIfType"), (0, "RADLAN-QOS-CLI-MIB", "rlQosPortPolicyStatisticsCntrType"))
if mibBuilder.loadTexts: rlQosPortPolicyStatisticsEntry.setStatus('current')
rlQosPortPolicyStatisticsCntrType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 1, 1, 1), StatisticsCntrType()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosPortPolicyStatisticsCntrType.setStatus('current')
rlQosPortPolicyStatisticsCntrNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 1, 1, 2), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosPortPolicyStatisticsCntrNumOfBits.setStatus('current')
rlQosPortPolicyStatisticsEnableCounting = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 1, 1, 3), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosPortPolicyStatisticsEnableCounting.setStatus('current')
rlQosPortPolicyStatisticsCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 1, 1, 4), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosPortPolicyStatisticsCounterValue.setStatus('current')
rlQosSinglePolicerStatisticsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 35, 2), )
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsTable.setStatus('current')
rlQosSinglePolicerStatisticsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 35, 2, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlIfIndex"), (0, "RADLAN-QOS-CLI-MIB", "rlQosPolicerIndex"))
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsEntry.setStatus('current')
rlQosSinglePolicerStatisticsInProfileCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 2, 1, 1), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsInProfileCounterValue.setStatus('current')
rlQosSinglePolicerStatisticsInProfileCntrNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 2, 1, 2), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsInProfileCntrNumOfBits.setStatus('current')
rlQosSinglePolicerStatisticsOutProfileCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 2, 1, 3), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsOutProfileCounterValue.setStatus('current')
rlQosSinglePolicerStatisticsOutProfileCntrNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 2, 1, 4), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsOutProfileCntrNumOfBits.setStatus('current')
rlQosSinglePolicerStatisticsStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 2, 1, 5), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosSinglePolicerStatisticsStatus.setStatus('current')
rlQosAggregatePolicerStatisticsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 35, 3), )
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsTable.setStatus('current')
rlQosAggregatePolicerStatisticsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 35, 3, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPolicerIndex"))
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsEntry.setStatus('current')
rlQosAggregatePolicerStatisticsInProfileCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 3, 1, 1), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsInProfileCounterValue.setStatus('current')
rlQosAggregatePolicerStatisticsInProfileCntrNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 3, 1, 2), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsInProfileCntrNumOfBits.setStatus('current')
rlQosAggregatePolicerStatisticsOutProfileCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 3, 1, 3), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsOutProfileCounterValue.setStatus('current')
rlQosAggregatePolicerStatisticsOutProfileCntrNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 3, 1, 4), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsOutProfileCntrNumOfBits.setStatus('current')
rlQosAggregatePolicerStatisticsStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 3, 1, 5), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosAggregatePolicerStatisticsStatus.setStatus('current')
rlQosOutQueueStatisticsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 35, 4), )
if mibBuilder.loadTexts: rlQosOutQueueStatisticsTable.setStatus('current')
rlQosOutQueueStatisticsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosOutQueueStatisticsCountrID"))
if mibBuilder.loadTexts: rlQosOutQueueStatisticsEntry.setStatus('current')
rlQosOutQueueStatisticsCountrID = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 1), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsCountrID.setStatus('current')
rlQosOutQueueStatisticsIfIndexList = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 2), PortList()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsIfIndexList.setStatus('current')
rlQosOutQueueStatisticsPortAll = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 3), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsPortAll.setStatus('current')
rlQosOutQueueStatisticsVlan = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 4), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsVlan.setStatus('current')
rlQosOutQueueStatisticsVlanAll = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 5), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsVlanAll.setStatus('current')
rlQosOutQueueStatisticsQueue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 6), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 8))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsQueue.setStatus('current')
rlQosOutQueueStatisticsQueueAll = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 7), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsQueueAll.setStatus('current')
rlQosOutQueueStatisticsDP = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 8), StatisticsDPType()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsDP.setStatus('current')
rlQosOutQueueStatisticsDPAll = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 9), TruthValue()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsDPAll.setStatus('current')
rlQosOutQueueStatisticsCounterTailDropValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 10), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsCounterTailDropValue.setStatus('current')
rlQosOutQueueStatisticsCounterAllValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 11), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsCounterAllValue.setStatus('current')
rlQosOutQueueStatisticsCntrNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 12), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsCntrNumOfBits.setStatus('current')
rlQosOutQueueStatisticsStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 4, 1, 13), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosOutQueueStatisticsStatus.setStatus('current')
rlQosGlobalStatisticsCntrsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 35, 5), )
if mibBuilder.loadTexts: rlQosGlobalStatisticsCntrsTable.setStatus('current')
rlQosGlobalStatisticsCntrsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 35, 5, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosGlobalStatisticsCntrsType"))
if mibBuilder.loadTexts: rlQosGlobalStatisticsCntrsEntry.setStatus('current')
rlQosGlobalStatisticsCntrsType = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 5, 1, 1), StatisticsCntrType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosGlobalStatisticsCntrsType.setStatus('current')
rlQosGlobalStatisticsCntrsNumOfBits = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 5, 1, 2), StatisticsCntrNumOfBitsType()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosGlobalStatisticsCntrsNumOfBits.setStatus('current')
rlQosGlobalStatisticsCntrsCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 5, 1, 3), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosGlobalStatisticsCntrsCounterValue.setStatus('current')
rlQosGlobalStatisticsStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 35, 5, 1, 4), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosGlobalStatisticsStatus.setStatus('current')
rlQosClearCounters = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 35, 6), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosClearCounters.setStatus('current')
rlQosClassifierUtilization = MibIdentifier((1, 3, 6, 1, 4, 1, 89, 88, 36))
rlQosClassifierUtilizationTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 36, 1), )
if mibBuilder.loadTexts: rlQosClassifierUtilizationTable.setStatus('current')
rlQosClassifierUtilizationEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 36, 1, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosClassifierUtilizationUnitId"))
if mibBuilder.loadTexts: rlQosClassifierUtilizationEntry.setStatus('current')
rlQosClassifierUtilizationUnitId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 36, 1, 1, 1), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(1, 4294967295)))
if mibBuilder.loadTexts: rlQosClassifierUtilizationUnitId.setStatus('current')
rlQosClassifierUtilizationPercent = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 36, 1, 1, 2), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierUtilizationPercent.setStatus('current')
rlQosClassifierUtilizationRulesNumber = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 36, 1, 1, 3), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierUtilizationRulesNumber.setStatus('current')
rlQosClassifierUtilizationFreeRulesNumber = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 36, 1, 1, 4), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierUtilizationFreeRulesNumber.setStatus('current')
rlQosClassifierUtilizationSystem = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 36, 2), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 100))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierUtilizationSystem.setStatus('current')
rlQosClassifierRulesNumberUtilizationSystem = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 36, 3), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierRulesNumberUtilizationSystem.setStatus('current')
rlQosClassifierFreeRulesNumUtilizationSystem = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 36, 4), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierFreeRulesNumUtilizationSystem.setStatus('current')
rlQosClassifierMaxRulesNumberUtilizationSystem = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 36, 5), Unsigned32().subtype(subtypeSpec=ValueRangeConstraint(0, 4294967295))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassifierMaxRulesNumberUtilizationSystem.setStatus('current')
rlQosPortToProfileMappingTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 37), )
if mibBuilder.loadTexts: rlQosPortToProfileMappingTable.setStatus('current')
rlQosPortToProfileMappingEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 37, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPort"))
if mibBuilder.loadTexts: rlQosPortToProfileMappingEntry.setStatus('current')
rlQosPort = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 37, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosPort.setStatus('current')
rlQosProfileName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 37, 1, 2), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosProfileName.setStatus('current')
rlQosCPUSafeGuardEnable = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 38), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosCPUSafeGuardEnable.setStatus('current')
rlQosPolicyClassPriorityRefTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 39), )
if mibBuilder.loadTexts: rlQosPolicyClassPriorityRefTable.setStatus('current')
rlQosPolicyClassPriorityRefEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 39, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosPolicyClassPriorityRefPriority"), (0, "RADLAN-QOS-CLI-MIB", "rlQosPolicyClassPriorityRefClassPointer"))
if mibBuilder.loadTexts: rlQosPolicyClassPriorityRefEntry.setStatus('current')
rlQosPolicyClassPriorityRefPriority = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 39, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosPolicyClassPriorityRefPriority.setStatus('current')
rlQosPolicyClassPriorityRefClassPointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 39, 1, 2), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyClassPriorityRefClassPointer.setStatus('current')
rlQosPolicyClassPriorityRefPolicyPointer = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 39, 1, 3), Integer32()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyClassPriorityRefPolicyPointer.setStatus('current')
rlQosPolicyClassPriorityRefStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 39, 1, 4), RowStatus()).setMaxAccess("readcreate")
if mibBuilder.loadTexts: rlQosPolicyClassPriorityRefStatus.setStatus('current')
rlQosDenyAceStatisticsTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 42), )
if mibBuilder.loadTexts: rlQosDenyAceStatisticsTable.setStatus('current')
rlQosDenyAceStatisticsEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 42, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosDenyAceStatisticsIfIndex"))
if mibBuilder.loadTexts: rlQosDenyAceStatisticsEntry.setStatus('current')
rlQosDenyAceStatisticsIfIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 42, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosDenyAceStatisticsIfIndex.setStatus('current')
rlQosDenyAceStatisticsIfCounter = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 42, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosDenyAceStatisticsIfCounter.setStatus('current')
rlQosDenyAceStatisticsOtherFlowCounter = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 43), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosDenyAceStatisticsOtherFlowCounter.setStatus('current')
rlQosDenyAceStatisticsClearIfCounters = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 44), InterfaceIndexOrZero()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosDenyAceStatisticsClearIfCounters.setStatus('current')
rlQosDenyAceStatisticsClearOtherFlowCounter = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 45), Integer32()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosDenyAceStatisticsClearOtherFlowCounter.setStatus('current')
rlQosModeGlobalCfgTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 46), )
if mibBuilder.loadTexts: rlQosModeGlobalCfgTable.setStatus('current')
rlQosModeGlobalCfgEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 46, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosGlobalIndex"))
if mibBuilder.loadTexts: rlQosModeGlobalCfgEntry.setStatus('current')
rlQosGlobalIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosGlobalIndex.setStatus('current')
rlQosGlobalQoSMode = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 2), QosGlobalMode()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosGlobalQoSMode.setStatus('current')
rlQosBasicGlobalTrustMode = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 3), QosTrustMode()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosBasicGlobalTrustMode.setStatus('current')
rlQosAdvcGlobalTrustMode = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 4), QosTrustMode()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosAdvcGlobalTrustMode.setStatus('current')
rlQoSPortTrustAdvancedMode = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 5), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQoSPortTrustAdvancedMode.setStatus('current')
rlQosDscpMutationEnable = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 6), TruthValue().clone('false')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosDscpMutationEnable.setStatus('current')
rlQosModeGlobalCfgStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 46, 1, 7), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQosModeGlobalCfgStatus.setStatus('current')
rlQosClassMapCounterTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 47), )
if mibBuilder.loadTexts: rlQosClassMapCounterTable.setStatus('current')
rlQosClassMapCounterEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 47, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosClassMapIndex"))
if mibBuilder.loadTexts: rlQosClassMapCounterEntry.setStatus('current')
rlQosClassMapCounterValue = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 47, 1, 2), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosClassMapCounterValue.setStatus('current')
rlQosApplicationTrapIdTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 48), )
if mibBuilder.loadTexts: rlQosApplicationTrapIdTable.setStatus('current')
rlQosApplicationTrapIdEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 48, 1), ).setIndexNames((1, "RADLAN-QOS-CLI-MIB", "rlQosApplicationName"))
if mibBuilder.loadTexts: rlQosApplicationTrapIdEntry.setStatus('current')
rlQosApplicationName = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 48, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(1, 32)))
if mibBuilder.loadTexts: rlQosApplicationName.setStatus('current')
rlQosApplicationTrapId = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 48, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosApplicationTrapId.setStatus('current')
rlQoSApplicationDefaultAction = MibScalar((1, 3, 6, 1, 4, 1, 89, 88, 49), RlQosApplicationDefaultActionType()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: rlQoSApplicationDefaultAction.setStatus('current')
rlQosLogInputInterfacesAceMatchedTable = MibTable((1, 3, 6, 1, 4, 1, 89, 88, 50), )
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedTable.setStatus('current')
rlQosLogInputInterfacesAceMatchedEntry = MibTableRow((1, 3, 6, 1, 4, 1, 89, 88, 50, 1), ).setIndexNames((0, "RADLAN-QOS-CLI-MIB", "rlQosLogInputInterfacesAceMatchedIndex"))
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedEntry.setStatus('current')
rlQosLogInputInterfacesAceMatchedIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 50, 1, 1), Integer32())
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedIndex.setStatus('current')
rlQosLogInputInterfacesAceMatchedPorts = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 50, 1, 2), PortList()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedPorts.setStatus('current')
rlQosLogInputInterfacesAceMatchedVlanList1to1024 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 50, 1, 3), VlanList1()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedVlanList1to1024.setStatus('current')
rlQosLogInputInterfacesAceMatchedVlanList1025to2048 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 50, 1, 4), VlanList2()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedVlanList1025to2048.setStatus('current')
rlQosLogInputInterfacesAceMatchedVlanList2049to3072 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 50, 1, 5), VlanList3()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedVlanList2049to3072.setStatus('current')
rlQosLogInputInterfacesAceMatchedVlanList3073to4094 = MibTableColumn((1, 3, 6, 1, 4, 1, 89, 88, 50, 1, 6), VlanList4()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rlQosLogInputInterfacesAceMatchedVlanList3073to4094.setStatus('current')
mibBuilder.exportSymbols("RADLAN-QOS-CLI-MIB", rlQosPolicerEntry=rlQosPolicerEntry, rlQosCirQueue1=rlQosCirQueue1, rlQosAclAceRefTable=rlQosAclAceRefTable, rlQosClassMapPolicer=rlQosClassMapPolicer, rlQosRedProbDp1=rlQosRedProbDp1, rlQosIfTrustActive=rlQosIfTrustActive, rlQosAceTuple5=rlQosAceTuple5, QosGlobalMode=QosGlobalMode, rlQosQueueProfileTable=rlQosQueueProfileTable, rlQosTupleValue2=rlQosTupleValue2, rlQosCliMib=rlQosCliMib, rlQosClearCounters=rlQosClearCounters, rlQosAclTable=rlQosAclTable, MarkVlanAction=MarkVlanAction, rlQosRedProbDp0=rlQosRedProbDp0, rlQosPolicerStatus=rlQosPolicerStatus, rlQosQueueShapeProfileEntry=rlQosQueueShapeProfileEntry, rlQosDscpIndex=rlQosDscpIndex, rlQosSinglePolicerStatisticsStatus=rlQosSinglePolicerStatisticsStatus, AceActionType=AceActionType, rlQosCbsPortShaper=rlQosCbsPortShaper, rlQosTypeQueue5=rlQosTypeQueue5, rlQosCbsQueue5=rlQosCbsQueue5, rlQosClassMapEntry=rlQosClassMapEntry, rlQosAceAccount=rlQosAceAccount, rlQosEfManageTable=rlQosEfManageTable, rlQosAggregatePolicerStatisticsTable=rlQosAggregatePolicerStatisticsTable, rlQosAceTidxTimeRangeIsActive=rlQosAceTidxTimeRangeIsActive, rlQosCirQueue7=rlQosCirQueue7, rlQosClassMapMarkValue=rlQosClassMapMarkValue, rlQosTupleType=rlQosTupleType, rlQosDscpRemarkTable=rlQosDscpRemarkTable, rlQosDscp=rlQosDscp, rlQosGlobalIndex=rlQosGlobalIndex, rlQosTcpPortQueueStatus=rlQosTcpPortQueueStatus, rlQosClassifierUtilizationFreeRulesNumber=rlQosClassifierUtilizationFreeRulesNumber, rlQosIfProfilePointer=rlQosIfProfilePointer, ClassTupleType=ClassTupleType, RlQosAceTidxActionDropType=RlQosAceTidxActionDropType, rlQosPolicyMapTable=rlQosPolicyMapTable, rlQosPolicyClassRefEntry=rlQosPolicyClassRefEntry, rlQosPolicyClassPriorityRefEntry=rlQosPolicyClassPriorityRefEntry, rlQosOffsetStatus=rlQosOffsetStatus, rlQosCbsQueue8=rlQosCbsQueue8, rlQosClassMapCounterEnable=rlQosClassMapCounterEnable, rlQosCosQueueTable=rlQosCosQueueTable, rlQosEfPriority=rlQosEfPriority, RlQosApplicationDefaultActionType=RlQosApplicationDefaultActionType, rlQosQueueShapeIndex=rlQosQueueShapeIndex, rlQosEfState=rlQosEfState, rlQosApplicationTrapIdEntry=rlQosApplicationTrapIdEntry, rlQosTypeQueue4=rlQosTypeQueue4, rlQosCirQueue2=rlQosCirQueue2, rlQosAclType=rlQosAclType, rlQosModeGlobalCfgTable=rlQosModeGlobalCfgTable, rlQosPolicerPbs=rlQosPolicerPbs, rlQosAggregatePolicerStatisticsOutProfileCntrNumOfBits=rlQosAggregatePolicerStatisticsOutProfileCntrNumOfBits, rlQosPort=rlQosPort, rlQosAggregatePolicerStatisticsEntry=rlQosAggregatePolicerStatisticsEntry, rlQosOldDscp=rlQosOldDscp, rlQosPolicerCasPointerRemVal=rlQosPolicerCasPointerRemVal, rlQosClassMapName=rlQosClassMapName, rlQosClassifierUtilization=rlQosClassifierUtilization, rlQosOutQueueStatisticsCounterAllValue=rlQosOutQueueStatisticsCounterAllValue, rlQosQueueProfileEntry=rlQosQueueProfileEntry, rlQosLogInputInterfacesAceMatchedVlanList1025to2048=rlQosLogInputInterfacesAceMatchedVlanList1025to2048, rlQosCbsQueue7=rlQosCbsQueue7, rlQosPortPolicyStatisticsTable=rlQosPortPolicyStatisticsTable, rlQosQueueProfileStatus=rlQosQueueProfileStatus, rlQosIfPolicyEntry=rlQosIfPolicyEntry, rlQosCosQueueEntry=rlQosCosQueueEntry, rlQosPolicerPeakAction=rlQosPolicerPeakAction, rlQosUdpPort=rlQosUdpPort, rlQosOutQueueStatisticsVlanAll=rlQosOutQueueStatisticsVlanAll, rlQosPortToProfileMappingEntry=rlQosPortToProfileMappingEntry, rlQosLogInputInterfacesAceMatchedPorts=rlQosLogInputInterfacesAceMatchedPorts, rlQosClassMapMarkVlan=rlQosClassMapMarkVlan, rlQosTupleTable=rlQosTupleTable, rlQosDscpQueueDefaultMapEntry=rlQosDscpQueueDefaultMapEntry, rlQoSApplicationDefaultAction=rlQoSApplicationDefaultAction, rlQosDenyAceStatisticsEntry=rlQosDenyAceStatisticsEntry, rlQosEfManageEntry=rlQosEfManageEntry, rlQosUdpQueueValue=rlQosUdpQueueValue, rlQosIfprofileStatus=rlQosIfprofileStatus, rlQosRedMaxDp1=rlQosRedMaxDp1, rlQosLogInputInterfacesAceMatchedIndex=rlQosLogInputInterfacesAceMatchedIndex, rlQosApplicationTrapIdTable=rlQosApplicationTrapIdTable, rlQosCosQueueDefaultMapVpt=rlQosCosQueueDefaultMapVpt, rlQosPortPolicyStatisticsCntrType=rlQosPortPolicyStatisticsCntrType, rlQosDenyAceStatisticsIfCounter=rlQosDenyAceStatisticsIfCounter, rlQosValueQueue4=rlQosValueQueue4, rlQosDscpQueueEntry=rlQosDscpQueueEntry, rlQosRmNewExceedDscp=rlQosRmNewExceedDscp, rlQosValueQueue5=rlQosValueQueue5, rlQosOffsetPattern=rlQosOffsetPattern, rlQosAclDefaultAction=rlQosAclDefaultAction, rlQosOutQueueStatisticsQueueAll=rlQosOutQueueStatisticsQueueAll, rlQosAclCounterAceIndex=rlQosAclCounterAceIndex, rlQosAclCounterTable=rlQosAclCounterTable, rlQosDscpToDpEntry=rlQosDscpToDpEntry, rlQosLogInputInterfacesAceMatchedVlanList3073to4094=rlQosLogInputInterfacesAceMatchedVlanList3073to4094, rlQosAclStatus=rlQosAclStatus, rlQosCbsQueue3=rlQosCbsQueue3, rlQosAceTuple3=rlQosAceTuple3, rlQosSinglePolicerStatisticsTable=rlQosSinglePolicerStatisticsTable, rlQosAclAceRefAclPointer=rlQosAclAceRefAclPointer, rlQosRmNewDscp=rlQosRmNewDscp, rlQosIfIpv6AclOut=rlQosIfIpv6AclOut, rlQosPolicyMapStatus=rlQosPolicyMapStatus, rlQosClassifierUtilizationSystem=rlQosClassifierUtilizationSystem, rlQosMibVersion=rlQosMibVersion, rlQosLogInputInterfacesAceMatchedEntry=rlQosLogInputInterfacesAceMatchedEntry, rlQosAggregatePolicerStatisticsStatus=rlQosAggregatePolicerStatisticsStatus, rlQosIfIpv6AclIn=rlQosIfIpv6AclIn, rlQosPolicyClassRefClassPointer=rlQosPolicyClassRefClassPointer, rlQosStackControlCos=rlQosStackControlCos, rlQosCirQueue8=rlQosCirQueue8, rlQosClassMapCounterTable=rlQosClassMapCounterTable, rlQosPolicyMapIndex=rlQosPolicyMapIndex, rlQosClassifierUtilizationTable=rlQosClassifierUtilizationTable, rlQosTdThersholdDp1=rlQosTdThersholdDp1, rlQosIfProfileCfgEntry=rlQosIfProfileCfgEntry, rlQosAggregatePolicerStatisticsOutProfileCounterValue=rlQosAggregatePolicerStatisticsOutProfileCounterValue, rlQosLogInputInterfacesAceMatchedVlanList1to1024=rlQosLogInputInterfacesAceMatchedVlanList1to1024, rlQosOffsetTable=rlQosOffsetTable, rlQosUdpPortQueueEntry=rlQosUdpPortQueueEntry, rlQosDscpRemarkEntry=rlQosDscpRemarkEntry, rlQosAceTidxTuple7=rlQosAceTidxTuple7, rlQosOutQueueStatisticsVlan=rlQosOutQueueStatisticsVlan, rlQosRedMinDp0=rlQosRedMinDp0, rlQosClassMapCounterValue=rlQosClassMapCounterValue, rlQosClassMapMatch3=rlQosClassMapMatch3, rlIfType=rlIfType, rlQosIfProfileCfgTable=rlQosIfProfileCfgTable, rlQosAceTidxAction=rlQosAceTidxAction, rlQosPolicyMapName=rlQosPolicyMapName, rlQosCosQueueDefaultMapTable=rlQosCosQueueDefaultMapTable, rlQosGlobalStatisticsCntrsTable=rlQosGlobalStatisticsCntrsTable, rlQosGlobalStatisticsCntrsEntry=rlQosGlobalStatisticsCntrsEntry, rlQosClassMapAction=rlQosClassMapAction, rlQosClassMapDestInterface=rlQosClassMapDestInterface, rlQosPortPolicyStatisticsCounterValue=rlQosPortPolicyStatisticsCounterValue, rlQosPolicyClassRefTable=rlQosPolicyClassRefTable, rlQosCbsQueue6=rlQosCbsQueue6, rlQosQueueNum=rlQosQueueNum, StatisticsCntrType=StatisticsCntrType, QosTrustMode=QosTrustMode, rlQosTypeQueue8=rlQosTypeQueue8, QueueType=QueueType, rlQosCirPortRateLimit=rlQosCirPortRateLimit, rlQosStackControlQueue=rlQosStackControlQueue, StatisticsCntrNumOfBitsType=StatisticsCntrNumOfBitsType, rlQosValueQueue7=rlQosValueQueue7, rlQosOutQueueStatisticsCountrID=rlQosOutQueueStatisticsCountrID, rlQosAclIndex=rlQosAclIndex, rlQosDscpToDpTable=rlQosDscpToDpTable, rlQosSinglePolicerStatisticsOutProfileCntrNumOfBits=rlQosSinglePolicerStatisticsOutProfileCntrNumOfBits, rlQosAceTidxType=rlQosAceTidxType, rlQosPolicyClassRefStatus=rlQosPolicyClassRefStatus, rlQosPolicyMapEntry=rlQosPolicyMapEntry, rlQosRedMinDp2=rlQosRedMinDp2, rlQosAceTuple7=rlQosAceTuple7, rlQosFreeIndexesTableId=rlQosFreeIndexesTableId, rlQosOutQueueStatisticsPortAll=rlQosOutQueueStatisticsPortAll, rlQosLogInputInterfacesAceMatchedTable=rlQosLogInputInterfacesAceMatchedTable, rlQosPolicerPir=rlQosPolicerPir, rlQosSinglePolicerStatisticsOutProfileCounterValue=rlQosSinglePolicerStatisticsOutProfileCounterValue, rlQosRedMaxDp0=rlQosRedMaxDp0, rlQosGlobalQoSMode=rlQosGlobalQoSMode, rlQosDscpQueueTable=rlQosDscpQueueTable, rlQosCirQueue4=rlQosCirQueue4, rlQosGlobalStatisticsCntrsType=rlQosGlobalStatisticsCntrsType, rlQosUdpPortQueueTable=rlQosUdpPortQueueTable, PolicerAction=PolicerAction, rlQosDscpQueueDefaultMapQueueId=rlQosDscpQueueDefaultMapQueueId, rlQosTupleValue1=rlQosTupleValue1, rlQosIfPolicyMapPointerIn=rlQosIfPolicyMapPointerIn, AclObjectType=AclObjectType, InterfaceType=InterfaceType, rlQosPolicyClassRefPolicyPointer=rlQosPolicyClassRefPolicyPointer, rlQosOffsetValue=rlQosOffsetValue, rlQosTcpQueueValue=rlQosTcpQueueValue, rlQosPolicyClassPriorityRefStatus=rlQosPolicyClassPriorityRefStatus, rlQosTypeQueue1=rlQosTypeQueue1, rlQosCirPortShaper=rlQosCirPortShaper, rlQosPredefBlockAclStatus=rlQosPredefBlockAclStatus, rlQosRmOldDscp=rlQosRmOldDscp, rlQosNamesToIndexesTableId=rlQosNamesToIndexesTableId, rlQosDscpQueueDefaultMapTable=rlQosDscpQueueDefaultMapTable, rlQosMaxNumOfAce=rlQosMaxNumOfAce, rlQosAceTuple2=rlQosAceTuple2, rlQosPortPolicyStatisticsEntry=rlQosPortPolicyStatisticsEntry, rlQosAceTuple8=rlQosAceTuple8, BinaryStatus=BinaryStatus, rlQosAceTuple6=rlQosAceTuple6, rlQosClassMapMatch2=rlQosClassMapMatch2, rlQosOutQueueStatisticsQueue=rlQosOutQueueStatisticsQueue, rlQosSinglePolicerStatisticsInProfileCntrNumOfBits=rlQosSinglePolicerStatisticsInProfileCntrNumOfBits, rlQosOutQueueStatisticsEntry=rlQosOutQueueStatisticsEntry, rlQosNamesToIndexesTable=rlQosNamesToIndexesTable, rlQosCirQueue5=rlQosCirQueue5, rlQosApplicationName=rlQosApplicationName, rlQosAceTidxActionDropType=rlQosAceTidxActionDropType, rlQosUdpPortQueueStatus=rlQosUdpPortQueueStatus, rlQueueProfileName=rlQueueProfileName, rlQosQueueShapeProfileStatus=rlQosQueueShapeProfileStatus, rlQosClassifierUtilizationPercent=rlQosClassifierUtilizationPercent, rlQosAclEntry=rlQosAclEntry, rlQosTypeQueue3=rlQosTypeQueue3, rlQosPredefBlockAclTable=rlQosPredefBlockAclTable, rlQosClassMapNewVlan=rlQosClassMapNewVlan, rlQosAceStatus=rlQosAceStatus, rlQosFreeIndexesEntry=rlQosFreeIndexesEntry, rlQosClassifierUtilizationRulesNumber=rlQosClassifierUtilizationRulesNumber, rlQosOutQueueStatisticsDP=rlQosOutQueueStatisticsDP, rlQosClassifierUtilizationEntry=rlQosClassifierUtilizationEntry, rlQosTypeQueue7=rlQosTypeQueue7, rlQosQueueProfilePointer=rlQosQueueProfilePointer, rlQosPolicerAction=rlQosPolicerAction, rlQosApplicationTrapId=rlQosApplicationTrapId, rlQosStatistics=rlQosStatistics, ClassMapType=ClassMapType, rlQosAceTidxEntry=rlQosAceTidxEntry, rlQosAceTidxTuple9=rlQosAceTidxTuple9, rlQosCbsPortRateLimit=rlQosCbsPortRateLimit, rlQosIfAclIn=rlQosIfAclIn, AceObjectType=AceObjectType, rlQosAceTuple4=rlQosAceTuple4, rlQosDenyAceStatisticsClearOtherFlowCounter=rlQosDenyAceStatisticsClearOtherFlowCounter, RlQosTimeBasedAclWeekPeriodicList=RlQosTimeBasedAclWeekPeriodicList, rlQosAceTidxTuple2=rlQosAceTidxTuple2, rlQosTupleIndex=rlQosTupleIndex, rlQosAggregatePolicerStatisticsInProfileCounterValue=rlQosAggregatePolicerStatisticsInProfileCounterValue, rlQosPortRateLimitStatus=rlQosPortRateLimitStatus, rlQosOutQueueStatisticsDPAll=rlQosOutQueueStatisticsDPAll, rlQosPortShaperStatus=rlQosPortShaperStatus, rlQosPolicyClassPriorityRefPriority=rlQosPolicyClassPriorityRefPriority, rlQosRedMaxDp2=rlQosRedMaxDp2, rlQosAceTidxTimeRange=rlQosAceTidxTimeRange, rlQosNumOfIfConnections=rlQosNumOfIfConnections, rlQosClassMapRedirectAction=rlQosClassMapRedirectAction, rlQosNamesToIndexesName=rlQosNamesToIndexesName, rlQosAclAceRefEntry=rlQosAclAceRefEntry, rlQosModeGlobalCfgStatus=rlQosModeGlobalCfgStatus, rlQosTcpPortQueueTable=rlQosTcpPortQueueTable, rlQosFreeIndexesValue=rlQosFreeIndexesValue, rlQosAceTidxAccount=rlQosAceTidxAccount, rlQosAceTidxTuple10=rlQosAceTidxTuple10, rlQosValueQueue6=rlQosValueQueue6, rlQosIfPolicyTable=rlQosIfPolicyTable, rlQosTupleStatus=rlQosTupleStatus, rlQosAclAceRefAcePointer=rlQosAclAceRefAcePointer, rlQosAclCounterEntry=rlQosAclCounterEntry, rlQosNamesToIndexesEntry=rlQosNamesToIndexesEntry)
mibBuilder.exportSymbols("RADLAN-QOS-CLI-MIB", rlQosAceEntry=rlQosAceEntry, rlQosCirQueue3=rlQosCirQueue3, rlQosValueQueue3=rlQosValueQueue3, rlQosValueQueue8=rlQosValueQueue8, rlQosCliQosMode=rlQosCliQosMode, rlQosPolicerCbs=rlQosPolicerCbs, rlQosRedProbDp2=rlQosRedProbDp2, rlQosAceIndex=rlQosAceIndex, rlQosGlobalStatisticsStatus=rlQosGlobalStatisticsStatus, rlQosOutQueueStatisticsStatus=rlQosOutQueueStatisticsStatus, rlQosPortToProfileMappingTable=rlQosPortToProfileMappingTable, rlQosCosIndex=rlQosCosIndex, rlQosDscpMutationTable=rlQosDscpMutationTable, rlQosTupleEntry=rlQosTupleEntry, rlQosAceAction=rlQosAceAction, rlQosDscpQueueDefaultMapDscp=rlQosDscpQueueDefaultMapDscp, rlQosCosQueueDefaultMapEntry=rlQosCosQueueDefaultMapEntry, rlQosClassMapTrapId=rlQosClassMapTrapId, rlQosClassMapStatus=rlQosClassMapStatus, rlQosIfPolicyMapStatus=rlQosIfPolicyMapStatus, rlQosValueQueue2=rlQosValueQueue2, rlQosAggregatePolicerStatisticsInProfileCntrNumOfBits=rlQosAggregatePolicerStatisticsInProfileCntrNumOfBits, rlQosAceTidxAclIndex=rlQosAceTidxAclIndex, rlQosValueQueue1=rlQosValueQueue1, rlQosDenyAceStatisticsTable=rlQosDenyAceStatisticsTable, rlQosClassMapIndex=rlQosClassMapIndex, rlQosClassMapTunnelIdx=rlQosClassMapTunnelIdx, rlQosPredefBlockAclMask=rlQosPredefBlockAclMask, rlQosLogInputInterfacesAceMatchedVlanList2049to3072=rlQosLogInputInterfacesAceMatchedVlanList2049to3072, PYSNMP_MODULE_ID=rlQosCliMib, rlQosPolicerType=rlQosPolicerType, rlQosClassifierMaxRulesNumberUtilizationSystem=rlQosClassifierMaxRulesNumberUtilizationSystem, rlQosAceTidxTuple6=rlQosAceTidxTuple6, rlQosPolicerIndex=rlQosPolicerIndex, rlQosCliBasicModeCfg=rlQosCliBasicModeCfg, rlQosClassMapCounterEntry=rlQosClassMapCounterEntry, rlQosRedMinDp1=rlQosRedMinDp1, rlQosQueueShapeProfileTable=rlQosQueueShapeProfileTable, rlQosClassifierRulesNumberUtilizationSystem=rlQosClassifierRulesNumberUtilizationSystem, rlQosCbsQueue2=rlQosCbsQueue2, rlQosOffsetTuplePointer=rlQosOffsetTuplePointer, rlQosOutQueueStatisticsTable=rlQosOutQueueStatisticsTable, rlQosCbsQueue4=rlQosCbsQueue4, rlQosClassMapMatch1=rlQosClassMapMatch1, rlQosPredefBlockAclEntry=rlQosPredefBlockAclEntry, rlQosIfPolicyMapPointerOut=rlQosIfPolicyMapPointerOut, rlQosAclNumOfAces=rlQosAclNumOfAces, rlQosIfPolicerIn=rlQosIfPolicerIn, rlQosAceTable=rlQosAceTable, rlQosDenyAceStatisticsOtherFlowCounter=rlQosDenyAceStatisticsOtherFlowCounter, rlQosTcpPort=rlQosTcpPort, rlQosAclCounterAclIndex=rlQosAclCounterAclIndex, rlQosTypeQueue6=rlQosTypeQueue6, rlQosQueueId=rlQosQueueId, rlQosCbsQueue1=rlQosCbsQueue1, rlQosPolicyClassPriorityRefClassPointer=rlQosPolicyClassPriorityRefClassPointer, rlQosAceTidxTuple3=rlQosAceTidxTuple3, rlQosAceTidxTuple4=rlQosAceTidxTuple4, rlQosGlobalStatisticsCntrsCounterValue=rlQosGlobalStatisticsCntrsCounterValue, rlQosAceTidxTuple5=rlQosAceTidxTuple5, rlQosOffsetEntry=rlQosOffsetEntry, rlQosClassMapTable=rlQosClassMapTable, rlQoSPortTrustAdvancedMode=rlQoSPortTrustAdvancedMode, rlQosOutQueueStatisticsIfIndexList=rlQosOutQueueStatisticsIfIndexList, rlQosAceTidxTuple8=rlQosAceTidxTuple8, rlQosPolicyClassPriorityRefPolicyPointer=rlQosPolicyClassPriorityRefPolicyPointer, rlQosCosQueueDefaultMapQueueId=rlQosCosQueueDefaultMapQueueId, rlQosTypeQueue2=rlQosTypeQueue2, rlQosIfAclOut=rlQosIfAclOut, rlQosPolicerCir=rlQosPolicerCir, RedirectAction=RedirectAction, rlQosProfileName=rlQosProfileName, rlIfIndex=rlIfIndex, rlQosDp=rlQosDp, rlQosCosQueueId=rlQosCosQueueId, ClassMapAction=ClassMapAction, rlQosAclCounterInterface=rlQosAclCounterInterface, rlQosTdThersholdDp2=rlQosTdThersholdDp2, rlQosAceTuple1=rlQosAceTuple1, rlQosAclName=rlQosAclName, rlQosOffsetMask=rlQosOffsetMask, rlQosNamesToIndexesValue=rlQosNamesToIndexesValue, rlQosOutQueueStatisticsCntrNumOfBits=rlQosOutQueueStatisticsCntrNumOfBits, PolicerType=PolicerType, rlQosPolicerName=rlQosPolicerName, rlQosDscpMutationEntry=rlQosDscpMutationEntry, rlQosSinglePolicerStatisticsInProfileCounterValue=rlQosSinglePolicerStatisticsInProfileCounterValue, rlQosPolicyClassPriorityRefTable=rlQosPolicyClassPriorityRefTable, rlQosPortPolicyStatisticsCntrNumOfBits=rlQosPortPolicyStatisticsCntrNumOfBits, rlQosQueueShapeProfilePointer=rlQosQueueShapeProfilePointer, rlQosAceTidxIndex=rlQosAceTidxIndex, rlQosAceTidxTuple11=rlQosAceTidxTuple11, rlQosNewDscp=rlQosNewDscp, rlQosCPUSafeGuardEnable=rlQosCPUSafeGuardEnable, rlQosAclCounterValue=rlQosAclCounterValue, rlIfProfileName=rlIfProfileName, rlQosModeGlobalCfgEntry=rlQosModeGlobalCfgEntry, rlQosPolicerTable=rlQosPolicerTable, rlQosSinglePolicerStatisticsEntry=rlQosSinglePolicerStatisticsEntry, rlQosAclAceRefStatus=rlQosAclAceRefStatus, ClassOffsetType=ClassOffsetType, rlQosBasicGlobalTrustMode=rlQosBasicGlobalTrustMode, rlQosOffsetIndex=rlQosOffsetIndex, rlQosOutQueueStatisticsCounterTailDropValue=rlQosOutQueueStatisticsCounterTailDropValue, rlQosAceTidxStatus=rlQosAceTidxStatus, rlQosAclDefaultActionOut=rlQosAclDefaultActionOut, rlQosPredefBlockAclIfType=rlQosPredefBlockAclIfType, rlQosAceTidxTuple1=rlQosAceTidxTuple1, rlQosClassMapType=rlQosClassMapType, rlQosGlobalStatisticsCntrsNumOfBits=rlQosGlobalStatisticsCntrsNumOfBits, rlQosFreeIndexesTable=rlQosFreeIndexesTable, rlQosDscpMutationEnable=rlQosDscpMutationEnable, AclDefaultAction=AclDefaultAction, rlQosPortPolicyStatisticsEnableCounting=rlQosPortPolicyStatisticsEnableCounting, rlQosDenyAceStatisticsIfIndex=rlQosDenyAceStatisticsIfIndex, rlQosTcpPortQueueEntry=rlQosTcpPortQueueEntry, rlQosTdThersholdDp0=rlQosTdThersholdDp0, rlQosOffsetType=rlQosOffsetType, rlQosClassifierFreeRulesNumUtilizationSystem=rlQosClassifierFreeRulesNumUtilizationSystem, rlQosClassifierUtilizationUnitId=rlQosClassifierUtilizationUnitId, rlQosAdvcGlobalTrustMode=rlQosAdvcGlobalTrustMode, rlQosEfQueueId=rlQosEfQueueId, rlQosAceType=rlQosAceType, rlQosCirQueue6=rlQosCirQueue6, rlQosAceTidxTable=rlQosAceTidxTable, rlQosDenyAceStatisticsClearIfCounters=rlQosDenyAceStatisticsClearIfCounters, rlQosPredefBlockAclIfIndex=rlQosPredefBlockAclIfIndex, rlQosRedQweight=rlQosRedQweight)
