#
# PySNMP MIB module SONUS-GATEWAY-SIGNALLING-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/SONUS-GATEWAY-SIGNALLING-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 21:01:49 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
OctetString, Integer, ObjectIdentifier = mibBuilder.importSymbols("ASN1", "OctetString", "Integer", "ObjectIdentifier")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ConstraintsUnion, ValueSizeConstraint, SingleValueConstraint, ValueRangeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "ValueSizeConstraint", "SingleValueConstraint", "ValueRangeConstraint")
NotificationGroup, ModuleCompliance = mibBuilder.importSymbols("SNMPv2-CONF", "NotificationGroup", "ModuleCompliance")
NotificationType, Counter64, ModuleIdentity, MibIdentifier, Unsigned32, Integer32, IpAddress, Gauge32, MibScalar, MibTable, MibTableRow, MibTableColumn, iso, Counter32, TimeTicks, Bits, ObjectIdentity = mibBuilder.importSymbols("SNMPv2-SMI", "NotificationType", "Counter64", "ModuleIdentity", "MibIdentifier", "Unsigned32", "Integer32", "IpAddress", "Gauge32", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "iso", "Counter32", "TimeTicks", "Bits", "ObjectIdentity")
TextualConvention, DisplayString, RowStatus = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention", "DisplayString", "RowStatus")
sonusEventDescription, sonusEventLevel, sonusEventClass = mibBuilder.importSymbols("SONUS-COMMON-MIB", "sonusEventDescription", "sonusEventLevel", "sonusEventClass")
sonusSignallingMIBs, = mibBuilder.importSymbols("SONUS-SMI", "sonusSignallingMIBs")
SonusServiceState, SonusAdminState = mibBuilder.importSymbols("SONUS-TC", "SonusServiceState", "SonusAdminState")
sonusGatewaySignallingMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2))
if mibBuilder.loadTexts: sonusGatewaySignallingMIB.setLastUpdated('200107310000Z')
if mibBuilder.loadTexts: sonusGatewaySignallingMIB.setOrganization('Sonus Networks, Inc.')
sonusGatewaySignallingMIBObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1))
sonusGwSigTimerObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 1))
sonusGwSigSrvTimerT301 = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535)).clone(30)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigSrvTimerT301.setStatus('obsolete')
sonusGwSigSrvTimerT303 = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535)).clone(180)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigSrvTimerT303.setStatus('obsolete')
sonusGwSigTimerEstabish = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535)).clone(10)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigTimerEstabish.setStatus('current')
sonusGwSigTimerKeepalive = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535)).clone(3)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigTimerKeepalive.setStatus('current')
sonusGwSigActionObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 2))
sonusGwSigAction = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 2, 1), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("open", 1), ("close", 2), ("none", 3))).clone('none')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigAction.setStatus('current')
sonusGwSigActionDestIpAddr = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 2, 2), IpAddress().clone(hexValue="00000000")).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigActionDestIpAddr.setStatus('current')
sonusGwSigActionDestPort = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 2, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535)).clone(2569)).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigActionDestPort.setStatus('current')
sonusGwSigActionDir = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 2, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3))).clone(namedValues=NamedValues(("to", 1), ("from", 2), ("both", 3))).clone('to')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigActionDir.setStatus('current')
sonusGwSigPortTable = MibTable((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3), )
if mibBuilder.loadTexts: sonusGwSigPortTable.setStatus('current')
sonusGwSigPortEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1), ).setIndexNames((0, "SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwSigPortIndex"))
if mibBuilder.loadTexts: sonusGwSigPortEntry.setStatus('current')
sonusGwSigPortIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortIndex.setStatus('current')
sonusGwSigPortIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 2), IpAddress().clone(hexValue="00000000")).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortIpAddress.setStatus('current')
sonusGwSigPortNum = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 65535))).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortNum.setStatus('current')
sonusGwSigPortInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("mgtNif", 1), ("nif", 2))).clone('mgtNif')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortInterface.setStatus('current')
sonusGwSigPortRole = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("primary", 1), ("secondary", 2))).clone('primary')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortRole.setStatus('current')
sonusGwSigPortMode = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 6), SonusServiceState().clone('inService')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortMode.setStatus('current')
sonusGwSigPortState = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 7), SonusAdminState().clone('disabled')).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortState.setStatus('current')
sonusGwSigPortRowStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 3, 1, 8), RowStatus()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: sonusGwSigPortRowStatus.setStatus('current')
sonusGwSigPortStatTable = MibTable((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4), )
if mibBuilder.loadTexts: sonusGwSigPortStatTable.setStatus('current')
sonusGwSigPortStatEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1), ).setIndexNames((0, "SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwSigPortStatIndex"))
if mibBuilder.loadTexts: sonusGwSigPortStatEntry.setStatus('current')
sonusGwSigPortStatIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatIndex.setStatus('current')
sonusGwSigPortStatIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatIpAddress.setStatus('current')
sonusGwSigPortStatNum = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatNum.setStatus('current')
sonusGwSigPortStatInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 4), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("mgtNif", 1), ("nif", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatInterface.setStatus('current')
sonusGwSigPortStatRole = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 5), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("primary", 1), ("secondary", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatRole.setStatus('current')
sonusGwSigPortStatNif = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatNif.setStatus('current')
sonusGwSigPortStatState = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 4, 1, 7), SonusServiceState()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigPortStatState.setStatus('current')
sonusGwSigActGwStatusTable = MibTable((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5), )
if mibBuilder.loadTexts: sonusGwSigActGwStatusTable.setStatus('current')
sonusGwSigActGwStatusEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1), ).setIndexNames((0, "SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwSigActGwIpAddress"))
if mibBuilder.loadTexts: sonusGwSigActGwStatusEntry.setStatus('current')
sonusGwSigActGwName = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 23))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwName.setStatus('deprecated')
sonusGwSigActGwIpAddress = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 2), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwIpAddress.setStatus('current')
sonusGwSigActGwLnkProto = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 3), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("ioi", 1), ("h323", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwLnkProto.setStatus('current')
sonusGwSigActGwNumActiveCalls = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwNumActiveCalls.setStatus('current')
sonusGwSigActGwNumActiveCallsTo = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwNumActiveCallsTo.setStatus('current')
sonusGwSigActGwNumActiveCallsFrom = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwNumActiveCallsFrom.setStatus('current')
sonusGwSigActGwToState = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 7), SonusServiceState()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToState.setStatus('current')
sonusGwSigActGwFromState = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 8), SonusServiceState()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromState.setStatus('current')
sonusGwSigActGwInterface = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 9), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2))).clone(namedValues=NamedValues(("mgtNif", 1), ("nif", 2)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwInterface.setStatus('current')
sonusGwSigActGwFromBytesSent = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 10), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromBytesSent.setStatus('current')
sonusGwSigActGwFromPdusSent = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 11), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromPdusSent.setStatus('current')
sonusGwSigActGwFromBytesReceived = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 12), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromBytesReceived.setStatus('current')
sonusGwSigActGwFromPdusReceived = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 13), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromPdusReceived.setStatus('current')
sonusGwSigActGwFromTotalCalls = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 14), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromTotalCalls.setStatus('current')
sonusGwSigActGwFromCallRate = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 15), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromCallRate.setStatus('current')
sonusGwSigActGwToBytesSent = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 16), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToBytesSent.setStatus('current')
sonusGwSigActGwToPdusSent = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 17), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToPdusSent.setStatus('current')
sonusGwSigActGwToBytesReceived = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 18), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToBytesReceived.setStatus('current')
sonusGwSigActGwToPdusReceived = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 19), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToPdusReceived.setStatus('current')
sonusGwSigActGwToTotalCalls = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 20), Counter64()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToTotalCalls.setStatus('current')
sonusGwSigActGwToCallRate = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 21), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToCallRate.setStatus('current')
sonusGwSigActGwFromLnkMajorVer = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 22), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromLnkMajorVer.setStatus('current')
sonusGwSigActGwFromLnkMinorVer = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 23), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwFromLnkMinorVer.setStatus('current')
sonusGwSigActGwToLnkMajorVer = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 24), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToLnkMajorVer.setStatus('current')
sonusGwSigActGwToLnkMinorVer = MibTableColumn((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 1, 5, 1, 25), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwSigActGwToLnkMinorVer.setStatus('current')
sonusGatewaySignallingMIBNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2))
sonusGatewaySignallingMIBNotificationsPrefix = MibIdentifier((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 0))
sonusGatewaySignallingMIBNotificationsObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 1))
sonusGwRemoteGwName = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 1, 1), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 23))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwRemoteGwName.setStatus('deprecated')
sonusGwCloseReasonCode = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 1, 2), Integer32().subtype(subtypeSpec=ConstraintsUnion(SingleValueConstraint(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22))).clone(namedValues=NamedValues(("administratorInitiatedClose", 1), ("closeRequestReceivedFromRemote", 2), ("remoteNotResponding", 3), ("internalError", 4), ("configError", 5), ("recvCallSigReqFromUnknownGw", 6), ("socketErrNetworkDown", 7), ("socketErrNetworkUnreachable", 8), ("socketErrNetworkReset", 9), ("socketErrSoftwareConnectionAbort", 10), ("socketErrConnectionResetByPeer", 11), ("socketErrNoBufferSpaceAvail", 12), ("socketErrAlreadyConnected", 13), ("socketErrNotConnected", 14), ("socketErrCantSendAfterShutdown", 15), ("socketErrTooManyReferences", 16), ("socketErrConnectionTimedOut", 17), ("socketErrUnknown", 18), ("recvDuplicateLinkOpenReq", 19), ("socketErrExceptionEvent", 20), ("linkXmtCongestion", 21), ("openNackReceivedFromRemote", 22)))).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwCloseReasonCode.setStatus('current')
sonusGwRemoteGwAddr = MibScalar((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 1, 3), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: sonusGwRemoteGwAddr.setStatus('current')
sonusGwCallSigChanOpenNotification = NotificationType((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 0, 1)).setObjects(("SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwRemoteGwName"), ("SONUS-COMMON-MIB", "sonusEventDescription"), ("SONUS-COMMON-MIB", "sonusEventClass"), ("SONUS-COMMON-MIB", "sonusEventLevel"))
if mibBuilder.loadTexts: sonusGwCallSigChanOpenNotification.setStatus('deprecated')
sonusGwCallSigChanCloseNotification = NotificationType((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 0, 2)).setObjects(("SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwRemoteGwName"), ("SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwCloseReasonCode"), ("SONUS-COMMON-MIB", "sonusEventDescription"), ("SONUS-COMMON-MIB", "sonusEventClass"), ("SONUS-COMMON-MIB", "sonusEventLevel"))
if mibBuilder.loadTexts: sonusGwCallSigChanCloseNotification.setStatus('deprecated')
sonusGwSigChanOpenNotification = NotificationType((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 0, 3)).setObjects(("SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwRemoteGwAddr"), ("SONUS-COMMON-MIB", "sonusEventDescription"), ("SONUS-COMMON-MIB", "sonusEventClass"), ("SONUS-COMMON-MIB", "sonusEventLevel"))
if mibBuilder.loadTexts: sonusGwSigChanOpenNotification.setStatus('current')
sonusGwSigChanCloseNotification = NotificationType((1, 3, 6, 1, 4, 1, 2879, 2, 6, 2, 2, 0, 4)).setObjects(("SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwRemoteGwAddr"), ("SONUS-GATEWAY-SIGNALLING-MIB", "sonusGwCloseReasonCode"), ("SONUS-COMMON-MIB", "sonusEventDescription"), ("SONUS-COMMON-MIB", "sonusEventClass"), ("SONUS-COMMON-MIB", "sonusEventLevel"))
if mibBuilder.loadTexts: sonusGwSigChanCloseNotification.setStatus('current')
mibBuilder.exportSymbols("SONUS-GATEWAY-SIGNALLING-MIB", sonusGwSigActGwFromBytesSent=sonusGwSigActGwFromBytesSent, sonusGwSigActGwLnkProto=sonusGwSigActGwLnkProto, sonusGwSigSrvTimerT303=sonusGwSigSrvTimerT303, sonusGwSigActionDestIpAddr=sonusGwSigActionDestIpAddr, sonusGwSigActGwStatusEntry=sonusGwSigActGwStatusEntry, sonusGwSigActGwFromState=sonusGwSigActGwFromState, sonusGwSigPortStatIndex=sonusGwSigPortStatIndex, sonusGwSigPortInterface=sonusGwSigPortInterface, sonusGwSigPortStatInterface=sonusGwSigPortStatInterface, sonusGwSigActGwFromPdusReceived=sonusGwSigActGwFromPdusReceived, sonusGwSigPortRole=sonusGwSigPortRole, sonusGwSigPortStatState=sonusGwSigPortStatState, sonusGwSigActGwToState=sonusGwSigActGwToState, sonusGwSigActGwNumActiveCallsFrom=sonusGwSigActGwNumActiveCallsFrom, sonusGwSigPortIpAddress=sonusGwSigPortIpAddress, sonusGwSigPortIndex=sonusGwSigPortIndex, sonusGwSigActionObjects=sonusGwSigActionObjects, sonusGwSigActGwToBytesReceived=sonusGwSigActGwToBytesReceived, sonusGwSigPortStatNum=sonusGwSigPortStatNum, sonusGwSigTimerKeepalive=sonusGwSigTimerKeepalive, sonusGwSigPortMode=sonusGwSigPortMode, sonusGwRemoteGwAddr=sonusGwRemoteGwAddr, sonusGwSigActionDir=sonusGwSigActionDir, sonusGwSigPortStatIpAddress=sonusGwSigPortStatIpAddress, sonusGwSigPortStatNif=sonusGwSigPortStatNif, sonusGwSigActGwNumActiveCallsTo=sonusGwSigActGwNumActiveCallsTo, sonusGwSigActGwToBytesSent=sonusGwSigActGwToBytesSent, sonusGwSigActGwIpAddress=sonusGwSigActGwIpAddress, sonusGwSigPortState=sonusGwSigPortState, sonusGatewaySignallingMIBNotificationsObjects=sonusGatewaySignallingMIBNotificationsObjects, sonusGwSigActGwToPdusSent=sonusGwSigActGwToPdusSent, sonusGwSigActGwFromLnkMajorVer=sonusGwSigActGwFromLnkMajorVer, sonusGwSigActGwNumActiveCalls=sonusGwSigActGwNumActiveCalls, sonusGwSigActGwToTotalCalls=sonusGwSigActGwToTotalCalls, sonusGwSigActionDestPort=sonusGwSigActionDestPort, sonusGatewaySignallingMIBNotificationsPrefix=sonusGatewaySignallingMIBNotificationsPrefix, sonusGwSigPortRowStatus=sonusGwSigPortRowStatus, sonusGwSigPortStatTable=sonusGwSigPortStatTable, sonusGwSigAction=sonusGwSigAction, sonusGwSigActGwToLnkMajorVer=sonusGwSigActGwToLnkMajorVer, sonusGwSigActGwToLnkMinorVer=sonusGwSigActGwToLnkMinorVer, sonusGwSigActGwFromPdusSent=sonusGwSigActGwFromPdusSent, PYSNMP_MODULE_ID=sonusGatewaySignallingMIB, sonusGwSigActGwToPdusReceived=sonusGwSigActGwToPdusReceived, sonusGwSigPortEntry=sonusGwSigPortEntry, sonusGwSigSrvTimerT301=sonusGwSigSrvTimerT301, sonusGwCloseReasonCode=sonusGwCloseReasonCode, sonusGwSigPortNum=sonusGwSigPortNum, sonusGwSigTimerEstabish=sonusGwSigTimerEstabish, sonusGwSigActGwFromTotalCalls=sonusGwSigActGwFromTotalCalls, sonusGwCallSigChanOpenNotification=sonusGwCallSigChanOpenNotification, sonusGwRemoteGwName=sonusGwRemoteGwName, sonusGwSigActGwName=sonusGwSigActGwName, sonusGwSigActGwStatusTable=sonusGwSigActGwStatusTable, sonusGwSigPortTable=sonusGwSigPortTable, sonusGwSigActGwToCallRate=sonusGwSigActGwToCallRate, sonusGwSigTimerObjects=sonusGwSigTimerObjects, sonusGwSigChanCloseNotification=sonusGwSigChanCloseNotification, sonusGwSigActGwFromLnkMinorVer=sonusGwSigActGwFromLnkMinorVer, sonusGwSigChanOpenNotification=sonusGwSigChanOpenNotification, sonusGwSigPortStatEntry=sonusGwSigPortStatEntry, sonusGatewaySignallingMIBNotifications=sonusGatewaySignallingMIBNotifications, sonusGatewaySignallingMIBObjects=sonusGatewaySignallingMIBObjects, sonusGwSigPortStatRole=sonusGwSigPortStatRole, sonusGwSigActGwInterface=sonusGwSigActGwInterface, sonusGwSigActGwFromBytesReceived=sonusGwSigActGwFromBytesReceived, sonusGwSigActGwFromCallRate=sonusGwSigActGwFromCallRate, sonusGatewaySignallingMIB=sonusGatewaySignallingMIB, sonusGwCallSigChanCloseNotification=sonusGwCallSigChanCloseNotification)
