#
# PySNMP MIB module WLSX-ESI-MIB (http://snmplabs.com/pysmi)
# ASN.1 source file:///Users/davwang4/Dev/mibs.snmplabs.com/asn1/WLSX-ESI-MIB
# Produced by pysmi-0.3.4 at Mon Apr 29 21:29:52 2019
# On host DAVWANG4-M-1475 platform Darwin version 18.5.0 by user davwang4
# Using Python version 3.7.3 (default, Mar 27 2019, 09:23:15) 
#
wlsxEnterpriseMibModules, = mibBuilder.importSymbols("ARUBA-MIB", "wlsxEnterpriseMibModules")
ArubaESIServerStatus, ArubaESIServerMode = mibBuilder.importSymbols("ARUBA-TC", "ArubaESIServerStatus", "ArubaESIServerMode")
ObjectIdentifier, Integer, OctetString = mibBuilder.importSymbols("ASN1", "ObjectIdentifier", "Integer", "OctetString")
NamedValues, = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
ConstraintsIntersection, ValueRangeConstraint, ConstraintsUnion, SingleValueConstraint, ValueSizeConstraint = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ValueRangeConstraint", "ConstraintsUnion", "SingleValueConstraint", "ValueSizeConstraint")
ModuleCompliance, NotificationGroup, ObjectGroup = mibBuilder.importSymbols("SNMPv2-CONF", "ModuleCompliance", "NotificationGroup", "ObjectGroup")
snmpModules, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, IpAddress, Counter32, TextualConvention, Counter64, Bits, Integer32, Gauge32, ObjectIdentity, MibIdentifier, Unsigned32, NotificationType, iso, ModuleIdentity = mibBuilder.importSymbols("SNMPv2-SMI", "snmpModules", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "IpAddress", "Counter32", "TextualConvention", "Counter64", "Bits", "Integer32", "Gauge32", "ObjectIdentity", "MibIdentifier", "Unsigned32", "NotificationType", "iso", "ModuleIdentity")
TAddress, PhysAddress, TestAndIncr, MacAddress, RowStatus, TimeInterval, TextualConvention, TDomain, DisplayString, StorageType, TruthValue = mibBuilder.importSymbols("SNMPv2-TC", "TAddress", "PhysAddress", "TestAndIncr", "MacAddress", "RowStatus", "TimeInterval", "TextualConvention", "TDomain", "DisplayString", "StorageType", "TruthValue")
wlsxESIMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10))
wlsxESIMIB.setRevisions(('1910-01-26 18:06',))
if mibBuilder.loadTexts: wlsxESIMIB.setLastUpdated('1001261806Z')
if mibBuilder.loadTexts: wlsxESIMIB.setOrganization('Aruba Wireless Networks')
wlsxESIConfigGroup = MibIdentifier((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1))
wlsxESIServerTable = MibTable((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1), )
if mibBuilder.loadTexts: wlsxESIServerTable.setStatus('current')
wlsxESIServerEntry = MibTableRow((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1), ).setIndexNames((0, "WLSX-ESI-MIB", "esiServerName"))
if mibBuilder.loadTexts: wlsxESIServerEntry.setStatus('current')
esiServerName = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 1), DisplayString())
if mibBuilder.loadTexts: esiServerName.setStatus('current')
esiServerGroup = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 2), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerGroup.setStatus('current')
esiServerMode = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 3), ArubaESIServerMode()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerMode.setStatus('current')
esiServerTrustedIP = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 4), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerTrustedIP.setStatus('current')
esiServerUntrustedIP = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 5), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerUntrustedIP.setStatus('current')
esiServerTrustedSlot = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 6), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerTrustedSlot.setStatus('current')
esiServerTrustedPort = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 7), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerTrustedPort.setStatus('current')
esiServerUntrustedSlot = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 8), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerUntrustedSlot.setStatus('current')
esiServerUntrustedPort = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 9), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerUntrustedPort.setStatus('current')
esiServerStatus = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 10), ArubaESIServerStatus()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerStatus.setStatus('current')
esiServerTrustedModule = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerTrustedModule.setStatus('current')
esiServerUntrustedModule = MibTableColumn((1, 3, 6, 1, 4, 1, 14823, 2, 2, 1, 10, 1, 1, 1, 12), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: esiServerUntrustedModule.setStatus('current')
mibBuilder.exportSymbols("WLSX-ESI-MIB", wlsxESIMIB=wlsxESIMIB, wlsxESIServerEntry=wlsxESIServerEntry, esiServerGroup=esiServerGroup, esiServerUntrustedIP=esiServerUntrustedIP, esiServerTrustedSlot=esiServerTrustedSlot, wlsxESIConfigGroup=wlsxESIConfigGroup, esiServerName=esiServerName, esiServerTrustedPort=esiServerTrustedPort, esiServerStatus=esiServerStatus, esiServerTrustedIP=esiServerTrustedIP, esiServerUntrustedModule=esiServerUntrustedModule, esiServerMode=esiServerMode, esiServerUntrustedPort=esiServerUntrustedPort, esiServerTrustedModule=esiServerTrustedModule, PYSNMP_MODULE_ID=wlsxESIMIB, wlsxESIServerTable=wlsxESIServerTable, esiServerUntrustedSlot=esiServerUntrustedSlot)
